### ISSUE TITLE
CI not running in RIOT-OS/applications

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/RIOT#10042]
I'm opening this issue because there are no CI tests for the apps in the RIOT-OS/applications repository.
If an application is not working with a RIOT upstream update, we would be informed very quickly.

Does it make sense to do this in a nightly build basis? How hard would be to implement this?

**Comment by miri64** [comment]
I'm not really involved with the CI management (apart from the occasional code contribution), so I remove myself from this. Maybe @smlng or @aabadie?

**Comment by aabadie** [comment]
I think this issue is out of the scope of RIOT repo and should be closed and moved to the RIOT-OS/applications.
It seems that there's already a PR there that tries to address this issue: https://github.com/RIOT-OS/applications/pull/48.
