### ISSUE TITLE
Abandon numeric PIDs?

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#1004]
I know, since ever PIDs were numeric. But do we really need that? A thread could be just identified by its TCB.

With that change we could obliterate the `sched_threads` variable, and could have any number of threads, since the caller of `thread_create()` has to provide the thread's stack, in with the TCB will reside. A fair amount of indirection could be removed that way.

**Comment by OlegHahm** [comment]
Any one in favor of not closing this?

**Comment by gebart** [comment]
>Any one in favor of not closing this?
Do you propose closing or leaving it open? I am sorry but I do not understand the above sentence.

This issue is quite old, did the discussion reach a conclusion somewhere? Keep numeric PIDs?
All I can find is "not future proof" in #1298

**Comment by OlegHahm** [comment]
My rational was that there is currently no working proposal to get rid of numeric PIDs and @Kijewski seems to more or less have abandoned this project. But you're right, we should first conclude if RIOT could benefit from non-numeric PIDs or not before we should close this.

**Comment by miri64** [comment]
Okay, there has bin no discussion whatsoever. I'm not really convinced by this whole non-numeric PIDs thing, though I would see some benefits of having non-PID messaging coupled to `core_mbox` somehow to get rid of (or merge it with) `core_msg`. This however is another scope than non-numeric PIDs and goes more into the direction of TCBs not in stack. For now, just in the spirit of cleaning things up I would prefer to close this as memo.
