### ISSUE TITLE
nRF52 Bluetooth UART?

### ISSUE THREAD

**Issue by Citrullin** [RIOT-OS/RIOT#10084]
Hey, I cannot find a documentation around this topic. Is there already an implementation for BLE UART? As I see this is the common way for the nordic chips to communicate over UART.

**Comment by haukepetersen** [comment]
Academically speaking, there is not such thing as `BLE UART`... What you probably mean is [Nordic's proprietary UART service](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v12.0.0%2Fgroup__ble__nus.html), right?

So for using BLE with RIOT we have currently two options:
1. use it with Nordic's proprietary SoftDevice. This option comes with this service, refer to the SoftDevice Docs on how to use it
2. use the NimBLE BLE stack (pkg/nimble). I can't tell if this stack has any support for the Nordic UART service, but I would thing it does not out of the box. So you would need to implement that service manually on top of NimBLE.

Hope that information suffices. I consider this issue as closed for now, but feel free to re-open if anything is unclear.
