### ISSUE TITLE
drivers/si70xx: modifications to support HTU21D/SHT21

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#10097]
#### Description

HTU21 is a simpler version of SI2021 that has no ID, revision and heater configuration mechanisms. The measuring commands and the measured value conversion are exactly the same. Therefore, the ```si7021``` driver can also be used for HTU21D, if the ID/revision check is disabled. BTW, it is the same with SHT21, but I checked HTU21D. In fact there are hardware modules that use either SI2021, SHT21, or HTU21D with same board design.

Now there are two options to support HTU21D:

1. Definition of a pseudomodule ```htu21d``` with corresponding dependencies, so that the ```si270x``` module and the ```si27021``` pdeudomodule are automatically used and the ID/revision check is deactivated.
2. New driver module

Option 1 has the advantage of reusing the source code, but the disadvantage that symbols are something like ```si70xx_*``` while using a module called ```htu21d```. This might lead to confusion.

I can provide both. I have an almost ready driver for HTU21D here.

#### Useful links

[TE Connectivity HTU21D](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FHPC199_6%7FA6%7Fpdf%7FEnglish%7FENG_DS_HPC199_6_A6.pdf%7FHPP845E031)
[Sensirion SHT21 Datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/0_Datasheets/Humidity/Sensirion_Humidity_Sensors_SHT21_Datasheet.pdf)

#### Other issues

Related to issue #10129

**Comment by gschorcht** [comment]
@basilfx What is your opinion as the author of the `si70xx` driver?

**Comment by basilfx** [comment]
@gschorcht: I'd rather have another pseudo-module to have them 'quickly' supported with the existing driver. It's important to have this documented properly, so people know it's supported. I think the chips you mention are the ones sold on eBay/AliExpress frequently, so they are quite common, I guess.

If the drivers do deviate too much (or we need certain functions/options only specific to certain chips), we can always split them up in the future.
