### ISSUE TITLE
sys/autoinit/saul:compilation problem in auto_init_*.c

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#10098]
#### Description

Compilation of ```tests/saul``` fails for most modules when the architecture doesn't  include ```thread.h``` in ```$(RIOTCPU)/$(CPU)/include/cpu.h```.

All ```sys/auto_init/saul/auto_init_*.c``` files use ```assert``` as following
```
 assert(<driver>_INFO_NUM == <driver>_NUM);
```
to ensure that the number of ```<driver>_params``` entries matches with the number of ```<driver>_saul_info entries```.

Unfortunatly, ```assert.h``` is not included. Nevertheless, it works for most platforms / boards because ```assert.h``` is included via the following path:
```
<driver>_params.h -> board.h -> cpu.h -> thread.h -> cib.h -> assert.h
```
Even though it would be easy to include ```thread.h``` in every ```$(RIOTCPU)/$(CPU)/include/cpu.h```, from my point of view, the file which is using a certain function is responsible to include everything it needs. Therefore, I would suggest to add
```
#include "assert.h"
```
in all ```sys/auto_init/saul/auto_init_*.c``` files. I could provide an according PR if desired.

#### Steps to reproduce the issue
```
USEMODULE="si7021" make flash BOARD=esp8266-esp-12x -C tests/saul QEMU=0
```

#### Versions

Observed with ESP8266.

**Comment by aabadie** [comment]
> the file which is using a certain function is responsible to include everything it needs. 

Agreed

> I could provide an according PR if desired.

Yes, go ahead. It will be reviewed and merged fast.
