### ISSUE TITLE
make: directory variables are not available for global targets

### ISSUE THREAD

**Issue by smlng** [RIOT-OS/RIOT#10100]
#### Description

When building an application there are several standard directories available in the environment, e.g. `BINDIRBASE` and so on, which are defined in the root `Makefile.include`. However, these variables are not available when using a global target such as `make doc` or `make static-test`. Some of these would still be useful to have, e.g. see #10038 that introduces a common build directory with the goal to allow for out-of-source-builds in the future, with that in place it would also be valuable to use such common build dir for doc and static-test output, too.

Hence, I would suggest to move all directory variables currently declared into a separate file under `makefiles` which would allow this file to be included for global targets, too.

#### Steps to reproduce the issue

use #10038 and run `make doc`

#### Expected results

Would be nice to redirect output to a common build directory, like `$(RIOTBASE)/build/doc`.

#### Actual results

Doxygen output is always created in `$(RIOTBASE)/doc/doxygen/html`

#### Versions

Not important.

**Comment by cladmi** [comment]
`BINDIR* ` variables are `APPLICATION` specific so cannot be put in common for now.
The ones based on `RIOTBASE` could be.

If there is work on these variables in general, maybe a global issue should be open to follow sub tasks.
I have many small issues that could be correctly solved if the root problem is addressed and is related to these variables definition.
