### ISSUE TITLE
drivers: AS7262 6-channel multispectral sensing device

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#10156]
#### Description

I'm thinking about to port an existing driver of mine for AS7262 to RIOT. I is an 6-channel multispectral sensing device in the visible wavelengths from approximately 430nm to 670nm.

Is someone interested or already working on it?

### Useful links

[AS7262 datasheet](https://ams.com/documents/20143/36005/AS7262_DS000486_2-00.pdf/3ea95f6b-a810-428d-3a6d-4cfe4ccd6e63)

**Comment by PeterKietzmann** [comment]
@aabadie aware of this?

**Comment by aabadie** [comment]
> aware of this?

Yes and I have no opened PR or ongoing work for this and I'm not planning to work on this.

**Comment by gschorcht** [comment]
Work is in progress.
