### ISSUE TITLE
tool: how to "make flash BOARD = stm32f429i-disc1" by jlink

### ISSUE THREAD

**Issue by thanhduongvs** [RIOT-OS/RIOT#10160]
#### Description

default, "make flash BOARD = stm32f429i-disc1" by OpenOCD. Now, I want to "make flash" by Jlink. But, I do not know how to change.

**Comment by PeterKietzmann** [comment]
@thanhduongvs if I see it correctly this is not yet part of the build system. Usually we use a build time variable `PROGRAMMER=...` to enable a non-default flasher. If you grep for "jlink" in the RIOT repository you'll find some `Makefile.include` files that could help implementing this.

**Comment by thanhduongvs** [comment]
Thank's @PeterKietzmann, in folder board/stm32f429i-disc1/Makefile.include. I replace
