### ISSUE TITLE
Support for asian based Microcontroller, RTCs & ADCs

### ISSUE THREAD

**Issue by Citrullin** [RIOT-OS/RIOT#10161]
#### Description
It's just a more general topic. Asia is an interesting market, especially for real-time operation system. It might be a good idea to push more into this market, since it is well known for more open source behavior. I've watched an interesting video about really cheap Components. Probably these are mostly used in really cheap devices. 

### Useful links
https://www.youtube.com/watch?v=VYhAGnsnO7w
https://lcsc.com/

**Comment by jcarrano** [comment]
> https://www.youtube.com/watch?v=VYhAGnsnO7w

WOW!

**Comment by MrKevinWeiss** [comment]
Gotta love Dave.

**Comment by miri64** [comment]
Asia is a big continent and also a big market. Can you specify what kind of microcontrollers you are talking about?

**Comment by Citrullin** [comment]
> Asia is a big continent and also a big market. Can you specify what kind of microcontrollers you are talking about?

It's more a general topic. But of course, I could take a look into that and try some microcontroller, RTCs & ADCs in the future. Maybe I can also find out which are the common used ones.

**Comment by PeterKietzmann** [comment]
@Citrullin any progress finding commonly used 'asian based Microcontrollers'? I find it cool to have kind of idea-sharing in the community but I don't see why we should keep this issue open. How do the others  see it?

**Comment by Citrullin** [comment]
@PeterKietzmann Since this currently also a topic at my work, I will pick this up again at some point. But you are right. I just close it.
