### ISSUE TITLE
drivers: Broadcom APDS-99xx ambient light and proximity sensor driver

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#10164]
#### Description

I plan to port a driver for Broadcom APDS-99xx sensors to RIOT. Is someone working on it already?

### Useful links

[Datasheed of APDS-9960](https://docs.broadcom.com/docs/AV02-4191EN)

**Comment by bergzand** [comment]
I have one over here, but I never started on writing a driver for it. If you have something I can review and test for you.

**Comment by obgm** [comment]
I just happen to need that. What is the status of your port?

**Comment by gschorcht** [comment]
@obgm No problem. I is just waiting for review.

**Comment by artafakhari** [comment]
Hey Guys
Any Update on APDS-9960?

**Comment by gschorcht** [comment]
Fixed with PR #10420
