### ISSUE TITLE
LLVM: C++ includes are not found

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/RIOT#10166]
#### Description
This issue was detected with the [output of Murdock](https://ci.riot-os.org/RIOT-OS/RIOT/9426/dc6b193e2a332230db8751a31f002108cc460c0c/output.html) after the latest workers update.

The location of the C++ includes changed in the provided ARM toolchain in RIOT-OS/riotdocker#53 and the build system is not able to find them.

#### Steps to reproduce the issue
E.g
`BUILD_IN_DOCKER=1 TOOLCHAIN=llvm make BOARD=samr21-xpro`

#### Expected results
The application should build without any issues.

#### Actual results

```
Building application "tests_cpp11_mutex" for "samr21-xpro" with MCU "samd21".

/data/riotbuild/riotproject/tests/cpp11_mutex/main.cpp:20:10: fatal error: 'string' file not found
#include <string>
```
#### Versions
riot/riotdocker:latest

**Comment by cladmi** [comment]
Any idea what is the header location to use in that case ?

**Comment by jia200x** [comment]
These seem to be the locations:

**Comment by jia200x** [comment]
This seem to be the location:
```
/opt/gcc-arm-none-eabi-7-2018-q2-uopt/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/include/c++/7.3.1/

**Comment by cladmi** [comment]
Thanks.

**Comment by cladmi** [comment]
I am thinking about replacing everything with what was done in `llvm.inc.mk` to ask gcc about its headers location.

**Comment by cladmi** [comment]
From my tests in `arch linux`, ubuntu 16.04 `gcc`, the previous `docker` image and the current docker image, the `GCC_MULTI_DIR` should be useless.

Replacing the directory with the same directory with `GCC_MULTI_DIR` should not change anything. The content of the base directory is the same, with only more directories in it, so I will remove from a proposed solution.

**Comment by jia200x** [comment]
great! Thank you. I will test it on my side
