### ISSUE TITLE
Packet Trace

### ISSUE THREAD

**Issue by npcode15** [RIOT-OS/RIOT#10186]
Hello, I would like to know if it is possible for me to time the packet formation process as the packet travels in the network stack. 

Basically, I would like to log the packet at each layer in the network Stack. I would like to do this for a UDP Packet.
![image](https://user-images.githubusercontent.com/25517038/47114088-78aa1900-d220-11e8-935c-fb5045bc663f.png)

Thank you.

**Comment by PeterKietzmann** [comment]
AFAIK there is no out of the box solution for this. Are you aware of the schedstatistics module (`USEMODULE += schedstatistics`)? It estimates the time spent in a thread and with the multi-threaded approach of our GNRC network stack it gives an estimation about the proportional processing times of each layer.

**Comment by miri64** [comment]
You could use `gnrc_netreg_register()` with the according type of the module(s) to register some kind of tracking thread, similar as to how `gnrc_pktdump` is doing it.

**Comment by gebart** [comment]
A timing benchmark for the gnrc stack from application layer down to link layer transmission and from link layer RX back to application layer would be a useful addition to the continuous integration to track performance changes over time just like the core benchmarks which were recently added (#9348)

**Comment by npcode15** [comment]
@PeterKietzmann No, I was not aware of ```schedstatistics``` module. I will look into that.

@miri64 I will check ````gnrc_netreg_register``` as well.

Thank you.

**Comment by npcode15** [comment]
@miri64 @ I looked up ```gnrc_netreg_register``` I am not sure about how to use this. You probably suggested that I do something like the following.

```
switch (pkt->type) {
        case GNRC_NETTYPE_UNDEF:
            printf("NETTYPE_UNDEF (%i)\n", pkt->type);
            od_hex_dump(pkt->data, pkt->size, OD_WIDTH_DEFAULT);
            break;
#ifdef MODULE_GNRC_NETIF
        case GNRC_NETTYPE_NETIF:
            printf("NETTYPE_NETIF (%i)\n", pkt->type);
            gnrc_netif_hdr_print(pkt->data);
            break;
#endif
#ifdef MODULE_GNRC_SIXLOWPAN
        case GNRC_NETTYPE_SIXLOWPAN:
            printf("NETTYPE_SIXLOWPAN (%i)\n", pkt->type);
            sixlowpan_print(pkt->data, pkt->size);
            break;
#endif
#ifdef MODULE_GNRC_IPV6
        case GNRC_NETTYPE_IPV6:
            printf("NETTYPE_IPV6 (%i)\n", pkt->type);
            ipv6_hdr_print(pkt->data);
            hdr_len = sizeof(ipv6_hdr_t);
            break;
#endif
#ifdef MODULE_GNRC_ICMPV6
        case GNRC_NETTYPE_ICMPV6:
            printf("NETTYPE_ICMPV6 (%i)\n", pkt->type);
            icmpv6_hdr_print(pkt->data);
            hdr_len = sizeof(icmpv6_hdr_t);
            break;
#endif
```

Issue is when do I do it. The following code represents the part where udp data is sent.
```
/* send packet */
if (!gnrc_netapi_dispatch_send(GNRC_NETTYPE_UDP, GNRC_NETREG_DEMUX_CTX_ALL, ip)) {
    puts("Error: unable to locate UDP thread");
    gnrc_pktbuf_release(ip);
    return;
}
```

Please let me know if I am missing something obvious. The only thing which comes to mind is following the ```gnrc_netapi_dispatch_send``` method but then changes I make to that method would be limited to compile time only I suppose. Thanks.

**Comment by npcode15** [comment]
@dylad I looked at the ```schedstatistics``` module. I guess I need to use ```runtime_ticks``` the property from

```
#ifdef MODULE_SCHEDSTATISTICS
/**
 *  Scheduler statistics
 */
typedef struct {
    uint32_t laststart;      /**< Time stamp of the last time this thread was
                                  scheduled to run */
    unsigned int schedules;  /**< How often the thread was scheduled to run */
    uint64_t runtime_ticks;  /**< The total runtime of this thread in ticks */
} schedstat;
```

My issue remains the same (similar to my previous comment), how do I put the module to use. I could not find any reference for this module except the module itself ```sched.h```.

Thanks.

**Comment by PeterKietzmann** [comment]
Include this to the applications Makefile:
```
USEMODULE+=schedstatistics
USEMODULE+=ps
```
Then, in your main.c for example, include the header
```
#include "ps.h"
```

and call `ps();` at some point. The output gives you information about initialized threads, stack usage as well as the overall time spent in each thread.

**Comment by npcode15** [comment]
@PeterKietzmann  I got the following. Run time for all the networking aspect came out to be 0.000%. 

I called ps(); right after packet was sent. 

```
pid | name                 | state    Q | pri | stack  ( used) | base addr  | current     | runtime  | switches
  - | isr_stack            | -        - |   - |   8192 (   -1) |  0x806f6a0 |  0x806f6a0
  1 | idle                 | pending  Q |  15 |   8192 (  420) |  0x806d4c0 |  0x806f334  |  0.000% |         0
  2 | main                 | running  Q |   7 |  12288 ( 2752) |  0x806a4c0 |  0x806d334  | 99.999% |         7
  3 | ipv6                 | bl rx    _ |   4 |   8192 ( 1840) |  0x807b720 |  0x807d594  |  0.000% |         3
  4 | udp                  | bl rx    _ |   5 |   8192 ( 1232) |  0x8077680 |  0x80794f4  |  0.000% |         3
  5 | gnrc_netdev_tap      | bl rx    _ |   2 |   8192 ( 2276) |  0x8079700 |  0x807b574  |  0.000% |         3
  6 | thread               | bl rx    _ |   6 |  12288 ( 2484) |  0x8067180 |  0x8069ff4  |  0.000% |         1
    | SUM                  |            |     |  65536 (11004)
```

**Comment by PeterKietzmann** [comment]
Try processing 1000 packets in a loop and run `ps()` then. If you want specific measurement values there is no way around implementing specific measurement procedures.

**Comment by npcode15** [comment]
@PeterKietzmann

I got the following for a 1000 packets:
```
pid | name                 | state    Q | pri | stack  ( used) | base addr  | current     | runtime  | switches
  - | isr_stack            | -        - |   - |    512 (  132) | 0x20000000 | 0x200001c8
  1 | idle                 | pending  Q |  15 |    256 (  132) | 0x20000640 | 0x200006bc  | 18.635% |      3626
  2 | main                 | running  Q |   7 |   1536 (  636) | 0x20000740 | 0x20000c64  | 80.958% |      3446
  3 | 6lo                  | bl rx    _ |   3 |   1024 (  424) | 0x2000378c | 0x20003a74  |  0.007% |      8088
  4 | ipv6                 | bl rx    _ |   4 |   1024 (  408) | 0x20001818 | 0x20001aec  |  0.003% |      3065
  5 | udp                  | bl rx    _ |   5 |   1024 (  300) | 0x20003f48 | 0x20004244  |  0.001% |      3001
  6 | at86rf2xx            | bl rx    _ |   2 |   1024 (  448) | 0x200013d8 | 0x200016dc  |  0.268% |      8091
  7 | thread               | bl rx    _ |   6 |   1536 (  520) | 0x20000dd8 | 0x2000129c  |  0.124% |      1001
    | SUM                  |            |     |   7936 ( 3000)
```
It is helpful in a way but not exactly what I was looking for.

Could you please help me identify the underlying code for ```gnrc_netapi_dispatch_send(GNRC_NETTYPE_UDP, GNRC_NETREG_DEMUX_CTX_ALL, ip)``` ?

> If you want specific measurement values there is no way around implementing specific measurement procedures.

Also, could you explain why do you say there is no way to implement?  
I was thinking a simple time difference (between ```before sending and after sending```) using riot's internal system clock. Would this work?

Thank you.

**Comment by npcode15** [comment]
@PeterKietzmann @miri64 
Hello, I have another question related to the GNRC stack. I wasn't sure If I needed another issue or not. 

My question is based on the following facts. The question follows the facts.

Stats for a UDP packet formation/transfer, ```6lo```, ```ipv6``` and ```udp``` threads are run.**
```
pid | name                 | state    Q | pri | stack  ( used) | base addr  | current     | runtime  | switches
  3 | 6lo                  | bl rx    _ |   3 |   1024 (  424) | 0x2000378c | 0x20003a74  |  0.007% |      8088
  4 | ipv6                 | bl rx    _ |   4 |   1024 (  408) | 0x20001818 | 0x20001aec  |  0.003% |      3065
  5 | udp                  | bl rx    _ |   5 |   1024 (  300) | 0x20003f48 | 0x20004244  |  0.001% |      3001

**Whereas, in the file ```udp.c (RIOT/examples/gnrc_networking/)```**
```udp = gnrc_udp_hdr_build(payload, port, port);
if (udp == NULL) {
    puts("Error: unable to allocate UDP header");
    gnrc_pktbuf_release(payload);
    return;
}
/* allocate IPv6 header */
ip = gnrc_ipv6_hdr_build(udp, NULL, &addr);
if (ip == NULL) {
    puts("Error: unable to allocate IPv6 header");
    gnrc_pktbuf_release(udp);

/* add netif header, if interface was given */
   if (iface > 0) {
    gnrc_pktsnip_t *netif = gnrc_netif_hdr_build(NULL, 0, NULL, 0);

    ((gnrc_netif_hdr_t *)netif->data)->if_pid = (kernel_pid_t)iface;
    LL_PREPEND(ip, netif);
   }
```

I have 2 questions:
----

**Firstly,** in the networking stack (please refer to the first statistic), why cannot I find a MAC layer or its equivalent layer. If ```6lo``` is supposed to represent the MAC layer, why is it not being added in the code?

**Secondly,** the ordering of layers should follow a pattern like ```PHY/MAC -> Network -> Transport/Application``` whereas, in the code, UDP is added before the IPv6. Could you please explain the ideology behind this.

Thank you.

**Comment by PeterKietzmann** [comment]
- @npcode15 are you aware of [this work](`https://arxiv.org/pdf/1801.02833.pdf`)?
- For `gnrc_netapi_dispatch_send()` see [doxygen documentation](https://riot-os.org/api/group__net__gnrc__netapi.html#ga2b5b0f662061aa332cc1cbb9c145ee07). Please also follow the links to the underlying (IPC) messaging system
- I never said there is no way to implement... I proposed an "out of the box" solution which gives an estimate about CPU usage withing the stack. What I said is that you need to investigate and implement specific measurement points (yourself) if you want specific measurement data
- Of course you can always check system clock differences to get an estimate about time elapsed. But it should be clear what you want to measure. From what you proposed above, you would measure packet creation times, not packet traversal.
- For the MAC: In the default configuration with *gnrc_networking* there is a network interface thread which gets its name according to the network interface. For example, if you are using the Atmel samr21-xpro then the `at86rf2xx` radio (802.15.4) will start the thread with the respective name. By default we only incorporate the MAC features of the hardware. There are other examples like *gnrc_networking_mac* which I personally never used, so I'm no help here

**Comment by PeterKietzmann** [comment]
It seems I forgot the link above. Please read [this work](https://arxiv.org/pdf/1801.02833.pdf) to get a better understanding of the GNRC network stack. You will get to know the `netapi` messaging infrastructure for packet traversal as well as getting/setting options of threads in the network stack. Once the infrastructure is clear you should be able to place `xtimer_now()` or pin toggles at proper positions to do time measurements.

Even for 6LoWPAN packet processing is done from withing the 6lo thread context.

**Comment by npcode15** [comment]
@PeterKietzmann I was able to find the packet trail. Please look at the following logs:

```
1541139342.133896;m3-98;udp: GNRC_NETAPI_MSG_TYPE_SND
1541139342.134409;m3-98;ipv6: GNRC_NETAPI_MSG_TYPE_SND received
1541139342.136468;m3-98;ipv6: set payload length to 67 (network byteorder 4300)
1541139342.136843;m3-98;ipv6: set next header to 17
1541139342.137471;m3-98;ipv6: set packet source to fe80::1711:6b10:65fb:b522
1541139342.138492;m3-98;ipv6: calculate checksum for upper header.
1541139342.139484;m3-98;ipv6: add interface header to packet
1541139342.140476;m3-98;ipv6: copy old interface header flags
1541139342.141471;m3-98;ipv6: removed old interface header
1541139342.142491;m3-98;ipv6: send unicast over interface 7
1541139342.142796;m3-98;ipv6: send to 6LoWPAN instead
1541139342.143465;m3-98;6lo: GNRC_NETDEV_MSG_TYPE_SND received
1541139342.144477;m3-98;6lo: iface->sixlo.max_frag_size = 102 for interface 7
1541139342.145492;m3-98;6lo: Send SND command for 0x20007058 to 7
1541139342.146493;m3-98;_send_ieee802154: Called
1541139342.147474;m3-98;6lo: waiting for incoming message.
1541139342.148470;m3-98;ipv6: waiting for incoming message.
1541139342.154294;m3-99;_recv_ieee802154: received packet from 15:11:6b:10:65:fb:b5:22 of length 68
```

These are debug logs from various files/network layers ```(from https://github.com/RIOT-OS/RIOT/tree/master/sys/net/gnrc)```

My issue could more of a ```c``` problem than a ```RIOT``` problem. But, I am having hard time storing all the xtimer_now() results in a single array since, the files are scattered for each layer. I tried creating a single header file with an array and included that in the appropriate files, eg. ```(https://github.com/RIOT-OS/RIOT/tree/master/sys/net/gnrc/network_layer/sixlowpan/gnrc_ipv6.c )``` etc.
Then, I referenced the array using keyword ```extern```.

I am getting two errors:
1) multiple definitions (when I include the header file more than once)
2) RAM overflow 
 ```
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: /home/vagrant/Tutorials/experiments/UDP/client/bin/iotlab-m3/client_udp.elf section `.bss' will not fit in region `ram'
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: region `ram' overflowed by 101264 bytes
collect2: error: ld returned 1 exit status
/home/vagrant/Tutorials/experiments/UDP/client/../../../RIOT/Makefile.include:320: recipe for target 'link' failed
```

I am aware that the overflow is because of the variable size, but, I did have file handling in mind as an alternative. I feel using a data structure is better than file handling but if there is a better solution please let me know.
Thank you.

And following are the contents of the header file.
**Header File:**
```
#ifndef GNRC_PKT_TRACE
#define GNRC_PKT_TRACE

struct NS_Layers {
 int time_radio_start;
 int time_radio_end;
 int time_6lo_start;
 int time_6lo_end;
 int time_ipv6_start;
 int time_ipv6_end;
 int time_udp_start;
 int time_udp_end;
} gnrc_layer;

int count;
int add_arr_cntr;

struct NS_Layers ns_time[4000];

#endif /* GNRC_PKT_TRACE */
```

**Comment by PeterKietzmann** [comment]
For error 1. please refer to [this answer](https://cs50.stackexchange.com/questions/1111/how-do-i-share-a-variable-between-source-files-in-c-with-extern). For error 2. :  8 * 4 * 4000 = 128kB cannot be allocated on RAM. Consider using a non-volatile memory to save all values, send them to a logger or print values from time to time and grep them from STDIO. 
As @kaspar030 already explained in #10295 GitHub issues are meant for issues with the code base, not general usage or measurement questions. This is why I'd like to close the issue.
