### ISSUE TITLE
How to do performance tests?

### ISSUE THREAD

**Issue by kbumsik** [RIOT-OS/RIOT#10211]
Hi, I came from a PR for porting a WiFi module, #7433. As the PR is getting close to the end, I would like to more extensive tests e.g. UDP bandwidth and latency, or like [the page 48 on Martine Lenders' master thesis](http://doc.riot-os.org/mlenders_msc.pdf).

I have to admit that I'm weak at testing. I'm wondering how the RIOT community do performance tests, not feature tests. Do you share any particular scripts to do that? Please let me know if there is any useful tools for performance tests.

Thank you in advance!

**Comment by jia200x** [comment]
maybe @miri64 or @PeterKietzmann can give some hints?

**Comment by PeterKietzmann** [comment]
AFAIK there is no public tool yet to do that kind of measurement but I think it's worth to add at least some of these measurement tests to our release specs.
The measurements you referenced from @miri64's M.A. thesis focus 802.15.4 radios and thus incorporate 6LoWPAN **but** don't include the device driver processing times or radio transmission. So, for comparisons with your WiFi module they won't be the right reference. Am I mistaken?

**Comment by miri64** [comment]
You can find the performance tests from my master thesis [here](https://github.com/miri64/RIOT_playground/tree/master/stack_comparison), but since they are as old as GNRC and untouched since (oops), I don't think they still work. And as @PeterKietzmann already stated: Those tests are the stack *traversal* times, so from radio to application, so they won't help you with testing WiFi radios.

**Comment by kbumsik** [comment]
Of course I know miri64's test is not for my WiFi driver. I just wanted to study what kinds of approaches are taken to do performance tests. Please consider including any benchmark/performance tests in the future specs. It would be useful information for RIOT users.

@miri64 Thank you for your link and paper BTW. Your explanation on gnrc stack (especially the sequence diagram) was very useful when I was implementing the WiFi driver :)

**Comment by PeterKietzmann** [comment]
@kbumsik can we close this issue?

**Comment by kbumsik** [comment]
@PeterKietzmann Yes. I close the issue now.
