### ISSUE TITLE
periph_init() never called on the MSB-A2, leaving the SPI bus uninitialized

### ISSUE THREAD

**Issue by maribu** [RIOT-OS/RIOT#10276]
#### Description
On boot up of the MSB-A2 `periph_init()` is never called. This leaves e.g. the SPI interface uninitalized, as `spi_init()` is never called.

#### Steps to reproduce the issue
Boot the MSB-A2 e.g. with the cc110x driver enabled.

#### Expected results
`periph_init()` gets called on boot up, which in turn calls `spi_init()`

#### Actual results
`periph_init()` is not called and so is - therefore - `spi_init()`. However, the cc110x driver calls `spi_init_pins()` before every SPI transfer to the transceiver - which is apparently enough to get the SPI interface working. But e.g. adding an `assert(0)` to `periph_init()` or  to `spi_init()` is an easy way to confirm that neither function is called.

I stumbled upon this issue while rewriting the `cc110x` driver. I'm using a different approach to prevent the SPI interface from being used while the CC110x transceiver is not yet ready, so constantly configuring the MISO-Pin as GPIO pin and as SPI pin is not needed.

#### How to fix
Actually, a quick and dirty would be this:

``` patch
diff --git a/boards/msba2/board_init.c b/boards/msba2/board_init.c
index a386a9984c..bcdfbb5120 100644
--- a/boards/msba2/board_init.c
+++ b/boards/msba2/board_init.c
@@ -26,6 +26,7 @@
 
 #include "board.h"
 #include "cpu.h"
+#include "periph/init.h"
 
 void bl_init_ports(void)
 {
@@ -41,6 +42,7 @@ void bl_init_ports(void)
 
     LED0_OFF;
     LED0_OFF;
+    periph_init();
 }
 
 void init_clks1(void)
```

But I'm not sure if this is the right way to do it. I'm not familiar with how RIOT initializes periphs, but it seems the LPC2387 is handled different. It seems other CPUs provide `cpu_init()`, which in turn calls `periph_init()`. But the LPC2387 does not provide `cpu_init()`. Maybe the start up process in RIOT has changed and the LPC2387 has not yet been updated to the new way?

**Comment by PeterKietzmann** [comment]
> Maybe the start up process in RIOT has changed and the LPC2387 has not yet been updated to the new way

I'm sorry to say but this seems really likely to me. As mentioned before, as far as I'm concerned you're the only people using this platform nowadays. So I propose you fix what can be fixed. If you do so, please don't forget the other boards that involve a lpc2387 (currently only avsextrem)

**Comment by maribu** [comment]
Maybe the quick fix mentioned above is the best option, as it does not affect the avsextrem. (I do not have an avsexterm to check if any change in the LPC2387 would result in regressions for the avsextrem, so keeping the change in the msba2 specific files might be the better approach here.)
