### ISSUE TITLE
native: fix documentation

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#1040]
Find warnings: `make doc 2>&1 | grep '[^   ]*native[^      ]*h' | grep warning`
Fix them =)

**Comment by LudwigKnuepfer** [comment]
I'm not going to work on this any time soon.
It's a good task for some maintainer who is more active than I am now to get to understand native. Of course I can answer questions if need be.

**Comment by kYc0o** [comment]
This warnings are still appearing?

**Comment by OlegHahm** [comment]
Yes.

**Comment by kYc0o** [comment]
Let's postpone this issue then.

**Comment by miri64** [comment]
Sadly, we have to postpone again.

**Comment by OlegHahm** [comment]
Hm, because of #6367 this issue isn't 100% solved, but I would still vote to keep it closed. Agreed, @LudwigKnuepfer?

**Comment by LudwigKnuepfer** [comment]
👍
