### ISSUE TITLE
doxygen: *_params.h files are excluded

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#10427]
#### Description

```*_params.h``` files which usually contain

- default configuration parameters for drivers or
- board specific configurations of GPIOs and ADCs that are mapped to SAUL

are excluded from doxygen documentation by the doxygen file.

What is the reason? Isn't it worth it to have these parameters and configurations documented in doxygen? IMHO, it is. It avoids looking into the corresponding files. Furthermore, at the moment, it is quite difficult to reference definitions, parameters and configuration from other parts of documentation.

I have seen, that excluding ```_params.h``` was added to ```EXCLUDE_PATTERN``` with PR #6688,  commit 28c335e8e7000f31283c0fe6b7a1590fe2ca0057 by @OlegHahm.

**Comment by jcarrano** [comment]
@jia200x I think this is relevant for the configurations discussion.

**Comment by gschorcht** [comment]
I have to bring up again this issue. When I tried to add compile-time configuration that are defined in `*_params.h` files as usual for drivers, they are not included in generated documentation :worried:.

From my point of view, we should fix this problem instead of extraction configuration parameters into separate `*_conf.h` files.

**Comment by jia200x** [comment]
@miri64 @kaspar030 @kaspar030 @OlegHahm  do you remember what were the reasons behind excluding `*_params.h` from Doxygen?

**Comment by gschorcht** [comment]
The problem was/is that `@file` throws a warning for some of the `*_param.h` files.

**Comment by gschorcht** [comment]
The reason is that for some drivers there are `<driver>_params.h` files in `drivers/<driver>/include` and in `boards` directories with board specific configuration. For example:
```
boards/nz32-sc151/include/sx127x_params.h
drivers/sx127x/include/sx127x_params.h
```

**Comment by gschorcht** [comment]
Hm, using
``` 
* @file        ./sx127x_params.h
```
in `drivers/sx127x/include/sx127x_params.h` refers the wrong file `boards/nz32-sc151/include/sx127x_params.h`.

**Comment by gschorcht** [comment]
Using additionally ```FULL_PATH_NAMES = YES``` in `riot.doxyfile` seems to solve the referencing problem. In group `drivers_sx127x`, the `drivers/sx127x/include/sx127x_params.h` file is used while group `boards_nz32-sc151` uses the board specific file `boards/nz32-sc151/include/sx127x_params.h`.

As a side effect, relative file paths are not shown any longer in the documentation. Since these paths look to me more random than deterministic, not showing such relative file paths might be rather an advantage than a disadvantage. For example, take a look to the `Modules / CPU /ESP32` entry in the navigation tree.
```
adc_arch.h
esp32/include/cpu.h
esp32/include/cpu_conf.h
esp_common.h
esp_common_log.h
esp32/include/exceptions.h
gpio_arch.h
esp32/include/irq_arch.h
cpu/esp32/include/log_module.h
esp32/include/periph_cpu.h
sdk_conf.h
cpu/esp32/include/sys/types.h
esp32/include/syscalls.h
esp32/include/thread_arch.h
esp32/include/tools.h
esp32/include/xtensa_conf.h
```
Although these files reside all in the same directory, the relative paths given here are different.

From my point of view it would be more important to get parameters documented than to have relative paths in documentation.

**Comment by jcarrano** [comment]
> Using additionally FULL_PATH_NAMES = YES in riot.doxyfile seems to solve the referencing problem.

Even with that, doxygen still shows warnings like:

```
/home/jcarrano/source/vanillaRIOT/drivers/sdcard_spi/include/sdcard_spi_params.h:13: warning: the name `/home/jcarrano/source/vanillaRIOT/drivers/sdcard_spi/include/sdcard_spi_params.h' supplied as the second argument in the \file statement matches the following input files:
   /home/jcarrano/source/vanillaRIOT/drivers/sdcard_spi/include/sdcard_spi_params.h
Please use a more specific name by including a (larger) part of the path!
```

For me there is _clearly_ a bug in Doxygen, if it gets confused with only ONE matching input file.

See [this comment](https://github.com/RIOT-OS/RIOT/issues/6367#issuecomment-273107319) regarding STRIP_FROM_INC_PATH.

I believe it's a bug because that option is supposed to only control the display of names. It seems as if doxygen is making a mess out of the internal naming of the files and the "display" names. Anyways, they've got 1849 open issues.

Also, if we use `FULL_PATH_NAMES = YES` then it is a good idea to set `STRIP_FROM_PATH = ../../` to avoid having the output depend on the location of the RIOT repo in the user's fs.

**Comment by gschorcht** [comment]
Strange, for
```
boards/nz32-sc151/include/sx127x_params.h
drivers/sx127x/include/sx127x_params.h
```
it seemed to help.

**Comment by gschorcht** [comment]
Concerning `FULL_PATH_NAMES`. Seems to be not logical. With `FULL_PATH_NAMES = YES` there are no path names in our documentation.

**Comment by gschorcht** [comment]
Closed by mistake.

**Comment by gschorcht** [comment]
@jcarrano Adding the folloing`@file` arguments helps a bit
```
boards/common/arduino-due/include/sdcard_spi_params.h:
 * @file        boards/common/arduino-due/include/sdcard_spi_params.h
```
```
boards/feather-m0/include/sdcard_spi_params.h:
 * @file        boards/feather-m0/include/sdcard_spi_params.h
```
```
boards/sensebox_samd21/include/sdcard_spi_params.h:
 * @file        boards/sensebox_samd21/include/sdcard_spi_params.h
```
```
drivers/sdcard_spi/include/sdcard_spi_params.h:
 * @file        drivers/sdcard_spi_params/include/sdcard_spi_params.h
```
reduces the warnings to only one:
```
drivers/sdcard_spi/include/sdcard_spi_params.h:13: warning: the name `drivers/sdcard_spi_params/include/sdcard_spi_params.h' supplied as the second argument in the \file statement is not an input file
```
which is quite strange.

**Comment by gschorcht** [comment]
A possible solution could be for the moment to remove `@file` in file `drivers/sdcard_spi/include/sdcard_spi_params.h`. Having not documented this single file is much better than not having documented `*_params.h` at all.

**Comment by gschorcht** [comment]
@jcarrano @jia200x 
Doxygen seems to be buggy. But we can't expect that there will be a solution in the short term, if there will be any solution at all.

How do we continue? Should we leave it as it is and let the `* _params.h 'files completely undocumented, which is a big disadvantage in my view? Or should we workaround the bug as below without having the file pathes in the documentation. The files paths seem to be arbitrary anyway, they are always relative to the parsed file formed and thus strongly determined by the include order.

As I said, I could resolve all warnings by 
- setting `FULL_PATH_NAMES = YES`
- setting `STRIP_FROM_PATH = ../../`
- adding the file path relative to `$(RIOTBASE)` to the `@file` statement to the `*_params.h` files that exist multiple times
- removing `@file` statement from `drivers/sdcard_spi/include/sdcard_spi_params.h`

With these changes all `*_params.h` files are documented.

**Comment by jcarrano** [comment]
> How do we continue? 

I think your changes are reasonable, do you mind PRing them?

**Comment by gschorcht** [comment]
@jcarrano I found out a very simple solution which solves the problem of redundant path names. 
```diff
- STRIP_FROM_INC_PATH    = $(STRIP_FROM_INC_PATH_LIST) # Exported from Makefile.
+ STRIP_FROM_INC_PATH    =
```
That's it. Everything looks as before, the include paths of header files in documentation, the unsorted arbitrary looking relative file paths in the navigation tree. The only differences are, that `*_params.h` files are now included in documentation as expected and the dependency graphs include all files from which they depend and not only the direct includes. A good example is `Networking » Generic (GNRC) network stack » IPv6 » ICMPv6 » gnrc/icmpv6.h`.

@A-Paul you introduced the `STRIP_FROM_INC_PATH_LIST` in `Makefile` and `riot.doxyfile` with https://github.com/RIOT-OS/RIOT/commit/bce61166ee91d82db94259b3af689a87ae303347. Do you remember why?

The purpose of this variable is clear. It should give doxygen a hint about the include paths so that doxygen knowns how to refer the relative files names in the documentation for includes. But, obviously it doesn't make any difference with the exception that we have problem with duplicate path names.

If it's okay with you, I'd remove it for now. I would provide a PR together with small corrections of some `*_params.h` files to solve remaining warnings.
