### ISSUE TITLE
Newlib/Send string over UART with multiple threads cuts string of thread with lower priority

### ISSUE THREAD

**Issue by biboc** [RIOT-OS/RIOT#10495]
#### Description
If two threads with different priorities try to write a string over UART using Ethos, the string of thread with lower priority will be cut.

[EDIT]
As I show below with uart-thread-mutex_pb_simple, the problem does not come from Ethos.
If you enable mutex in main.c, output is good. If you use only mutex in stdio_uart.c, string are cut.
Between these two calls, it is newlib? Am I right?

Is newlib and printf thread safe?

#### Steps to reproduce the issue
Checkout my branch: https://github.com/biboc/RIOT/tree/uart_mutex_thread_pb
And run example uart-thread-mutex_pb_BR on samr21-xpro (make flash BOARD=samr21-xpro)
OR
Run example uart-thread-mutex_pb_simple on samr21-xpro (make flash BOARD=samr21-xpro)

My problem first appeared on STM32F4 as a Border Router, I didn't try the example above on this board but it should behave the same.

#### Expected results
The string of thread with lower priority should be fully printed before other thread can print string

#### Actual results
Output from example uart-thread-mutex_pb_BR :
```
2018-11-28 11:58:50.71 ~~33     `@0909]!UHCP@~~}!main(): This is RIOT!
(Version: 2018.10-RC1-330-gd8cfe-uart_mutex_thread_pb)
2018-11-28 11:58:50.71 ~~}!RIOT border router example application
2018-11-28 11:58:50.72 ~~}!THREAD 2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+
2018-11-28 11:58:50.74 ~~}!THREAD 2-|+2-|+2-|+2-|+THREAD
1_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*1
2018-11-28 11:58:50.75
~~}!2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+
2018-11-28 11:58:50.76 ~~}!THREAD
2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+
```

Output from example uart-thread-mutex_pb_simple :
```
main(): This is RIOT! (Version: 2018.10-RC1-330-gd8cfe)
RIOT border router example application
THREAD 2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+2-|+
THREAD 2-|+2-|+2-|+2-11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*1
THREAD 1_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*11_!*1
```

#### Versions
Ubuntu 16.04 and RIOT master (28/11/2018)

**Comment by kaspar030** [comment]
Newlib is not thread-safe. Could you try merging #8619?
