### ISSUE TITLE
gnrc: source address selection never selects global address

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#10560]
#### Description

I'm facing a problem where a 6lowpan node running gnrc_networking always selects it's link-local address as source, despite of the destination address being global. I'm using a RasPi with openlab as peer, and I'm trying to send UDP packets.

I traced it down to this line:

https://github.com/RIOT-OS/RIOT/blob/b6abbad6fbece3004e65deb092263bafefc2108d/sys/net/gnrc/netif/gnrc_netif.c#L1031.

The function seems to return "3" for the node's global address, making the condition true, which causes the address to not be considered as source address.

I'm assuming that some logic in the duplicate address selection is broken, or that the RIOT node is expecting some kind of reply which the raspi doesn't send.

#### Steps to reproduce the issue

Setup Raspi to distribute global prefix via 802.15.4, connect with RIOT node gnrc_networking, send udp packet via gnrc_networking's "udp send" to the RasPi's global address, watch tcpdump.

#### Expected results

tcpdump shows udp packets with both source and destination address global.

#### Actual results

tcpdump shows link-local source address.

#### Versions

Compiled on current Arch linux, current master, gcc.

**Comment by miri64** [comment]
Yepp. Activate classic SLAAC so DAD can pass `CFLAGS=-DGNRC_IPV6_NIB_SLAAC=1`. Linux doesn't implement 6Lo-ND so it needs to fall back to classic SLAAC (but that needs to be compiled in).

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/9522

**Comment by kaspar030** [comment]
Thanks @miri64, that was it!

It's ```CFLAGS += GNRC_IPV6_NIB_CONF_SLAAC=1```, though.

**Comment by miri64** [comment]
oops sorry yes. Was writing from memory ;-)
