### ISSUE TITLE
dist/tools/ci: print_toolchain_version requires update for ESP toolchains

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#10674]
#### Description

`./dist/tools/ci/print_toolchain_versions.sh` doesn't print any information related to installed ESP toolchains.

#### Steps to reproduce the issue

Try `./dist/tools/ci/print_toolchain_versions.sh` in riotdocker.

#### Expected results
```
     xtensa-esp32-elf-gcc: gcc version 5.2.0 (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a)
     xtensa-lx106-elf-gcc: gcc version 4.8.5 (crosstool-NG crosstool-ng-1.22.0-60-g37b07f6)
     ...
```

**Comment by miri64** [comment]
See #10675 for a fix.
