### ISSUE TITLE
Linking a pre compiled library with RIOT

### ISSUE THREAD

**Issue by ahendon93** [RIOT-OS/RIOT#10835]
I am wondering what the process is for linking a pre compiled library to RIOT(not in gitlab). I know how to use RIOT to pull in packages and build them, but this is a different situation. I have the .a and header files for this library, but I am not sure how to link the library to RIOT.

**Comment by kaspar030** [comment]
In RIOT every module get's built into an archive (```.a```) in ```bin($(BOARD)/```, and ```USEMODULE += foo``` causes ```bin($(BOARD)/foo.a``` to be linked in.

**Comment by kaspar030** [comment]
As this has also been asked on users@riot-os.org and that is the right place, I'm closing this.
