### ISSUE TITLE
Preemption of malloc on AVR

### ISSUE THREAD

**Issue by maribu** [RIOT-OS/RIOT#10842]
#### Description
[This post](https://www.mail-archive.com/avr-libc-dev@nongnu.org/msg06263.html) in the AVR libc development email list describes that memory corruption can occur on FreeRTOS when a call to `malloc()` or `free()` is preempted. They suppose to address this by adding hooks at the beginning and end of `malloc()` and disable preemption while `malloc()` or `free()` works on the allocator structures.

As the AVR libc does not have those hooks yet, I don't see any way how any OS using preemption can work reliable when `malloc()` is called. So I believe the same problem applies to RIOT as well.

#### Steps to reproduce the issue
Have one thread call `malloc()` or `free()` and let this thread be preempted by a second thread while `malloc()` or `free()` was working on the allocator structures. If the second thread also accesses the allocation structures (e.g. by calling `malloc()` or `free()`), it might find those structures in a corrupted state.

#### Expected results
The call to `malloc()` or `free()` should not be preempted in order to keep the allocator structures in a useable state.

#### Actual results
`malloc()` and `free()` is not protected against preemption, so preemption could lead to one thread accessing the allocator structures in a corrupted state.

#### Versions
Should apply to any version of RIOT using any avr-libc version including the (as of now) most recent version.

**Comment by miri64** [comment]
Maybe related to what spun out of https://github.com/RIOT-OS/RIOT/issues/10800.

**Comment by maribu** [comment]
Yes, this contains indeed the same approach FreeRTOS wants to follow:

https://github.com/OTAkeys/RIOT/blob/2a31cbf8d61f6437d41273e980351d709b9ff1c8/sys/newlib_thread_safe/syscalls.c#L42-L54

**Comment by gschorcht** [comment]
The rmutex approach in __mallo_lock/unlock functions might not be working:

- It would not be possible to use malloc in ISRs.
- I'm not sure for AVR, but if interrupts are not disabled, a context switch might happen when returning from an ISR.

Maybe, __ malloc_lock/unlock functions should simply disable/enable interrupts.

**Comment by maribu** [comment]
To be honest, I would add an `assert()` in the pre_hook of `malloc()` to make sure it is called in thread-context and document that `malloc()` must not be called from interrupt context. I never did perform benchmark on `malloc()`, but I was told it can be quite costly and should not occur in hot code paths.

But if we decide to support `malloc()` in interrupt context, there will be no other option to disabling all interrupts. (One might be tempted to call `mutex_trylock()` form ISR instead of `mutex_lock()` and just let `malloc()` return `NULL` if `mutex_trylock()` fails, but as the hooks are `void`-Functions, this is not an option.)

**Comment by gschorcht** [comment]
The question is whether the use of "malloc" should be really prohibited in the interrupt context. There are certainly use cases, e.g., network device drivers, in which an ISR stores data in a piece of dynamically allocated memory to provide them to to the user of the driver.

Even it is not related to this issue, it woud be a probably a good idea to have `assert()` in `mutex` functions to avoid their usage in interrupt context.

**Comment by maribu** [comment]
> e.g., network device drivers

For a similar reason (locking the mutex of the SPI bus) running code in interrupt context is avoided for network drivers anyway. I personally would try to avoid dynamic memory management on constrained devices in general, and during ISR in particular.

Btw: The [TLSF-based allocator](https://doc.riot-os.org/group__pkg__tlsf__malloc.html) does disable interrupts during `malloc()`/`free()`. So assume this approach has been proven to work in practice. Maybe it should be considered to use that allocator by default?

**Comment by kaspar030** [comment]
> The question is whether the use of "malloc" should be really prohibited in the interrupt context.

We shouldn't prohibit it for political reasons, but I'd always argue that ```malloc()``` in ISR should be avoided at all costs. If not prohibiting would force us to make the sane case (```malloc()``` in user space) more costly, I'd rather not support it for performance reasons.

**Comment by kaspar030** [comment]
> Maybe it should be considered to use that allocator by default?

TLSF has nice properties (O(1) malloc() and free()), but it uses ~3.5kB for "free lists". I don't think we can afford that. There's room for optimization for our low-end devices in the implementation (allowing higher internal fragmentation, limit max allocation size to something practical like 2**16 or less, use pointer compression), but that needs work.

**Comment by maribu** [comment]
> If not prohibiting would force us to make the sane case (malloc() in user space) more costly, I'd rather not support it for performance reasons.

I think disabling interrupts during `malloc()` / `free()` instead of using a mutex will not have a performance penalty  - I guess it would be faster. (The mutex itself will disable and re-enable interrupts for each lock and unlock anyway, so less code is executed.) So unless `malloc()` is not "super slow", I personally think disabling interrupts would be better approach - even putting calling `malloc()` from interrupt context aside.

Does anyone have a rough idea how fast/slow `malloc()` is?

**Comment by kaspar030** [comment]
> Does anyone have a rough idea how fast/slow malloc() is?

Here is a crude test (and malloc()'s best case):

```
[kaspar@ng hello-world (master)]$ cat alloc.c
#include <stdlib.h>

void *alloc(size_t size)
{
    return malloc(size);
}

void dealloc(void *ptr)
{
    free(ptr);
}
[kaspar@ng hello-world (master)]$

main.c:

#define ITERATIONS 1000000

int main(void)
{
    puts("malloc bench");

    uint32_t before = xtimer_now_usec();
    for (uint32_t i = 0; i < ITERATIONS; i++) {
        void *ptr = alloc(1024);
        dealloc(ptr);
    }
    printf("%u iterations took %"PRIu32"us\n", ITERATIONS, xtimer_now_usec() - before);

    return 0;
}
```

On a nucleo-f401re:

```
main(): This is RIOT! (Version: 2018.10-RC1-1171-g1f729)
malloc bench
100000 iterations took 151192us
main(): This is RIOT! (Version: 2018.10-RC1-1171-g1f729)
malloc bench
1000000 iterations took 1511906us
```

Roughly, it is fast.

**Comment by maribu** [comment]
Slightly adapted:

``` C
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "xtimer.h"

#define ITERATIONS 1000000

int main(void)
{
    puts("malloc bench");

    uint32_t before = xtimer_now_usec();
    for (uint32_t i = 0; i < ITERATIONS; i++) {
        void *ptr = malloc(1024);
        free(ptr);
    }
    printf("%" PRIu32 " iterations took %"PRIu32"us\n", (uint32_t)ITERATIONS,
           xtimer_now_usec() - before);

    return 0;
}
```

On the Arduino Mega2560:
```
2019-01-24 11:08:34,814 - INFO # main(): This is RIOT! (Version: 2018.10-RC1-1167-g33c43)
2019-01-24 11:08:34,814 - INFO # malloc bench
2019-01-24 11:08:41,824 - INFO # 1000000 iterations took 7000892us
```

So about 7µs per `malloc()` and `free()` on slow platforms. I'm in favor of @gschorcht proposal to just disable interrupts during `malloc()` and `free()`.

**Comment by gschorcht** [comment]
> So about 7µs per `malloc()` and `free()` on slow platforms. I'm in favor of @gschorcht proposal to just disable interrupts during `malloc()` and `free()`.

It seems that we had already agreed to implement the locking mechanism simply by disabling interrupts.

**Comment by maribu** [comment]
The callback hooks have not yet been merged to AVR libc, so we have no chance to implement it. The AVR libc is seemingly no longer actively maintained and bit rotting for some time.

@MicrochipTech or @arduino: Wouldn't you have interest in maintaining it? Judging from the [activity of the mailing list](https://www.mail-archive.com/avr-libc-dev@nongnu.org/maillist.html) this would require more than a few days a month of work, once the backlog is done.

**Comment by gschorcht** [comment]
@maribu Another solution could be to use wrapper functions like `__wrap_malloc`, ... together with `-Wl -wrap malloc` linker option. We would just have to implement functions like:
```
void* __wrap_malloc(size_t size)
{
    unisigned state = irq_disable();
    void *ptr = malloc(size_t size);
    irq_restor(state);
    return ptr;
}
```
With the linker option `-Wl -wrap malloc` all calls to `malloc` will be replaced by a call to `__wrap_malloc`. An easy solution at minimal cost.

**Comment by maribu** [comment]
Sounds good. Some care needs to be taken that the call to `malloc()` inside `__wrap_malloc()` is not rerouted to `__wrap_malloc()` as well.

**Comment by gschorcht** [comment]
> Some care needs to be taken that the call to malloc() inside __wrap_malloc() is not rerouted to __wrap_malloc() as well.

Yes, of course. I missed that this approach works when we use it a bit different:
```
extern void *__real_malloc(size_t size);

void *__wrap_malloc(size_t size)
{
    unisigned state = irq_disable();
    void *ptr = __real_malloc(size_t size);
    irq_restor(state);
    return ptr;
}
```
I could try to provide a PR with this approach.
