### ISSUE TITLE
Add the ability to set pin inversion on stm32 uart

### ISSUE THREAD

**Issue by bluephoton** [RIOT-OS/RIOT#10935]
#### Description
SBUS protocol (widely used for radio controlled drones) uses inverted serial and requires the ability to invert UART RX pin.

Current implementation provides a function uart_mode() that doesn't allow this functionality. 

### Useful links
See related discussion about this here: https://github.com/RIOT-OS/RIOT/pull/10743

**Comment by MrKevinWeiss** [comment]
@yegorich @haukepetersen I think this could be done statically in the cpu struct right?

**Comment by yegorich** [comment]
I'm cooking a PR right now.

**Comment by MrKevinWeiss** [comment]
Should we follow this up?  Is there still any interest?

**Comment by bluephoton** [comment]
I think this is important feature to add to RIOT, at the moment I’m using private fork that fixes this, hence I’m not blocked. But it will be great to have it out of the box.

**Comment by MrKevinWeiss** [comment]
Ok, if @yegorich doesn't want to do a PR I can do one once my list is done... or you can @bluephoton

**Comment by bluephoton** [comment]
I’m pretty swamped with work at the time and don’t have free cycles :(

**Comment by yegorich** [comment]
Me neither :-( It would be good to continue the work on https://github.com/RIOT-OS/RIOT/pull/10937 introducing an IOCTL.

**Comment by bluephoton** [comment]
@MrKevinWeiss I'm out in vacation for two weeks, so I do have time but may still not be able to get to it :)
It will be great if we at least add the extra init method described in #10937 that will enable scenarios require pin inversion. @yegorich  if you add some details on how to properly implement IOCTL I may be able to squeeze this in.
