### ISSUE TITLE
tests/gnrc_tcp_*: not working on 6Lo-based boards

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/RIOT#10947]
#### Description
Both test applications *tests/gnrc_tcp_server* and *tests/gnrc_tcp_client* do not work on current master using boards (I tried with samr21-xpro and iotlab-m3). It used to work on 2018.07 release branch though.

#### Steps to reproduce the issue
Build/flash/term one of the aforementioned applications to a board and wait for the serial output.

#### Expected results
The respective application should print some status information, among others IPv6 address, port, ...

#### Actual results
You see nothing because the board sees to hard fault before main() is reached. By enabling `ENABLE_DEBUG` in `auto_init` you can see at least some output before the board crashes.

#### Versions
```
Installed compiler toolchains 
-----------------------------
             native gcc: gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
      arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q3-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
                avr-gcc: missing
       mips-mti-elf-gcc: missing
             msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
   riscv-none-embed-gcc: missing
                  clang: missing

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
               avr-libc: missing (missing)

Installed development tools
---------------------------
                  cmake: cmake version 3.10.2
               cppcheck: missing
                doxygen: 1.8.13
                 flake8: 3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.6.7 on Linux
                    git: git version 2.17.1
             coccinelle: missing
```

**Comment by PeterKietzmann** [comment]
@smlng, @miri64 ideas?

**Comment by miri64** [comment]
I'd just do a `git bisect` to find the regression.

**Comment by miri64** [comment]
0a9793c49bf7d127f3281aaaa1b5584ee15b02c6 introduced the regression according to my bisect. Will investigate.

**Comment by miri64** [comment]
However, there is more to this. In 0a9793c the hardfault handler is still called and I get a dump of all registers. Later I don't see that anymore. I will investigate this as well.

**Comment by miri64** [comment]
Ok, it is confirmed to be https://github.com/RIOT-OS/RIOT/commit/0a9793c49bf7d127f3281aaaa1b5584ee15b02c6 now.
