### ISSUE TITLE
net: netdev_driver_t::send() doc unclear

### ISSUE THREAD

**Issue by maribu** [RIOT-OS/RIOT#10969]
#### Description
The [documentation of `netdev_driver_t::send()`](http://api.riot-os.org/structnetdev__driver.html#a39585137953a92c1c58b5e0ad3262096) is unclear on the return value.

#### Steps to reproduce the issue
Read the doc regarding the return value.

#### Expected results
The reader is aware what the return value should be.

#### Actual results
The reader is confused, as the correct return value on success could be any of the following:

1. The number of bytes of layer 2 PDU send
2. The number of bytes of the layer 2 frame send without hardware supplied overhead (e.g. preamble, sync word, FCS, ...)
3. The number of bytes of the layer 2 frame send including FCS, but without preamble and sync word
4. The number of bytes of the layer 2 frame send including all overhead

#### Versions
Current master

-----
Update 1: Numbered possible return values for easier reference
Update 2: Added additional alternative to allow classifying current implementations

**Comment by maribu** [comment]
Looking into the current drivers, variant 2 seems to be the predominant approach: 

Drivers implementing variant 1. (PDU):
- None

Drivers implementing variant 2. (frame size without FCS, preamble, etc.)
- `at86rf2xx`
- `enc28j60`
- `encx24j600`
- `esp_now`
- `ethos`
- `mrf24j40`
- `nrfmin`
- `kw2xrf`
- `slipdev
- `sx127x` (?)

Drivers implementing variant 3 (frame size with FCS, but without preamble etc.)
- `cc110x` (current master version, not my PR)
- `cc2420`

Drivers implementing variant 4 (frame size including all overhead)
- None

(I might have classified some wrong, as I only looked briefly at it.)

**Comment by miri64** [comment]
@maribu I assume this issue still persists? How about converting it into a tracking issue?

**Comment by miri64** [comment]
> @maribu I assume this issue still persists? How about converting it into a tracking issue?

Ping?

**Comment by maribu** [comment]
Sorry for the late reply.

> I assume this issue still persists?

Yes. "number of bytes sent" is not really clear (at least to me), what it should include.

> How about converting it into a tracking issue?

Sure. But maybe a decision on what the correct behavior is should be done first. If interpretation 2 of the sentence is chosen, only few drivers need to be adapted.

Maybe the first thing to do after the decision is to update the documentation, so that new drivers implement the behavior correctly right away.

**Comment by miri64** [comment]
As there is no clear default on what device overhead entails (not even among IEEE 802.15.4 devices), I would also prefer variant 2.

**Comment by maribu** [comment]
`netdev_driver_t::confirm_send()` is clear in its wordings on what to return. It will take a bit of time until all drivers will make use of that, but the immediate issue of the doc being unclear is solved.
