### ISSUE TITLE
hts221: wrong bit for "one-shot enable" register

### ISSUE THREAD

**Issue by chamisso** [RIOT-OS/RIOT#11013]
In the file RIOT/drivers/hts221/include/hts221_regs.h line 128 should read:
`#define HTS221_REGS_CTRL_REG2_OS_EN     (1 << 0)    /**< One-shot enable, start new dataset */`
and not:
`#define HTS221_REGS_CTRL_REG2_OS_EN     (1 << 2)    /**< One-shot enable, start new dataset */`.

**Comment by PeterKietzmann** [comment]
@smlng you are the author of that file. Mind to have a look?

**Comment by smlng** [comment]
mhm looks like copy paste from the REG3 definition, see #11017
