### ISSUE TITLE
omit/rename "struct names" in typedef struct definitions for cscope usage

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#1102]
Many type definitions in core/include (and maybe somewhere else, too)
have the following scheme:
```c
typedef struct name_t {
    ...
} name_t;
```
Cscope users will notice that a definition search for "name_t" with this scheme will yield two results, instead of one.

E.g., searching in cscope for the definition of "tcb_t" yields two results:
Line: 59 in RIOT/core/include/tcb.h > typedef struct tcb_t {
Line: 77 in RIOT/core/include/tcb.h > } tcb_t;

Renaming the first occurrence of "name_t" to "name" (or completely omitting that name) won't do any harm, but would yield only one search result and thus would jump directly to that definition in cscpe.
In addition the first occurrence of "name_t" actually describes the following struct and not the type itself, so that "*_t" might sound misleading.

This would greatly enhance the usability of cscope.

**Comment by cgundogan** [comment]
I guess finding these struct definitions and renaming them properly is a great newbie task

**Comment by Kijewski** [comment]
@cgundogan, how do you translate Arbeitsbeschaffungsmaßnahme into English? :)

**Comment by rajma996** [comment]
So what convention can be finalised  typedef struct name {…} name_t; or  typedef struct {...} name_t; for the changes...

**Comment by cgundogan** [comment]
The prefarable way is:
```c
typedef struct {
...
} name_t
```

**Comment by haukepetersen** [comment]
@cgundogan: this was not yet addressed and is not critical - so it's save to postpone to 2016.07?!

**Comment by DipSwitch** [comment]
Working on it, PR in a minute I hope.
