### ISSUE TITLE
drivers/l3g42000d: scale has wrong data type

### ISSUE THREAD

**Issue by TorbenPetersen** [RIOT-OS/RIOT#11151]
#### Description

Introduced by 2ace1a2dfe scale changed from int32_t to int, which breaks conversion of data from the sensor. PR will follow soon.

**Comment by PeterKietzmann** [comment]
@TorbenPetersen thanks for reporting. Please always use the template when opening an issue and give some more description. Do you know why the data type was changed? What exactly breaks? How do we reproduce this bug? Which platform, which application...

**Comment by PeterKietzmann** [comment]
@dylad, @aabadie I assigned you as you were the authors of the @l3g42000d or [2ace1a2](https://github.com/RIOT-OS/RIOT/commit/2ace1a2dfeed7ac59e74753b9bed9ff619f53596)

**Comment by TorbenPetersen** [comment]
> @TorbenPetersen thanks for reporting. Please always use the template when opening an issue and give some more description. Do you know why the data type was changed? What exactly breaks? How do we reproduce this bug? Which platform, which application...
1. I do not know why the data type was changed, according to the commit (2ace1a2) they reworked the driver API and the param definitions
2. All data, that is read from the sensor, is converted to zero during the conversion. That is the issue this bug causes
3. I used the driver test (tests/driver_l3g4200d). And as stated in my PR (#11152) I'm using an Atmega1284p
