### ISSUE TITLE
Support for EFM32

### ISSUE THREAD

**Issue by rasgo-xyz** [RIOT-OS/RIOT#1123]
Are there any plans to port RIOT to EFM32 microcontrollers? (ARM Cortex-M0/M3)

**Comment by PeterKietzmann** [comment]
@cidadao, anything in progress?

**Comment by basilfx** [comment]
I have created [this bootstrap script](https://gist.github.com/basilfx/49a467ffeb5e7678d90f) which initializes a `cpu/exm32xx` folder for each target that currently is supported by emlib (mentioned above). It creates configuration files, makefiles and linker scripts, based on actual parameters. Although it is not ready yet and I certainly cannot test all targets, I hope to have it running on my STK3600 development kit soon. Just wanted to share this with anybody interested.

I have seen the support for [EZR32WG](https://github.com/RIOT-OS/RIOT/tree/master/cpu/ezr32wg) by @haukepetersen which doesn't use emlib, but I think emlib doesn't add much overhead and certainly helps to bring RIOT-OS to more targets sooner. After all this issue is open for 1.5 years already.

**Comment by haukepetersen** [comment]
I must confess that I am not a big fan of vendor supplied board support libraries in general. In my experience they are often bloated and inefficient. Further they make portability over vendor borders not necessarily easier - often even in contrary... Above that I found, that it is also not much harder to configure and program a MCU on register level - as you have to understand how the peripherals are working in any case...

But in general I don't see a reason in using the emlib, as long as we can show that the overhead is indeed not that big. Further I would strongly vote for using RIOTs cortexm_common linkerscript, as we should use as much of the shared code as possible to simply maintenance for the future!

**Comment by cidadao** [comment]
Hi all,

​​
Regarding the usage of emlib, it's actually not a board support package
(BSP) but a generic peripheral library, so even if you code it by yourself,
on register level, you'll end up doing similar things, and since emlib is
developed and maintained by the SiliconLabs I guess it contains the "best
practices" to use their own peripherals and eventually some workarounds to
erratas.
So, if I'm allowed to, I would like to vote this up in the hope it would
accelerate the port to EFM32 and also to facilitate its maintenance.

On 17 November 2015 at 12:29, Hauke Petersen <notifications@github.com>
wrote:

> I must confess that I am not a big fan of vendor supplied board support
> libraries in general. In my experience they are often bloated and
> inefficient. Further they make portability over vendor borders not
> necessarily easier - often even in contrary... Above that I found, that it
> is also not much harder to configure and program a MCU on register level -
> as you have to understand how the peripherals are working in any case...
>
> But in general I don't see a reason in using the emlib, as long as we can
> show that the overhead is indeed not that big. Further I would strongly
> vote for using RIOTs cortexm_common linkerscript, as we should use as much
> of the shared code as possible to simply maintenance for the future!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RIOT-OS/RIOT/issues/1123#issuecomment-157357450>.
>



-- 
Mário Ribeiro

**Comment by haukepetersen** [comment]
I fully understand, periph lib is what I meant (BSP was the wrong expression)... 

> I guess it contains the "best practices" to use their own peripherals and eventually some workarounds to erratas.

This is what one would think, but at least for other vendors this is not always the case...

Anyway, I'd say go ahead with the emlib inclusion for now and let's see where that leads. I think we have always the option to implement our periph interface using emlib functions and if we find these to be too in-efficient we can always switch to direct implementations as started for the wonder gecko.

The only thing I would really like to see is that we use as much of the existing infrastructure as possible, especially the common linkerscript!

**Comment by basilfx** [comment]
To demonstrate, I have merged an initial structure (via the bootstrap script) in my branch: https://github.com/basilfx/RIOT/tree/feature/efm32/cpu and https://github.com/basilfx/RIOT/tree/feature/efm32/boards. Note that I have remove the existing ezr32wg for now (when finished, I will not submit a PR for this branch without the existing ezr32wg).

I have re-used as much as possible from the existing cortex-m infrastructure.

The code compiles emlib, but the actual driver implementations are missing, so I'm currently at:

```
/Users/basilfx/SimplicityStudio/v3_workspace/src/bin/stk3600/uart_stdio.a(uart_stdio.o): In function `uart_stdio_init':
/Users/basilfx/SimplicityStudio/v3_workspace/lib/sys/uart_stdio/uart_stdio.c:73: undefined reference to `uart_init'
/Users/basilfx/SimplicityStudio/v3_workspace/src/bin/stk3600/uart_stdio.a(uart_stdio.o): In function `uart_stdio_write':
/Users/basilfx/SimplicityStudio/v3_workspace/lib/sys/uart_stdio/uart_stdio.c:87: undefined reference to `uart_write'
/Users/basilfx/SimplicityStudio/v3_workspace/src/bin/stk3600/stk3600_base.a(board.o): In function `board_init':
/Users/basilfx/SimplicityStudio/v3_workspace/lib/boards/stk_common/board.c:29: undefined reference to `gpio_init'
/Users/basilfx/SimplicityStudio/v3_workspace/lib/boards/stk_common/board.c:30: undefined reference to `gpio_set'
/Users/basilfx/SimplicityStudio/v3_workspace/lib/boards/stk_common/board.c:32: undefined reference to `gpio_init'
/Users/basilfx/SimplicityStudio/v3_workspace/lib/boards/stk_common/board.c:33: undefined reference to `gpio_init'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

**Comment by haukepetersen** [comment]
Looks interesting so far, though the most interesting part (implementation of the periph interfaces) is missing... Maybe you can start with uart, timer and gpio? Then we could compare the emlib based solution against my efm32wg port to figure out the pros/cons of both approaches. Easiest would be if you just open a PR with your changes and we continue discussion there?!

One more thing: I don't think it makes sense to include all possible EFMxx CPUs that are available... So far we only include CPU(models) that are actually used on a board that RIOT supports. Otherwise we end up with millions of lines of unused header files...

**Comment by basilfx** [comment]
I have started to work on the peripheral drivers. It compiles, but it is not working yet (I have to attach the debugger and read the manual, but wanted to get the code compiling first). Especially the timer is tricky for me.

As soon as I have the Hello World running I will make a PR.

I see your point of not including all targets. I have not filtered them. However, the existing EZR32WG plus @ryankurte's EFM32G (in his branch), and I the EFM32LG, EFM32WG and EFM32GG (STK3600, STK3700 and STK3800 devkits) I have access to makes five of nine CPUs already.

**Comment by haukepetersen** [comment]
cool. So don't worry about this now, we ca sort that out together when shaping your code for merging...

**Comment by basilfx** [comment]
Quick update: got basic GPIO, USART and SPI working. Now working on timers.

I did a quick comparison of the binary sizes between the register-based approach (my initial attempt based on EZR32WG) and the emlib-based approach:

Register-based:
```
   text	   data	    bss	    dec	    hex	filename
   7816	    128	   2744	  10688	   29c0	hello-world.elf
```

emlib-based:
```
   text	   data	    bss	    dec	    hex	filename
  9544	    136	   2752	  12432	   3090	hello-world.elf
```

Not much difference, yet I can probably squeeze some more. But the code is more readable now, IMHO.

**Comment by OlegHahm** [comment]
I must confess I have little knowledge here, but 1.7kB aka 20% overhead in ROM doesn't seem to be negligible to me.

**Comment by haukepetersen** [comment]
The results look about what I had expected, in terms of efficiency even the best peripheral lib cannot compete with the direct register based approach in terms of run-time and memory.

So IMHO we should proceed like this: 
- leave the existing, register based periph implementatations (e.g. for the EZR32WG) in place
- for added implementations use the emlib for fast results
- BUT clearly mark these implementations as subject for optimization and point out the drawbacks
-> for the devices RIOT is targeting, efficiency (on all levels) is one of the most important aspects!

**Comment by basilfx** [comment]
The MCU I test on has 256kb of flash. Therefore I find the additional 1.7kb not much :-) 

I have compared both `*.map` files and found out:

1. About ~1kb of flash is used by the `CMU_*` methods. The CMU is used for setting up clocks/baudrate/speed calculations.
2. Another part of flash is occupied by initialization methods from emlib (e.g. `USART_InitAsync`). These methods ensure a consistent and valid initialization, depending on clocks/model/etc.
3. Get/set/read/write/isr-related methods are negligible/not present. They are inlined or defined as macros, resulting in similar/same code as register-based ones.

The additional cost of (1) is expected to be 'constant': adding other peripherals will depend on the same methods. 

@haukepetersen I agree. Will try to keep code compatible both ways.

**Comment by haukepetersen** [comment]
Cool, then I am looking forward to your PR!

**Comment by basilfx** [comment]
Small update:

* Still working on the device drivers. I added I2C and RTC/RTT.
* Added support for the LEUART peripherals.
* Upgraded to emlib 4.2.0, which adds support for [EFM32 Gemstone](http://www.silabs.com/Support%20Documents/TechnicalDocs/AN0918.pdf) CPUs (Pearl Gecko and Jade Gecko).
* Basic power power management.
* Cleanup/testing of code.

The new EFM32 Gemstone CPUs are a bit different. The peripherial clocks changed, GPIO interrupts changed and peripheral pin location is now flexible (for instance UART1 RX can be at location 1 while UART1 TX can be at location 7). There is now a proper RTC (not an RTT named RTC) and an extended [crypto](http://www.silabs.com/Support%20Documents/TechnicalDocs/AN0955.pdf) peripheral.

I bought the [SLSTK3401a](https://www.silabs.com/products/mcu/32-bit/efm32-pearl-gecko/Pages/efm32-pearl-gecko-starter-kit.aspx) and [STK3200](https://www.silabs.com/products/mcu/lowpower/Pages/efm32zg-stk3200.aspx) devkits to test other platforms too. As a side project I also try to integrate [u8glib](https://github.com/basilfx/RIOT/tree/feature/u8glib) as a package, to drive the LCDs on these devkits.

I still have to do a benchmark of code sizes and energy consumption. I don't regret the decision of picking the emlib, even if this means it will not get merged into RIOT-OS. It suites my needs and I learned a lot.

**Comment by basilfx** [comment]
I created PR #4722.

**Comment by basilfx** [comment]
@miri64 Yes, I am still working on it.

**Comment by PeterKietzmann** [comment]
Now that #7929 and #8139 are merged we can close this issue I guess.

**Comment by miri64** [comment]
> #8139 are merged

#8139 isn't merged yet (maybe you referenced the wrong PR?), but I agree, that since we have support for this platform now, we can close this issue.
