### ISSUE TITLE
Multiple peripheral configuration for a single board

### ISSUE THREAD

**Issue by ofauchon** [RIOT-OS/RIOT#11270]
Hi. 

I have several RIOT-OS application that need different peripheral configuration  (for a same board) eg: 

- One board configuration that uses two serial port and PWM for a RIOT application
- One board configuration that uses three serial ports for another RIOT application

There can be conflicts between the GPIOs (ex: third serial port pins  vs PWM pins)   

What is the correct way to handle multiple peripheral configuration for the same board  ? 

Should I :

1/ Duplicate board ( board/myboard_3uart and board/myboard_2serial_1pwm )
2/ Use #ifdefs GPIO_PROFILE_X in a local board/xxxxxx/include/periph_conf.h to switch peripheral config at compile time ?

Thanks for your help 

Olivier

**Comment by MrKevinWeiss** [comment]
I believe the [configuration task force](https://github.com/RIOT-OS/RIOT/wiki/Configuration-Task-Force-%28CTF%29) should be able to solve this with board configuration files but that seems to be a ways away.

Ultimately it is your choice how to do it.  In RIOT the `boards/esp32-olimex-evb/include/periph_conf.h` has an #ifdef
```c
#ifndef ADC_GPIOS
#if MODULE_OLIMEX_ESP32_GATEWAY
#define ADC_GPIOS { GPIO32, GPIO35, GPIO36, GPIO39 }
#else /* MODULE_OLIMEX_ESP32_GATEWAY */
#define ADC_GPIOS { }
#endif /* MODULE_OLIMEX_ESP32_GATEWAY */
#endif /* ADC_GPIOS */
```

I personally would prefer creating my own board file and playing around with it.  As long as it is only for you it is only up to you.
