### ISSUE TITLE
RFC 3306 Unicast-Prefix-based-IPv6 Multicast with BorderRouter

### ISSUE THREAD

**Issue by Strieglitz** [RIOT-OS/RIOT#11295]
Hello, is the **BorderRouter-Example** able to Route to **RFC 3306 Addresses** (Unicast-Prefix-based-IPv6-Multicast-Adresses)? At the time of writing i'am not sure were the Package gets lost. 

**The Structure**

- **Gcoap-Node** with RFC3306-Address added to the Interface
`ifconfig 7 add ff3e:003c:2003:5f:6e4c:8810:0:1`
- **BorderRouter** can ping this RFC3306-Address via term
- **LinuxPc(Ubuntu 16.04)** with IPv6 Forwarding enabled trying to ping the RFC3306 Address on interface tap0 from the console (with HopLimit 64 not 1 as its regular for multicast Addresses) gives no Result (pinging the global Gcoap-Node Address works)
`ping6 -I tap0 -t 64 ff3e:003c:2003:5f:6e4c:8810:0:1`

Could this be an Issue with the BorderRouter? I could imagine that the Problem is within the Linux-Routing tables or another Pc related Source, but wanted to ask if some knows if the BorderRouter knows how to handle RFC3306 Destinations. ( maybe my RFC3306 understanding is wrong too, hard to find an Example)

**Comment by miri64** [comment]
First of all, sorry for getting to this so late. GNRC is a bit flaky, when it comes to global multicast addresse, mainly due to the missing MLD implementation. This is a known issue (but I can't find it right now :-/, so let's use this as a feature request :-)
