### ISSUE TITLE
Incorporate tests/test_* application into tests/unittests if it makes sense

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#1131]
Identified candidates so far:
- [x] tests/test_bloom
- [ ] tests/test_bloom_bytes
- [x] tests/test_netif
- [ ] tests/test_posix_semaphore
- [x] tests/test_sha256

**Comment by kushalsingh007** [comment]
@phiros : So what are the part's that can be currently worked upon , Although your previous comment does explain the reason for shifting it to next release , however since it has been recently tagged as ``` Newbie-Task-Candidate```I think there might be some areas on which I could work upon , can you point out a few.

**Comment by kushalsingh007** [comment]
@authmillenon  : So what are the part's that can be currently worked upon , Although the previous comment does explain the reason for shifting it to next release , however since it has been recently tagged as ``` Newbie-Task-Candidate```I think there might be some areas on which I could work upon , can you point out a few.

**Comment by kushalsingh007** [comment]
It would be great if I could get some sort of direction to start the work.

**Comment by authmillenon** [comment]
I think in the current version this applies only `tests/libfixmath_unittests` and `tests/net_if`. `tests/libfixmath_unittests` is notorious for having problems to download from the repository (which caused a lot of false positives on Travis e.g. yesterday and why it should remain seperated from the other unittests) and `tests/net_if` is on its way of being obsolete. But if you want to, you can go through the current `sys` modules and see if there are modules where no unittests are implemented at `tests/unittests`.

**Comment by authmillenon** [comment]
(and where it makes sense. modules that involve a lot of threading or timers usually can't be tested this way for now for example)

**Comment by authmillenon** [comment]
A quick evaluation later the following modules seem like suitable candidates:

* `hashes`
* `hash_string`
* `tm`
* `utlist`

**Comment by kushalsingh007** [comment]
Thanks for having a look , working on the these now ;)

**Comment by kushalsingh007** [comment]
I think along with the tests there needs to be some change in the code itself , for instance current [hash string function] (https://github.com/RIOT-OS/RIOT/blob/master/sys/hash_string/hash_string.c#L24)
has no check to ensure that the value of variable ```hash``` does not exceed size of ```unsigned long```,
so I am changing it by breaking the loop if size is greater than ```unsigned long``` size limit . So I am changing the code too.

**Comment by authmillenon** [comment]
That is good, if errors like this surface :-), but please do the fixes in a seperate PR than the tests (or do the fixes + the tests for the module in module-wise).

**Comment by PeterKietzmann** [comment]
@authmillenon I think the list is not up to date, right?

**Comment by authmillenon** [comment]
Not really, no. But don't hesitate to update it ;-)

**Comment by PeterKietzmann** [comment]
As far as I see it there are *some* unittests fot the new netif. There are still no unittests for the semaphores. I don't get why you listed `bloom` and `bloom_bytes` separately.

**Comment by authmillenon** [comment]
Because those were seperate test applications in the `tests/` directory at the time I opened the issue.

**Comment by kYc0o** [comment]
Somehow this was reaaaally forgotten... moving for the next release.

**Comment by miri64** [comment]
To be honest, reevaluating this issue I would say it is fixed. Except `bloom_bytes` and `posix_semaphore` they are all ported to unittests, but the two tests use threads and timers respectively, so they are less suitable for unittests anyway.
