### ISSUE TITLE
Seeed Tiny BLE board

### ISSUE THREAD

**Issue by marrakchino** [RIOT-OS/RIOT#11444]
Hi,

Are there any plans to port the Seeed Tiny BLE board to RIOT?

### Useful links
* http://wiki.seeedstudio.com/Tiny_BLE/

Thanks!

**Comment by kaspar030** [comment]
Hi Nabil,

On 4/25/19 11:15 AM, Nabil Elqatib wrote:
> Are there any plans to port the Seeed Tiny BLE board to RIOT?

AFAIK noone is working on that. The used NRF51 is well supported,
though, so getting RIOT running on the board should be a matter of hours.

Kaspar

**Comment by kaspar030** [comment]
I'll close this. @marrakchino feel free to reopen if needed!
