### ISSUE TITLE
RFC: Peer review trading board

### ISSUE THREAD

**Issue by danpetry** [RIOT-OS/RIOT#11476]
#### Description

The idea is to have somewhere where people can post reviews they need doing. People reply to these postings with reviews that they need doing in turn. The two people then negotiate what both of them consider to be a fair trade in terms of work done. Also, timescales, if they wish.

Probably keeping things simple would be best. I.e. there are many different factors to consider when figuring out a like-for-like exchange of work, but this would be up to the reviewers to work out between themselves. No rules, but if people start using it, it might be helpful to gather tips from people of how best to use it.

Re implementation, I guess it would be pretty easy to do by using a Project board in github to post PRs as "ads". So, if people don't use it, there hasn't been much time spent on it.

Any thoughts?

**Comment by PeterKietzmann** [comment]
Personally, I don't think this would improve my workflow for different reasons: 
(i) I'm doing more reviews than I do provide PRs 
(ii) Whenever I can I'm doing my best to review as much as possible and what I think is most responsible ATM 
(iii) When I really need a review in time, I ask single persons directly (mailing list could be an alternative)
(iv) Eventually, this adds management overhead.
