### ISSUE TITLE
Warnings from objcopy and size (binutils 2.32)

### ISSUE THREAD

**Issue by brummer-simon** [RIOT-OS/RIOT#11472]
Hi Everyone,

I ran a Systemupdate on my Arch Linux Notebook, updating gcc and binutils. After the update,
building any RIOT application for native shows Warnings from the objcopy and size commands. I added a screenshot building the hello-world example. I don't know if this causes any issues but warnings from tools like binutils get me usually nervous ;).

![corrupt_property](https://user-images.githubusercontent.com/3950119/56981482-44c09080-6b7f-11e9-884a-2a01e87ebbb2.png)

**Comment by jcarrano** [comment]
I'm annoyed by that too. It is weird. It complains that segment GNU_PROPERTY (composed of the section ".note.gnu.property" has size zero, but readelf shows it has size 0x10.

**Comment by miri64** [comment]
Saw it as well, but don't know how to fix it :-/

**Comment by aabadie** [comment]
Is this still an issue ?

**Comment by miri64** [comment]
Did not see it for a while, but not sure.

**Comment by brummer-simon** [comment]
I didn't see it either in a long time

**Comment by miri64** [comment]
Then let's close. Seemed to have been a toolchain issue anyways.
