### ISSUE TITLE
rn2xx3_cmd_append - Not terminating strings

### ISSUE THREAD

**Issue by Alexander-M1** [RIOT-OS/RIOT#11499]
#### Description
LoRa RN2XX3 driver function `rn2xx3_cmd_append` doesn't correctly terminate strings.

#### Steps to reproduce the issue
_Arduino Due + Mikroelektronika's RN2483 module_
When calling `rn2xx3_mac_set_nwkskey (&rn2xx3_dev, nwkskey)`, where `uint8_t nwkskey[16] = {0x78, ... , 0xBE}` the RN2483 module responds with an error. The problem is, when each byte of `nwkskey` is sent, the byte is converted to a string, which is incorrectly terminated and results in the sending of additional characters, ex: `78 `.
Substituting the following lines in `rn2xx3_cmd_append(rn2xx3_t *dev, const uint8_t *payload, uint8_t payload_len)` fixed the issue:
```
//char payload_str[2];
char payload_str[3] = {0};
```

#### Expected results
`[rn2xx3] RET: 0, RESP: ok`

#### Actual results
`[rn2xx3] RET: 0, RESP: alid_param`

#### Versions
Operating System Environment
-----------------------------
       Operating System: "Ubuntu" "16.04.3 LTS (Xenial Xerus)"
                 Kernel: Linux 4.15.0-47-generic x86_64 x86_64

Installed compiler toolchains
-----------------------------
             native gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
      arm-none-eabi-gcc: arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
                avr-gcc: avr-gcc (GCC) 4.9.2
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
   xtensa-esp32-elf-gcc: missing
   xtensa-lx106-elf-gcc: missing
                  clang: clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "2.2.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
xtensa-esp32-elf-newlib: missing
xtensa-lx106-elf-newlib: missing
               avr-libc: "1.8.0svn" ("20111229")

Installed development tools
---------------------------
                  cmake: missing
               cppcheck: missing
                doxygen: 1.8.11
                 flake8: missing
                    git: git version 2.7.4
                   make: GNU Make 4.1
                openocd: Open On-Chip Debugger 0.9.0 (2018-01-24-01:05)
                 python: Python 2.7.12
                python2: Python 2.7.12
                python3: Python 3.5.2
             coccinelle: missing

**Comment by aabadie** [comment]
Thanks @Alexander-M1 for reporting this issue. I wasn't able to reproduce it but I think the fix you proposed makes sense. I opened #11658 to address your issue. Can you test ?
