### ISSUE TITLE
emcute_mqttsn example setup contains invalid steps

### ISSUE THREAD

**Issue by jvijtiuk** [RIOT-OS/RIOT#11494]
#### Description
Cannot run emcute_mqttsn example, due to invalid setup instructions in the "Setting up RIOT 'native'" section

#### Steps to reproduce the issue
Follow the instructions listed in RIOTDIR/examples/emcute_mqttsn/README.md

#### Expected results
The emcute_mqttsn example application should be able to run and successfully reproduce the behaviour documented in README.md, mainly connecting, subscribing and publishing to the RSMB MQTT-SN broker.

#### Actual results
The command 'ifconfig 5 add fec0:affe::99' fails with the following output:
SIOGIFINDEX: No such device

The issue is due to the invalid interface name 5. I've tried to unsuccessfully use tap0 instead.
Later on, due to the invalid setup the con command fails with the following output

```
> con fec0:affe::1 1885
con fec0:affe::1 1885
[emcute] syncsend: sending round 0
[emcute] syncsend: sending round 1
[emcute] syncsend: sending round 2
[emcute] syncsend: sending round 3
error: unable to connect to [fec0:affe::1]:1885
```

#### Versions
Operating system: Debian GNU/Linux 9 (stretch)
Build environment:
```
Operating System Environment
-----------------------------
       Operating System: "Debian GNU/Linux" "9 (stretch)"
                 Kernel: Linux 4.9.0-9-amd64 x86_64 unknown

Installed compiler toolchains
-----------------------------
             native gcc: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
      arm-none-eabi-gcc: arm-none-eabi-gcc (15:5.4.1+svn241155-1) 5.4.1 20160919
                avr-gcc: missing
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
   xtensa-esp32-elf-gcc: missing
   xtensa-lx106-elf-gcc: missing
                  clang: clang version 3.8.1-24 (tags/RELEASE_381/final)

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "2.4.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
xtensa-esp32-elf-newlib: missing
xtensa-lx106-elf-newlib: missing
               avr-libc: missing (missing)

Installed development tools
---------------------------
                  cmake: cmake version 3.7.2
               cppcheck: Cppcheck 1.76.1
                doxygen: missing
                 flake8: missing
                    git: git version 2.11.0
                   make: GNU Make 4.1
                openocd: Open On-Chip Debugger 0.10.0
                 python: Python 2.7.13
                python2: Python 2.7.13
                python3: Python 3.5.3
             coccinelle: missing
```

**Comment by miri64** [comment]
Hi @jvijtiuk, welcome to RIOT!

> The command 'ifconfig 5 add fec0:affe::99' fails with the following output:
> SIOGIFINDEX: No such device

This does not read like an error in RIOT. Did you type this within the native application or in Linux?

**Comment by miri64** [comment]
Looking at the README with some distance it is indeed not clear, that you have to start the RIOT application first ;-).

**Comment by miri64** [comment]
@jvijtiuk does #11495 help with that.

**Comment by jvijtiuk** [comment]
Hi @miri64 #11495 resolves the issue, I was running the command on the Linux host, not inside the RIOT native application. Thank you for the quick response :)
