### ISSUE TITLE
error in build riot helloworld with docker

### ISSUE THREAD

**Issue by jhx2002** [RIOT-OS/RIOT#11555]
Please read this post:
https://stackoverflow.com/questions/56231750/build-riot-helloworld-with-docker

**Comment by kaspar030** [comment]
Hi @jhx2002 and welcome to RIOT!

```
/home/huaxing/oproj/riot/RIOT-2019.04/dist/tools/openocd/openocd.sh flash /home/huaxing/oproj/riot/RIOT-2019.04/examples/hello-world/bin/stm32f4discovery/hello-world.elf
 Flashing Target 
sh: 1: openocd: not found
```

You'll need to install openocd. Which OS or distribution are you using?

**Comment by jhx2002** [comment]
I'v fixed it.  Thank you
