### ISSUE TITLE
Connect to MQTT-SN Gateway failed from RIOT virtual machine

### ISSUE THREAD

**Issue by jhx2002** [RIOT-OS/RIOT#11586]
setup:

- virtual network in Ubuntu 18.04

![image](https://user-images.githubusercontent.com/42711262/58411737-90475b00-80a7-11e9-9622-b378a3f88d39.png)

- from Ip6:xxx ping6  Ip6:yyy,   is OK

- from Ip6:yyy ping6  Ip6:xxx,   is OK

- broker and gateway run on host with ip4: 192.168.0.104

- MQTT-SN tools in host ,  pub and sub to gateway is OK

- connect gatway in virtual machine of RIOT ,  FAILED.  The RIOT mqttsn client see  `https://github.com/RIOT-OS/RIOT/tree/master/examples/emcute_mqttsn`

**Comment by smlng** [comment]
Hi @jhx2002 welcome to RIOT,

you must not mix IP versions, i.e. don't bind the MQTT broker to `192.168.0.104` (IPv6) but rather configure it to use IPv6 with `::` (any address). 

---

Further, can you please elaborate and clarify your setup a bit more. What is you overall goal you want to achieve from a high level perspective, i.e. without talking about what runs where and how. 

If I understood your setup correctly there are 3 players/nodes in you scenario:

1. a RIOT node running emcute example
2. a MQTT-Broker/Gateway
3. a MQTT Linux (?) node using MQTT-SN tools

The RIOT node is running in an VM and the other 2 parts are running on the host, where the VM is running too, right - so everything in one box?

**Comment by jhx2002** [comment]
Thank you @smlng .
Test a case, running gateway with ipv6. got error:
```

20190529 181941.706 MQTT-SN/gateway1 has been started.

 ConfigFile: ./gateway.conf
 ClientList: ./clients.conf
 PreDefFile: ./predefinedTopic.conf
 SensorN/W:  UDP Multicast 225.1.1.1:1883 Gateway Port 10000
 Broker:     ::C0A8:0078 : 1883, 8883
 RootCApath: (null)
 RootCAfile: (null)
 CertKey:    (null)
 PrivateKey: (null)



20190529 181943.000   error:getaddrinfo(): Address family for hostname not supported
Error: BrokerSendTask: MQTT-SN/gateway1QoS-1 can't connect to the broker. errno=0 Success 


```
