### ISSUE TITLE
phynode-kw41w/Makefile.include does not use the `common/kw41z/Makefile.include`

### ISSUE THREAD

**Issue by cladmi** [RIOT-OS/RIOT#11616]
#### Description

When migrated in https://github.com/RIOT-OS/RIOT/commit/8bd320b34ff6bbcece5ef82000b4436560000fd3 it looks like the `phynode-kw41z` `Makefile.include` was not updated to use the new `common/kw41z/Makefile.include` as was for example done for `frdm-kw41z` https://github.com/RIOT-OS/RIOT/pull/11044/commits/151803da5b80027c993e57dd576dd2b60279fef9

If it is a mistake, the board just need to be updated (not sure on my side), otherwise we have somehow an issue as partial common boards are a dangerous pattern.

#### Expected result

All the boards using `common/kw41z` use `common/kw41z/Makefile.include`.

#### Versions

Versions after https://github.com/RIOT-OS/RIOT/pull/11044

#### Reference

Found while rebasing https://github.com/RIOT-OS/RIOT/pull/11477

**Comment by aabadie** [comment]
It was made on purpose but after thinking of it a second time I came up to #11618.
