### ISSUE TITLE
gnrc_tftp: use of uninitialized values

### ISSUE THREAD

**Issue by nmeum** [RIOT-OS/RIOT#11772]
#### Description

The `gnrc_tftp_server` doesn't initialize all members of the `tftp_context_t` in `gnrc_tftp_server` causing an access of ununinitialised values when receiving messages in an unexpected order.

#### Steps to reproduce the issue

1. Build `examples/gnrc_tftp` with `make all-valgrind`
2. Run the application using `make term-valgrind`
3. Start the TFTP server using `tftps start` and wait until it started
4. Send a `DATA` tftp packet to the server, for example:

```
echo AAMAAGZvb2Jhcg== | base64 -d | nc -u '[ip-address%tap0]' 69
```

#### Expected results

Valgrind shouldn't report any accesses of uninitialised values.

#### Actual results

Valgrind reports various conditional jumps or moves which depend on uninitialised values.

**Comment by miri64** [comment]
Confirmed and fixed in #11773.
