### ISSUE TITLE
how to time sync differnt nodes in wsn?

### ISSUE THREAD

**Issue by saggl** [RIOT-OS/RIOT#11819]
#### Description
Hello I wanted to ask if there is already a service to syncronize the time in a sensor network. As it is proposed for example in the following papern FTSP, TPSN, MTS.

### Useful links
Review of Time Sync Protocols for WSN: 
http://www.airccse.org/journal/iju/papers/0410iju6.pdf

**Comment by guyyst** [comment]
Any particular reason why you closed this? I've been looking around as well and so far it seems RIOT doesn't provide any options to synchronize time across 2 nodes.

Did you find a different solution to your problem?

**Comment by saggl** [comment]
i closed the issue again because i thought it was the wrong channel for this question.
However, I would still be interested in an answer=)
