### ISSUE TITLE
cpu/lpc2387: periph_rtc completely broken

### ISSUE THREAD

**Issue by maribu** [RIOT-OS/RIOT#11908]
#### Description

PR https://github.com/RIOT-OS/RIOT/pull/11413 fixes a bug in the RTC implementation of the lpc2387. While testing the fix it become apparent, that the RTC implementation is not working at all.

#### Steps to reproduce the issue

Run `tests/periph_rtc` on the MSB-A2

#### Expected results

"Alarm!" is printed 4 times

#### Actual results

Not a single "Alarm!" is printed

#### Versions

RIOT master

**Comment by benpicco** [comment]
This should be fixed now.
