### ISSUE TITLE
nordic_softdevice_ble: Update to allow modern kernels for IPSP

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/RIOT#11951]
There is an interoperability cut in 6lo-over-bluetooth (Bluetooth's IPSP) that happened in Linux around 4.12 and in nRF SDK between the currently-used "nRF IoT SDK" and the "nRF SDK" (which supports it at least since the [14.1 release](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v14.1.0%2Fiot_sdk_user_guides_linux_commands.html))

The current [documentation in RIOT](https://github.com/RIOT-OS/RIOT/blob/master/pkg/nordic_softdevice_ble/README-BLE-6LoWPAN.md) says it requires the old behavior by indicating the maximum supported Linux version as 4.12.

Please consider updating the upstream version, allowing to set `BLE_6LOWPAN_LEGACY_MODE = 0`, and updating the documentation.

(Note this is all from reading current documentation; I did not test the behavior as I don't have suitable hardware yet, so the fix might be as easy as stating in the documentation that RFC7668 mode can be enabled).

**Comment by miri64** [comment]
I'm not sure about the future of the nordic softdevice, however for IPSP there is also #11578 as an alternative.

**Comment by haukepetersen** [comment]
AFAIK there is nobody working on the Nordic Softdevice integration in RIOT currently, and not sure if anyone plans to do so in the near future...

The (soon to be) default BLE stack in RIOT is NimBLE, where all our efforts go into. As @miri64 stated, #11578 is the first step towards IP-over-BLE support using NimBLE. However, I did not test this agains Linux (yet), and there are most likely some more adaptions in GNRC needed to make it fully compliant to RFC7668 and the upcoming draft-ietf-6lo-blemesh-05. I am actively working on this as we speak :-)

**Comment by miri64** [comment]
See also https://github.com/RIOT-OS/RIOT/pull/9473.

**Comment by miri64** [comment]
@chrysn is this still up-to-date given that we now have nimble support?

**Comment by chrysn** [comment]
Yes, but solving it is easier. A notice about, depending on what's the case, "This module is deprecated, use NimBLE" or "This module is supported, but has severe shortcomings in interoperability, use NimBLE if you need to interoperate with modern Linux kernels" would do.

I can put the documentation in a PR, but would need some direction on where nortic_softdevice_ble is going.

**Comment by miri64** [comment]
> I can put the documentation in a PR, but would need some direction on where nortic_softdevice_ble is going.

@kaspar030 @haukepetersen @pekkanikander and others might better know about this. How about opening that PR and then discuss it there.

**Comment by kaspar030** [comment]
> where nortic_softdevice_ble is going.

IMO, let's try to not use it anymore. It was a closed source blob. I'd rather concentrate on Nimble.

**Comment by chrysn** [comment]
Opened as #13334. Actually I'm closing this here right away, as it *is* a duplicate of #9473 (and #13334 is just documenting that those exist and are not expected to move forward).
