### ISSUE TITLE
tests: Examine the need for thread_sleep() in test_hwtimer

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1204]
In #1083 a `thread_sleep()` at the end of `test_hwtimer` was introduced to assure that a broken `thread_exit()` for any platform would not interfere with intended testing functionality. However, this is suboptimal and prevents the test from terminating which is desirable for automatic testing.

**Comment by PeterKietzmann** [comment]
@Kijewski any ideas?

**Comment by PeterKietzmann** [comment]
@OlegHahm so do you suggest to remove the `thread_sleep()` again?

**Comment by OlegHahm** [comment]
Actually, yes, I think that would be the most sensible option. However, a (unit)test for `thread_exit()` would be very useful for this.

**Comment by kaspar030** [comment]
+1 for removing the sleep
