### ISSUE TITLE
How to use w5100 with stm32f4

### ISSUE THREAD

**Issue by jhx2002** [RIOT-OS/RIOT#12076]
Is there any difference of pin wiring and ip address setting between w5100 and enc28j60 ? 
I try to use w5100, but can not ping6 successfully.

**Comment by jhx2002** [comment]
Can you share  experience on how to use w5100 ?  Thank you @maribu

**Comment by maribu** [comment]
Does it initialize? For me it only worked on a cold boot. Maybe I have time to PR a fix for that today.

Some boards (e.g. some Arduinos) reboot when the shell is connected. Surprisingly, on Arduinos I didn't experience the issue. I assume that the reset pin on the ISP pin header of my W5100 shield is connected to the reset pin of the W5100, reproducing the cold boot experience on reboot.

On Nucleos and the nRF52840DK the reset pin seems to not emit a signal when the board reboots, preventing a hardware reset of the shield. (At least that is my theory.)
