### ISSUE TITLE
gnrc_tcp leaks memory when gnrc_netapi_send fails

### ISSUE THREAD

**Issue by nmeum** [RIOT-OS/RIOT#12081]
`gnrc_tcp` uses `gnrc_netapi_send` in two places:

https://github.com/RIOT-OS/RIOT/blob/20dec77e39cd68b5915b6a13b2dcae2bb2f2da2a/sys/net/gnrc/transport_layer/tcp/gnrc_tcp_eventloop.c#L221

https://github.com/RIOT-OS/RIOT/blob/45989aa60e1bd2def064e1dd321116f5bbc7ef6e/sys/net/gnrc/transport_layer/tcp/gnrc_tcp_pkt.c#L274

Unfortunately, the return value isn't checked and it seems to me that the caller is responsible for freeing the pktbuf memory on error. As an example: Consider how `gnrc_ipv6` handles this:

https://github.com/RIOT-OS/RIOT/blob/7f2cc4f0b39f5c920fc12045644902891e6a3979/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L262-L265

This shouldn't be a big issue as `gnrc_netapi_send` only fails when `msg_try_send` fails this is just a minor issue I noticed while debugging #12001.

**Comment by brummer-simon** [comment]
I'll look into it on the Weekend.
