### ISSUE TITLE
boards/lobaro-lorabox: blindly sets TERMFLAGS

### ISSUE THREAD

**Issue by jcarrano** [RIOT-OS/RIOT#12090]
#### Description

The lorabox board directly sets termflags in a way that it break when the user requests a terminal different from the default (pyterm).

#### Steps to reproduce the issue

Try to use RIOT_TERMINAL=socat.

This is the offending line:

https://github.com/RIOT-OS/RIOT/blob/e2b2b8e43cbaad911fc6156e9beb574b675d12a3/boards/lobaro-lorabox/Makefile.include#L20

**Comment by cladmi** [comment]
I added a PR to not use `TERMFLAGS` directly https://github.com/RIOT-OS/RIOT/pull/12095

**Comment by aabadie** [comment]
This was fixed by #12095.
