### ISSUE TITLE
ESP_now network module has warnings during compile.

### ISSUE THREAD

**Issue by LordTy** [RIOT-OS/RIOT#12257]
#### Description

The esp_now module gives a warning when compiling. Thus it will stop due to WERROR=1.

#### Steps to reproduce the issue

1. Checkout the RIOT tutorial according to the instructions
2. Install riot/riotbuild in docker according to: 
http://doc.riot-os.org/group__cpu__esp32.html#esp32_manual_toolchain_installation
2. Go to task-05
2. Add USEMODULE+=esp_now to the makefile
3. connect esp32/esp8266 board.
4. Try to make and flash te example using:
`make BOARD=ESP32-WROOM-32 PORT=/dev/cu.usbmodem1410 BUILD_IN_DOCKER=1 all`
or 
`make BOARD=ESP8266-esp-12x PORT=/dev/cu.usbmodem1410 BUILD_IN_DOCKER=1 all`

#### Expected results

Everything builds without errors

#### Actual results

You get the error:

    error: unused variable 'hdr' [-Werror=unused-variable]
     esp_now_pkt_hdr_t *hdr = (esp_now_pkt_hdr_t*)esp_hdr->data;
                        ^
    cc1: all warnings being treated as errors

And the build stops.

Adding WERROR=0 is a workaround, but should not be required.

#### Versions

Operating System Environment
-----------------------------
       Operating System: Mac OS X 10.14.5
                 Kernel: Darwin 18.6.0 x86_64 i386

Installed compiler toolchains
-----------------------------
             native gcc: Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
      arm-none-eabi-gcc: missing
                avr-gcc: avr-gcc (GCC) 4.8.1
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
      riscv-none-embed-gcc: missing
      xtensa-esp32-elf-gcc: missing
      xtensa-lx106-elf-gcc: missing
                  clang: Apple LLVM version 10.0.1 (clang-1001.0.46.4)

Installed compiler libs
-----------------------
      arm-none-eabi-newlib: missing
      mips-mti-elf-newlib: missing
      riscv-none-embed-newlib: missing
      xtensa-esp32-elf-newlib: missing
      xtensa-lx106-elf-newlib: missing
      avr-libc: "1.8.0svn" ("20111229")

Installed development tools
---------------------------
                  cmake: cmake version 3.15.3
               cppcheck: Cppcheck 1.82
                doxygen: missing
                    git: git version 2.16.2
                   make: GNU Make 3.81
                openocd: Open On-Chip Debugger 0.10.0
                 python: Python 2.7.15
                python2: Python 2.7.15
                python3: Python 3.7.4
                 flake8: error: /usr/local/opt/python/bin/python3.7: No module named flake8
             coccinelle: missing

**Comment by gschorcht** [comment]
@benpicco Many thanks for fixing the problem. I also realized the problem when I was starting to investigate issue #12258. Unfortunatly, we haven't seen this warning since we always checked `esp_now` and `esp_wifi` network devices with the `examples/gnrc_networking` application which enables module `gnrc_ipv6` which in turn enables `gnrc_sixlowpan` by default.
