### ISSUE TITLE
tests / pkg: Applications for packages missing

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1231]
There are no applications for the external libraries like libcoap, OpenWSN, or oonf_api. That's particular bad for two reasons:
1.) Breaking these packages is more likely since the CI does not even build against them.
2.) It's quite difficult for new users to find these libraries.

**Comment by haukepetersen** [comment]
postponed to 2016.07, as no new application that would fix this made it in before feature freeze

**Comment by kYc0o** [comment]
Someone has a hint on how this issue can be addressed? BTW for this release it seems to be difficult to find something, so I need to postpone it.

**Comment by miri64** [comment]
@kYc0o build an application that uses a package for that there isn't any application at the moment.

**Comment by OlegHahm** [comment]
libcoap and oonf_api have test applications, OpenWSN is about to be removed.
