### ISSUE TITLE
Context health checker

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1233]
It would be very helpful, particular when porting RIOT to new architectures, to have a automatic test that checks if context switching works correctly.

For discussion see also http://lists.riot-os.org/pipermail/devel/2013-October/000352.html

**Comment by miri64** [comment]
Any news?

**Comment by thomaseichinger** [comment]
No, no news from my side on this.

**Comment by OlegHahm** [comment]
phew...
