### ISSUE TITLE
Undocumented uint8_t assumptions in nrf52840 peripherals

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/RIOT#12370]
### Description

The nrf52840 peripherals jump back and forth between using gpio_t (not overridden, defaulting to unsigned int) and uint8_t (eg. in `cpu/nrf52/include/periph_cpu.h`). GPIOs are cast to uint8_t without further explanation (eg. in `boards/nrf52840-mdk/include/periph_conf.h`) when assigning to uart_conf_t's rts_pin, which is indeed uint8_t, but then cast back when the UART_PIN_RX (which peeks in there) is fed to `gpio_init` in `cpu/nrf5x_common/periph/uart.c:108`, of which I'm not sure why it works with the thusly truncated GPIO_UNDEF at all (probably that code path is not hit when it's undef, and the valid GPIO numbers all happen to fit in a uint8_t).

I had a glimpse of hope for understanding when I read in the next line that the value was fed directly into a peripheral configuration register (`PSEL_RXD = UART_PIN_RX`), but even that takes the pin as a u32 (or rather 31-bit pin number with the highest bit 0 meaning connect and 1 meaning disconnect, which'd be a straight fit for GPIO_UNDEF except it's coming along truncated to u8).

#### Steps to reproduce the issue

Look for unrelated errors in the GPIO setup, get confused by the undocumented casts.

#### Expected results

A consistent type should be used for GPIO unless there is good reason for a deviation, which should be documented.

Especially, if the gpio_t value construction in the GPIO_PIN macro are aligned with the platform's register definitions, that should be pointed out there.

If memory use for a gpio_t is a concern, uint8_t could be used consistently (and if the "GPIO_UNDEF means disconnected' property should hold, which kind of makes sense but is not currently the case as I understand, there could still be a `uint32_t pin_number_from_gpio(gpio_t)` function that does a signed int8_t to int32_t cast and thus efficiently gets the 1 bit in the right position).

#### Actual results

I'm confused and unsure of whether there is an actual point in having uint8_t around at some places, but not on others.

#### Versions

Current RIOT master.

#### Suggestions for next steps

Find there's a reason for this and document it, or decide on a size of gpio_t and switch all users there. (There'd be a third possibility of having both a fastgpio_t and leastgpio_t, one of which is the actual gpio_t, with adaequate conversion fuctions, which could lead to identical machine code as in the current situation, but it'd be a first).

**Comment by SemjonKerner** [comment]
Thanks for assigning me.
I understand this is confusing and you are right with your call for consistency, but since it's not actually a breaking bug I am not touching it.
