### ISSUE TITLE
How to detect RIOT-OS toolchain?

### ISSUE THREAD

**Issue by rurban** [RIOT-OS/RIOT#12575]
I need to detect in my C header if the library was compiled on riot-os.
I need some defined cc predef to check for, as in
https://sourceforge.net/p/predef/wiki/OperatingSystems/

something like
```
#ifdef __RIOT_OS__
```

**Comment by kaspar030** [comment]
`#ifdef RIOT_VERSION` should work. It is passed to every file compiled using the RIOT build system.

**Comment by rurban** [comment]
Thanks a lot
