### ISSUE TITLE
Weak ref not working for led_init

### ISSUE THREAD

**Issue by schlatterbeck** [RIOT-OS/RIOT#12618]
Weak symbols: we have a board-specific led_init in board.c which ends up in board.a. It is still not linked instead of the default weak led_init in atmega/board.c because when our board.a is parsed by the linker, the led_init symbol is not yet open. Later when the boards_common_atmega.a is parsed the default weak led_init is used. Any way around this behaviour? How do other boards solve this?

Note that if we could somehow force the linking of the board.a the issue would be solved because board.a contains the non-weak symbol and even if the led_init is later used it would use the already-present led_init in board.a.

Also note that reversing the order of linking of the .a files would *not* fix the issue because the reference to led_init in boards_common_atmega.a would be satisfied by the weak ref in the same file. So a later static lib would not be linked in because the symbol is already satisfied.

#### Steps to reproduce the issue
Define a board.c for a given atmega-derived board that *only* contains a led_init
When compiling observe that the weak led_init from atmega/board.c  is used and the object resulting from compilation of board.c never makes it into the .elf -- this can be checked with nm or objdump.

#### Expected results
The code from the board-specific board.c should always end up in the executable. Maybe it should not be put into a static lib (.a) but into an unconditionally linked .o

#### Versions
We have a (not yet integrated) atmega RFR-2 based board. We're using current trunk. Build is avr-gcc 5.4.0 in debian buster. But the behaviour of weak symbols hasn't changed for some time, so this is probably reproduceable with any avr-gcc version.

**Comment by mexx42** [comment]
Maybe one solution could be to link against the boards .o files and not the .a files. As symbols in the .a files are not considered if the linker already has a symbol at hand (the weakref which is defined in the same file as where it is used) see: [https://stackoverflow.com/questions/51656838/attribute-weak-and-static-libraries](https://stackoverflow.com/questions/51656838/attribute-weak-and-static-libraries)
