### ISSUE TITLE
sys: the TLSF implementation contains (a) read-before-write error(s)

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#1263]
Merge #1259, compile and run the mere hello-world example, see the debug messages.

The library either needs a proper source code review, or at least a dynamic examination in valgrind. Findings should be pushed upstream.

**Comment by PeterKietzmann** [comment]
Is this outdated?

**Comment by OlegHahm** [comment]
I somehow fail to build for qemu-i386 at all.

**Comment by OlegHahm** [comment]
Because master is not building...

With the fixed master I still get the warnings when building hello-world as followed:
`CFLAGS=-DDEBUG_READ_BEFORE_WRITE BOARD=qemu-i386 make -B clean all term`

**Comment by haukepetersen** [comment]
@OlegHahm this will not be fixed for this release, right?

**Comment by OlegHahm** [comment]
I don't think so.

**Comment by OlegHahm** [comment]
-> known issue?

**Comment by haukepetersen** [comment]
yes.

**Comment by kaspar030** [comment]
any news here?

**Comment by OlegHahm** [comment]
I was probably the RIOTer with the most extensive use of TLSF over the last three months, but apart from concurrency issues with calloc() I couldn't find a problem.

**Comment by kYc0o** [comment]
Should we close it then?

**Comment by Kijewski** [comment]
> Should we close it then?

No.

**Comment by kYc0o** [comment]
Then it will postponed since there is no PR solving this bug.

**Comment by Kijewski** [comment]
@OlegHahm, @emmanuelsearch, there are enough bored out BSc students, aren't there? Maybe implementing TLSF from scratch according to [its paper](http://www.gii.upv.es/tlsf/files/ecrts04_tlsf.pdf), and comparing it to more common allocators would make an interesting bachelor thesis?

**Comment by kYc0o** [comment]
Is this still an issue?

**Comment by kYc0o** [comment]
@jcarrano did you fix this?

**Comment by jcarrano** [comment]
Duplicate of #5796
