### ISSUE TITLE
LPC2387 MCI driver init timeout

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#127]
A proper check for an inserted memory card is missing. Therefore, initialization runs into an timeout.

**Comment by x3ro** [comment]
You mean this check? https://github.com/RIOT-OS/RIOT/blob/master/cpu/lpc2387/mci/lpc2387-mci.c#L532

**Comment by OlegHahm** [comment]
I reported this issue three years ago - so I don't remember what was causing the timeout. Can you reproduce the problem?

**Comment by x3ro** [comment]
In my case, the condition I linked to was triggered when I had no card inserted. So no, I couldn't really reproduce the timeout :D

**Comment by miri64** [comment]
So.... close?

**Comment by x3ro** [comment]
It's been around for three years, I couldn't reproduce it and there doesn't seem to be any interest from anyone else, so I'd say yes.
