### ISSUE TITLE
sys\net\gnrc\link_layer\lwmac: cast error with avg-gcc

### ISSUE THREAD

**Issue by chudov** [RIOT-OS/RIOT#12869]
#### Description
Cast error in gnrc_lwmac while build test/gnrc_lwmac for AVR-based derfmega256 board. 
Similar to #12853.
#### Steps to reproduce the issue
- Take RIOT-OS latest master
- Update the file tests/gnrc_lwmac/Makefile :  
`-BOARD_WHITELIST := samr21-xpro`
`+BOARD_WHITELIST := samr21-xpro derfmega256` 
- Execute `BOARD=derfmega256 make all`

#### Expected results
The tests/gnrc_lwmac builds on deRFmega256 without errors.

#### Actual results
cast error:
`/RIOT/sys/net/gnrc/link_layer/lwmac/lwmac.c: In function ‘rtt_cb’:
/RIOT/sys/net/gnrc/link_layer/lwmac/lwmac.c:679:26: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]`
`     msg.content.value = ((uint32_t) arg) & 0xffff;`
`                          ^`
`cc1: all warnings being treated as errors`

#### Versions
RIOT latest master

**Comment by herjulf** [comment]
For what's is worth. Also with rtt patches. Casting the pointer to 16bit on avr-rss2 similar oops/panic

```
main(): This is RIOT! (Version: 2020.01-devel-1239-gbd254d)
LWMAC test application
> IRQ_STATUS 0x81
IRQ_STATUS1 00
SCIRQS 00
BATMON 0x22
EIFR 00
PCIFR 00
*** RIOT kernel panic:
ze: %3i byte


```
It's still some sort of result...
