### ISSUE TITLE
kconfiglib: only pull when needed

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#12920]
#### Description
Currently I'm sitting on a train with a machine that did not build with newest master yet. The consequence: I'm waiting for at least 5 min for `kconfiglib` to be pulled due to the slow WiFi here, even though I don't want to configure anything with kconfig at the moment.

#### Steps to reproduce the issue
Make sure `kconfiglib` is not downloaded yet, start a build e.g. `make -C examples/hello-world`.

#### Expected results
Unless required, `kconfiglib` should not be pulled.

#### Actual results
`kconfiglib` is pulled in any case.

#### Versions
Current RIOT master (f44d9f8)

**Comment by dylad** [comment]
Is this somehow related to #11491 ?

**Comment by miri64** [comment]
No not really, that one is about fetching (updating) a packet when it is already there. My problem relates to a specific packet being downloaded (cloned) in the first place even if it is not needed.

**Comment by leandrolanzieri** [comment]
> My problem relates to a specific packet being downloaded (cloned) in the first place even if it is not needed.

Kconfig runs on every build. Even if no modules get configured, it will read the root `Kconfig` file, it cannot know beforehand that it will produce no configuration values.

One way of solving this problem you just had could be to place the needed files in `dist/tools/kconfiglib` instead of pulling them from the repo.

**Comment by miri64** [comment]
> One way of solving this problem you just had could be to place the needed files in `dist/tools/kconfiglib` instead of pulling them from the repo.

How about using a submodule instead?

**Comment by miri64** [comment]
Or another alternative: this is (optional!) tooling, so we could also just only use it **if** it is available. Why is this bootstrapped on build anyway. We could just expect the user to install it, as we do with the toolchain, libc, and the build system as well.

**Comment by leandrolanzieri** [comment]
> We could just expect the user to install it, as we do with the toolchain, libc, and the build system as well.

@miri64 This seems reasonable, given that the tool can be installed from [PyPI](https://pypi.org/project/kconfiglib/). We could check if it is present before including `makefiles/kconfig.mk`.

**Comment by kaspar030** [comment]
> Kconfig runs on every build. Even if no modules get configured, it will read the root `Kconfig` file, it cannot know beforehand that it will produce no configuration values.

As in, use of Kconfig is not optional, as the build is broken if kconfiglib is not available?
Can't Kconfig be guarded, e.g., by (OR'ed)

1. user calls "make menuconfig"
2. there's a config file created by a previous run of "make menuconfig"
3. a Kconfig Kconfig file is present in APPDIR?

**Comment by ulfalizer** [comment]
I'm a bit old-school, but I'd just copy the scripts into the project. It's so simple it's really hard for it to break. :)
