### ISSUE TITLE
Gcoap: Clarify idempotency requirements

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/RIOT#12938]
Currently, the Gcoap documentation says nothing about idempotency; from that, it'd be perfectly OK to implement, say, a toggling POST.

I did not find any code in Gcoap that handles message deduplication (ie. caching the response to a CON request for EXCHANGE_LIFETIME, or radio-inefficiently answering all CONs with non-piggybacked CON responses that only need to stay around as long as they are retried), which admittedly would require some ample buffer space, and is generally not easy on a constrained system.

Not doing deduplication on non-idempotent requests opens the application up to replay attacks in DTLS. (Where a MitM delays a message containing a Toggle, lets the retransmission and its response through, and then sends the original message and it toggles the state back to its original value.)

The easiest solution would be to put a requirement around the resource registration and coap_handler_t that all handlers must be idempotent, ie. not have any additional side effects when called consecutively. That is already a requirement for GET, PUT and DELETE handlers per RFC7252, and imposing it on all remaining handlers would suffice to justify the permanent omission of deduplication. Given that applications for contrained devices should be designed to allow that optimization, this should work.

If someone could confirm that Gcoap does not do deduplication, I'll write a PR to change the documentation accordingly.

**Comment by kb2ma** [comment]
@chrysn, apologies for the delay in responding. You are correct. Neither gcoap or nanocoap acting as a server includes any request tracking to deduplicate requests. I am happy to review a PR that discusses the lack of deduplication and the value of resource idempotency for security.
