### ISSUE TITLE
net: more statistics!

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1297]
For testing and experimentation statistics on all layers are really helpful. I'm thinking about stats like
* sent and received packets
* different packet types
* retransmissions
* detected error cases like collisions, duplicates, orphaned fragments etc.

**Comment by authmillenon** [comment]
Still interesting (and a lot easier to do) in the new network stack.

**Comment by OlegHahm** [comment]
:+1:

**Comment by haukepetersen** [comment]
@OlegHahm: I guess this issue is still of interest but only partly fixed by #4801. So I would keep this open for the next release?!

**Comment by OlegHahm** [comment]
I would also be okay with closing this one and open a more specific one for the next release. This issue was mostly meant as a reminder to tackle this issue at all - which is handled by #5176.

**Comment by haukepetersen** [comment]
will you do this, then?

**Comment by OlegHahm** [comment]
Done, see #5318.
