### ISSUE TITLE
Try dtls riot on ubuntu

### ISSUE THREAD

**Issue by jabberimaher** [RIOT-OS/RIOT#12976]
Hi,
please i hope to implement dtls with riot os (ubuntu) and measure the energy consumption , the time execution by  node communicate with server.
thanks a lot

**Comment by miri64** [comment]
Welcome @jabberimaher! We have two packages already that support DTLS: [`tinydtls`](https://doc.riot-os.org/group__pkg__tinydtls.html) and [`wolfssl`](https://doc.riot-os.org/group__pkg__wolfssl.html). RIOT comes with three examples that might help you get it running for your own application:

- [`examples/dtls-echo`](https://github.com/RIOT-OS/RIOT/tree/master/examples/dtls-echo): a basic `tinydtls` example
- [`examples/dtls-sock`](https://github.com/RIOT-OS/RIOT/tree/master/examples/dtls-sock): usage of the `sock_dtls` API with the `tinydtls` implementation
- [`examples/dtls-wolfssl`](https://github.com/RIOT-OS/RIOT/tree/master/examples/dtls-wolfssl): usage of DTLS with `wolfssl`.

**Comment by jabberimaher** [comment]
thank you for your answer,
i tried dtls-sock, i follow steps of the link... but when i launch command "dtlsc <4A:E0:42:98:75:C5> "data" ...it display  error parsing destination adress..it seems that can't read correctly the destination adress... 
best regards

**Comment by miri64** [comment]
> i tried dtls-sock, i follow steps of the link... but when i launch command "dtlsc <4A:E0:42:98:75:C5> "data" ...it display error parsing destination adress..it seems that can't read correctly the destination adress...

That looks more like a MAC address than an IP address. Also, the `<>` are just to denote a variable in doc. So have you tried something like `dtlsc fe80::... "data"`?

**Comment by pokgak** [comment]
Using the command as stated @miri64 above will solve your problem. I also want to point to documentation of [DTLS support](http://api.riot-os.org/group__net__dtls.html) in RIOT.

**Comment by miri64** [comment]
Sorry, hit the wrong button. @jabberimaher does this solve your problem?

**Comment by jabberimaher** [comment]
Hi, thank you
with dtls-echo it display:
dtlsc fe80::80be:30ff:febb:8909 "DATA to send under encrypted channel!"
Client: got DTLS Data App -- DATA to send under encrypted channel! --

**Comment by miri64** [comment]
So I guess it is solved?

**Comment by jabberimaher** [comment]
Now if i want to display ergy onsumption , time execution and occupation memory of node when executing dtls...... so i want to compare between three authentication algorithms (DTLS, MDA,..) by measuring for each algorithm the metrics of performances (time , energy, memory, throughput) , it's possible with riot?...
i will be very grateful for your help

**Comment by miri64** [comment]
This should be discussed in #12979 ;-). Closing this issue.

**Comment by jabberimaher** [comment]
thank you
