### ISSUE TITLE
sys: replace `timex_t` with `struct timeval`

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#1305]
Our `timex_t` describes the same values as the standardized `struct timeval`:

``` c
typedef struct timex_t {
    uint32_t seconds;
    uint32_t microseconds;
} timex_t;

struct timeval {
    time_t         tv_sec;
    suseconds_t    tv_usec;
};
```

Removing our own name makes implementing standards compatibility easier.

**Comment by authmillenon** [comment]
I guess we postpone it again ;-)

**Comment by kYc0o** [comment]
And postponed again?

**Comment by Kijewski** [comment]
> And postponed again?

Seems so, unless you want to open a last-minute PR.

**Comment by kYc0o** [comment]
It wasn't solved by #1843?

**Comment by Kijewski** [comment]
`timex_t` is still used in 18 files. Most of the seem to be unit tests, though.

**Comment by kYc0o** [comment]
Uhm... I don't know if postpone it since it's a minor issue, but it's true that adding compatibility with standards is one of our main goals... Let's see if I have time to change it before the feature freeze.

**Comment by kYc0o** [comment]
I didn't addressed this issue so I'll postpone it.

**Comment by miri64** [comment]
Clearing milestone because there doesn't seem to be much traction behind this family of issues.
