### ISSUE TITLE
C++ on the boards

### ISSUE THREAD

**Issue by BytesGalore** [RIOT-OS/RIOT#1323]
RIOT now provides a seamless c and c++ handling in the RIOT build system for user applications.
But using c++ on specific boards requires adjustments, e.g. (un)set specific compiler and linker flags, provide/change system calls or even provide a custom tweaked compiler.

Here we can track the progression of board support and discuss related issues.
- \- [x] Family: native
  - \- [x] native
- \- [x] Family: ARM
  - \- [x] Airfy Beacon
  - \- [x] Arduino Due
  - \- [x] cc2538dk
  - \- [x] f4vi1
  - \- [x] IoT LAB_M3
  - \- [x] mbed_lpc1768
  - \- [x] MSB-IoT
  - \- [x] MSBA2
  - \- [x] Mulle
  - \- [x] OpenMote
  - \- [x] PCA1000x
  - \- [x] Phytec phyWAVE KW22
  - \- [x] Samr21 xpro
  - \- [x] Spark Core 
  - \- [x] STM32F0discovery
  - \- [x] STM32F3discovery
  - \- [x] STM32F4discovery
  - \- [x] UDOO
  - \- [x] yunjia-nrf51822
- \- [ ] Family: ATmega
  - \- [ ] Arduino Mega2560
  - \- [ ] Arduino Uno
  - \- [ ] Arduino Duemilanove
- \- [ ] Family: MSP430
  - \- [ ] eZ430-Chronos
  - \- [ ] MSB-430H
  - \- [ ] TelosB
  - \- [ ] WSN430
  - \- [ ] Zolertia Z1
- \- [ ] Family: x86
  - \- [ ] Intel Galileo

**Comment by kausthub** [comment]
hi i am a new comer , can you help me on how to get started with this issue ? few links or what am i looking to resolve ? 
thanks in advance

**Comment by OlegHahm** [comment]
@BytesGalore, @josephnoir, since @dangnhat has become quite silent recently, maybe you can help here.

**Comment by dangnhat** [comment]
Sorry for the long silence after I finished my thesis (I think I have enjoyed Lunar New Year holiday too much :D )

@kausthub : There may be two directions to go from here:
First, we can continue providing the basic C++ programming for the remaining boards. (I'm working on Intel Galileo now, and @BytesGalore might be working on msp430 board, so if you choose this direction then avr might be the good way to go :-) ). The basic idea is to compile C++ project as easy as possible. To do that we might want to change RIOT's build system so understanding the makefiles is needed. You might want take a quick look at PR #981 (https://github.com/RIOT-OS/RIOT/pull/981). It introduce the main idea and some new Make variables. Some Googling is also needed.

Second, we can try and test some other features on the boards which can compile C++ such as STL; evaluate the resource needed and its real time capacity. I don't have much experiences about this so Google might be your good friend. ;-)

Other comments are welcome if I missed something.

**Comment by OlegHahm** [comment]
@dangnhat, no need to apologize! I'm really happy to see that you're still aboard! :)

**Comment by dangnhat** [comment]
@OlegHahm : I'm so glad to hear that! :D

**Comment by josephnoir** [comment]
Maybe this is a good place to discuss the `void* __dso_handle` i added to the stm32f4 startup file in #2540. I guess this is required for all boards? Other question would be why this was never notices before. [Here](http://wiki.osdev.org/C%2B%2B) is some information on the handle.

**Comment by dangnhat** [comment]
On the very first day of C++ support in RIOT, I had to add this handle to startup file to compile C++ code on iot-lab_M3 which has destructors, but when I create PR to support C++ for iot-lab_M3, this problem somehow disappeared. At that time, I didn't found any clear document about it (I have read your link before) so I leave this handle aside. Therefore, if we can come up with some clear documents about the necessity of ```__dso_handle``` then we can easily add this to our startup files. :-)

**Comment by gebart** [comment]
see #3107 for `__dso_handle` and some other definitions that may help for general C++ support.

**Comment by haukepetersen** [comment]
ongoing effort, modified milestone...

**Comment by josephnoir** [comment]
As this still is an ongoing effort, I wanted to add that support for static initialization would be nice. Some time I go, I used the code below to achieve this on the native board. I don't remember the problems with other boards though. Not sure if there is a generic solution or if this is board dependent.

```C
#if (defined(__GNUC__) || defined(__GNUG__)) && !defined(__clang__)
    /* manually call other contructors in __init_array which haven't been called */
    typedef void (*func_ptr)(void);
    extern func_ptr __init_array_start[];
    extern func_ptr __init_array_end[];
    int size = __init_array_end - __init_array_start;
    int i, flag = 0;
    for (i = 0; i < size; i++) {
        if (__init_array_start[i] == startup) {
            flag = 1;
            continue;
        }
        if (flag == 1){
            (__init_array_start[i])();
        }
    }
#endif
```

**Comment by josephnoir** [comment]
Exceptions are printed, by can't be caught in code it seems. Here is my test and the output.

Test code (from [here](http://www.tutorialspoint.com/cplusplus/cpp_exceptions_handling.htm)):
```C++
#include <cstdio>
#include <exception>
using namespace std;

struct MyException : public exception
{
  const char * what () const throw ()
  {
    return "C++ Exception";
  }
};

int main()
{
  try
  {
    throw MyException();
  }
  catch(MyException& e)
  {
    printf("MyException caught");
    printf("%s",e.what());
  }
  catch(std::exception& e)
  {
    //Other errors
  }
}
```

Output from samr21-xpro:
```
2016-05-06 21:17:42,019 - INFO # main(): This is RIOT! (Version: 2016.03-devel-1800-gefb1-mobi19.inet.haw-hamburg.de)
2016-05-06 21:17:42,021 - INFO # *** RIOT kernel panic:
2016-05-06 21:17:42,023 - INFO # UNHANDLED C++ EXCEPTION
2016-05-06 21:17:42,023 - INFO # 
2016-05-06 21:17:42,024 - INFO # *** halted.
2016-05-06 21:17:42,025 - INFO # 
2016-05-06 21:17:42,025 - INFO # 
2016-05-06 21:17:42,027 - INFO # Context before hardfault:
2016-05-06 21:17:42,028 - INFO #    r0: 0x00000000
2016-05-06 21:17:42,030 - INFO #    r1: 0x00000000
2016-05-06 21:17:42,032 - INFO #    r2: 0x20000834
2016-05-06 21:17:42,033 - INFO #    r3: 0x000001b3
2016-05-06 21:17:42,035 - INFO #   r12: 0x00000000
2016-05-06 21:17:42,036 - INFO #    lr: 0x000001bb
2016-05-06 21:17:42,038 - INFO #    pc: 0x00000350
2016-05-06 21:17:42,039 - INFO #   psr: 0x41000000
2016-05-06 21:17:42,040 - INFO # 
2016-05-06 21:17:42,040 - INFO # Misc
2016-05-06 21:17:42,042 - INFO # EXC_RET: 0xfffffffd
2016-05-06 21:17:42,046 - INFO # Attempting to reconstruct state for debugging...
2016-05-06 21:17:42,047 - INFO # In GDB:
2016-05-06 21:17:42,048 - INFO #   set $pc=0x350
2016-05-06 21:17:42,049 - INFO #   frame 0
2016-05-06 21:17:42,049 - INFO #   bt
```

**Comment by josephnoir** [comment]
Regarding static initialization. Tested that on the samr21-xpro and it worked. I didn't find the issue or the PR that is why I asked. Here is my test code (maybe, we should add a test for that):

```C++
#include <cstdio>
#include <cassert>

using namespace std;

namespace {
  constexpr int val = 2;
}

struct my_struct {
  my_struct() : data(val) { }
  int data;
};

static my_struct ms;

int main() {
  printf("\n************ C++ const initialization test ***********\n");

  assert(ms.data == val);

  printf("Done.\n");
  printf("********************************************************\n");
  return 0;
}
```

**Comment by kYc0o** [comment]
As there's still some ongoing work, I'll mark this issue for the next release. Thanks for the work you're doing and keep going! :D

**Comment by OlegHahm** [comment]
Where are we at?

**Comment by mali** [comment]
@BytesGalore : can you add arduino uno and duemilanove to the Atmega Family list (not checked) ?

**Comment by BytesGalore** [comment]
@mali added

**Comment by fjmolinas** [comment]
This should have had tracking Issue Tag, should not have been closed. Re-open.

**Comment by mfp20** [comment]
For AVR, [this guys](https://modm.io/) did an awesome job. It generates a fairly complete C++ lib for the target, and they are focused on performance. It could be a good companion for RIOT.

The only annoying thing is their extensive use of C++17 features, forcing the use of avr-gcc v7+; all major distros are stuck at v5.4 or alike, so a custom toolchain must be built. They distribute a pre-made v9.2 toolchain tough.
There's a big question mark about the future, because GCC will disable AVR target in v10 and remove in v11. And llvm avr target is unstable.

**Comment by miri64** [comment]
@mfp20 would you be interested in looking into porting this e.g. as a package? The caveats can be dealt with later as long as there is documentation on it.

**Comment by maribu** [comment]
Basic C++ support on RIOT is working on pretty much every board (except native on FreeBSD or so?). With the ETL package even a usable standard template lib exists.

More native C++ wrappers for the C APIs that do make use of C++ features such as OOP, RAII, etc. where sensible would be nice, but that is orthogonal to this issue.

Also, some platforms are still missing a C++ standard lib, at least AVR does. For AVR https://github.com/modm-io/avr-libstdcpp could be used. But I personally do not feel the itch to package that to just tick a box. If there would be users actually needing this, I could be motivated to do so.

IMO this issue can be closed. Even thought there are still areas of improvement for C++ users, IMO new issues that are more explicit and focused on a single issue should be opened instead.

But if someone disagrees: Feel free to reopen.

**Comment by mfp20** [comment]
@miri64 I apologize, I must have missed the notification mail of your message in 2020. I've just noted the thread now, on closing by @maribu. I am currently not using RIOT, relying on readily available firmware for my application, just for simple time/money availability constraints (in my life). So no, can't develop anything isn't a paid commercial project. But I hope to be able to change this whenever possible.
