### ISSUE TITLE
tests: compilation of some test applications fail with NDEBUG

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#13265]
#### Description

Some test applications use `assert` to check the test results for correctness. Applications that rely on `assert` should undefine `NDEBUG` at the beginning of their source code. Otherwise their compilation fail in
```
dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
```
with defined environment variable `CLFAGS='-NDEBUG'`.

The following test application could already be identified:
```
- tests/gnrc_sock_ip
- tests/periph_eeprom
- tests/thread_msg_block_race
```

#### Steps to reproduce the issue

Compile these application for any board, for example:
```
CFLAGS='-DNDEBUG' make BOARD=arduino-mega2560 -C tests/gnrc_sock_ip
CFLAGS='-DNDEBUG' make BOARD=arduino-mega2560 -C tests/periph_eeprom
CFLAGS='-DNDEBUG' make BOARD=arduino-mega2560 -C tests/thread_msg_block_race
```

**Comment by kaspar030** [comment]
> Applications that rely on `assert` should undefine `NDEBUG` at the beginning of their source code.

Good idea!

**Comment by kaspar030** [comment]
> Some test applications use `assert` to check the test results for correctness.

BTW, IMO that should be avoided. While convenient, IMO we should be more interested in running tests that are compiled with different compilations, e.g., LTO enabled, or different optimizations, or with NDEBUG=1 (testing the rest of the codebase, not the test application itself).

Maybe we should work towards using something like `expect(condition)`, which would be like `assert()` but unaffected by NDEBUG.

**Comment by kaspar030** [comment]
> Maybe we should work towards using something like `expect(condition)`, which would be like `assert()` but unaffected by NDEBUG.

Like this: https://github.com/RIOT-OS/RIOT/pull/13268
