### ISSUE TITLE
native:in file gnrc_rpl_p2p.c function trickle_start() has extra and some undeclared variables.

### ISSUE THREAD

**Issue by avinigam** [RIOT-OS/RIOT#13369]
![Screenshot from 2020-02-13 19-17-21](https://user-images.githubusercontent.com/40672052/74443039-874a2400-4e98-11ea-8d63-7c03efbea09e.png)

**Comment by smlng** [comment]
@cgundogan can you have a look?

**Comment by cgundogan** [comment]
see #13379

**Comment by cgundogan** [comment]
@avinigam did #13379 solve the issues also on your side?
