### ISSUE TITLE
Can't use nimble as prefix for modules

### ISSUE THREAD

**Issue by HendrikVE** [RIOT-OS/RIOT#13419]
#### Description
It's not possible to use the prefix `nimble_` for custom modules in `sys/`

#### Steps to reproduce the issue
Add a new dummy module with the name `nimble_prefix_test` and add `USEMODULE += nimble_prefix_test` to the Makefile, e.g. of the `default` example. 
#### Expected results
It should be build. There should be no technical restriction for choosing module names, except duplicates.

#### Actual results
Make will fail with the following message:
```
make[1]: *** No rule to make target 'nimble_test', needed by 'all'. Stop.
make: *** [/home/hendrik/RIOT/examples/default/../../Makefile.include:639: pkg-build-nimble] Error 2
```
But if you rename the module to `my_nimble_prefix_test` everything works as expected.

**Comment by kaspar030** [comment]
Yeah, nimble takes that prefix. Not sure where exactly.

Can you try adding "nimble_test" here:

https://github.com/RIOT-OS/RIOT/blob/ea3296df62d7a54b08dcc5292bbbe53ce6b7a4bc/pkg/nimble/Makefile#L26

**Comment by HendrikVE** [comment]
Thank you very much, this fixes the issue. But it feels quite hacky. Is it intended that a whole prefix is "reserved" for a specific purpose?

**Comment by miri64** [comment]
> […] this fixes the issue.

I take this as a reason for this issue to be closed.
