### ISSUE TITLE
Contributing to RIOT page has been overwritten

### ISSUE THREAD

**Issue by adamcoding** [RIOT-OS/RIOT#13445]
This page probably needs reverting to something more useful?
https://github.com/RIOT-OS/RIOT/wiki/Contributing-to-RIOT

Thanks

**Comment by miri64** [comment]
We moved all its content to https://github.com/RIOT-OS/RIOT/blob/master/CONTRIBUTING.md, to have it more central and keep it up to date with the code base.

**Comment by miri64** [comment]
(it also keeps people from messing with the content without a PR ;-))
