### ISSUE TITLE
Use both UART and USB CDC ACM at same time

### ISSUE THREAD

**Issue by toonst** [RIOT-OS/RIOT#13555]
Since the STM32 USB driver is merged, I would like to start using it for stdio logging, while at the same time keeping UART for the shell. We use the vfs abstraction for writing logs in our application.
Currently both USB and UART fall under the stdio_base abstraction, see image to get an idea.

![Stdio abstraction](https://user-images.githubusercontent.com/5477573/75927856-796f3980-5e6d-11ea-83d4-2e36d78b1a70.png)

I tried modifying the shell implementation to optionally use periph/uart.h directly, but I don't think this is a clean solution. Do you have some ideas on how to accomplish this in a clean way?
Maybe both USB and UART stdio could be made different files under VFS, but I don't directly see how this would work.

Thanks for the help!

**Comment by toonst** [comment]
apparently there's already a discussion going on here https://github.com/RIOT-OS/RIOT/issues/13469. I'll join the discussion there.

**Comment by miri64** [comment]
:+1: I'll close this as a duplicate then.
