### ISSUE TITLE
CC2538-bsl submodule

### ISSUE THREAD

**Issue by JelmerT** [RIOT-OS/RIOT#13566]
I wanted to check if the position on sub-modules is still the same. See https://github.com/RIOT-OS/RIOT/pull/5784 and https://github.com/RIOT-OS/RIOT/pull/4237 and https://github.com/JelmerT/cc2538-bsl/pull/92

In the mean while there's been improvements on the script on the RIOT side that I would love to have upstream and the other way round. Submodule or something that tracks upstream would be very convenient for this.

(@smlng )

**Comment by benpicco** [comment]
We don't do submodules, but tools like [edbg](https://github.com/RIOT-OS/RIOT/tree/master/dist/tools/edbg) are just downloaded on-demand.

I didn't even realize cc2538-bsl was an external tool - we should definitely replace it with e pkg-based approach then instead of maintaining a fork.

**Comment by JelmerT** [comment]
👍 thanks for this! 

Welcoming all improvements upstream
