### ISSUE TITLE
FPU support for the Cortex-M4F family

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#1366]
based on the introduction of support for the Cortex-M4 familiy (#1191), support for the FPU has to be added. This means adjusting the context-switching code by including the FPU registers.

**Comment by gebart** [comment]
Reassigned to @kaspar030, reassign if you feel someone else is more suited for this.

**Comment by haukepetersen** [comment]
To be on the safe side, I created a PR to disable the use of the hardware FPU on M4F based CPUs -> #3112

**Comment by miri64** [comment]
What's the state of this issue?
