### ISSUE TITLE
random travis fails

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#1377]
Travis fails apparently randomly at the moment. Restarting a build of the same commit can yield a different result.

**Comment by OlegHahm** [comment]
It's annoying - that's all I have to say for now. ;)

**Comment by LudwigOrtmann** [comment]
While `make buildtest`-ing this just happened:
```
Building for avsextrem .. failed
/home/lo/RIOT/examples/hello-world/bin/avsextrem/arm7_common.a(bootloader.o): In function `bootloader':
/home/lo/RIOT/cpu/arm7_common/bootloader.c:171: undefined reference to `bl_init_clks'
collect2: error: ld returned 1 exit status
```
When running `make buildtest` again this did not occur.

**Comment by OlegHahm** [comment]
Well, Travis is still a bitch, but behave rather deterministically recently.
