### ISSUE TITLE
Problems with boards

### ISSUE THREAD

**Issue by valeriova96** [RIOT-OS/RIOT#13849]
Hello everyone I am stuck into this problem and can't go on with the exercises. I'm using a mac with the Vagrant VM and at the compiling moment, if I try to change the board I get this error, anyone went through the same issue?
<img width="796" alt="screenshot_2020-04-08_at_18 02 54" src="https://user-images.githubusercontent.com/45147652/78905275-06fe0480-7a7e-11ea-821e-b99f33af504f.png">

**Comment by benpicco** [comment]
You need to install toolchain first. Check out [the documentation](https://doc.riot-os.org/group__cpu__esp8266.html#esp8266_manual_toolchain_installation).

**Comment by aabadie** [comment]
The RIOT tutorials are using an old version of the Virtual Machine which doesn't contain the ESP8266 toolchain.
You can install the toolchain following the same way it's done for the latest version of the virtual machine:
https://github.com/RIOT-OS/RIOT/blob/c68475eb0d61d8729ea3ae8d835d5247638f01a8/dist/tools/packer/scripts/toolchains.sh#L80-L104

**Comment by valeriova96** [comment]
thanks a lot, it worked!
