### ISSUE TITLE
CC2531 support

### ISSUE THREAD

**Issue by Citrullin** [RIOT-OS/RIOT#14070]
#### Description
I got some of these cheap CC2531 USB sticks here. In comparison to all the nrf52840 USB sticks, they expose normal through holes. Normally they are used as 802.15.4 sniffer. But they would make ideal 6LoWPAN to  USB CDC ECM Sticks for something like routers. 

### Useful links
https://www.ti.com/product/CC2531

**Comment by benpicco** [comment]
You'd have to port RIOT to 8051 first.
Surely interesting as ATmega wouldn't be the only 8-bit architecture then.

Getting both the network and the USB stack into 8k RAM will be another challenge :wink:
