### ISSUE TITLE
Communication between two cc2538 motes using GNRC(Generic network stack)

### ISSUE THREAD

**Issue by hcnhcn012** [RIOT-OS/RIOT#14115]
Hello guys, now I have two cc2538 motes and want to set up a  UDP communication tunnel between these two motes, I use `gnrc_networking` from RIOT examples, but I found that I could not ping one mote to another successfully. Here are two motes' interface configs:
(1) Mote 1
> \> ifconfig
Iface  7  HWaddr: B7:9D  Channel: 26  Page: 0  NID: 0x23
          Long HWaddr: 00:12:4B:00:19:2E:44:67 
           TX-Power: 0dBm  State: IDLE 
          AUTOACK  L2-PDU:102 MTU:1280  HL:64  RTR  
          6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::212:4b00:192e:4467  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff2e:4467
          \
          Statistics for Layer 2
          RX packets 0  bytes 0
            TX packets 3 (Multicast: 3)  bytes 129
            TX succeeded 0 errors 0
            Statistics for IPv6
            RX packets 0  bytes 0
            TX packets 3 (Multicast: 3)  bytes 192
            TX succeeded 3 errors 0

(2)Mote 2
> \> ifconfig
Iface  7  HWaddr: ED:CA  Channel: 26  Page: 0  NID: 0x23 
          Long HWaddr: 00:12:4B:00:19:33:5E:48 
           TX-Power: 0dBm  State: IDLE 
          AUTOACK  L2-PDU:102 MTU:1280  HL:64  RTR  
          6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::212:4b00:1933:5e48  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff33:5e48
          \
         Statistics for Layer 2
            RX packets 5  bytes 215
            TX packets 4 (Multicast: 4)  bytes 172
            TX succeeded 0 errors 0
          Statistics for IPv6
            RX packets 5  bytes 320
            TX packets 4 (Multicast: 4)  bytes 256
            TX succeeded 4 errors 0

I noticed that each mote's ipv6 address scope is `link`, not `local`, I guess the problem is RIOT don't get the write RF information from board or I missed some flags for switching on RF
Thanks for helping:)

**Comment by Citrullin** [comment]
You shouldn't use images. You can simply copy the text from your terminal and use Markdown in order to mark your code etc. "Syntax highlighting" is the part interesting for you in this case.
https://guides.github.com/features/mastering-markdown/

**Comment by jeandudey** [comment]
@hcnhcn012 On the second image seems you're pinging yourself, could you try with the other mote address?

**Comment by benpicco** [comment]
Actually pinging yourself should work too.
I'm confused because this should just work™

Since you are pinging link-local addresses, have you tried passing the interface ID with the address:

    ping6 fe80::212:4b00:1933:5e56%7

Or did you try to ping the broadcast address

    ping6 ff02::1%7

Do you have antennas connected?

**Comment by hcnhcn012** [comment]
> You shouldn't use images. With text only your issue is more accessible for everybody. Especially for people with disabilities. They rely on screen readers. These tools are not necessary able to read the text in your image. You can simply copy the text from your terminal and use Markdown in order to mark your code etc. "Syntax highlighting" is the part interesting for you in this case.
> https://guides.github.com/features/mastering-markdown/

Thanks, I have adjusted my issue post so others can read it fluently and thanks to @benpicco this problem has been solved :)

**Comment by hcnhcn012** [comment]
> Actually pinging yourself should work too.
> I'm confused because this should just work™
> 
> Since you are pinging link-local addresses, have you tried passing the interface ID with the address:
> 
> ```
> ping6 fe80::212:4b00:1933:5e56%7
> ```
> 
> Or did you try to ping the broadcast address
> 
> ```
> ping6 ff02::1%7
> ```
> 
> Do you have antennas connected?

Really appreciate that! I actually solved this by tacking your advice. For my board is self-made with a cc2538 MCU I believed that there was an issue in hardware abstract then I spent days reading codes of RIOT-os :)
Thanks again!
