### ISSUE TITLE
ESP32/ESP8266 Toolchain Building Instructions

### ISSUE THREAD

**Issue by jeandudey** [RIOT-OS/RIOT#14124]
#### Description

RIOT uses a custom toolchain to compile itself to ESP32/ESP8266 targets, it would be great if there were instructions on how to build binary releases of the toolchain, for example, to build it on OS X or for Raspberry Pi's.

### Useful links

- RIOT ESP32 Xtensa Toolchain: https://github.com/gschorcht/xtensa-esp32-elf

**Comment by gschorcht** [comment]
I haven't had time to respond to this issue yet.
