### ISSUE TITLE
kconfig is broken on case-insensitive file systems

### ISSUE THREAD

**Issue by janschlicht** [RIOT-OS/RIOT#14158]
#### Description
You can either have the file `Kconfig` or the folder `kconfig`. For now either `Kconfig` or `kconfig/Kconfig.consts` and `kconfig/Kconfig.features` are deleted automatically when checking out riot.

#### Steps to reproduce the issue
Clone riot onto a case-insensitive APFS-Volume.

#### Expected results
All files are present.

#### Actual results
Either `Kconfig` or `kconfig/Kconfig.consts` and `kconfig/Kconfig.features` are deleted

#### Versions
MacOs 10.15.5 with a case-insensitive APFS-Volume.

**Comment by leandrolanzieri** [comment]
@janschlicht could you check if #14160 fixes the issue for you?

**Comment by janschlicht** [comment]
@leandrolanzieri yes, that fixes the problem! Thank you.

**Comment by leandrolanzieri** [comment]
Good! Thanks for reporting and testing!
