### ISSUE TITLE
tests/periph_timer_periodic is failing

### ISSUE THREAD

**Issue by keestux** [RIOT-OS/RIOT#14217]
#### Description

Test `tests/periph_timer_periodic` is failing on my SODAQ boards. These are the only boards I have so I can't tell if the test fails on other boards boards as well. My suspicion is that it fails on SAMD21.

#### Steps to reproduce the issue
Build and run `tests/periph_timer_periodic`

#### Expected results
The output should end with
```
TEST SUCCEEDED
```

#### Actual results
```
...
2020-06-07 21:08:53,834 # [0] tick
2020-06-07 21:08:53,838 # [1] tick
2020-06-07 21:08:53,869 # [0] tick
2020-06-07 21:08:53,869 # 
2020-06-07 21:08:53,869 # Cycles:
2020-06-07 21:08:53,870 # channel 0 = 12	[OK]
2020-06-07 21:08:53,870 # channel 1 = 11	[ERROR]
2020-06-07 21:08:53,871 # TEST FAILED
```

**Comment by keestux** [comment]
@benpicco sorry, I have "assigned" you, mainly to draw your attention. Maybe you can first answer this question: what SAMD21 board did you run the test on, and did it succeed?

**Comment by keestux** [comment]
@benpicco Nevermind. It is a missing define of `XTIMER_DEV` in common sodaq includes. I'll fix that.

**Comment by benpicco** [comment]
Yea this relies on the xtimer defines to get a known good timer configuration.
Unfortunately there is no universal timer config (e.g. requesting a 1 MHz hardware timer will not work on all platforms) but the XTIMER configuration is guaranteed to provide a working timer that can measure the ranges of time used by this test.

**Comment by benpicco** [comment]
Can this be closed now?

**Comment by miri64** [comment]
Ping @keestux?

**Comment by keestux** [comment]
The test is passing. Closing
