### ISSUE TITLE
Output of tests/posix_semaphore depends on timing

### ISSUE THREAD

**Issue by keestux** [RIOT-OS/RIOT#14281]
#### Description

Test `posix_semaphore` may depend on timing, or perhaps on other active threads. This test has four sub tests, TEST1 .. TEST4. The text output of TEST1 is different when running on stdio via UART or CDC ACM (USB).

#### Steps to reproduce the issue
Run tests/posix_semaphore on a board which uses CDC ACM as stdio, and just look at TEST1.

#### Expected results
A well defined sequence of output lines.

#### Actual results
On a board with CDC ACM as stdio, the first few lines of TEST1 are
```
######################### TEST1:
first: sem_init
first: thread create
first: thread created
second: sem_trywait
second: sem_trywait failed
second: sem_trywait done with == 0
second: wait for post
first: sem_getvalue
first: sem_getvalue != 0
first: do yield
first: done yield
```

On a board with "normal" UART, the first few lines of TEST1 are:
```
######################### TEST1:
first: sem_init
first: thread create
first: thread created
first: sem_getvalue
first: sem_getvalue != 0
first: do yield
second: sem_trywait
second: sem_trywait failed
second: sem_trywait done with == 0
second: wait for post
first: done yield
```
The remainder of the test output (including TEST2..TEST4) is identical in the above two scenarios.

**Comment by keestux** [comment]
@kaspar030 I need your help again.

**Comment by kaspar030** [comment]
I think the issue is again starting a higher-priority thread (lower value) with THREAD_CREATE_WOUT_YIELD. With the usb thread interrupting, the logic breaks.
To fix, I suggest removing "THREAD_CREATE_WOUT_YIELD". The output should then always look like with CDC ACM as stdio.
