### ISSUE TITLE
shell: txtsnd command is broken

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1433]
The shell command handler `_transceiver_send_handler()` builds an `radio_packet_t`, but the `transceiver` module expects an `ieee802154_packet_t` for IEEE 802.15.4 capable drivers instead. Hence, the casting produces nonsense.

**Comment by thomaseichinger** [comment]
@OlegHahm fixed by #1434?

**Comment by OlegHahm** [comment]
I guess so.
