### ISSUE TITLE
vtimer: a removed vtimer might still get called back by hwtimer

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#1449]
There seem to be corner cases where `vtimer_callback()` gets called although `vtimer_remove()` was called. If there was no further vtimer scheduled, then the application crashes (worked around in #1446). If there was another vtimer scheduled, then it gets called before its time, which might hurt the programming logic, too.

I found the bug while writing #1444, and my initial assumption is that there are problems with the usage of `in_callback`.

**Comment by x3ro** [comment]
@OlegHahm Isn't vtimer dead?

**Comment by OlegHahm** [comment]
The last vtimer I saw looked like ![](https://s3-eu5.ixquick.com/cgi-bin/serveimage?url=http:%2F%2Frileymwr.com%2Fodr%2Fwp-content%2Fuploads%2F2012%2F10%2Fzombie.jpg&sp=121b5e803cdc87563589352f4e052b3b)
