### ISSUE TITLE
Add the "riot-os" topic to the repository description

### ISSUE THREAD

**Issue by jhaand** [RIOT-OS/RIOT#14505]
#### Description
At the moment a Github topics in the about field for RIOT-OS is not present. I can find projects with the topics "riotos" and "riot-os". Could you add the topic "riot-os" to the description of the pinned repositories (RIOT, Tutorials, applications). 
This makes searching for RIOT-OS applications much easier. This allows people to start faster with their application. Adding this topic also creates a uniform topic name for people to adapt. 

### Useful links
https://github.com/RIOT-OS/RIOT
https://github.com/RIOT-OS/Tutorials
https://github.com/RIOT-OS/applications
![RIOT-OS_topics](https://user-images.githubusercontent.com/14841399/87301585-2179cb00-c510-11ea-8281-ad2ea26b517e.png)

**Comment by wosym** [comment]
I suggest also adding related tags and de-facto names for RIOT-os.
e.g. "rtos", "riotos", "riot"

**Comment by jhaand** [comment]
You could also mention the other tags. That makes it easier to click through. But mention somewhere which tags remains the preferred one.

**Comment by miri64** [comment]
Good point. I'm going to update the respective repositories.

**Comment by jhaand** [comment]
Thnx. 
I'm glad this is now closed.
