### ISSUE TITLE
Uncrustify enforces deviation of coding convention

### ISSUE THREAD

**Issue by benpicco** [RIOT-OS/RIOT#14514]
#### Description

Our [`CODING_CONVENTIONS.md`](https://github.com/RIOT-OS/RIOT/blob/master/CODING_CONVENTIONS.md) states

> - Please obey the Linux coding style as described in https://www.kernel.org/doc/Documentation/process/coding-style.rst with the following modifications and additions:
> (nothing about indentation in switch statements)

#### coding-style.rst

> The preferred way to ease multiple indentation levels in a switch statement is
> to align the ``switch`` and its subordinate ``case`` labels in the same column
> instead of ``double-indenting`` the ``case`` labels.  E.g.:
> 
> ```C
> 	switch (suffix) {
> 	case 'G':
> 	case 'g':
> 		mem <<= 30;
> 		break;
> 	case 'M':
> 	case 'm':
> 		mem <<= 20;
> 		break;
> 	case 'K':
> 	case 'k':
> 		mem <<= 10;
> 		fallthrough;
> 	default:
> 		break;
> 	}
> ```

However as @maribu pointed out in https://github.com/RIOT-OS/RIOT/pull/14322#discussion_r454418230, `uncrustify` does not like this.

#### Steps to reproduce the issue

```
$ cat test.c
#include <stddef.h>

size_t foo(char suffix)
{
    size_t mem = 1;
    switch (suffix) {
    case 'G':
    case 'g':
        mem <<= 30;
        break;
    case 'M':
    case 'm':
        mem <<= 20;
        break;
    case 'K':
    case 'k':
        mem <<= 10;
        fallthrough;
    default:
        break;
    }

    return mem;
}

$ uncrustify -c uncrustify-riot.cfg test.c 
Output suffix: .uncrustify
Parsing: test.c as language C
```

#### Expected results

No code changes.

#### Actual results

```
$ diff -p test.c test.c.uncrustify 
--- test.c
+++ test.c.uncrustify
@@ -3,21 +3,22 @@
 size_t foo(char suffix)
 {
     size_t mem = 1;
+
     switch (suffix) {
-    case 'G':
-    case 'g':
-        mem <<= 30;
-        break;
-    case 'M':
-    case 'm':
-        mem <<= 20;
-        break;
-    case 'K':
-    case 'k':
-        mem <<= 10;
-        fallthrough;
-    default:
-        break;
+        case 'G':
+        case 'g':
+            mem <<= 30;
+            break;
+        case 'M':
+        case 'm':
+            mem <<= 20;
+            break;
+        case 'K':
+        case 'k':
+            mem <<= 10;
+            fallthrough;
+        default:
+            break;
     }
 
     return mem;
```

**Comment by maribu** [comment]
Can be fixed like this:

```patch
diff --git a/uncrustify-riot.cfg b/uncrustify-riot.cfg
index 5ef98e8122..618f605cba 100644
--- a/uncrustify-riot.cfg
+++ b/uncrustify-riot.cfg
@@ -7,7 +7,7 @@ input_tab_size          = 4                 # original tab size
 output_tab_size         = 4                 # new tab size
 indent_columns          = output_tab_size   #
 indent_label            = 1                 # pos: absolute col, neg: relative column
-indent_switch_case      = 4                 # number
+indent_switch_case      = 0                 # number
 indent_ternary_operator = 2                 # When the `:` is a continuation, indent it under `?`
 
 #
```

I can open a PR for this later. I currently have a lot of uncommited code that I want to finish first. @benpicco: Feel free to open the PR, if you want this in soon ;-)
