### ISSUE TITLE
tests/llittlefs - tests/llittlefs2 - tests/pkg_spiffs: need a speed up

### ISSUE THREAD

**Issue by fjmolinas** [RIOT-OS/RIOT#14579]
#### Description

These fs related test take a very long time and are not deterministic, a quick fix is increasing the timeout, would be better to refactor the tests so they finish up faster.

```
Benchmark #1: IOTLAB_NODE=nrf52840dk-2.saclay.iot-lab.info BUILD_IN_DOCKER=1 BOARD=nrf52840dk make -C tests/pkg_littlefs2/ test
  Time (mean ± σ):     149.844 s ±  3.759 s    [User: 1.911 s, System: 0.279 s]
  Range (min … max):   145.948 s … 160.623 s    50 runs
```

```
hyperfine -r 50 -w 1 'IOTLAB_NODE=nrf52840dk-1.saclay.iot-lab.info BUILD_IN_DOCKER=1 BOARD=nrf52840dk make -C tests/pkg_littlefs/ test'
Benchmark #1: IOTLAB_NODE=nrf52840dk-1.saclay.iot-lab.info BUILD_IN_DOCKER=1 BOARD=nrf52840dk make -C tests/pkg_littlefs/ test
  Time (mean ± σ):     132.642 s ±  1.858 s    [User: 1.876 s, System: 0.272 s]
  Range (min … max):   130.011 s … 136.879 s    50 runs
```

Didn't run the benchmark for `tests/pkg_spiffs`, or rather my experiment timeout but the estimate was around `656.285s`

**Comment by aabadie** [comment]
These tests are failing in the [test-on-iotlab action](https://github.com/RIOT-OS/RIOT/runs/1964404209?check_suite_focus=true) because of timeout issues. Increasing (or putting) the timeout to 180s works for littlefs/littlefs2.
