### ISSUE TITLE
doc: transform existing documentation to markdown

### ISSUE THREAD

**Issue by LudwigOrtmann** [RIOT-OS/RIOT#1458]
There are some files that could benefit from being transformed to markdown.

E.g.:
https://github.com/RIOT-OS/RIOT/tree/master/pkg/PORTING
https://github.com/RIOT-OS/RIOT/blob/master/pkg/USING

(I did not look for more..)

**Comment by kushalsingh007** [comment]
I will be working on this task.

**Comment by kushalsingh007** [comment]
I think the issue can be closed

**Comment by OlegHahm** [comment]
I think so, too. @LudwigOrtmann, do you have something else on the list?

**Comment by LudwigOrtmann** [comment]
I have no list.
