### ISSUE TITLE
stm32f405rtg6 stdin/out uart not working

### ISSUE THREAD

**Issue by Jalili-73** [RIOT-OS/RIOT#14687]
#### Description

i'm beginner and i designed a board that near to stm32f4discovery but different in MCU.
board mcu is stm32f405rtg6 .
i connect uart to usb ((cp2102)) ==> ((RX=PA3 TX=PA2 GND=GND))
i compile **riot-course/exercises/getting-started/first-app** with **gcc-arm-none-eabi-10-2020-q2-preview-x86_64-linux** toolchain and command  **BOARD=stm32f4discovery make binfile all**.

I flash MCU but after i console to MCU nothing happeد even i reset it but not working a gain.

what should i do?

**Comment by fjmolinas** [comment]
Hi @Jalili-73, can you point me do your code if its a public repository? Otherwise, can you check basic functionality like toggling a led?

What environment are you are? LINUX? OSX? can you check that your are opening the terminal on the correct PORT? You can specify as such:

```PORT=<your port /dev/tty* or whetever> make flash term```
