### ISSUE TITLE
periph_pwm API needs a way to define the initial duty cycle during init

### ISSUE THREAD

**Issue by benemorius** [RIOT-OS/RIOT#14721]
### Description
The `periph_pwm` API has no way to provide an initial duty cycle during init. Most (?) implementations automagically initialize the duty cycle to 0% and enable the output. In the worst case, this can be the exact opposite of what the user wants.

#### Steps to reproduce the issue
Use PWM to drive an LED connected in an active-low configuration and try to initialize it in the off (0%) state.

The application code to initialize the LED in an off state would look like this:
```c
pwm_init(...);
pwm_set(100); /* 100 for 0% because inverted LED */
```

#### Expected results
The code initializes the LED into an off state without any intermediate on states.

#### Actual results
After `pwm_init()` the LED is running at 100% until `pwm_set()`. The duration of the on state is long enough to see with human eyes.

### Proposed Solution
Modify the `periph_pwm` API as such:
```diff
- uint32_t pwm_init(pwm_t pwm, pwm_mode_t mode, uint32_t freq, uint16_t res);
+ uint32_t pwm_init(pwm_t pwm, pwm_mode_t mode, uint32_t freq, uint16_t res, uint16_t duty_cycle);
```

Similar to the situation with `gpio_init()` and `gpio_init_low/high()`, I think it makes no sense from a hardware perspective to enable a pin as an output without atomically defining what state to output.

**Comment by hugueslarrive** [comment]
Why not add .active_low or .polarity field in the pwm_chan_t data structure, so pwm_init should know it is needed to initialize the comparator to res instead of 0 and the gpio output to high.

Moreover this way you can use pwm_set(0); for turn off led, no matter if it is inverted or not and there is no need to correct existing applications that are using pwm_init();
