### ISSUE TITLE
Interest for potential new examples using nanocoap with SAUL?

### ISSUE THREAD

**Issue by samken600** [RIOT-OS/RIOT#14732]
I've been working on a few applications that I think might have a place as examples in the RIOT ecosystem. I spoke to some people in the IRC the other day and they suggested I make a post here. I was looking to see if this kind of thing is something that would be of interest to people here. I have two applications specifically that could be of use, would be great to hear any feedback and if people think this is something that would be nice to have in the main repository.

Both look for temperature sensors and LEDs in SAUL and control them, with some other features. Might require some confirguration in Makefiles for adding non-onboard sensors, however I can outline this in the READMEs. These examples were developed on some hardware I made, so the target board would have to be changed before adding them to RIOT, as well as I expect a number of other changes (not all covered here). Just looking to see if it would be worth putting it the time to make them more generic.

* [nanocoap server with SAUL](https://github.com/samken600/3YP/tree/master/project_workspace/3yp_node_coap_saul) - exposes resources to allow to GET temperatures and PUT/POST LED status as well as PUT TX power 

* [nanocoap client & server with SAUL](https://github.com/samken600/3YP/tree/master/project_workspace/3yp_node_coap_saul_puts) - auto puts temperature readings with a period dynamically configurable over CoAP. Some work needs to be done to make configuration of i.e. ip addresses a bit easier and not require a forwarding proxy

**Comment by miri64** [comment]
Hi @samken600, sorry for the late reply. Of course we would be interested in such examples. With #15358, we could just group them under e.g. `examples/nanocoap` with the already existing example. Of course, if you have any interesting projects in general, feel free to share them in the [Show Case category in our forum](https://forum.riot-os.org/c/community/showcase-projects/21)
