### ISSUE TITLE
pyterm + freshly connected arduino-due == no connection (often)

### ISSUE THREAD

**Issue by LudwigOrtmann** [RIOT-OS/RIOT#1480]
When using pyterm to connect to a freshly plugged in arduino-due (with hello-world), the terminal does not connect properly.
Using pseudoterm instead works.
Also, after flashing an application pyterm works.

**Comment by PeterKietzmann** [comment]
@LudwigOrtmann I assume this is fixed?

**Comment by OlegHahm** [comment]
Should be solved by https://github.com/OlegHahm/RIOT/commit/73f6a0c51815144a128f3a368fafae73b1b69215 - can you confirm, @LudwigOrtmann?

**Comment by LudwigOrtmann** [comment]
works
