### ISSUE TITLE
Is there a simulation support for RIoT system?

### ISSUE THREAD

**Issue by desword** [RIOT-OS/RIOT#14918]
Is there a simulation support for RIoT system?

**Comment by benpicco** [comment]
Depends on what you want to simulate.
There is the `native` board that compiles your application to a native Linux binary and simulates the hardware / allows you to use the hardware of the host machine.

You can also load target binaries into [Renode](https://renode.io/) and emulate the hardware.

**Comment by jia200x** [comment]
You can maybe check now https://github.com/RIOT-OS/RIOT/pull/15512#issuecomment-759524602

**Comment by jeandudey** [comment]
Closing as the question has been answered, if not, please reopen it.
