### ISSUE TITLE
Does RIOT support OTA?

### ISSUE THREAD

**Issue by Tong0217** [RIOT-OS/RIOT#14983]
I'm looking for a OS which can OTA with ble. Does RIOT support OTA? Is there any example？
Thanks in advance.

**Comment by emmanuelsearch** [comment]
@Tong0217 take a look at https://github.com/RIOT-OS/RIOT/tree/master/examples/suit_update and try the BLE version. This follows the SUIT specification: https://tools.ietf.org/html/draft-ietf-suit-manifest

**Comment by Tong0217** [comment]
thank you so much. @emmanuelsearch

**Comment by emmanuelsearch** [comment]
@Tong0217 in complement, in case you are in a paper reading type of mood, you can also check this paper which dissects basic aspects of this implementation and of the SUIT spec https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8725488
