### ISSUE TITLE
flashpage on STM32F4 CPU

### ISSUE THREAD

**Issue by biboc** [RIOT-OS/RIOT#15020]
#### Description

All other CPU on STM32 board have flashpage implemented, why not on STM32F4, what's missing?

Thanks,

**Comment by aabadie** [comment]
There was a tentative PR in #11681. Maybe @fjmolinas can describe what were the limitations and give some advice on how this could get in one day ?

**Comment by fjmolinas** [comment]
The main issue is that `stm32f2` `stm32f4` `stm32f7` have sectors and not pages, these sectors are bigger than pages and more importantly do not have an uniform size. For one family they might be: 8kb, 8kb, 16kb, 32kb, 64kb.

My initial attempt #11681, faked pages within sectors, but it was a bit hacky, and I ended up not liking the solution at all. So currently `flashpage` needs to be adapted, or `flashpage_raw` converted to a `flash_raw`.

**Comment by biboc** [comment]
Ok thanks for your answer
Yes STM32F4 works with sector, so writting a page means erasing a sector then write the page, it is difficult to standardize the process with pages
Apart from erasing problem, the function `flashpage_write` works as expected without sync problem?

**Comment by fjmolinas** [comment]
> Apart from erasing problem, the function flashpage_write works as expected without sync problem?

Are you referring to the close PR? Or to current code?

**Comment by biboc** [comment]
Close PR

**Comment by fjmolinas** [comment]
I don't remember the exact state the PR was in when closed, I think everything was working, but erasing was hacky.

**Comment by biboc** [comment]
Ok let's close this issue then
