### ISSUE TITLE
2020.07-branch bug:RIOT/cpu/stm32/include/vendor/stm32f103xe.h

### ISSUE THREAD

**Issue by kex2017** [RIOT-OS/RIOT#15041]
#### Description
2020.07-branch
RIOT/cpu/stm32/include/vendor/stm32f103xe.h content is !!!stm32f101xe.h!!!

**Comment by miri64** [comment]
> Do we need to backport a fix ?

On one hand-side I'd say, definitely yes. On the other, the release process for 2020.10 was already kicked off, so I am hesitant to having another point release for 2020.07, so the bug fix will just reside in the branch.

**Comment by miri64** [comment]
> On one hand-side I'd say, definitely yes.

Only now looked at the change: IMHO that "fix" is too substantial to be backported, so my final answer is no ^^".

**Comment by aabadie** [comment]
The change is to replace the cmsis header file by the right one. This would just be a single PR, only for 2020-07-branch because in master it's already fixed (the file no longer exists :) ).
Leaving it like this means the 2020.07 is potentially broken on stm32f103xe based boards.

**Comment by miri64** [comment]
> The change is to replace the cmsis header file by the right one. This would just be a single PR, only for 2020-07-branch because in master it's already fixed (the file no longer exists :) ).
> Leaving it like this means the 2020.07 is potentially broken on stm32f103xe based boards.

Ah, so not really a backport, but a hotfix for 2020.07. That's alright, yes :-).

**Comment by aabadie** [comment]
> That's alright, yes :-)

Ok, I'll open the PR. Then I leave to you to decide whether you want to publish a new point release :)

**Comment by aabadie** [comment]
I made the change but I found another issue on iotlab-m3... Need to open an issue for this one (I know the culprit!).

**Comment by miri64** [comment]
> I made the change but I found another issue on iotlab-m3 while testing...

Where can I find it?

**Comment by aabadie** [comment]
> Where can I find it?

It's here: #15044
I was running the compile_and_test_for_board.py on iotlab-m3 and was waiting for the results (no major problems so far).

**Comment by miri64** [comment]
#15044 was merged.
