### ISSUE TITLE
x86: qemu-i386's terminal stops after many printed lines

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#1504]
The `libfixmath` test of #1460 prints almost 20k lines. The terminal of `make BOARD=qemu-i386 term` cannot handle this amount to lines for no obvious reason, and terminates after ~4500 lines. There is no error message, and the exit code is 0.

Running `qemu-system-i386 -kernel libfixmath.hex` directly prints all the lines correctly.

**Comment by LudwigKnuepfer** [comment]
I'm not going to work on this any time soon.

**Comment by kYc0o** [comment]
Since x86 support was dropped it's safe to close this one.
