### ISSUE TITLE
cpu: Provide CPU ID for all supported CPUs

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#1511]
Make CPU ID feature introduced in #854 available for all supported CPUs, if they have a serial number stored:
- [ ] atmega2560
- [x] cc430
- [x] cc2538
- [x] ezr32wg
- [x] kinetis_common
- [x] lm4f120
- [x] lpc11u34
- [x] lpc1768
- [ ] lpc2387
- [ ] msp430fxyz
- [x] native (see #854)
- [x] nrf51
- [x] sam3
- [x] samd21
- [x] saml21
- [x] stm32f0
- [x] stm32f1
- [x] stm32f3
- [x] stm32f4
- [x] stm32l1
- [ ] x86

**Comment by ShubhC** [comment]
Hi all. I am a newbie and interested to work on CPU-ID for intel galileo. can anyone help me to port RIOT on intel galileo board? I have already looked at https://github.com/RIOT-OS/RIOT/wiki/Board:-Intel-Galileo but didn't get any help.
Can anyone suggest a few such links to further proceed on the issue?

**Comment by LudwigOrtmann** [comment]
@ShubhC this issue is not the right place for such a request.

**Comment by LudwigOrtmann** [comment]
@ShubhC sorry, I misread, this is the right place ;)

**Comment by LudwigOrtmann** [comment]
@Kijewski - any idea?

**Comment by LudwigOrtmann** [comment]
@ShubhC Ah I forgot, we don't support the Galileo. Compare http://lists.riot-os.org/pipermail/devel/2015-March/002203.html

**Comment by miri64** [comment]
@haukepetersen @PeterKietzmann @kYc0o @thomaseichinger can you give an estimate how the current state of this issue is?

**Comment by PeterKietzmann** [comment]
I can't. I wasn't even aware of this PR. As it seems there is no CPUID on msp430 MCUs.

**Comment by kYc0o** [comment]
Same for atmega, I'll try to check for the others.

**Comment by basilfx** [comment]
LPC1768 has a [driver](https://github.com/RIOT-OS/RIOT/blob/master/cpu/lpc1768/periph/cpuid.c) by now.

**Comment by miri64** [comment]
Feel free to tick of the boxes (and of course extent it with new CPU types ;-))

**Comment by haukepetersen** [comment]
I think every CPUID feature not implemented by today does not seem to be that important and will simply be implemented on demand... So I'll close this issue for now - re-open if you disagree!
