### ISSUE TITLE
2020.07-branch[bug]:RIOT/cpu/stm32/include/vendor/stm32f103xb.h line:4230 lose "TIM_CCER_CC4NP" define 

### ISSUE THREAD

**Issue by kex2017** [RIOT-OS/RIOT#15216]

**Comment by aabadie** [comment]
Thanks for reporting but you should rather complain against ST directly. The `TIM_CCER_CC4NP` related defines are indeed missing on the upstream project where RIOT retrieves the vendor headers and and they are now kept untouched.

https://github.com/STMicroelectronics/cmsis_device_f1/blob/6601104a6397299b7304fd5bcd9a491f56cb23a6/Include/stm32f103xb.h#L4223-L4232
