### ISSUE TITLE
Kconfig file/folder name collision on case-insensitive filesystem

### ISSUE THREAD

**Issue by kugel2** [RIOT-OS/RIOT#15256]
#### Description

The Kconfig file in cpu/stm32/ is missing in the cloned repository. 
Because there is a folder with the same name the file cannot be created.

I think this is related to #14158 and #14160

#### Steps to reproduce the issue

Clone repository on MacOS with case-insensitive APFS filesystem.

#### Expected results

Both file and folder available.

#### Actual results

cpu/stm32/Kconfig is missing.

#### Versions

MacOS 10.13.6 with case-insensitive APFS filesystem.

**Comment by basilfx** [comment]
@kugel2 Thanks for reporting. The issue should be fixed now with #15257.
