### ISSUE TITLE
master:boards/nucleo-f207zg/include/periph_conf.h line:254

### ISSUE THREAD

**Issue by kex2017** [RIOT-OS/RIOT#15272]
dma_chan should be set to[0-7]
set to 8,It works, but it's not recommended

**Comment by aabadie** [comment]
8 means first stream (stream 0) of DMA2, so it seems correct. @bergzand, can you confirm ?

**Comment by kex2017** [comment]
> 8 means first stream (stream 0) of DMA2, so it seems correct. @bergzand, can you confirm ?

not stream ,channel

**Comment by wosym** [comment]
It was my very first day using an STM32 when I added this ethernet configuration in #12804. So it's definitely not unlikely that I made a mistake here. 

Would you care to elaborate why you think it should be 0-7 instead of 8?
