### ISSUE TITLE
vtimer: refactor vtimer_set_msg

### ISSUE THREAD

**Issue by LudwigOrtmann** [RIOT-OS/RIOT#1533]
`vtimer_set_msg` has a useless return value.

**Comment by PeterKietzmann** [comment]
I think this could be 1. a newbie task or 2. be closed as it is gonna be refactored by the TTF (timer task force). What do you think @haukepetersen ?

**Comment by OlegHahm** [comment]
I would say it doesn't hurt to "fix" this and we don't know how long it will take until the new timer will be in place. We already made the mistake once to postpone all vtimer issues waiting for the glorious new timer.

**Comment by kushalsingh007** [comment]
Can you explain what you mean by fixing the value , does that mean changing the return type to void ?
Since vtimer_set_msg  is being used at only two places and that too in vtimer.c , I guess it wouldn't hurt to change the return type to void ?

**Comment by OlegHahm** [comment]
Fixed by #2545
