### ISSUE TITLE
Does riot has parallel interface driver?

### ISSUE THREAD

**Issue by liyue75** [RIOT-OS/RIOT#15356]
For boards like stm32f4, they have FSMC(flexible static memory controller) which is used to interface with memories through parallel port. Does riot has driver for FSMC or parallel interface?

**Comment by benpicco** [comment]
Is this comparable with QSPI?

**Comment by liyue75** [comment]
@benpicco Maybe I didn' t describe it clearly. Which I mean  is parallel bus which use address lines and data lines, STM32 has a peripheral to control these lines called FSMC.
Now I can use the FSMC to control the parallel data transmission. It seems there is no FSMC driver in RIOT.

**Comment by benpicco** [comment]
No unfortunately there is no driver yet, you would need to provide one yourself.
You can compare what they are doing over at Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/29686

**Comment by liyue75** [comment]
@benpicco Thank you for your reply, I have alreadly used it.
Now I will close this issue.
