### ISSUE TITLE
`PKG_SOURCE_LOCAL` checked in `pr_check`

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#15665]
#### Description
The build system variable `PKG_SOURCE_LOCAL` is checked in PR sanity checker script `dist/tools/pr_check/pr_check.sh` for some reason:

https://github.com/RIOT-OS/RIOT/blob/6eb8e17861be1914cf4a86df9815243ee2776a2f/dist/tools/pr_check/pr_check.sh#L60-L64

This rather should go into `dist/tools/buildsystem_sanity_check/check.sh`.

**Comment by fjmolinas** [comment]
Fixed in #15730
