### ISSUE TITLE
periph_can is missing into nucleo-f722ze/Makefile.features

### ISSUE THREAD

**Issue by donsez** [RIOT-OS/RIOT#15711]
#### Description
periph_can is missing into nucleo-f722ze/Makefile.features

nucleo-f722ze board and stm32f722ze CPU have 1 × CANs (2.0B Active) interface

### Useful links
* https://github.com/RIOT-OS/RIOT/blob/master/boards/nucleo-f722ze/Makefile.features
* Section 3.28 in https://www.st.com/resource/en/datasheet/stm32f722ze.pdf

**Comment by madokapeng** [comment]
If no one work on this. I can take it.

**Comment by madokapeng** [comment]
Just got my nucleo board. working on adding CAN feature.
Due to the hardware limitation, I would like to use loopback mode to run the test. It will be some changes on tests/candev application as well.
