### ISSUE TITLE
GitHub: Typo in WIP label

### ISSUE THREAD

**Issue by janosbrodbeck** [RIOT-OS/RIOT#15765]
#### Description

I know very minor but....there is one 'and' too much in the WIP label. It's sadly not PRable.
![Screenshot from 2021-01-14 02-42-03](https://user-images.githubusercontent.com/5045674/104533690-2a5c6e00-5613-11eb-9ef2-b0b602a0936d.png)

#### Steps to reproduce the issue

Go to Pull requests and hover over a PR with WIP state

**Comment by dylad** [comment]
Hello @janosbrodbeck and thanks for your report !
This should be fixed now !

**Comment by miri64** [comment]
Confirmed!
