### ISSUE TITLE
No null-pointer checks in low-level drivers

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#1581]
In the current (revised) version of the low-level drivers, there is no check if the given device is actually valid. For example we do something like this in most drivers (shortened down):
```c
int gpio_read(gpio_t dev)
{
    GPIO_TypeDef *port = 0;
    uint32_t pin = 0;

    switch (dev) {
        case GPIO_0:
            port = GPIO_0_PORT;
            pin = GPIO_0_PIN;
            break;
    }
    return port->ODR & (1 << pin);          /* read output data register */
}
```
This can certainly lead to a null-pointer exception if the device given in `dev` is out of range. The current rationale is however, that only values defined int `gpio_t` (enum) are being passed to these functions at the first hand.

An alternative would be a negative return value on invalid devices, e.g. `default: return -1`. But this would change the interface and the way you could use some interfaces in some ways, for the function above you could for example not use it as `if(gpio_set(GPIO_x) {...}` anymore.

As we talk about low-level interface, I personally vote for omitting device/null-pointer checks in favor of a lighter and slimmer interfaces.

Other opinions on this?

**Comment by thomaseichinger** [comment]
Consensus found.
