### ISSUE TITLE
Support for TI CC2530

### ISSUE THREAD

**Issue by cyclonmaster** [RIOT-OS/RIOT#1587]
Do you have a plan to support Texas Instrument Zigbee module CC2530?

**Comment by avalon12** [comment]
Question here is for CC2530, its a diff chip. MCU is based on 8051 architecture and should be quite different from the CC2538.

**Comment by haukepetersen** [comment]
@avalon12 I was not aware of this difference... I agree that in this case this issue should stay open.

**Comment by LudwigOrtmann** [comment]
Apparently nobody is working on support this chip at the moment, so the *question* is answered.
(I'm not in favor of having an open issue for every possible feature we can think of unless someone is at least potentially working on it.)
