### ISSUE TITLE
cpu/stm32f1: implement SPI slave mode

### ISSUE THREAD

**Issue by thomaseichinger** [RIOT-OS/RIOT#1588]
The SPI slave mode is not implement yet for the stm32f1 because of lack of hardware to test this.

**Comment by PeterKietzmann** [comment]
This also applies to other boards as we said that we have nearly no use case for it. We could close this issue or add the newbie label.

**Comment by khawajamechatronics** [comment]
Hi,

I have expertise in SPI Communication on STM32 Boards, Specifically on STM32F0.

I would like to know, whether Patch needs Software Programming only or, Also need to be Hardware tested?

**Comment by LudwigOrtmann** [comment]
Of course you need to test the patch on hardware.

**Comment by khawajamechatronics** [comment]
Hi,
I finally recieved STM32F1 board. Can you please just guide me how to get started with this board so I can test this patch.
Thanks

**Comment by LudwigOrtmann** [comment]
@khawajamechatronics STM32F1 is a CPU, which board are you referring to?

**Comment by PeterKietzmann** [comment]
@khawajamechatronics do you mean something like this [getting started](https://github.com/RIOT-OS/RIOT/wiki/Getting-started-with-STM32F%5B0|3|4%5Ddiscovery-boards)?

**Comment by khawajamechatronics** [comment]
@LudwigOrtmann I am using STM32F1 Discovery Board(STM32VL Discovery).
@PeterKietzmann Yes, as there is NO Stm32f1discovery board folder in RIOT.

**Comment by PeterKietzmann** [comment]
@khawajamechatronics we currently support some boards including the stm32f1 cpu but we never portetd RIOT to a stm32f1discovery board. Would this also be interesting to you :-) ? All drivers should be usable, it's mostly about the peripheral configuration.

**Comment by khawajamechatronics** [comment]
@PeterKietzmann Yes, this is fun. I also have STM32F0, STM32F4 Discovery, 
I am also working on STM32F4, I would like to first understand complete working of RIOT and then go for implmentation of CAF.

**Comment by khawajamechatronics** [comment]
Just guide me how to proceed.

**Comment by katezilla** [comment]
Hi,
this might help you to port your board: https://github.com/RIOT-OS/RIOT/wiki/Porting-Guide
You can skip the CPU part, since it is already supported but you will have to set it in the MAKEFILE.include.

**Comment by PeterKietzmann** [comment]
@khawajamechatronics was the porting guide helpful?

**Comment by PeterKietzmann** [comment]
@khawajamechatronics did you find time to work on this or are you planning to do so?

**Comment by khawajamechatronics** [comment]
Hi @PeterKietzmann Sorry I got busy with work. Yes I am planning to complete this task asap. I will be in touch with you.
Thanks

**Comment by PeterKietzmann** [comment]
@khawajamechatronics still plan to implement it :-) ?

**Comment by PeterKietzmann** [comment]
We decided against implementing slave modes as they haven't been used by someone. I'll close that issue with memo label set, just *if* someone cares about the slave mode at any time.
