### ISSUE TITLE
improve:mtd spi nor

### ISSUE THREAD

**Issue by kex2017** [RIOT-OS/RIOT#15894]
#### Description
mtd:https://github.com/RIOT-OS/RIOT/blob/master/drivers/mtd_spi_nor/mtd_spi_nor.c#L396

 while (res < 0 || retries < MTD_POWER_UP_WAIT_FOR_ID);
should be
 while (res < 0 && retries < MTD_POWER_UP_WAIT_FOR_ID);

**Comment by jia200x** [comment]
hi @kex2017 

could you please elaborate more about this issue? E.g why is this an issue, what's the expected result, what happens now, etc.

**Comment by kex2017** [comment]
> hi @kex2017
> 
> could you please elaborate more about this issue? E.g why is this an issue, what's the expected result, what happens now, etc.

The maximum number of times the ID is always retried regardless of whether it is read successfully or not

**Comment by kex2017** [comment]
> hi @kex2017
> 
> could you please elaborate more about this issue? E.g why is this an issue, what's the expected result, what happens now, etc.

I expect to end the retry loop after reading the correct return value

**Comment by benpicco** [comment]
Indeed, good catch!
Do you want to submit a PR?

**Comment by madokapeng** [comment]
Looks like @benpicco has a PR to fix the issue? if not, I can work on this.
