### ISSUE TITLE
net: eliminate RIOT IPv6 network layer bottleneck

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#16]
In the current state, the RIOT network layer tolerates only 1 IPv6 packet going in or out of the device at the same time. Outgoing packets can overwrite incoming packets and the other way around due to the fact that there is only 1 buffer for incoming and outgoing packets (IPv6 Buffer: uint8_t buffer[BUFFER_SIZE]". Find a solution to avoid overwriting of incoming/outgoing packets, especially when using fast transmissions.

The TCP layer (only!) is currently using a dirty HACK for sending packets via a separate output buffer "uint8_t ip_send_buffer[BUFFER_SIZE]" in sys/net/sixlowpan/sixlowip.c

**Comment by authmillenon** [comment]
"fixed" in new network stack.
