### ISSUE TITLE
Implement config module for all platforms

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#162]
The config module was developed for the MSB-A2, but should be ported to all supported platforms.

**Comment by PeterKietzmann** [comment]
I don't really know what config does. Is this still an issue? Will it be solved by the new network stack?

**Comment by OlegHahm** [comment]
The config module is meant to store persistent configuration data on a node in non-volatile (i.e. flash) memory. It can be implemented by using a particular ROM region that doesn't get overwritten when flashing a new program. TI MSP430 provide a so called INFOMEM region for that and I implemented a similar section for the ARM7 of the MSBA2.

**Comment by LudwigOrtmann** [comment]
In the context of the firmware update taskforce this module will probably be overhauled.

**Comment by kushalsingh007** [comment]
@LudwigOrtmann : When is the firmware update scheduled ?

**Comment by LudwigOrtmann** [comment]
Out of scope for the GSOC application period.

**Comment by kaspar030** [comment]
Solved through #5756.
