### ISSUE TITLE
CAN: raw_can_set/get_bitrate doesn't work on native board.

### ISSUE THREAD

**Issue by Ciusss89** [RIOT-OS/RIOT#16207]
#### Steps to reproduce the issue
Compile test **conn_can** for native board.

#### Expected results
This issue regards only NATIVE board,  it works fine on my STM32 board 

#### Actual results
both set/get bitrate fails:
```
> test_can list
test_can list
CAN #0: can0
CAN #1: can1
> test_can get_bitrate 0
test_can get_bitrate 0
no link data found
Error when getting bitrate: res=-95
```

With debug ON
```
no link data found
raw_can_set_bitrate: error when getting clock (-95)
register_filter_entry: ifnum=0, filter=0x100, mask=0x400007ff, param=0x8076018
```
#### Versions
current master.

**Comment by vincent-d** [comment]
There are 2 things with bitrate on native IIRC:
- virtual CAN interface do not have a bitrate
- changing bitrate on a real CAN interface with libsocketCAN requires root access

**Comment by Ciusss89** [comment]
> There are 2 things with bitrate on native IIRC:
> 
>     * virtual CAN interface do not have a bitrate
> 
>     * changing bitrate on a real CAN interface with libsocketCAN requires root access

Ok, this means that is not a bug.

Just a question, to test a specific bitrate with the native board, can I use the userspace **ip** command, eg : `sudo ip link set vcan0 type can bitrate 1000000` 
should be equal or not?

**Comment by vincent-d** [comment]
> can I use the userspace ip command, eg : sudo ip link set vcan0 type can bitrate 1000000

yes, this is equivalent as what libsocketCAN does (note that you are using the `sudo` command ;) )

**Comment by Ciusss89** [comment]
> > can I use the userspace ip command, eg : sudo ip link set vcan0 type can bitrate 1000000
> 
> yes, this is equivalent as what libsocketCAN does (note that you are using the `sudo` command ;) )

Thanks for the support. I close the issue :beers:
