### ISSUE TITLE
(Optional) UDP-ZEP header encapsulation for nativenet

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#163]
Packets transmitted over the tap interface of nativenet should be optionally encapsulated in UDP datagrams using the ZEP header to enable easy debugging of IEEE802.15.4 frames via Wireshark.

**Comment by authmillenon** [comment]
After a little bit of thinking: This sounds not like a newbie task.

**Comment by OlegHahm** [comment]
Almost 2 years...

**Comment by authmillenon** [comment]
One of the oldest remaining issues :)
