### ISSUE TITLE
Can nimble's host and controller runs on different devices?

### ISSUE THREAD

**Issue by sada45** [RIOT-OS/RIOT#16310]
Hey:
I used to use contiki os, it has provided an example called `slip-radio`. The example requires a node and a host (e.g. a raspberry pi) connected with USB. The protocol below the data link layer run on the node and the others on the host.

So, is there any "slip-radio like" example for nimble and RIOT which can run the controller on node and host (e.g. L2CAP, GAP) on a linux-based machine? It seems that nimble's HCI layer can support RAM, UART etc.

Thanks!

**Comment by haukepetersen** [comment]
Hej @sada45,

running the NimBLE controller stand-alone is indeed possible with NimBLE in general. However, this configuration option is currently not available for the RIOT port. But then again, there is nothing in the NimBLE pkg in RIOT, that actually would prevent this setup, so it should be rather simple to add this configuration option to RIOT. As far as I know, nobody is working on this currently, so feel free to PR something :-)
