### ISSUE TITLE
No output in pyterm after flashing to STM32F0discovery board

### ISSUE THREAD

**Issue by hoekstraarie** [RIOT-OS/RIOT#16336]
Hello everyone,

I'm trying to get started with RIOT-OS, I followed the tutorials and can compile and run my code on my native system. But when I try to flash my code on my board I don't get any output on my terminal. 

My OS can find the USB so that is not the issue, it just doesn't give any output. Though I expect hello world to be printed. 

I compile and flash my code on a virtualbox with Ubuntu and my host is a Windows 10 machine. 

![knip1](https://user-images.githubusercontent.com/44606223/114850906-8df86200-9de1-11eb-9aca-ff42f726f2bf.PNG)

![knip2](https://user-images.githubusercontent.com/44606223/114850947-9a7cba80-9de1-11eb-86ca-3196d9bc7154.PNG)

I got some pictures attached with my commands and the output.

**Comment by jeandudey** [comment]
Hello @hoekstraarie !

Have you added your user to the `dialout` group in your OS? This might be necessary to access serial ports with your user. If thats the case and still no output is shown, resetting the board while the serial terminal is open shows anything?

Another thing to do is to check if it's flashing process is working and the board works, you might want to flash the `tests/leds` test to see if the on board leds blink. E.g.:

- `BOARD=stm32f0discovery make -C tests/leds flash reset`

**Comment by hoekstraarie** [comment]
Hello @jeandudey,

Thanks for your comment on my issue. Fortunately I solved the problem, there was a problem with the USART breakoutboard. 

Have a great day!

**Comment by jeandudey** [comment]
Thanks for the response @hoekstraarie !

Closing this now since it was solved
