### ISSUE TITLE
Can't add a static library to RIOT

### ISSUE THREAD

**Issue by neuromancer-valis** [RIOT-OS/RIOT#16355]
#### Description

Hey guys, I can't add a static library (cross-compiled) `libexample.a` to my project via the `USEMODULE += libexample.a` field.

#### Actual results

Instead I get the following warning message:

`error: ISO C99 requires whitespace after the macro name
#define MODULE_LIBEXAMPLE.A 1
`

**Comment by kaspar030** [comment]
> `USEMODULE += libexample.a` field.

try `USEMODULE += libexample`(without `.a`) instead.

**Comment by kaspar030** [comment]
@neuromancer-valis I'll close this, as I'm certain this solved your issue. Please reopen if you think otherwise!

**Comment by aabadie** [comment]
Maybe have a look at the [bindist example](https://github.com/RIOT-OS/RIOT/tree/master/examples/bindist). It seems that you can't use `USEMODULE` with archive but rather have to use `BIN_DIRS` and `BIN_USEMODULE` variables:

https://github.com/RIOT-OS/RIOT/blob/855a6fa36a9f807227121ca3fc54a1927317079c/examples/bindist/Makefile#L20-L26

Let us know if that solves your problem.

**Comment by aabadie** [comment]
It seems that another possibility to a `.a` file to the build is to use the `ARCHIVES` variable: https://github.com/RIOT-OS/RIOT/search?q=ARCHIVES

**Comment by ubik-valis** [comment]
Thank you all for your answers! I followed the bindist example, but still have include errors. Adding the include files with `INCLUDES` throws an error that no such file or directory exists.
