### ISSUE TITLE
riotctrl: shell interaction seems timing sensitive

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#16415]
#### Description

`tests/turo` and `tests/congure_test`fail on samr21-xpro since the programmer wrapper has been disabled.
A simple delay fixes the issue: https://gist.github.com/kaspar030/a3022c79e4ed07ec82b91a988db5b4cb

#### Steps to reproduce the issue

`BOARD=samr21-xpro make -Ctests/turo flash test`

#### Expected results

tests succeed

#### Actual results

tests fail

**Comment by miri64** [comment]
Do you think adding a small (configurable) delay before https://github.com/RIOT-OS/riotctrl/blob/904778c7ab01463faf196ef3971deafad4ae5913/riotctrl/ctrl.py#L139 could help with that as well? If yes, maybe the issue should be cross-reported over at the `riotctrl` as well.
