### ISSUE TITLE
fatal error: sys/ioctl.h: No such file or directory 

### ISSUE THREAD

**Issue by robertobruzzese** [RIOT-OS/RIOT#16424]

**Comment by robertobruzzese** [comment]
When I try to make the board this error message comes to me.

**Comment by jeandudey** [comment]
Hello @robertobruzzese , are you using any external code in your application? What are you trying to achieve?

The `sys/ioctl.h` include header is common on unix systems but it isn't provided on RIOT.

**Comment by jeandudey** [comment]
Any update on this?

**Comment by robertobruzzese** [comment]
NO

Il giorno 15 maggio 2021 2:04, Jean Pierre Dudey ***@***.***> ha scritto:






Any update on this?

**Comment by jeandudey** [comment]
Closing this since no information about the error has provided, if the error is still present please reopen this issue and add the corresponding data about it 😉
