### ISSUE TITLE
STM32F4DISCOVERY make term hangs

### ISSUE THREAD

**Issue by forellendev** [RIOT-OS/RIOT#16431]
#### Description

I execute the following command:
`$ BOARD=stm32f4discovery make all flash term`
But the the terminal now hangs after outputting these two lines:
`
Welcome to pyterm!
Type '/exit' to exit.
`

#### Versions

I'm running this under Ubuntu 20.04.2.0 LTS.

**Comment by fjmolinas** [comment]
Hi, the [stm32f4discovery](https://doc.riot-os.org/group__boards__stm32f4discovery.html) does not provide UART over the usb port, are you using an external usb/tty converter?

**Comment by fjmolinas** [comment]
Stale, closing since an ftdi device was probably not used.
