### ISSUE TITLE
Multithreading in RIOT

### ISSUE THREAD

**Issue by hoekstraarie** [RIOT-OS/RIOT#16467]
#### Description

Example code for multithreads in RIOT.
#### Steps to reproduce the issue

We got some working code with one thread but there are no examples with more than one thread.
#### Actual results

When I try to make more threads one thread is spitting his results while the others are blocked

**Comment by kaspar030** [comment]
There's some documentation in https://api.riot-os.org/group__core__sched.html. If your threads share the same priority level, the behaviour you're seeing is expected.

**Comment by hoekstraarie** [comment]
Thanks for your answer, I got it working a few minutes ago. I made a mistake with the stack size. So I'm going to close this issue now.
