### ISSUE TITLE
test:master stm32_eth module

### ISSUE THREAD

**Issue by kex2017** [RIOT-OS/RIOT#16516]
Is there an example for this module?

**Comment by jeandudey** [comment]
**If you only want to test it by plugging an ethernet cable:**

You can test it using [examples/gnrc_networking](https://github.com/RIOT-OS/RIOT/tree/master/examples/gnrc_networking) for your board, `stm32_eth` is pulled by the boards when `netdev_default` module is used (which in turn is pulled by `gnrc_netdev_default`), so if your stm32 board provides Ethernet support and is present on RIOT it should work out of the box, if it's for a custom board you own and you have your own board definitions file you may want to check [this](https://github.com/RIOT-OS/RIOT/blob/3d18f1ad672ac5eeab1f2a25b14a2aece0eb7e58/boards/nucleo-f746zg/Makefile.dep#L1-L3) as an example in how to include that module automatically when `netdev_default` is used.

**If you need to use it directly (the netdev device)**

You may want then to use the netdev device driver API directly, on GNRC code there is great and example code of how it should be used.
