### ISSUE TITLE
tests: test/libfixmath hangs on Travis CI

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#1652]
Cannot reproduce at home: The compilation for `test/libfixmath` hangs on Travis CI, not always, but often. As of #1648 the test does not get built on Travis CI.

**Comment by authmillenon** [comment]
This is an issue once again. This time it fails randomly.

**Comment by authmillenon** [comment]
Now the svn at googlecode.com has a 502 error -.-

**Comment by authmillenon** [comment]
Maybe #2645 can fix it

**Comment by phiros** [comment]
#1648 fixed this (by not building libfixmath on Travis).
Could be relevant for other CI systems as well -> memo
