### ISSUE TITLE
RFC: Divide sixlowpan into more than just ipv6 and sixlowpan

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#1655]
Deviding sixlowpan into 2 seperate modules makes sense from an architectural standpoint. But additionally regarding space constraints I wonder if it would be even more plausible to devide them further up with a dependency graph as follows (in `git-log --graph` like syntax ;-)):

```bash
* ipv6                   # core IPv6 functionality (without the stuff routers do)
|\ 
| * sixlowpan            # core 6LoWPAN functionality (without the 6LR-ND and 6LBR-ND part)
* | ipv6_router          # IPv6 router functionalities
|\ 
* | sixlowpan_router     # 6LR-ND
* | sixlowpan_border     # 6LBR-ND
  * rpl, olsr2, aodv2, …
```

I guess this way we can save a lot of space (no forwarding table, neighbor cache size == 1, less code) and overhead in general in the network stack.

**Comment by OlegHahm** [comment]
Fixed in gnrc.
