### ISSUE TITLE
Lora sx1278 Module +Riot+Arduino

### ISSUE THREAD

**Issue by IagoMrt** [RIOT-OS/RIOT#16645]
#### Description
 Hello everyone, I am a new user of RIOT, right now I am working in the concept of using RIOT + Lora + Arduino.

I am trying to run the sx127x driver example for that I am using:
Lora module: Ra-01 Sx1278.
Arduino board: arduino-mega2560.

I am aware the drivers are designed for sx1276 modules, however the difference between them is just the band they work on (800mhz-433mhz) so I don't know if that could be an issue.

So far I have modified the sx127x_params.h librari to remap the ports for the arduino board as follows:

#ifndef SX127X_PARAM_SPI
#define SX127X_PARAM_SPI                    (SPI_DEV(0))
#endif

#ifndef SX127X_PARAM_SPI_NSS
#define SX127X_PARAM_SPI_NSS                GPIO_PIN(PORT_B, 0)       /* 51 */
#endif

#ifndef SX127X_PARAM_RESET
#define SX127X_PARAM_RESET                  GPIO_PIN(PORT_B, 4)       /* 10 */
#endif

#ifndef SX127X_PARAM_DIO0
#define SX127X_PARAM_DIO0                   GPIO_UNDEF     /* No connected */
#endif

#ifndef SX127X_PARAM_DIO1
#define SX127X_PARAM_DIO1                   GPIO_PIN(PORT_B, 5)      /* 11 */
#endif

#ifndef SX127X_PARAM_DIO2
#define SX127X_PARAM_DIO2                   GPIO_UNDEF       /* No connected   */
#endif

#ifndef SX127X_PARAM_DIO3
#define SX127X_PARAM_DIO3                   GPIO_UNDEF       /*  No connected  */
#endif

#ifndef SX127X_PARAM_PASELECT
#define SX127X_PARAM_PASELECT               (SX127X_PA_BOOST)
#endif

#ifndef SX127X_PARAM_TX_SWITCH
#define SX127X_PARAM_TX_SWITCH              GPIO_UNDEF
#endif

#ifndef SX127X_PARAM_RX_SWITCH
#define SX127X_PARAM_RX_SWITCH              GPIO_UNDEF
#endif

but  I haven't been able to run the example I get the following errors within the debug information:
**2021-07-14 13:27:25,822 # Failed to initialize SX127x device, exiting
2021-07-14 13:27:25,821 # [sx127x] error: no valid device found**
 

If any of you have worked with this kind of modules or even the sx1276 modules together with arduino would be nice to have some guideliness on how to proceed in order to make the system work.

Thanks for your help.

Iago Martínez.

**Comment by Citrullin** [comment]
You should format your code with markdown. That makes it easier to read. 
Have you checked the pins for it? Often it is just a simple mistake in the wiring. 
Maybe even check with a logicAnalyzer if anything is going over the lanes.

Personally I don't recommend to use the mega2560 with RIOT OS. You are probably better off using just the Arduino IDE, even though you don't get the nice abstraction and features of RIOT. It's still a not very powerful 8-Bit microcontroller. You reach the limits of it with RIOT pretty quickly. 
You are probably better off with an ESP32, nRF52 or something similar, if you want to use RIOT.
