### ISSUE TITLE
Add CITATION.cff 

### ISSUE THREAD

**Issue by pokgak** [RIOT-OS/RIOT#16696]
#### Description
Github adds support for showing citation for the repo. Since the RIOT community have a lot of contributors from academia, this should be a nice addition.

### Useful links

https://github.blog/changelog/2021-07-29-enhanced-citation-support/
https://citation-file-format.github.io

**Comment by waehlisch** [comment]
i saw this too but was not really happy with the information that can be included in the CFF.

**Comment by pokgak** [comment]
I don't have any preference for this. Just came across this and think that some people here might be interested. Feel free to close if not relevant 😄
