### ISSUE TITLE
Implement MAC protocol for CC2420

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#167]
The CC2420 driver seems to miss MAC layer implementation so far.

**Comment by authmillenon** [comment]
Is this still an issue with `netdev2`/`GNRC`?

**Comment by OlegHahm** [comment]
Yes, but since we do not even have any driver for cc2420 any more, we can close this.

**Comment by authmillenon** [comment]
Even if it was implemented (it's a real shame it isn't) this wouldn't be a `cc2420` issue since MAC should be implemented above `netdev2`.
