### ISSUE TITLE
particle: error while flashing using Docker build and DFU mode

### ISSUE THREAD

**Issue by nicoHarel** [RIOT-OS/RIOT#16749]
#### Description

Hello everyone. I've decided to switch to Docker recently since I'm tired of using VMs. It's awesome that RIOT offers that possibility. 

However I've been running into a problem:
When I try to flash my particle board (Xenon) using the command under, I get a missing file error.
`make flash BUILD_IN_DOCKER=1 BOARD=particle-xenon PARTICLE_MONOFIRMWARE=1`

I know in this mode the checksum needs to be verified at startup so it of course makes sense that this file is needed. Yet it simply isn't there when building with Docker. 

#### Steps to reproduce the issue

- Go to examples/hello-world
- Use the following command: `make flash BUILD_IN_DOCKER=1 BOARD=particle-xenon PARTICLE_MONOFIRMWARE=1`

#### Expected results
Make flash runs without issues. 

#### Actual results
The error: 
`Could not open file /my_file_path/RIOT/examples/hello-world/bin/particle-xenon/hello-world.bin-checksummed for reading: No such file or directory
`

I've checked, the file doesn't exist. It is there if I build without Docker.

Have a good week everybody. 

Edit: I didn't want to post the full build logs. But I have them if needed.

**Comment by dylad** [comment]
@nicoHarel Are you on Windows ?
I can't reproduce your issue with Linux Mint 19.3.

**Comment by nicoHarel** [comment]
> @nicoHarel Are you on Windows ?
> I can't reproduce your issue with Linux Mint 19.3.

No, I'm on Fedora. And it is probably only occurring on Fedora.
I'm also unable to reproduce on Linux Mint.

**Comment by dylad** [comment]
I was able to reproduce on Linux Mint after all, I had to run make clean before and the same error appears.
@nicoHarel could you check if  #16857 fixes this issue please ?

**Comment by nicoHarel** [comment]
Yeap, perfect. Thanks.
