### ISSUE TITLE
doc: Cleanup CMSIS headers

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1676]
The imported CMSIS headers could need some cleanup to be aligned with coding conventions and better integration into the API documentation.

**Comment by PeterKietzmann** [comment]
Do we really want to clean up those large header files???

**Comment by gebart** [comment]
Can we just put them inside their own Doxygen sub group? Like @haukepetersen said, they will be overwritten from time to time and we don't want spend much effort on maintaining them.

**Comment by OlegHahm** [comment]
I think they are mostly excluded from Doxygen anyway in the mean time. I say `wontfix`.

**Comment by haukepetersen** [comment]
excluding like we do right now sounds good to me. Can we close this issue then?

**Comment by gebart** [comment]
Exclude sounds fine. I'm OK with closing as wontfix
