### ISSUE TITLE
verify author of `sys/include/bloom.h`

### ISSUE THREAD

**Issue by LudwigOrtmann** [RIOT-OS/RIOT#1682]
The file gives @mehlis as the author, but it appears to be largely a copy of the original [`bloom.c`](https://github.com/linehan/bloom/blob/master/bloom.c) with the implementation removed.

**Comment by mehlis** [comment]
@OlegHahm @LudwigOrtmann I recommend to use the time on earth with something more productive than this discussion.

Code is public domain. So I say I am the author.

**Comment by OlegHahm** [comment]
Thanks for the recommendation - I hope you haven't spend the last four months (unsuccessfully) reasoning about this question.
