### ISSUE TITLE
GD32VF103 tracking issue

### ISSUE THREAD

**Issue by benpicco** [RIOT-OS/RIOT#16935]
#### Description

This issue is to track progress on support for the GD32VF103 line of MCUs. Peripherals are similar to the ones found on STM32F103, so it's possible to borrow some code from there.

##### Missing Drivers

 - [x] GPIO interrupts
 - [x] SPI
 - [x] I2C
 - [x] USB
 - [x] ADC

### Useful links

 - [GD32VF103 user manual](http://www.gd32mcu.com/data/documents/shujushouce/GD32VF103_User_Manual_EN_V1.2.pdf)

**Comment by maribu** [comment]
A quick look at `cpu/gd32v` indicates that all listed feature have been implemented.
