### ISSUE TITLE
examples: demonstrate more within the existing examples

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1694]
Mostly for maintenance reasons we should keep the number of examples within RIOT's main repository small. However, the examples should cover a big fraction of RIOT's (important) features to demonstrate how they can be used.

Currently, most important of all, a simple example with 6LoWPAN (and UDP), but without routing, is missing. This example should comprise an ICMP *ping* command and something like basic version of *netcat*. I think the most sensible way would be to actually implement this as system wide shell commands and extend the default example application to use 6LoWPAN. However, it might be necessary to have a basic and an enhanced default example due to heavy memory constraints on certain platforms.

Candidates that might be removed or integrated into other examples are *ccn-lite-relay* and *ipc_pingpong*.

**Comment by OlegHahm** [comment]
Should we close this?

**Comment by LudwigKnuepfer** [comment]
Why not.
