### ISSUE TITLE
floating point numbers are not displayed correctly when using printf/sprintf

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#17]
example code:
`uint32_t value = 4688400;
float test_secs = (float)(value);
printf("Value: %lu, test_secs: %f, test_secs/1000000: %f\n", value, test_secs, test_secs/1000000.0);
`
output:

`Value: 4688400, test_secs: -593395331576418032070107601347274796814779226477615119074935151325494288374806955180858448199930421815096455549544570545856896334085141326372559621036970412650772246306121905719839090181013742283966753869290184601151471616.000000, test_secs/1000000: 0.000000`

**Comment by timmmmmey** [comment]
It is still happening with CodeBench Lite 2014.05-28 and GNU Tools for ARM Embedded Processors 4.9.3 20141119. 
Still no work around?

**Comment by gebart** [comment]
Just an idea: try building without nano.specs, i.e. full functionality
newlib. It should be somewhere in the makefile.include for the board or
CPU.
(I am not at my computer right now and I don't know anything about the code
bench tool chain so I can't provide any more information)

**Comment by cgundogan** [comment]
this issue is quite old, but I came across this linker option several days ago: `-u _printf_float` or `-u _scanf_float`respectively for newlib-nano. According to the docs this should pull in float support for printf/scanf. Can someone test this?

**Comment by haukepetersen** [comment]
And while testing, do a code size comparison! I guess that would be most interesting here.

**Comment by authmillenon** [comment]
Is this still an issue?

**Comment by kYc0o** [comment]
It is related to #5094 ?

**Comment by authmillenon** [comment]
Does #5094 solve it or only partly?

**Comment by gebart** [comment]
I have a printf test in the works which will reveal missing format identifiers.
With the current default build options on Mulle the float `%f` specifier is simply ignored, native works fine without changes. I guess that means that all other newlib_nano platforms are broken too..
Adding `LINKFLAGS += -u _printf_float` to the Makefile fixes the problem on my machine, but it adds about 8 kB ROM usage..

**Comment by gebart** [comment]
#5094 solves the problem on mulle. (Add `USEMODULE += printf_float` to Makefile)

**Comment by kYc0o** [comment]
Good! Can we close this?

**Comment by gebart** [comment]
yes, let's close this
