### ISSUE TITLE
why does mtd_native refuse to write more than 1 page?

### ISSUE THREAD

**Issue by mcr** [RIOT-OS/RIOT#17044]
#### Description
What does this test do?  It seems to prevent more than page to be written.
https://github.com/RIOT-OS/RIOT/blob/master/cpu/native/mtd/mtd_native.c#L89

#### Steps to reproduce the issue

Write 4096 bytes at offset 4096, for instance.

#### Expected results

Multiple pages should be allowed to be written, if they have been erased.

#### Actual results

-EOVERFLOW (-75)

#### Versions

running native code on Linux.

**Comment by fjmolinas** [comment]
Hi @mcr I believe that check is to enforce what the api specifies https://github.com/RIOT-OS/RIOT/blob/70744a7a9281ca0e85018bdf41dda0a1b1d9ae39/drivers/include/mtd.h#L272-L277. I'm not very involved with mtd to say much more, but I think the user is expected to handle splitting writes over pages, maybe @bergzand or @benpicco can confirm this?

**Comment by benpicco** [comment]
The `mtd_write()` function provides no abstraction at all from the underlying hardware and pushes handling of hardware differences to the application.

The `mtd_write_page()` function will take care of splitting the request into multiple page writes if necessary to fulfill the requirements of the device. The application does not have to do any hardware specific special cases.

**Comment by mcr** [comment]
Thank you.  The naming of the functions feels backwards, but I understand now.

**Comment by benpicco** [comment]
#15380 should make `mtd_write()` behave the same as `mtd_write_page()` in that regard, but it still needs to be adopted for `mtd_flashpage`
