### ISSUE TITLE
ztimer_msec conflicts with direct usage of RTT

### ISSUE THREAD

**Issue by benpicco** [RIOT-OS/RIOT#17060]
#### Description

The `ztimer_msec` module will take control of the RTT peripheral. This is a problem for applications that rely on the `periph_rtt` API to manually schedule wake from Deep Sleep:

 - some driver schedules a wake-up in 10 ms
 - The application decides to go to Deep Sleep (no RAM retained) and sets the RTT to reset the board in 1h, calls `pm_set(0)`
 - The board will wake up from Deep Sleep after 10ms

It is also a problem for platforms where `periph_rtc` and `periph_rtt` share the same peripheral and only either of the two modes can be used.

See e.g. the [sleepy node](https://github.com/benpicco/sleepy_node) application for an example of such usage pattern.

**Comment by fjmolinas** [comment]
> It is also a problem for platforms where periph_rtc and periph_rtt share the same peripheral and only either of the two modes can be used.

IMO this is not a problem, this will be flagged by `FEATURES_CONFLICT`

**Comment by fjmolinas** [comment]
Does https://github.com/RIOT-OS/RIOT/pull/17099  implement (1) close enough?

**Comment by maribu** [comment]
> @benpicco is this fixed by #17284

There is a :+1: below, so let's close the issue.
