### ISSUE TITLE
Possibility to exclude modules or source files for mocking functions in unit tests

### ISSUE THREAD

**Issue by jenswet** [RIOT-OS/RIOT#17081]
When introducing the fake functions framework to allow mocking functions in unit tests, it would be helpful to exclude certain files or modules from the build process. This is necessary to allow mocking functions without conflicting definitions.

Previous discussion:

> > > I think that's probably better since IMHO fff can be really useful when testing a driver without the hardware. I agree that adding a way to exclude the mocked module from the build system is probably the best solution but I'm not sure if it should be done by extending PERIPH_IGNORE_MODULES.
> > > We could need to test a higher level API by mocking another high level API, not directly connected to a periph API (I'm thinking of disp_dev that depends on a high-level driver).
> > > Would it makes sense to introduce an IGNORE_MODULES variables that would be used to filter-out its content from USEMODULE ? That should also work for periph_% features since in the end they are turned into regular modules.
> > 
> > +1 for `IGNORE_MODULES` as this would allow mocking non-peripheral functions as well.
> 
> I would be in favor of a simpler solution that would fit this use case, and then open a separate PR/ISSUE to discuss this generic solution. There are already cases of mocked modules in the tree, and this will make this PR more complicated than it needs.

Maybe instead of filtering out `USEMODULE` we can filter out the `c` file, this already works for `REALMODULES` by declaring them `PSEUDOMODULES` (e.g.: xtimer), we would have tho address the `SUBMODULE` case only.

_Originally posted by @fjmolinas in https://github.com/RIOT-OS/RIOT/issues/17076#issuecomment-954589350_

**Comment by maribu** [comment]
Likely the easiest way would be to wrap the function calls at link time, e.g. to replace calls to `malloc()` and friends with calls that provide thread safety, we add

```
LINKFLAGS += -Wl,-wrap=malloc -Wl,-wrap=calloc -Wl,-wrap=realloc -Wl,-wrap=free
```

With that, `__wrap_malloc()` is called in stead of `malloc()` and `__real_malloc()` can be used to call to the actual implementation. It would be quite feasible to e.g. overwrite `i2c_acquire()` and friend for mocking the I2C bus using the same trick, without major pain.

I'm optimistically closing this in the hope that above suggestion sufficiently answers the question. If not, feel free to reopen the issue.
