### ISSUE TITLE
combine all msg types

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#1749]
so the numbers dont overlap

**Comment by PeterKietzmann** [comment]
@LudwigOrtmann do you "remember what this is about"?

**Comment by LudwigOrtmann** [comment]
@PeterKietzmann the referencing PR https://github.com/RIOT-OS/RIOT/issues/1758 contains more context.

**Comment by OlegHahm** [comment]
And we still need a solution.

**Comment by authmillenon** [comment]
https://github.com/RIOT-OS/RIOT/pull/3362#discussion_r45792239 triggered me to think about this again a little. Why not make it as simple as it can get?
* all message types used in core into `core/include/msg/core_types.h`. This way they don't lose context, but we don't need a core-change double-ACK we do for non-core related messages.
* all other messages into `sys/include/msg/types.h`, which also includes `core/include/msg/core_types.h`, so anything beyond core can just include `sys/include/msg/types.h`

The grouping can then be done via documentation. z. B.:

```C
/**
 * @name Network message types
 *
 * Network message types are in the range of `0x0400` - `0x04ff`
 *
 * @{
 */
#define GNRC_NETAPI_MSG_TYPE_ACK (0x0400)
#define GNRC_NETAPI_MSG_TYPE_RCV (0x0401)
#define GNRC_NETAPI_MSG_TYPE_SND (0x0402)
/* ... */
/**
 * @}
 */
```

Then anybody introducing a new message type can add it to `msg/types.h`

**Comment by kaspar030** [comment]
While being "simple", it will lead to several problems:
- types.h will be another "rebase-congested" file like Makefile.dep. That fact alone IMHO shows that this is not an optimal solution. It is the opposite of keeping modules seperate.
- "anonymous-useless-feature" will clutter types.h
- types.h would have to remain rather static (only additions) if we want to support any kind of dynamic (or static re-)linking.

Can't you use the sender PID to differentiate between packets?
Or would your problem be solved if you could wait for messages on multiple mailboxes simultaneously?

**Comment by authmillenon** [comment]
> Can't you use the sender PID to differentiate between packets?
> Or would your problem be solved if you could wait for messages on multiple mailboxes simultaneously?

"My" problem (or rather everyones problem, ... My personal opinion is that this works as it is as long as one is careful, which on the flip side makes it maybe harder for newer people to find a good value) is that message types aren't unique. I don't get how your proposal would fix that without extra memory or code resources.

> types.h would have to remain rather static (only additions) if we want to support any kind of dynamic (or static re-)linking.

Since the only instance where we would remove something from that would be that we remove a module altogether, that's a given IMHO.

> "anonymous-useless-feature" will clutter types.h

Maybe that's a great point to see if we can find some "common" message types, that everyone can use, so "anonymous-useless-features" can use them (also if you group them appropriately in doc, I don't really see a problem with that anyway, since to a degree the same goes for stuff like `errno.h`).

> types.h will be another "rebase-congested" file like Makefile.dep. That fact alone IMHO shows that this is not an optimal solution. It is the opposite of keeping modules seperate.

There is potential merge conflict material in the current situation, too. If two features choose to have the same msg type value that's a merge conflict. Just not one that git realizes. With this solution you have to review your values when a merge conflict happens => no duplicates.

**Comment by OlegHahm** [comment]
I still think that a static list of message types makes it harder to use code outside the main RIOT repository (e.g.., proprietary applications/libraries, third party code) with RIOT. But maybe assigning a reserved range of ports would be sufficient for this. However, I still think that something that can be compiled at build time, would be more flexible. Some script (preferably integrated into the build system) could collect all modules that require dedicated message types and generate an application-unique message type.

**Comment by kaspar030** [comment]
Could use the same infrastructure as desired #4290.

**Comment by OlegHahm** [comment]
yup

**Comment by kaspar030** [comment]
@authmillenon The problem with a static list is that yes, it will run with one compile and included sources, but no, it breaks as soon as that is not longer the case. Third (+fourth) party code, static relinking, ...

If a thread receives messages from multiple sources, it has to select by source, then by type.

**Comment by OlegHahm** [comment]
Selecting only by source won't be enough for many use cases.

**Comment by kaspar030** [comment]
That's why we need to decouple endpoints from threads, in order to enable selecting by the missing option (currently we can select by source and content).

**Comment by OlegHahm** [comment]
You mean content-centric IPC? ;-)

**Comment by LudwigKnuepfer** [comment]
I am not going to work on this any time soon.

**Comment by OlegHahm** [comment]
bump

**Comment by miri64** [comment]
bump bump

**Comment by kaspar030** [comment]
Can we close this as "wontfix"?

**Comment by miri64** [comment]
I'm not against it ;)

**Comment by kaspar030** [comment]
I'll close, feel free to reopen.
