### ISSUE TITLE
doc: doc.riot.org and circle-ci  use different doxygen versions doxygen 1.8.17 vs 1.9.1

### ISSUE THREAD

**Issue by kfessel** [RIOT-OS/RIOT#17580]
#### Description

circle-ci builds doc using old doxygen 1.8.17
![image](https://user-images.githubusercontent.com/814189/151352651-321b3e06-bd21-4512-a383-cfe69c5a6538.png)

doc.riot.org is build using a more current 1.9.1
![image](https://user-images.githubusercontent.com/814189/151352563-820b0eaa-64ee-49f0-80c6-cc1cad3377c5.png)

#### Steps to reproduce the issue

look at:
https://15379-7370241-gh.circle-artifacts.com/0/doc/index.html
and 
https://doc.riot-os.org/index.html

#### Expected results

doc.riot.org and circle-ci  use the same doxygen version 

#### Actual results

doc.riot.org and circle-ci  use different doxygen versions

#### Versions

doxygen 1.8.17 ->  1.9.1
https://www.doxygen.nl/manual/changelog.html

**Comment by aabadie** [comment]
I think the issue comes from version used to generated doc.riot-os.org. The version used by circleci is the same as the one used by the static tests, e.g from Docker image riot/static-test-tools:

```
$ docker run --rm riot/static-test-tools:latest doxygen --version
1.8.17
```

**Comment by kfessel** [comment]
debian stable is at version 1.9.1

**Comment by aabadie** [comment]
The Docker image is based on Ubuntu Focal, latest LTS (next LTS will 22.04):

https://github.com/RIOT-OS/riotdocker/blob/14fa5cda36f0f09282f3d1efdca79b7c1cb83dca/riotdocker-base/Dockerfile#L1

IMHO, we should use the same version to generate doc.riot-os.org. If we wait for 22.04 and use the same Docker image to generate the doc on doc.riot-os.org, everything will use the same Doxygen version, probably higher 1.9.1.

**Comment by maribu** [comment]
Does anyone know what the state of this is?

**Comment by aabadie** [comment]
> Does anyone know what the state of this is?

The problem is potentially still there since the published online documentation is generated on a separate server with a different version than the one used for previews (Docker based).
But we can assume that both versions are the same now the riotdocker image is based on 22.04.
