### ISSUE TITLE
Kconfig: `genconfig.py` rewrites `/dev/null`

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#17862]
#### Description

... if it gets the chance (e.g., because it is run as root).

#### Steps to reproduce the issue

__WARNING__: this breaks your system!

`TEST_KCONFIG=1 sudo make -Cexamples/hello-world`

#### Expected results

`/dev/null` is still the null device

#### Actual results

`/dev/null` has random contents.

**Comment by leandrolanzieri** [comment]
Please check #17873
