### ISSUE TITLE
Implement time functions without RTC

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#179]
By now, real time functions such as `_localtime()` are only provided through the rtc driver module, which is only implemented on platforms that have a real time clock in hardware. Since many libraries need some kind of "real time", a software real time clock is required.

**Comment by authmillenon** [comment]
How about something like the following as a starting point that should be simply implementable with both `periph/rtc.h` and `xtimer.h` (if no hardware rtc exists). One thing missing are alarms, but those could be amended (maybe by someone who is a little bit more experienced with hardware timers and clocks than me ;-))

```C
/**
 * @brief   Time representation type.
 *
 * The time in seconds is always
 *
 * xrtc_time_t::sec + (xrtc_time_t::nsec / * `1e-9`).
 */
typedef struct {
    uint64_t sec;   /**< seconds */
    uint32_t nsec;  /**< nanoseconds */
} xrtc_time_t;

/**
 * @brief   Get current time in UNIX time
 *
 * Gets the current time in UNIX time (number of seconds since
 * 1970-01-01 00:00 UTC).
 *
 * @param[out] t Current time in seconds since 1970-01-01 00:00 UTC.
 */
void xrtc_now(xrtc_time_t *t);

/**
 * @brief   Get current time in UNIX time (only seconds part).
 *
 * Gets the seconds part (rounded down) of the current time in UNIX time
 * (number of seconds since 1970-01-01 00:00 UTC).
 *
 * @return  Current time in seconds since 1970-01-01 00:00 UTC.
 */
static inline uint64_t xrtc_now_sec(void)
{
    xrtc_time_t t;

    xrtc_now(&t);
    return t.sec;
}

/**
 * @brief   Set time to absolutely.
 *
 * @param[in] t     Time to set in seconds since 1970-01-01 00:00 UTC.
 */
void xrtc_set(const xrtc_time_t *t);

/**
 * @brief   Set time relatively to current time.
 *
 * Sets time relatively to current time. If the offset is bigger than with
 * @p sec representable it is adviced to use @ref xrtc_set() instead.
 *
 * @param[in] sec   Offset in seconds.
 * @param[in] nsec  Fraction in nanoseconds from second.
 */
void xrtc_set_offset(int64_t sec, int32_t nsec);
```

**Comment by miri64** [comment]
ping? (e.g. @kaspar030)

**Comment by jia200x** [comment]
is this still an issue?

**Comment by miri64** [comment]
Yes. Real-time is still pretty much dependent on `periph_rtc`.

**Comment by miri64** [comment]
This is solved by #11874 right @kaspar030 @MichelRottleuthner?

**Comment by miri64** [comment]
Ping @kaspar030 @MichelRottleuthner?

**Comment by miri64** [comment]
Looking at it, it does not look like `ztimer` provides an API for real time. This is an issue effectively unaddressed for 7 years, so is there a demand for a software real time API? /cc @kaspar030 @MichelRottleuthner @JulianHolzwarth et al.
