### ISSUE TITLE
vtimer magic constant / dead code

### ISSUE THREAD

**Issue by corecode** [RIOT-OS/RIOT#1797]
This code in vtimer_set uses a magic constant (10), and only runs right after startup (when absolute.seconds is still 0):

``` C
    if (timer->absolute.seconds == 0) {
        if (timer->absolute.microseconds > 10) {
            timer->absolute.microseconds -= 10;
        }
    }
```

https://github.com/RIOT-OS/RIOT/blob/920f49c268530e73325e8d66fafe68a4ecf1d23a/sys/vtimer/vtimer.c#L249-L253

**Comment by PeterKietzmann** [comment]
@corecode revised his statement. Can we close this issue @OlegHahm, @LudwigOrtmann ?

**Comment by corecode** [comment]
I don't remember exactly, but I do not think that I meant to say that this is a non-issue.

**Comment by gebart** [comment]
vtimer was removed
