### ISSUE TITLE
Warn : Prefer GDB command "target extended-remote :3333" instead of "target remo te :3333"

### ISSUE THREAD

**Issue by cmjang** [RIOT-OS/RIOT#18068]
#### Description
Burning is normal, but when I try to debug it, a page like this will appear and the lights on the board flash wildly. I use a nucelo board, stlinkv2-1, but I try to update the firmware and it can be successful Burning, but it doesn't work after that, using stm32cubemxide can debug normally

#### Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/29453690/167110987-923cf440-6f6a-4ae9-bbcf-ba9b80eba55a.png)
been stuck here

**Comment by qidian256** [comment]
just reset of your MCU
