### ISSUE TITLE
Bug: adc_sample() returns values in range of 16bit resolution

### ISSUE THREAD

**Issue by mariemC** [RIOT-OS/RIOT#18118]
#### Description
Using adc_sample() with 12bit resolution doesn't return negative values but it considers the return value as a 16bit value.

#### Steps to reproduce the issue
A board based on samd51 is used with a custom application, whithin the application I have used adc_sample() 
int32_t val[i] =adc_sample(ADC_LINE(i), ADC_RES_12BIT).

#### Expected results
I was expecting negative values or values within the 12bit resolution range. 
For example for some voltage on the pin, I was expecting to get 4095 or a negative value. 

#### Actual results
The output was in a 16bit range, I am actually getting values like this: 65536

 #### Fixes

What fixed my issue is to cast adc_sample() to 16 bit.
int16_t value[i] = (int16_t) adc_sample();

#### Versions

Operating system: Linux ubuntu 5.13.0-41-generic #46~20.04.1-Ubuntu
Build environment:arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)

**Comment by benpicco** [comment]
AFAIR this was with an early version of #18146 which can return negative values.
Since now `int16_t` is used internally, the issue should no longer occur.

**Comment by maribu** [comment]
IMO issues with https://github.com/RIOT-OS/RIOT/pull/18146 while it has not been merged yet should be better discussed there as part of the review process. And apparently the issue only was found in a previous version of that PR and is fixed anyway.
