### ISSUE TITLE
Unexpected ztimer assert when using with stdio_rtt

### ISSUE THREAD

**Issue by sada45** [RIOT-OS/RIOT#18116]
#### Description
The ztimer will assert when `ztimer_now()` is called and used with stdio_rtt.

#### Steps to reproduce the issue
I am using the NimBLE in the RIOT OS. The older version is fine with my environment. 
I update to the latest RIOT OS and try the `tests/nimble_l2cap`. 
Since I use the SEGGER RTT as the output, I added `USEMODULE += stdio_rtt` in the `cpu/nrf52/Makefile.dep`. Then I build the project as normal. 

#### Expected results
The output of the node is shown as:
```shell
ztimer_init(): ZTIMER_TIMER using periph timer 0, freq 1000000, width 32
sys/ztimer/core.c:174 => 0x705
```

#### Actual results
The bug is in `_ztimer_now_extend(clock)` called by `ztimer_now()`. The `clock->max_value` is 0.
For now, I not quiet sure what cause the bug, but it definitly  related to the SEGGER RTT.
In the `ztimer_init()`, there are some log outputs with  `LOG_DEBUG` macro. 
I find that only the first log will be correctly output, even if I extend the SEGGER RTT output buffer to 1024 bytes.
So I change the `LOG_DEBUG` macro to `do {} while(0U)`, and the example runs normally!
```shell
NimBLE L2CAP test application
# Scanning now
```

#### Versions
The RIOT OS version is 2022.07-devel-481-g37da8
The operating system is Ubuntu20.04 VM, and the RIOT OS is in a share directory
GCC: gcc version 10.2.1 20201103 (release) (GNU Arm Embedded Toolchain 10-2020-q4-major)

**Comment by sada45** [comment]
I think I found the reason. Inspired by the #issue14980, the timer is call before the `ztimer_init()`. 
The function `stdio_write() ` in `stdio_rtt.c` will call the `ztimer_now()` to output the log through the RTT.
However, the first log is output before the timer is initilized and cause the issue above.

**Comment by fjmolinas** [comment]
Hi @sada45, Nice catch this is probably also an issue if using `semi-hosting`, so as a quick fix simply don't set `LOG_LEVEL > LOG_DEBUG` in https://github.com/RIOT-OS/RIOT/blob/f6d5a54c3e5780001bc0869c305a8ea1420d576e/tests/nimble_l2cap/Makefile#L20.

But generally I guess not `stdio` module depending on ztimer so output anything before `ztimer` is initiated, I'll add a patch.
