### ISSUE TITLE
reference/core: primers missing

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#1837]
In order to learn RIOT from the reference, introductory material is missing.

TODO:
- [ ] [Scheduler](http://riot-os.org/api/group__core__sched.html)
- [x] [Threading](http://riot-os.org/api/group__core__thread.html)
- [ ] [Synchronization](http://riot-os.org/api/group__core__sync.html)
- [x] [Messaging / IPC](http://riot-os.org/api/group__core__msg.html) (https://github.com/RIOT-OS/RIOT/pull/4475)
- [ ] [Power Management](http://riot-os.org/api/group__core__lpm.html)
- [ ] [IRQ Handling](http://riot-os.org/api/group__core__irq.html)
- [ ] [IO Interface](http://riot-os.org/api/group__core__io.html)
- ~~[Hardware timer](http://riot-os.org/api/group__core__hwtimer.html)~~ (does not exist anymore)
- [ ] [Startup and Configuration](http://riot-os.org/api/group__core__internal.html)

**Comment by miri64** [comment]
Updated the list.

**Comment by smlng** [comment]
close in favor of #4309 ?

**Comment by miri64** [comment]
I would prefer to keep this open, because this is more core specific and thus of more importance
