### ISSUE TITLE
net: inet_ntop might be broken

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1845]
Looking at https://github.com/RIOT-OS/RIOT/blob/master/sys/net/include/inet_ntop.h#L30:
```
/*
* WARNING: Don't even consider trying to compile this on a system where
* sizeof(int) < 4.  sizeof(int) > 4 is fine; all the world's not a VAX.
*/
```
I wondered if this could be a problem on MSP430 and ATMega.

I've added data type size comparison to the MCU familiy pages in the wiki (see https://github.com/RIOT-OS/RIOT/wiki/Family%3A-ATmega#data-type-sizes, https://github.com/RIOT-OS/RIOT/wiki/Family%3A-MSP430#data-type-sizes, https://github.com/RIOT-OS/RIOT/wiki/Family%3A-ARM#data-type-sizes, and https://github.com/RIOT-OS/RIOT/wiki/Family:-native#data-type-sizes).

**Comment by authmillenon** [comment]
Did anybody test this by now (with the new version of `inet_ntop` or `ipv6_addr_to_str()`/`ipv4_addr_to_str()` respectively)?

**Comment by miri64** [comment]
@kYc0o @PeterKietzmann could one of you test this on msp430?

**Comment by PeterKietzmann** [comment]
@miri64 what exactly do you want me to test? I can confirm that `ipv6_addr_to_str()` definitely works on msp430 boards.

**Comment by miri64** [comment]
Yes.

**Comment by miri64** [comment]
(you can just run the unittests for that module)

**Comment by PeterKietzmann** [comment]
Ran some unittest on a z1 node.
tests-gnrc_ipv6: ok
tests-gnrc_ipv6_hdr: ok
tests-gnrc_netif: ok
tests-inet_csum: ok
tests-ipv4_addr: ok
tests-ipv6_addr: ok
tests-ipv6_hdr: `ipv6_hdr_tests.test_ipv6_hdr_inet_csum__initial_sum_overflows (tests/unittests/tests-ipv6_hdr/tests-ipv6_hdr.c 266) exp 5961 was 5962`

**Comment by miri64** [comment]
Interesting, but from what I can see, this has nothing to do with `ipv6_addr_to_str()`. Will open a separate issue for that.
