### ISSUE TITLE
LVGL SDL Disp Resizing

### ISSUE THREAD

**Issue by tvanfossen** [RIOT-OS/RIOT#18461]
When running a native application using the SDL driver, lvgl_init sets the display size used by the LVGL display driver.

When using an actual LCD, ths display driver ver/hor resolution are set after the driver has been initialized as below:
![image](https://user-images.githubusercontent.com/17345424/185127788-b5087b69-57d3-4cf1-9279-fd1921261348.png)

For a native application using SDL, I have not been able to resize the display outside of performing a similar action as above, but for SDL.

For reference, I have attempted editing lv_drv_conf.h under the lv_drivers pkg 

![image](https://user-images.githubusercontent.com/17345424/185130117-2dd1cec5-bef6-4cf9-afff-1845c58f9d5a.png)

editing SDL_HOR_RES and SDL_VER_RES does not adjust the screen size and the SDL display always runs at the default 320x240 size as defined in lv_disp_drv_init below:

![image](https://user-images.githubusercontent.com/17345424/185129625-72e9b5d3-dc7e-4a2c-96cf-6ad8c03992ce.png)

Alternatively, I also attempted editing lvgl_riot_conf to a similar end, but the result remained an lvgl display window of 320x240.

The SDL window itself will map to the SDL_HOR_RES/SDL_VER_RES size, but the LVGL display window always remains unchanged at 320x240.

In order to resolve this, the simplest solution seemed to be passing LCD_SCREEN_WIDTH/LCD_SCREEN_HEIGHT into the display driver, LCD_SCREEN_WIDTH/HEIGHT being passed in as CFLAGS in a pkg Makefile.include

![image](https://user-images.githubusercontent.com/17345424/185134358-655d73db-3d9a-4a32-b4b5-403e68559ca6.png)

Passing disp_dev_width/height into the disp_drv for SDL results in a kernel panic

**Comment by tvanfossen** [comment]
Clarification: SDL window and display window are two separate pieces - the SDL window is adjustable in its current form by editing lv_drv_conf or passing a CFLAG with SDL_HOR/VER_RES, but the display driver used by LVGL is NOT editable with the current conf files, when using SDL drivers in a RIOT native application

**Comment by maribu** [comment]
I only skimmed this issue, but I think with https://github.com/RIOT-OS/RIOT/pull/18463 merged, this issue can be closed. Please re-open, if this isn't fixed by https://github.com/RIOT-OS/RIOT/pull/18463
