### ISSUE TITLE
remote-revb documenation page has the wrong picture

### ISSUE THREAD

**Issue by jdavid** [RIOT-OS/RIOT#18612]
#### Description

In https://doc.riot-os.org/group__boards__remote-revb.html the pictures https://raw.githubusercontent.com/contiki-os/contiki/master/platform/zoul/images/remote-reva-pinout-front.png and  https://raw.githubusercontent.com/contiki-os/contiki/master/platform/zoul/images/remote-reva-pinout-back.png are of the A version.

The image of the B version can be found in https://github.com/Zolertia/Resources/wiki/RE-Mote#re-mote-revision-b-pin-out

#### Steps to reproduce the issue

See https://doc.riot-os.org/group__boards__remote-revb.html

#### Expected results

See https://github.com/Zolertia/Resources/wiki/RE-Mote#re-mote-revision-b-pin-out

**Comment by maribu** [comment]
Would you mind to open a PR to fix it? If not, I can do so.
