### ISSUE TITLE
Debugging Hamilton board with J-Link

### ISSUE THREAD

**Issue by rizkiprnomo** [RIOT-OS/RIOT#18855]
Hi, i'm beginner on Embedded C especially RIOT-OS

I have tried several programs from RIOT-OS. In this example i tried the FXOS8700 accelerometer driver. 
Then I tried to debug using j-link via rtt-studio. But the debug output always terminates and stops producing output as I show in the attached image. How do I fix this?
![photo_6285075049148953414_y](https://user-images.githubusercontent.com/92814576/200548146-61f5aa67-42b4-4eb4-afa0-e49c0834ebb0.jpg)

**Comment by maribu** [comment]
You could try

```
make BOARD=hamilton debug
```

to see where it got stuck. This should open GDB and connect to the board (via JLink or OpenOCD). You should then be able to step through the code and see what went wrong. 

Btw: A [screenshot](https://en.wikipedia.org/wiki/Screenshot) is easier to read and create than a camera picture of the display.

**Comment by maribu** [comment]
reporter is unresponsive, so I'm closing this. Feel free to reopen.
