### ISSUE TITLE
Cannot flash Arduino-hello-world example (native and esp8266-esp-12x)

### ISSUE THREAD

**Issue by mugekuskon** [RIOT-OS/RIOT#18927]
### **Description:**

I perform the make flash term command in order to run the arduino_hello-world example (https://github.com/RIOT-OS/RIOT/tree/master/examples/arduino_hello-world). Unfortunately I get an error related to the init.c file in RIOT/core/lib/init.c path as explained below. Moreover, later on I want to flash an Arduino code into my NodeMCU V3 ESP8266 ESP-12E, is it possible to flash arduino code with RIOT in a esp8266-esp-12x board? 

 ### **Steps**
Clone the RIOT repository and then run 
> make flash term 

command. The error is :

> make" -C /home/muge/Desktop/RIOT/sys/auto_init
>/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib32/crt1.o: in function `_start': (.text+0x22): undefined reference to `main'
>/usr/bin/ld: /...../..../..../RIOT/examples/helloforard-/bin/native/core_lib/init.o: in function `main_trampoline':
>/..../..../..../RIOT/core/lib/init.c:58: undefined reference to `main'
>collect2: error: ld returned 1 exit status
>make: *** [/..../..../..../RIOT/examples/helloforard-/../../Makefile.include:729: >/.../..../.../RIOT/examples/helloforard-/bin/native/arduino_hello-world.elf] Error 1

I am stuck with that problem, I hope you can help. 

### **Versions**
OS: Windows 11 - VirtualBox Ubuntu 22.04.1 LTS

**Comment by maribu** [comment]
Issue reporter unresponsive, unable to reproduce the issue.
