### ISSUE TITLE
cppcheck: add rationale to suppressed warnings

### ISSUE THREAD

**Issue by N8Fear** [RIOT-OS/RIOT#1895]
All suppressions for warnings/errors in cppcheck should be annotated with a rationale why the warning/error is suppressed instead of being fixed.

Also it would make sense to add a statement about this to the coding conventions in the wiki, if there is consent about this.

**Comment by PeterKietzmann** [comment]
@N8Fear can we close this issue?

**Comment by OlegHahm** [comment]
`git grep ccpcheck-suppress` still gives a big number of unexplained suppressions.

**Comment by authmillenon** [comment]
Sure? Some of them are rationalized in the next line. Better check with `git grep -A 1 ccpcheck-suppress`

**Comment by OlegHahm** [comment]
Actually I checked with `-C 1`. Same result.

**Comment by miri64** [comment]
Still a lot unexplained.

**Comment by miri64** [comment]
Quick

```bash
git grep -C 1 cppcheck-suppress
```

revealed some of these still to be uncommented (and not in line with #6024)

**Comment by miri64** [comment]
Also a checker script that checks this in the static tests would also be great.

**Comment by kYc0o** [comment]
How are we doing here?
