### ISSUE TITLE
CI: can_fast_ci_run.py misclassifying sub unittests

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#18987]
#### Description

From #18950 

"can_fast_ci_build.py correctly identified just tests/unittests/tests-core as changed, but the build system doesn't understand APPS=tests/unittests/tests-core."

**Comment by kaspar030** [comment]
maybe hard-replacing "tests/unittests/*" with "tests/unittests" is a sensible work-around?

**Comment by MrKevinWeiss** [comment]
Also occurred on #18734

**Comment by MrKevinWeiss** [comment]
I suppose another workaround would be unittest changes should have the full build label?

**Comment by kaspar030** [comment]
> I suppose another workaround would be unittest changes should have the full build label?

yup, but is there a benefit? why not just build all unittests?

**Comment by MrKevinWeiss** [comment]
> yup, but is there a benefit? why not just build all unittests?

If there is no fix already in, but you promptly supplied one 👍
