### ISSUE TITLE
Rust building ignores Makefile job control

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/RIOT#19045]
#### Description

@maribu has observed that Rust behaves badly w/rt job numbers; @kaspar030 pointed me toward Make's job servers.

Even though cargo should (and [is tested to](https://github.com/rust-lang/cargo/pull/4110/files)) adhere to make's job server protocol, a simple test shows it's not.

#### Simplified to reproduce the issue

This does not directly depend on RIOT, and is probably best tested in a temporary directory

```
$ cat Makefile
all:
	cargo install cargo-crev -j2
$ make -j100
```

This happily builds two crates at a time, while according to the above-mentioned tests, it should show an error message that its own `-j2` is ignored because it's running under a Make job server.

#### Next steps

Find out why it doesn't work; possibly try running the cargo test manually 1:1, and maybe just report as bug in cargo (but I'm not confident enough it's not something in our setup to do that right now).

**Comment by kaspar030** [comment]
I tracked this down to GNU make using a different method since 4.4. [jobserver-rs issue](https://github.com/alexcrichton/jobserver-rs/issues/47).

**Comment by kaspar030** [comment]
(it might be that our build system also misses the "+" prefix for cargo calls)
