### ISSUE TITLE
In file included from kernel.h:3,                  from kernel.c:1: /usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory    27 | #include <bits/libc-header-start.h>       | 

### ISSUE THREAD

**Issue by asmaalgarably** [RIOT-OS/RIOT#19093]

**Comment by asmaalgarably** [comment]
how fix it??

**Comment by maribu** [comment]
I consider this as SPAM. There is no `kernel.c` nor a `kernel.h` in RIOT's code base.

I think it is also fair to expect people who want us to invest time helping them to at least spend the time to fill in the details into the issue template we provided. After all, there is no way we can help without having the slightest hint on how to reproduce the issue.
