### ISSUE TITLE
Specify RIOT version in application Makefile

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#1910]
When building an application for RIOT, it would be interesting/needed for production environments to precisely specify a RIOT version for building. This is not possible so far...

**Comment by authmillenon** [comment]
Isn't that given by the `RIOT_VERSION` string by now? It's made up [as follows](https://git-scm.com/docs/git-describe#_examples) `<release/tag>-<new commits since release>-g<current commit hash>`.

**Comment by haukepetersen** [comment]
yes, that should do.
