### ISSUE TITLE
bug: esp32-wroom-32 some test failures

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#19138]
These esp32-wroom-32 tests fail:

- [ ] tests/log_color
- [ ] tests/log_printfnoformat
- [ ] tests/sys_arduino

**Comment by gschorcht** [comment]
I'm already investigating it. It is caused by the changes in PR #19100 which allows to reconfigure UART0. I have no idea yet why it doesn't works with other log backends.
