### ISSUE TITLE
make: APPLICATION define gets overridden

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#1923]
When building `tests/nativenet`, the `APPLICATION` is overridden depending on the target.
For the `all` target (`APPLICATION=nativenet.a`) everything is fine, but for the `sender` target this does not work.
For `sender`, `BASELIBS` contains `nativenet.a` instead of `nativenet_sender.a` although `nativenet_sender.*` is being built.
The effect is that the wrong application (in this case the `main.c` that has been compiled with `CFLAGS` missing the `-DSENDER`) gets linked.

Workaround for this application: build with `clean sender` first, `all` afterwards.

**Comment by authmillenon** [comment]
Is this still an issue?

**Comment by Kijewski** [comment]
[This](https://github.com/RIOT-OS/RIOT/blob/333c49a344b807cb27f15afd1b8da0e195153481/tests/nativenet/Makefile) is possibly the last state of `tests/nativenet/Makefile` before it was removed / renamed (I did not look). The Makefile is simply wrong. Should be:

```make
ifeq (, $(filter sender, $(MAKECMDGOALS)))
  APPLICATION = nativenet
else
  APPLICATION = nativenet_sender
endif
```

**Comment by Kijewski** [comment]
Closed as invalid

**Comment by authmillenon** [comment]
Mh, I agree. Let's close this.
