### ISSUE TITLE
core: higher priority has lower value

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#1943]
Our priorities are like on unix systems - high priorities have low values.
I find that rather irritating. 
Maybe we should change that?

**Comment by kushalsingh007** [comment]
So, is this one still open to discussion ? 
@OlegHahm: Can you elaborate the  ```(priority)_class``` idea so that I can try to implement it.

**Comment by OlegHahm** [comment]
Well, the basic idea was not to change the system's behavior but just chose another name for priorities that reflect the basic behavior. I guess the discussion is still open, but not very active. ;)

**Comment by kaspar030** [comment]
Well, as we've all got used to writing "higher priority (lower priority value)", I'll close this.
