### ISSUE TITLE
Undefined reference to `servo_init' using USEMODULE += servo_pwm

### ISSUE THREAD

**Issue by simonescaccia** [RIOT-OS/RIOT#19474]
#### Description
Undefined reference to `servo_init' using USEMODULE += servo_pwm

I'm trying to control my micro servo SG90 using RIOT-OS on a Heltec ESP32 v3 board. As suggested in the [RIOT-OS servo driver documentation page](https://doc.riot-os.org/group__drivers__servo.html), I need to specify the USEMODULE += servo_pwm in the Makefile to use the PWM implementation.

#### Steps to reproduce the issue
**Makefile**:

    # name of your application
    APPLICATION = servo
    
    # If no BOARD is found in the environment, use this default:
    BOARD ?= native
    
    # This has to be the absolute path to the RIOT base directory:
    RIOTBASE ?= $(CURDIR)/../..
    
    # Comment this out to disable code in RIOT that does safety checking
    # which is not needed in a production environment but helps in the
    # development process:
    DEVELHELP ?= 1
    
    # Change this to 0 show compiler invocation lines by default:
    QUIET ?= 1
    
    USEMODULE += servo_pwm
    USEMODULE += xtimer
    
    include $(RIOTBASE)/Makefile.include

**main.c**:

    #include <stdio.h>
    
    // servo
    #include "servo.h"
    #include "xtimer.h"
    
    // servo
    #define POS0 0
    #define POS1 UINT8_MAX
    
    #define SERVO_PWM_PARAM_RES 10000
    #define SERVO_PWM_PARAM_FREQ 50
    #define SERVO_PWM_PARAM_CHAN 0
    #define SERVO_PWM_PARAM_DEV PWM_DEV(0)
    #define SERVO_PARAM_MIN_US 1000UL
    #define SERVO_PARAM_MAX_US 2000UL
    
    static servo_t servo;
    servo_pwm_params_t my_servo_pwm_params = {
        .pwm = SERVO_PWM_PARAM_DEV,
        .freq = SERVO_PWM_PARAM_FREQ,
        .res = SERVO_PWM_PARAM_RES
    };
    
    servo_params_t my_servo_params = {
        .pwm = &my_servo_pwm_params, 
        .pwm_chan = SERVO_PWM_PARAM_CHAN,
        .min_us = SERVO_PARAM_MIN_US,
        .max_us = SERVO_PARAM_MAX_US
    };
    
    int main(void)
    {
        puts("Hello World!");
    
        if (servo_init(&servo, &my_servo_params)) {
            printf("Error to initialize servo");
            return -1;
        } else {
            printf("Servo init ok\n");
        }
    
        while(1) {
            printf("Servo set\n");
            servo_set(&servo, POS0);
            xtimer_sleep(5);
            printf("Servo set2\n");
            servo_set(&servo, POS1);
            xtimer_sleep(5);
        }
    
        return 0;
    }

**Flash command**:
    BUILD_IN_DOCKER=1 Docker="sudo docker" BOARD=esp32s3-devkit PORT=/dev/ttyUSB0 make all flash term

#### Actual results
> /opt/esp/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld:
> /data/riotbuild/riotbase/examples/servo/bin/esp32s3-devkit/application_servo/main.o:(.text.startup.main+0x24):
> undefined reference to `servo_init'
> 
> /opt/esp/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld:
> /data/riotbuild/riotbase/examples/servo/bin/esp32s3-devkit/application_servo/main.o:(.text.startup.main+0x28):
> undefined reference to `servo_set'
> 
> /opt/esp/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld:
> /data/riotbuild/riotbase/examples/servo/bin/esp32s3-devkit/application_servo/main.o:(.text.startup.main+0x41):
> undefined reference to `servo_init'
> 
> /opt/esp/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld:
> /data/riotbuild/riotbase/examples/servo/bin/esp32s3-devkit/application_servo/main.o:
> in function `main':
> 
> /data/riotbuild/riotbase/examples/servo/main.c:36: undefined reference
> to `servo_set'
> 
> /opt/esp/xtensa-esp32s3-elf/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld:
> /data/riotbuild/riotbase/examples/servo/main.c:45: undefined reference
> to `servo_set'
> 
> collect2: error: ld returned 1 exit status
> 
> make: *** [/data/riotbuild/riotbase/Makefile.include:740:
> /data/riotbuild/riotbase/examples/servo/bin/esp32s3-devkit/servo.elf]
> Error 1
> 
> make: *** [/home/simone/Documents/RIOT/makefiles/docker.inc.mk:351:
> ..in-docker-container] Error 2

#### Versions
```
Operating System Environment

----------------------------

         Operating System: "Ubuntu" "22.04.2 LTS (Jammy Jellyfish)"

                   Kernel: Linux 5.19.0-38-generic x86_64 x86_64

             System shell: /usr/bin/dash (probably dash)

             make's shell: /usr/bin/dash (probably dash)



Installed compiler toolchains

-----------------------------

               native gcc: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

        arm-none-eabi-gcc: arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)

                  avr-gcc: missing

           msp430-elf-gcc: missing

       riscv-none-elf-gcc: missing

  riscv64-unknown-elf-gcc: missing

     riscv-none-embed-gcc: missing

      riscv32-esp-elf-gcc: missing

     xtensa-esp32-elf-gcc: missing

   xtensa-esp32s2-elf-gcc: missing

   xtensa-esp32s3-elf-gcc: missing

   xtensa-esp8266-elf-gcc: missing

                    clang: missing



Installed compiler libs

-----------------------

     arm-none-eabi-newlib: "3.3.0"

        msp430-elf-newlib: missing

    riscv-none-elf-newlib: missing

riscv64-unknown-elf-newlib: missing

  riscv-none-embed-newlib: missing

   riscv32-esp-elf-newlib: missing

  xtensa-esp32-elf-newlib: missing

xtensa-esp32s2-elf-newlib: missing

xtensa-esp32s3-elf-newlib: missing

xtensa-esp8266-elf-newlib: missing

                 avr-libc: missing (missing)



Installed development tools

---------------------------

                   ccache: missing

                    cmake: missing

                 cppcheck: missing

                  doxygen: 1.9.1

                      git: git version 2.40.0

                     make: GNU Make 4.3

                  openocd: Open On-Chip Debugger 0.11.0

                   python: missing

                  python2: missing

                  python3: Python 3.10.6

                   flake8: error: /usr/bin/python3: No module named flake8

               coccinelle: missing
```

**Comment by maribu** [comment]
Sorry, my bad. Would you mind to give https://github.com/RIOT-OS/RIOT/pull/19515 a try and add a comment there whether or not this fixes the issue? Thx :)
