### ISSUE TITLE
HELP FOR ARDUINO MEGA2560

### ISSUE THREAD

**Issue by Taxx354** [RIOT-OS/RIOT#19491]
Hello, good afternoon. My name is Patricio, a high school student from an industrial school in Argentina. The school is part of an inter-school aerospace-themed project. Our proposal is to make a series of measurements in the atmosphere by launching a payload on a rocket, and as an innovation, we want to apply RIOT on an Arduino Mega2560. We are having many problems trying to install it. We have tried many methods, but none of them end up installing the system on the board. We are trying to install it from various versions of Ubuntu, and we have problems with drivers and keys to install these. It would be very helpful if you could provide us with a foolproof method for flashing the system.
PD: we are using a generic Arduino Mega2560.
Thank you very much.

**Comment by kaspar030** [comment]
> we want to apply RIOT on an Arduino Mega2560.

Great idea!

> We are having many problems trying to install it. We have tried many methods, but none of them end up installing the system on the board. We are trying to install it from various versions of Ubuntu, and we have problems with drivers and keys to install these. It would be very helpful if you could provide us with a foolproof method for flashing the system.

We now now *what* you are trying to do, but not what went wrong. What did you try, what happened? Without more details, we can't help.

May I direct you towards our [forum](https://forum.riot-os.org/), which is more suited for general help and support? This is the issue tracker, to be used for bugs.
