### ISSUE TITLE
format strings incorrect

### ISSUE THREAD

**Issue by maddin200** [RIOT-OS/RIOT#19517]
sys/shell/cmds/gnrc_icmpv6_echo.c line 347
Code:
 else if (corrupted >= 0) {
        printf(" corrupted at offset %u", corrupted); // <-- should be %d
    }

**Comment by maddin200** [comment]
also:
cpu/esp32/periph/pwm.c line 326
Code:
  for (unsigned pwm = 0; pwm < PWM_NUMOF; pwm++) {
        printf("\tPWM_DEV(%d)\tchannels=[ ", pwm); // <-- should be %u

**Comment by maribu** [comment]
Thx for the report. I opened a PR to fix the issues.
