### ISSUE TITLE
Cannot build examples/suit_update application since clang_compat.h is missing

### ISSUE THREAD

**Issue by donsez** [RIOT-OS/RIOT#19590]
#### Description
Cannot build examples/suit_update application for samr21-xpro and nucleo-f446re boards.

#### Steps to reproduce the issue

```bash
cd examples/suit_update
make
```

```
...
compiling /Users/thingsat/github/RIOT-OS/RIOT/dist/tools/riotboot_gen_hdr/bin/genhdr...
In file included from ../../../sys/riotboot/hdr.c:37:
../../../sys/include/byteorder.h:27:10: fatal error: 'clang_compat.h' file not found
#include "clang_compat.h"
     	^~~~~~~~~~~~~~~~
1 error generated.
...
```

#### Expected results

For fixing, `clang_compat.h` should be (re)added into `~/github/RIOT-OS/RIOT/cpu/native/include/`
```
wget https://raw.githubusercontent.com/jia200x/RIOT/0b5f270b15482df07dd6af03ee89460ae40e9daa/cpu/native/include/clang_compat.h
cp ~/Downloads/clang_compat.h ~/github/RIOT-OS/RIOT/cpu/native/include/
```
#### Versions

Commit is 356a47d1bb691a122323b4719400052115f38513 (Fri May 12 15:03:12 2023 +0000)

```bash
clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.07) 10.3.1 20210621 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by maribu** [comment]
Thanks for reporting the issue. Building applications for embedded targets should now work again on Mac OS. The virtual `native` remains for now Linux-only, sadly.

We sadly have pretty much zero test coverage with Mac OS, as non of the active RIOT developers uses Mac OS. It would be relatively easy to mitigate this by spinning up a VM that does compile testing with Mac OS - however, Apple's licensing prohibits such things. This is why issues like this sadly slip through.

Would you mind to confirm that this did indeed fix the issue and building on Mac OS again works?
