### ISSUE TITLE
Problem with wireshark dissector

### ISSUE THREAD

**Issue by sieben** [RIOT-OS/RIOT#1963]
I've installed the Wireshark dissector and launch the commands documented in the wiki and it still doesn't work on my Ubuntu 14.10.

$ wireshark --version
wireshark 1.12.0 (Git Rev Unknown from unknown)

$ uname -a
Linux sieben-lincs 3.16.0-25-generic #33-Ubuntu SMP Tue Nov 4 12:06:54 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by authmillenon** [comment]
Is this still an issue? In general this won't be an issue with the new network stack because the dissector is not needed anymore and I've got the feeling this is more a wireshark error than an error of the dissector.
