### ISSUE TITLE
iot-lab_M3: shell not working after booting

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1964]
The following behavior can be observed in the testbed: Sometimes the node wouldn't react to any input after booting. Kernel init and so on is printed normally. After resetting this problem disappears, but sometimes several resets are necessary.

**Comment by cgundogan** [comment]
I did not encounter such a behavior when using the iot lab testbed (m3 nodes) with the RPL_UDP example. Is this still valid for you @OlegHahm ?

**Comment by OlegHahm** [comment]
I haven't seen it for a long time.
