### ISSUE TITLE
iot-lab_M3: connectivity problems

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#1965]
Sometimes links in the testbed that should be able to communicate (nodes are in neighborhood and working with iot-lab software) cannot communicate or only unidirectional. This behavior seems to be independent from the set channel. Maybe the TX power is set to a too low value?

**Comment by PeterKietzmann** [comment]
Any progress in this issue?

**Comment by OlegHahm** [comment]
I think we'll have to wait for the new driver. Once it's ready I will run tests on IoT-LAB again.

**Comment by PeterKietzmann** [comment]
Did the "new" driver help here :-) ?

**Comment by OlegHahm** [comment]
Haven't seen this problem for a long time, so I guess something helped - maybe the new driver. ;)
