### ISSUE TITLE
Deprecated documentation?

### ISSUE THREAD

**Issue by libf-de** [RIOT-OS/RIOT#19667]
As discussed in person, the documentation refers to the deprecated xtimer under "Timers" (https://api.riot-os.org/group__sys__xtimer.html) instead of ztimer

**Comment by miri64** [comment]
While #19681 points out that `xtimer` is deprecated, `xtimer` is still the API being listed when clicking at https://doc.riot-os.org/ on Modules > System > Timers, which was what @libf-de wanted to point out.

**Comment by miri64** [comment]
Sorry, that I only realized that now.

**Comment by miri64** [comment]
Or is https://doc.riot-os.org/ just not updated yet?

**Comment by miri64** [comment]
Nvm, confirmed that https://ci.riot-os.org/results/552f671f036e4b7c98913d18fd624a66/doc-preview/ shows the expected TOC.
