### ISSUE TITLE
A stack address is assigned to a non-local variable

### ISSUE THREAD

**Issue by szsam** [RIOT-OS/RIOT#19748]
#### Description

https://github.com/RIOT-OS/RIOT/blob/fe92f676b4f5facb49ebae0e3f7d4bbc499e07bf/sys/usb/usbus/usbus.c#L395
A stack address is assigned to a non-local variable.
Storing the address of a local variable in non-local memory can cause a dangling pointer bug if the address is used after the function returns.

**Comment by kaspar030** [comment]
> A stack address is assigned to a non-local variable.
> Storing the address of a local variable in non-local memory can cause a dangling pointer bug if the address is used after the function returns.

The function doesn't return (see the `while(1)` below, and no "return" or "break").

(please reopen if you disagree)
