### ISSUE TITLE
core: More THREAD_STACKSIZE_* options

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#1976]
Currently there is only `THREAD_STACKSIZE_DEFAULT` (or `THREAD_STACKSIZE_PRINTF`) as a real option to set up your stacksize for threads. Some more options would be nice. I analyzed some stack usage and some stacks are only using half, or sometimes even only a quarter of the allocated stack size on most boards I looked at.

Suggestions for these macros:
- `THREAD_STACKSIZE_TINY`: an eighth of `THREAD_STACKSIZE_DEFAULT`
- `THREAD_STACKSIZE_SMALL`: a quarter of `THREAD_STACKSIZE_DEFAULT`
- `THREAD_STACKSIZE_MEDIUM`: half of `THREAD_STACKSIZE_DEFAULT`
- `THREAD_STACKSIZE_LARGE`: alias for `THREAD_STACKSIZE_DEFAULT`
- `THREAD_STACKSIZE_HUGE`: double of `THREAD_STACKSIZE_DEFAULT`

**Comment by miri64** [comment]
Considering my optimization experimets I did a few weeks back I still consider this issue relevant.

**Comment by miri64** [comment]
Updated macro naming.

**Comment by kaspar030** [comment]
@miri64 care to open a PR for this?

I propose having the default as MEDIUM.
