### ISSUE TITLE
cpu/nrf51822: timer callback may be fired too early

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#2006]
In the current implementation of the NRFs low-level timer it may happen, that a timer callback fires too early. This happens if a timer is set to be triggered after an overflow happens.

**Comment by PeterKietzmann** [comment]
@haukepetersen is this fixed with #1827?

**Comment by haukepetersen** [comment]
nope.

**Comment by haukepetersen** [comment]
I can't reproduce this behavior anymore, so I consider it fixed.
