### ISSUE TITLE
sys/hashes: SHA-384, SHA-512/224 and SHA-512/256 support

### ISSUE THREAD

**Issue by mguetschow** [RIOT-OS/RIOT#20127]
As a follow-up for #19969, implement the three FIPS specified truncated versions of SHA-512 in `sys/hashes`. For unified access, add frontend support for the PSA Crypto API, too.

- [x] SHA-384
- [x] SHA-512/224
- [x] SHA-512/256
- [x] PSA Crypto API support

**Comment by Teufelchen1** [comment]
Could you give a short status update? The soft feature freeze is on the 25th ;)

**Comment by mguetschow** [comment]
Sure, I have an almost finished implementation at https://github.com/mguetschow/RIOT/tree/hashes-sha512-truncated including the necessary PSA Crypto glue code. Still outstanding:
- SHA-384 seems to fail on the nrf52840dk cryptocell for some reason, although it should be supported according to the cryptocell API. This needs to be further investigated.
- The PSA compilation tests in `tests/sys/psa_crypto_*` should be adapted to the change in `examples/psa_crypto` (they use a symlinked `main.c`)

If you wanted, I could split this in two PRs, one that adds truncated SHA512 support to `sys/hashes` and a second one that adds support for it to PSA crypto. The first one would be ready to be merged, while the second one would require some more work.

**Comment by Teufelchen1** [comment]
> If you wanted, ..

I think that's up to you!

> I could split this in two PRs

The linked branch has 4 commits with around ~1800 edits. Could be enough to justify the overhead of splitting it in two PRs.

> one that adds truncated SHA512 support to sys/hashes and a second one that adds support for it to PSA crypto

Both are probably minor enough to still get them in during soft-freeze :>

**Comment by Teufelchen1** [comment]
Everything is checked off! :tada:

Can this issue be closed?

**Comment by mguetschow** [comment]
I would keep it open until #20598 is merged, which is currently hold back by #20545. The former should close the issue automatically as soon as it is merged.
