### ISSUE TITLE
Maintainer Wikipage is outdated: Proposal to delete it by the end of the year

### ISSUE THREAD

**Issue by Teufelchen1** [RIOT-OS/RIOT#20188]
Hellooo! :penguin: 

The wikipage about the [Maintainer](https://github.com/RIOT-OS/RIOT/wiki/Maintainers) is:
* outdated
* did not see any recent activity
* is content-wise duplication of [CODEOWNERS](https://github.com/RIOT-OS/RIOT/blob/master/CODEOWNERS)

I am going to delete the page in 14 days / on the 29.12.23 if nobody speaks up against it.

**Comment by maribu** [comment]
Strong +1

**Comment by miri64** [comment]
I think that page was the basis for Maintainer (and some other stuff, such as subsystem maintainers...) so :+1:
