### ISSUE TITLE
Missing spi_deinit_pins() function for stm32 devices

### ISSUE THREAD

**Issue by leocordier** [RIOT-OS/RIOT#20227]
#### Description
I want to reconfigure the GPIO associated with a spi peripheral on STM32 target, in order to use these GPIO for other use.

**Comment by maribu** [comment]
Thanks for the feature request. This should be relatively straight forward to provide.

However: Are you actually using the pins as SPI bus? If you just want to use them as regular GPIOs, it would be best to copy the board specification and adapt `periph_conf.h` in the copy to not configure the SPI bus conflicting with your use case in the first place.

Note: You might want to make use of `EXTERNAL_BOARD_DIRS` for your use case.
