### ISSUE TITLE
STM32 f4_f7 ADC sample time register configuration

### ISSUE THREAD

**Issue by sada45** [RIOT-OS/RIOT#20261]
Hi~
I am learning the ADC sampling in on STM32F722, and I think I find a bug in the file `cpu/stm32/periph/adc_f4_f7.c`. 
In function `adc_init()`, the code setting the sampling time is follows:
```C
  if (adc_config[line].chan >= 10) {
      dev(line)->SMPR1 &= ~(MAX_ADC_SMP << (3 * (adc_config[line].chan - 10)));
      dev(line)->SMPR1 |= MAX_ADC_SMP << (3 * (adc_config[line].chan - 10));
  }
  else {
      dev(line)->SMPR1 &= ~(MAX_ADC_SMP << (3 * adc_config[line].chan));
      dev(line)->SMPR2 |= MAX_ADC_SMP << (3 * adc_config[line].chan);
  }
```
To my understanding, the code first clear the `SMP<chan>` bits in the SMPR1 and SMPR2, then set the new value.
<img src="https://github.com/RIOT-OS/RIOT/assets/49777976/7735d75d-4fe6-424a-aa02-6fcec15a1b7c" width="60%">
<img src="https://github.com/RIOT-OS/RIOT/assets/49777976/ff46c9b7-7dc1-4420-8240-d04461e70d13" width="62%">

When the `chan<10`, the SMP<chan> are all in the SMPR2 register, so the correct code for `chan<10` should be:
```C
  if (adc_config[line].chan >= 10) {
          ........
  }
else {
    dev(line)->SMPR2 &= ~(MAX_ADC_SMP << (3 * adc_config[line].chan));
    dev(line)->SMPR2 |= MAX_ADC_SMP << (3 * adc_config[line].chan);
}
```

**Comment by maribu** [comment]
Thx for spotting the issue :)

Would you mind to open a pull request with the fix? Feel free to ping me in the pull request
