### ISSUE TITLE
make sure custom APPLICATION works as expected

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#2039]
In order to support building and flashing different versions of an application, it should be possible to override the `APPLICATION` variable which is usually set in the application's Makefile.

Check if this works as expected and document the use case in the wiki.

Compare:
https://github.com/RIOT-OS/RIOT/pull/1724
https://github.com/RIOT-OS/RIOT/pull/2012

**Comment by PeterKietzmann** [comment]
@LudwigOrtmann can you live with that "compromise"?

**Comment by LudwigKnuepfer** [comment]
I am still alive => yes.
