### ISSUE TITLE
make: feature definitions not working as expected in makefiles

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#2058]
Compare https://github.com/RIOT-OS/RIOT/pull/1922#issuecomment-61293824

When using a construct like this:

``` make
ifneq (,$(filter periph_rtc,$(FEATURES_PROVIDED)))
       SRC += sc_periph_rtc.c
endif
```

it is never true.

**Comment by haukepetersen** [comment]
this issue should be fixed by #3420

**Comment by authmillenon** [comment]
That PR was closed. Is it still an issue?

**Comment by OlegHahm** [comment]
@LudwigKnuepfer, ping!

**Comment by LudwigKnuepfer** [comment]
@OlegHahm pong

**Comment by miri64** [comment]
Not an answer to my question ;-)

**Comment by LudwigKnuepfer** [comment]
I don't know, maybe you could just test it? A code snippet is in the issue description...

**Comment by miri64** [comment]
Nope, still an issue. The problem is that `FEATURES_PROVIDED` is not imported to `sys/shell/commands/Makefile` for some reason (just checked with `$(warning $(FEATURES_PROVIDED))`). Will investigate when I find some time.

**Comment by miri64** [comment]
Obviously hadn't had the time to work on this... Anyone care to look into this?
