### ISSUE TITLE
test files required to compile

### ISSUE THREAD

**Issue by bmewen** [RIOT-OS/RIOT#20680]
#### Description

Related to my PR #20668, I noticed that the board was not always flashed correctly and didn't seem to respond most of the time. For your information all the tests were done using the default example. Usually on this example you should see RIOT outputs and be able to type your commands however the boards seemed locked in a state where it was not printing anything and where it was not responding to the commands typed (so basically it was not initialized or flashed correctly).

As the code in my PR, for the arduino nano 33 BLE sense, was based on the already existing code of the arduino nano 33 BLE, I tried to look for extra common configuration somewhere else than in the board directory and found out that there was only some tests that were defining the board as one that provides a net interface. I saw, using the `dependency-debug` target, that the dependencies were not the same and that the original arduino nano 33 BLE had more dependencies than the board I added when it should have been the opposite. 

I added my new board in the following files (that seemed to be the only locations where there was an actual usage of the arduino-nano-33-ble) : 

- [x] tests/Makefile.boards.netif
- [x] tests/drivers/mrf24j40/Makefile
- [x] tests/net/ieee802154_hal/Makefile
- [x] tests/net/ieee802154_submac/Makefile
- [x] tests/pkg/openwsn/Makefile
- [x] tests/pkg/openwsn_sock_udp/Makefile

Here you can find a zip containing the output of the command with and without the board included in the mentioned files :  
[debug_dependencies-output-files.zip](https://github.com/RIOT-OS/RIOT/files/15389374/debug_dependencies-output-files.zip)

For your information, this issue is not specifically related to my new board as some tests were made using the old one and the native board which also depends on the tests directory.

I don't think that it is normal that the compilation step needs some elements in the tests directory as they should not be related.

#### Versions
Operating System Environment
----------------------------
         Operating System: "Ubuntu" "22.04.4 LTS (Jammy Jellyfish)"
                   Kernel: Linux 6.5.0-35-generic x86_64 x86_64
             System shell: /usr/bin/dash (probably dash)
             make's shell: /usr/bin/dash (probably dash)

Installed compiler toolchains
-----------------------------
               native gcc: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)
                  avr-gcc: missing
           msp430-elf-gcc: missing
       riscv-none-elf-gcc: missing
  riscv64-unknown-elf-gcc: missing
      riscv32-esp-elf-gcc: missing
     xtensa-esp32-elf-gcc: missing
   xtensa-esp32s2-elf-gcc: missing
   xtensa-esp32s3-elf-gcc: missing
   xtensa-esp8266-elf-gcc: missing
                    clang: Ubuntu clang version 14.0.0-1ubuntu1.1

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.3.0"
        msp430-elf-newlib: missing
    riscv-none-elf-newlib: missing
riscv64-unknown-elf-newlib: missing
   riscv32-esp-elf-newlib: missing
  xtensa-esp32-elf-newlib: missing
xtensa-esp32s2-elf-newlib: missing
xtensa-esp32s3-elf-newlib: missing
xtensa-esp8266-elf-newlib: missing
                 avr-libc: missing (missing)

Installed development tools
---------------------------
                   ccache: missing
                    cmake: cmake version 3.22.1
                 cppcheck: missing
                  doxygen: 1.9.1
                      git: git version 2.34.1
                     make: GNU Make 4.3
                  openocd: Open On-Chip Debugger 0.11.0
                   python: Python 3.12.2
                  python2: missing
                  python3: Python 3.12.2
                   flake8: error: /usr/bin/miniconda3/bin/python3: No module named flake8
               coccinelle: missing

**Comment by maribu** [comment]
Fixed. Thanks for reporting the issue :heart:
