### ISSUE TITLE
debug. simplify debugging

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#2075]
As discussed in #2068 undefining the `ENABLE_DEBUG` in `debug.h` is (apparently) no longer required. This also eliminates the kludge of defining `DEBUG_ENABLED` in various files.

**Comment by kushalsingh007** [comment]
@OlegHahm : I had a look a ```core/include/debug.h```. However I don't find that the debug is undefined anywhere . Would you tell where exactly are you referring to.

**Comment by OlegHahm** [comment]
I think this was fixed by https://github.com/RIOT-OS/RIOT/pull/2130
