### ISSUE TITLE
gnrc_sixlowpan_nd: Implement 6LoWPAN multihop DAD

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#208]
Until now a duplicate address detection according to [RFC 6775](http://tools.ietf.org/html/rfc6775) is missing. This includes:
- Header definition for [DA messages](http://tools.ietf.org/html/rfc6775#section-4.4)
- Implementation of [Multihop Duplicate Address Detection](http://tools.ietf.org/html/rfc6775#section-8.2)

**Comment by miri64** [comment]
Updated the title a little bit.

**Comment by danpetry** [comment]
@miri64 still an issue?

**Comment by miri64** [comment]
Yep, just very low on the priority list sadly... :(

**Comment by miri64** [comment]
This is part of https://github.com/RIOT-OS/RIOT/issues/3052 I just noticed. So let's close this as https://github.com/RIOT-OS/RIOT/issues/3052 is more holistic
