### ISSUE TITLE
Is the separation between PKGs and sys modules useful?

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#2081]
I guess we should merge the folders `sys` and `pkg` into one new folder which I would call `modules`. The separation is quite arbitrary (having external dependencies or none) and not needed for our make system to work. Then we only need the variable `USEMODULE` and no more `USEPKG`. The users only want the modules to work, but should not need to know how.

**Comment by PeterKietzmann** [comment]
@OlegHahm did you think about that a bit :-) ?

**Comment by kaspar030** [comment]
+1!

**Comment by OlegHahm** [comment]
I think the separation makes sense, because building behaves completely different and potential bugs cannot (or should not) be fixed in RIOT.

**Comment by Kijewski** [comment]
Closed, because I changed my mind. The separation is useful.
