### ISSUE TITLE
core: limit message queue size

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#2096]
Currently there can be up to 32k items in a message queue on 16bit platforms, and up to 2 billion items on 32 bit platforms. I don't think this is reasonable.

I would limit the message queue to 128 items. This reduces the size of `cib_t` (which is used in `tcb_t`) from 12 bytes to 4 bytes (including padding) on 32bit platforms.

If you think that 128 message queue items is too restrictive (I doubt it), then we can restrict the message queue to 32k items, which would shrink `cib_t` to 8 bytes.

But I don't think that the current limit of `MAXINT / 2` is reasonable. At least it hurts portability.

**Comment by jhollister** [comment]
It doesn't look like the change to `uint16_t` was ever implemented. Should I submit a PR for this?

**Comment by Darredevil** [comment]
I saw no one tackled this so I submitted a PR #2547

**Comment by LudwigOrtmann** [comment]
PR was merged prematurely

**Comment by mlohse** [comment]
Imho, the performance aspect is more important here than saving some extra bytes of memory. I haven't testet it, but according to some posts on the internet accessing smaller datatypes (char, uint8_t, short,...) is slower than accessing unsigned/int on some 32-Bit ARM platforms - at least when unaligned.
The current implementation looks good to me, I would rather leave it the way it is.

As this is marked as a "Newbie Task", please keep in mind integer conversion rules when refactoring:
https://wiki.sei.cmu.edu/confluence/display/c/INT02-C.+Understand+integer+conversion+rules

**Comment by miri64** [comment]
@kaspar030 do you think this is still an issue / should be fixed?

**Comment by miri64** [comment]
@kaspar030 ping?

**Comment by miri64** [comment]
No real engagement for over three years and there are doubts regarding the performance of such a memory optimization. Let's close it. Reopen if you disagree.
