### ISSUE TITLE
ccn: use dynamic chunk sizes

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#2098]
Chunks sizes are currently fixed to `CCNL_RIOT_CHUNK_SIZE` as defined in https://github.com/RIOT-OS/RIOT/blob/master/sys/net/include/ccn_lite/ccnl-riot.h#L63. However, the content might be smaller than a full chunk.

On top, `CCNL_HEADER_SIZE` is fixed to 40, which requires at least an explanation. On IEEE 802.15.4 platforms it only works if `CCNL_RIOT_CHUNK_SIZE` is set to `(PAYLOAD_SIZE - CCNL_HEADER_SIZE - 1)`. Therefore, I assume that the header size might be off by one.

**Comment by miri64** [comment]
@OlegHahm is this still an issue?

**Comment by OlegHahm** [comment]
AFAIK, this should be fixed.
