### ISSUE TITLE
Is there a risk associated with the bitarithm_lsb function

### ISSUE THREAD

**Issue by muaxiaohei** [RIOT-OS/RIOT#21049]
#### Description

In my testing, v might be 0 which will cause a mcu stall.

```C
    unsigned r = 0;
    printf("v: %d\n", v);
    while ((v & 0x01) == 0) {
        v >>= 1;
        r++;
    }

    return r;
```

**Comment by muaxiaohei** [comment]
I will add details later.

**Comment by kaspar030** [comment]
Yes, as [documented](https://github.com/RIOT-OS/RIOT/blob/a841fc39b99de4fa4c0af0f8b1dc09edf7909d9f/core/lib/include/bitarithm.h#L109-L116).
