### ISSUE TITLE
msp: make: "make BOARD=z1 term" returns Garbage

### ISSUE THREAD

**Issue by xav13er** [RIOT-OS/RIOT#2109]
Dear development Team of Riot-OS,

I am using Riot (or trying to), and I need a feedback from yours. I’ve successfully compiled the hello-world for the platform Zolertia Z1 (Toolchain msp430), and also flash the firmware, and use the terminal! However, what I get I shouldn’t get (attached). 

I’ve tried both in Linux and Mac OS X, and the problem persists on both. This is not a problem of the Toolchain, because I’ve successfully used it under Contiki-OS and TinyOS.
I would like to have your help regarding this and other problems, before moving onto other Embedded OSes.

Mit freundlichen Grüßen,
-- 
Francisco Xavier
![1 - riot - hello-world z1_linux](https://cloud.githubusercontent.com/assets/9551933/5228856/a8752aa8-7707-11e4-8e59-899e7f4e12d1.png)

**Comment by l3nko** [comment]
I've three z1 and with two of them i've the same problem, on OS X and also on ubuntu. 
From [here](https://e2e.ti.com/support/microcontrollers/msp430/f/166/t/287659), the uart registers UCA0BR0 and UCA0BR1 depend on CPU_SPEED / BAUD_RATE,  so for default values of z1: 8MHz / 115200 = 69,4 .
I try to manual set the uart registers:
```
UCA0BR0 = 0x45; 
UCA0BR1 = 0x00;
```

but with these settings the two z1 still do not work, so i try:
```
UCA0BR0 = 0x46; 
UCA0BR1 = 0x00;
```
And with these they work!

So i notice that the registers UCA0BR0 and UCA0BR1 used into *z1/uart.c*:
1. are unsigned bytes, but in riot they are used as *int*
2. the value obtained by the calculation CPU_SPEED / BAUD_RATE has to be 'ceiled'

I solved with this code:
```
#define UCA0_BAUD_RATE    (int)(MSP430_INITIAL_CPU_SPEED / BAUDRATE)

if( BAUDRATE * UCA0_BAUD_RATE < MSP430_INITIAL_CPU_SPEED ) {
    UCA0BR0 = (uint8_t)((UCA0_BAUD_RATE+1) & 0x00FF );
}
else {
    UCA0BR0 = (uint8_t)(UCA0_BAUD_RATE & 0x00FF );
}
UCA0BR1 = (uint8_t)((UCA0_BAUD_RATE & 0xFF00) >> 8);
```

**Comment by OlegHahm** [comment]
Do you care to make a PR? (Otherwise I could make one on my own with your proposed changes.)

**Comment by l3nko** [comment]
No, i didn't. Ok make it in your PR.
Il giorno ven 7 ago 2015 alle 07:53 Oleg Hahm <notifications@github.com> ha
scritto:

**Comment by Joelfp** [comment]
I have tested the hello world program on several zolertia z1 boards and in some boards I recieve nothing from the UART port. I have read all the posts and tried the following code.
`//dev->BBR0 = (uint8_t)(br & 0x00FF);`
`UCA0BR0 = 0x46;`
`//dev->BBR1 = (uint8_t)((br & 0xFF00) >> 8);`
`UCA0BR1 = 0x00;`
and receive the following output:
![pyterm-exit1](https://cloud.githubusercontent.com/assets/16922021/13161631/fb327ffa-d66c-11e5-88fe-07980dd76087.jpg)
But when I force the value to
`//dev->BBR0 = (uint8_t)(br & 0x00FF);`
`UCA0BR0 = 0x47;`
`//dev->BBR1 = (uint8_t)((br & 0xFF00) >> 8);`
`UCA0BR1 = 0x00;`
I recieve the correct output from the pyterm
![pyterm-exit2](https://cloud.githubusercontent.com/assets/16922021/13161671/4946e992-d66d-11e5-9157-86f5b859f3f0.jpg)
What can be the problem in the UART configuration. I don´t know were to look to fix this problem.

**Comment by xav13er** [comment]
Hello good evening,

To answer that, you would have to help me understand what is that variable UCA0BR0. You might have to understand that by looking at the port made to zolertia.

Best,
Xav13rua

No dia 18/02/2016, às 23:40, Joelfp <notifications@github.com> escreveu:

**Comment by Joelfp** [comment]
Hello:
The UCA0BR0 is the register where you set the prescaler of the Buad rate
generator. The formula is the following:
UCA0BR0=CPU_CLOCK/Baudrate
In the zolertia board the clock frequency is 8MHz. For 115200 bps the
UCA0BR0 is value is 69.4. Which in hexadecimal is 0x45.
I don't understand why the UART works correctly by forcing the value to 0x47

Regards
Joel

**Comment by Joelfp** [comment]
I have been checking the clock configuration for the MSP430 in the file "RIOT/boards/z1/board.c". In lines 191 and 192 the written code is:
`BCSCTL1 = 0x0d;`
`DC0CTL = 0x9a;`
I don't understand how this works but I have contrasted these values with the ones used in Contiki OS and found different values:
`BCSCTL1 = 0x8d;`
`DC0CTL = 0x88;`
I have tried with this values and the problems goes away. Now all my boards print correctly the hello world message.

**Comment by xav13er** [comment]
Yes, that is part of my fear... I argue that the compilation process of RIOT is not reliable. Other OSes like contiki, you compile 2000 times, and you get correct code execution in Zolertia... But the same cannot be said for RIOT. This is a constructive critic.

Xav13rua





No dia 19/02/2016, às 21:40, Joelfp <notifications@github.com> escreveu:

**Comment by OlegHahm** [comment]
To be honest, I lost a little bit track of what is being discussed here. Can someone give a short update on this?

1. @l3nko wrote: "No, i didn't. Ok make it in your PR." Does this PR exist, got merged and fixed anything?
2. Is it correct that one can flash the **same** binary of a RIOT application on different Z1 nodes and it will fail to produce correct output for **some** of them?
3. If the problem is caused by the build system, did you check if compiling **always** with `make -B clean all` fixes the issue?
4. Is this problem somehow related to the OS used for development, flashing or serial access?
5. What is required to reproduce the problem?

**Comment by Joelfp** [comment]
I will explain what happened with my zolertia z1 boards. I´ve bought 10 zolertia boards and started to use RIOT-OS with the hello-world program. I have succesfully compile the program on 4 boards in the remaining boards I either receíved garbage or nothing in pyterm. I asked Zolertia about this problem and they redirected me to this issue.
After reading all the posts I tried forcing the register values for the UART baudrate generator with:

`UCA0BR0 = 0x47`
`UCA0BR1 = 0x00`

And with this I get the correct output from the UART port. Although the formula states that UCA0BR0 = CPU_CLOCK/BAUDRATE where CPU_CLOCK is 8Mhz and the baudrate is 115200. With these values I obtain 69.4 or 0x45
Then I looked into the board configuration file to see how the cpu_clock was set, and found in the "RIOT/boards/z1/board.c" that the clock configuration was different from the contiki code. In lines 191 and 192 I changed the register values from:

`BCSCTL1 = 0x0d`
`DC0CTL = 0c9a`

to

`BCSCTL1 = 0x8d`
`DC0CTL = 0x88`

This changes seems to fix my issue across all the boards I have.

@OlegHahm, regarding your questions,

1. As far as I checked in the commits, I didn't see it being merged.
3. Yep, same results.
4. Don't really know. But for reference, I am using a VM (with Ubuntu 14.0) running on Windows.
5. Without access to the boards it is hard to reproduce. An even with access to a pair of them, you may get
the right output. Thing is it fails for some boards.

**Comment by OlegHahm** [comment]
@Joelfp, thanks for explanation.

>  In lines 191 and 192 I changed the register values from:
>
> BCSCTL1 = 0x0d
> DC0CTL = 0c9a
>
> to
> 
> BCSCTL1 = 0x8d
> DC0CTL = 0x88
>
> This changes seems to fix my issue across all the boards I have.

Seems to be worth opening a PR then, or am I mistaken?

**Comment by kYc0o** [comment]
@haukepetersen I think this is not an issue anymore... ?

**Comment by haukepetersen** [comment]
Still is as I see it, and even if only that we need to update the clock init code for MSP430 based boards...

**Comment by kYc0o** [comment]
Oh... since you were working on this platform I thought you didn't have this issue... well, let's for the next release ;-)

**Comment by kYc0o** [comment]
in #5024 they say it is not an issue anymore... anyone with a Z1 to test?

**Comment by OlegHahm** [comment]
Well, I can't reproduce, but IIRC it was showing only on some boards.

**Comment by kYc0o** [comment]
I'm using now the z1 and I don't get any garbage... should we close this?

**Comment by kYc0o** [comment]
As far as I can see, the garbage is a known problem related to a specific version of the compiler (4.6.3) which displays this garbage, some info [here](http://wsn.blogs.ua.sapo.pt/270.html?thread=270).

So I'll close this issue.
