### ISSUE TITLE
Relocation Truncated to fit (rom/ram overflowed, on z1 msp430) #msp #bug

### ISSUE THREAD

**Issue by xav13er** [RIOT-OS/RIOT#2112]
Besides the examples default, hello-world and ipc_pingpong, I cannot compile any other example. I guess that riot_and_cpp is not yet possible due to the zolertia z1 not having c++ support yet. 

However, the other examples can't compile because it seems, for the first time, the result firmware ends up being bigger than the available resources! this is a first.

![2 - riot why you cant compile all examples](https://cloud.githubusercontent.com/assets/9551933/5229672/3c665812-7713-11e4-931b-b70ffca61fc9.png)
![2 - riot why you cant compile all examples2](https://cloud.githubusercontent.com/assets/9551933/5229676/464b97ac-7713-11e4-8e3f-db70aa83d74e.png)

**Comment by PeterKietzmann** [comment]
Current CI also builds for msp430 platforms (e.g. z1). I also used that board recently and ran several applications. Will close this issue cause it seems to be fixed.
