### ISSUE TITLE
periph/spi: Use context pointer instead of spi_t enum

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#2116]
The current `periph/spi.h` API is a bit limited with regards to hardware dependent settings. I propose replacing the `spi_t dev` parameter passed to all functions by a pointer to a struct with context information. One of the parameters in the struct would still be the device number, but it opens the possibilities of adding more configuration parameters as well. The context struct would have a hardware independent beginning and hardware dependent variables appended. It would be possible to handle the Chip Select signals within the SPI driver itself instead of needing to use GPIO API functions in the slave device drivers.

Some usage examples: the Kinetis CPU has hardware chip select capability, which needs some extra bits to be set in the data register when pushing a new byte to the SPI bus, these bits can not be passed using the current API. Another feature that would be possible and which I would use is the ability to choose between multiple timing and clock polarity/phase settings depending on which device I am addressing.
The Kinetis SPI hardware also has a FIFO queue for transfer operations, which means that it is possible to queue several bytes to different devices and put the core to sleep while they are being transferred on the wire, the CS signals are asserted/deasserted by the hardware for each individual transfer queued.

I guess that Cortex-M devices from other manufacturers have similar functionality in their SPI hardware as well.

I would like your opinions on this alternate API design.

**Comment by gebart** [comment]
Reopened upon request https://github.com/jfischer-phytec-iot/RIOT/pull/8

**Comment by gebart** [comment]
I have been thinking some more about this.
I don't think there is any good argument for using hardware CS over gpio CS when not using DMA for the actual transfers, and then only if you are doing some really heavy transfers, say mass storage devices (SDHC etc).
The benefits of using software CS are:
- simpler API
- unlimited number of CS lines on all boards (limited only by the number of gpio)
- Only device drivers need to know the polarity of the CS line, the bus driver only needs to know the polarity of the clock line (common to all bus slaves), this means slightly less configuration per board.

I believe currently the most important improvement we can do to our (`kinetis_common`) bus driver is to start using SPI interrupts during transfer and add a thread yield to the transfer function in order to let the CPU go to sleep during TX instead of busy waiting, burning CPU cycles and battery power.

**Comment by jfischer-phytec-iot** [comment]
@gebart ok, I agree.
Our RF driver uses its own code for spi, we would move it to a
"platform specific driver", as haukepetersen has proposed. What do you think?

**Comment by gebart** [comment]
@jfischer-phytec-iot is the RF device on its own bus? Otherwise you should ensure that you lock the bus even from your platform specific driver. (once #2314 gets merged and we have the equivalent in kinetis_common)

**Comment by jfischer-phytec-iot** [comment]
@gebart Yes, one SPI is dedicated to the radio interface inside SiP.

**Comment by gebart** [comment]
@jfischer-phytec-iot I am interested in seeing what difference it makes for the actual performance of the RF device to use HW CS, (when considering other parts, such as packet processing etc.) and thus, if it is worth it really to make the driver platform specific (if the HW CS is the only Kinetis specific part).

The GPIO CS translates to something like 4 machine instructions, which is pretty small compared to the I/O time for sending a 128 byte packet over the SPI bus at 10 MHz bit rate.

**Comment by jfischer-phytec-iot** [comment]
@gebart At the kw2x, I can not measure the signals because the are internal.
Even if there is no big difference:
- why should I care about CS if the hardware makes it for me?
- we just need one CS signal and I can not imagine a real example with modern hardware where someone needs more than 2-4 CS.
- I have problems to find modern sensors with SPI, and we need SPI only for RF
- we need HW CS for DMA

**Comment by haukepetersen** [comment]
> I don't think there is any good argument for using hardware CS over gpio CS when not using DMA for the actual transfers, and then only if you are doing some really heavy transfers, say mass storage devices (SDHC etc).

That were exactly what I thought when designing the interface... As far as I read the datasheets for Atmel and STM devices so far, it shouldn't even be a problem to use DMA with external CS code (though I have not yet tried that).
I completely agree that the obvious steps to making our SPI implementations better is to start with using an interrupt driven mode and further looking into DMA. My idea was to make it dependent on the number of bytes to transfer which of both is used -> I think the overhead for configuring DMA makes only sense if more than say 3-10 bytes are transferred. Anyhow, both improvements are completely agnostic to the interface - so it's basically free to choose for each implementation how optimized it is.

**Comment by jfischer-phytec-iot** [comment]
I'm sorry :smile:, but I can not be satisfied with a CS that is operated from outside the SPI driver. SW or HW CS, it is not a clean interface separation.

**Comment by gebart** [comment]
Responding to a comment to a commit (https://github.com/gebart/RIOT/commit/ece822552db82c099b81f65feeab2fb43082fab0#commitcomment-9458583)

>Note: We want to move our spi code for the radio(#2329) to kinetis_common and also continue to use hardware-CS (I want to enhance it with dma soon). It would be nice, if we could share the code of RIOT-spi and there would be a possibility for use the hardware CS.

There is a problem when implementing hardware CS: All current SPI device drivers are using gpio_clear/gpio_set for handling the CS pin, so you would either have to define some "ghost" GPIOs which do nothing, or rewrite all drivers to move CS handling to the SPI bus layer. This last option however was commented on in this PR (in https://github.com/RIOT-OS/RIOT/issues/2116#issuecomment-65667941) as going against the RIOT driver API design philosophy.

**Comment by jfischer-phytec-iot** [comment]
>so you would either have to define some "ghost" GPIOs which do nothing

Why? No one is forced to use hardware-CS.

I think the SPI driver should be redesigned. Currently, I see two things that are problematic:
- No clear interface separation, cs_set and cs_clear should be controlled by the driver
- It is only possible to transfer octets or the multiple of that.

 When kinetis_common is mainline, I would like to improve spi interface.

**Comment by haukepetersen** [comment]
@jfischer-phytec-iot 
> No clear interface separation, cs_set and cs_clear should be controlled by the driver
I think clearer than we have it at the moment as rarely possible: GPIO driver does GPIO stuff, SPI driver does SPI stuff. The CS is a GPIO function after all...

Also the SPI interface will become very bloated once you integrage the CS control into it (parameters for which CS pins to use and for timings...). This would lead to a more resource hungry and more bloated interface, which goes against the overall design principle for the peripheral drivers to keep them as simple and slim as possible!

> It is only possible to transfer octets or the multiple of that.
What what would be the use cases for something other than this?

**Comment by jfischer-phytec-iot** [comment]
>It is only possible to transfer octets or the multiple of that.
>>What what would be the use cases for something other than this?

There are devices (for example, displays) where a byte is not equal to one octet. We have one and can not make it easy to use with RIOT.

Below are the promised measurements.
cpu-clock = 48MHz, flash-clock = 24MHz
CH1: spi-data
CH2: spi-clock
CH3: spi-kinetis-cs
CH4: spi-gpio-cs, (the gpio-cs setup time (of course) is always the same)

**spi clock = 1 MHz**
Here it's not so much, ca 1.5bit

![1mhz](https://cloud.githubusercontent.com/assets/9864546/6806836/7967b18c-d24b-11e4-9d6d-a31b1c6c8aef.png)

**spi clock = 5 MHz**
ca 1.5 octets

![5mhz](https://cloud.githubusercontent.com/assets/9864546/6806838/7968b7da-d24b-11e4-9709-6a38e0540e5a.png)

**spi clock = 5 MHz**
ca 3 octets

![10mhz](https://cloud.githubusercontent.com/assets/9864546/6806837/79687536-d24b-11e4-951b-464012ffcdf6.png)

**Comment by PeterKietzmann** [comment]
Wow that takes a long time.. 5MHz on stm32f4discovery looks better:
![bildschirmfoto vom 2015-03-25 08-40-46](https://cloud.githubusercontent.com/assets/7765855/6819935/d801bab6-d2c9-11e4-8522-8422cf6b81d4.png)

**Comment by haukepetersen** [comment]
@jfischer-phytec-iot thx for the measurements. I gues your third picture was measured with 10MHz, right? 

 So what I see, is that the setup time for the CS pin (when handled externally) is pretty much fixed at ~1.77µs and a little less when finished. AT 48MHz that are ~85 CPU cycles, that seems to be about right so besides some small gains due to optimization, this number we can not cut down too much, I guess. @PeterKietzmann, the same (although slightly different numbers) I see for the STM32F4discovery, right?

So taken 10MHz SPI speed of your setup, the additional delay introduced by external CS accounts to 150% when reading or writing a single byte device register (2 byte transfer). When transferring 100 byte (a typical radio packet), the overhead is about 1%. 

I agree that these numbers motivate to think about a concept of enabling the use of internal chip select capabilities. However: right now we paying these overheads for a very straight forward, simple to use and extremely portable SPI API, and I am still thinking that this is well spend... So for me the only option would be to come up with a revised concept, that is still portable to all platforms (especially those without HW CS) while not blowing up the API to something un-usable for most!

**Comment by miri64** [comment]
Can somebody tell me if this issue was resolved? I seem to remember that there was some PR regarding CS in SPI a few days back.

**Comment by haukepetersen** [comment]
IMHO partly resolved in #4780 (at least the allowance of hw-cs), but not reached an end of discussion...

**Comment by PeterKietzmann** [comment]
Outdated due to the SPI rework.
