### ISSUE TITLE
core/thread: Forbid ISRs to create threads?

### ISSUE THREAD

**Issue by LudwigOrtmann** [RIOT-OS/RIOT#2136]
Rationale:
@kaspar030 your input here

Compare:
https://github.com/RIOT-OS/RIOT/pull/2108#issuecomment-65058888

**Comment by PeterKietzmann** [comment]
@LudwigOrtmann any objections?

**Comment by LudwigOrtmann** [comment]
No objections to documentation ;)
Furthermore: I think we can't forbid it per se because some initial thread always needs to be created when the system starts and *I guess* this happens in ISR context / semantic on most systems.

**Comment by kushalsingh007** [comment]
Started working on this one :)

**Comment by kushalsingh007** [comment]
So the warning that it a bad practice has to be added to ``` /doc/doxygen/src/mainpage.txt
``` ? or some other file.

**Comment by LudwigOrtmann** [comment]
I'd say either put it with `thread_create` or a general intro for `thread.h`.

**Comment by kushalsingh007** [comment]
@LudwigOrtmann : Created a PR https://github.com/RIOT-OS/RIOT/pull/2589 have a look :)
