### ISSUE TITLE
documentation of thread_arch_start_threading is odd

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#2140]
This is in `core/include/arch/thread_arch.h`:

```
#define cpu_switch_context_exit         thread_arch_start_threading
...
/**
 * @brief Start threading by loading a threads initial information from the stack
 */
void thread_arch_start_threading(void) NORETURN;
```

As of now, `cpu_switch_context_exit` is called from within a terminating thread/context. This information might be relevant for the implementation, and it is definitely important for understanding the purpose.
From my understanding it should at least be mentioned that `sched_run` needs to be called. Not sure about possible interrupts status changes. I think we also should document if the function could be called from an ISR context.

**Comment by miri64** [comment]
Bump
