### ISSUE TITLE
unittests: tests-core doesn't compile for all platforms

### ISSUE THREAD

**Issue by phiros** [RIOT-OS/RIOT#2143]
Currently, the unit test for core doesn't compile for msp430 based platforms.
In my opinion at least the unit test for core must compile for _every_ platform we support.

The primary problem seems to be the use of gcc compiler builtins (`__builtin_clz` and `__builtin_ctz`) in the bitarithm test:

```
$ msp430-gcc --version
msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make tests-core BOARD=telosb
touch /home/philipp/RIOT/tests/unittests/main.c
Building application unittests for telosb w/ MCU msp430f1611.
"make" -C /home/philipp/RIOT/boards/telosb
"make" -C /home/philipp/RIOT/core
"make" -C /home/philipp/RIOT/cpu/msp430x16x
"make" -C /home/philipp/RIOT/cpu/msp430-common
"make" -C /home/philipp/RIOT/drivers
"make" -C /home/philipp/RIOT/sys
"make" -C /home/philipp/RIOT/sys/oneway-malloc
"make" -C /home/philipp/RIOT/tests/unittests/embunit/embUnit
"make" -C /home/philipp/RIOT/tests/unittests/tests-core
/home/philipp/RIOT/tests/unittests/bin/telosb/tests-core.a(tests-core-bitarithm.o): In function `test_bitarithm_lsb_all':
/home/philipp/RIOT/tests/unittests/tests-core/tests-core-bitarithm.c:188: undefined reference to `__ctzhi2'
/home/philipp/RIOT/tests/unittests/bin/telosb/tests-core.a(tests-core-bitarithm.o): In function `test_bitarithm_msb_16bit':
/home/philipp/RIOT/tests/unittests/tests-core/tests-core-bitarithm.c:164: undefined reference to `__clzhi2'
collect2: ld returned 1 exit status
make: *** [all] Error 1
```

Does anybody have an idea how to fix this?

**Comment by PeterKietzmann** [comment]
@phiros is this fixed now?

**Comment by authmillenon** [comment]
Nope.

**Comment by OlegHahm** [comment]
I don't think we gonna fix this until Monday.

**Comment by gebart** [comment]
We should fix this for next release. I'm getting the same build error for BOARD=z1 1½ years later.

**Comment by miri64** [comment]
Agreed! Does anyone has a fix? #2094 was closed.

**Comment by gebart** [comment]
The problem was with the old MSPGCC toolchain (4.6.x in the Debian repos). The official TI supported msp430-elf GCC toolchain (4.9.x and newer) does include the `__ctzhi2`, `__clzhi2` functions.

I believe #4766 would fix this problem, with the added requirement that the toolchain used is from the newer series, and not the ancient MSPGCC.

MSP430 is officially supported by upstream vanilla GCC since at least version 4.9-something.
IMO once we have working newlib support and some clear instructions for the users on how to install the toolchain, we should finally bump the GCC version requirement to at least 4.8 or so, that would let us move on with -std=c11 and remove a bunch of silly hacks for old tool chains.

**Comment by miri64** [comment]
:+1:

**Comment by OlegHahm** [comment]
> The problem was with the old MSPGCC toolchain (4.6.x in the Debian repos). The official TI supported msp430-elf GCC toolchain (4.9.x and newer) does include the __ctzhi2, __clzhi2 functions.

Okay, I will check, but I seem to remember that the TI toolchain had other issues.

> I believe #4766 would fix this problem, with the added requirement that the toolchain used is from the newer series, and not the ancient MSPGCC.

Hm, unfortunately, this toolchain also requires newlib which increases the code size quite a bit.

> MSP430 is officially supported by upstream vanilla GCC since at least version 4.9-something.
IMO once we have working newlib support and some clear instructions for the users on how to install the toolchain, we should finally bump the GCC version requirement to at least 4.8 or so, that would let us move on with -std=c11 and remove a bunch of silly hacks for old tool chains.

One the one hand, I completely agree that it would be very desirable to get rid of this special treatment for MSP430 platforms. On the other hand, the msp430-libc in the old tool chain is very memory efficient in comparison to the rather bloated newlib. We will need to investigate further how we can reduce the memory requirements for this.

**Comment by gebart** [comment]
@OlegHahm It would be interesting to see a comparison between a nano newlib and the old msp libc.

Most nano patches from ARM have been upstreamed in newlib and should benefit most platforms when building with the nano configuration flags.

**Comment by OlegHahm** [comment]
I will try to investigate on this.

**Comment by kYc0o** [comment]
Is this still an issue?

**Comment by miri64** [comment]
```sh
BOARD=z1 make -C tests/unittests/ tests-core
```

;-)

**Comment by miri64** [comment]
Doesn't seem to be the case anymore, so close.

**Comment by miri64** [comment]
(also tested for telosb as it was used in the issue report)

**Comment by kYc0o** [comment]
Excellent! Thanks! 😃
