### ISSUE TITLE
netdev2_tap: make driver capable to handle multiple TAP interfaces

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#2195]
With `netdev` coming up we are able to speak to multiple devices of the same type in one RIOT instance. This would also allow for having multiple TAP interfaces for one RIOT instance in nativenet. One could easily add the TAP's file descriptor to the `netdev::more`-field of, only the signal handling must be adapted for multiple interfaces.

**Comment by authmillenon** [comment]
Nativenet does not exist anymore. Will rename.

**Comment by miri64** [comment]
Fixed by #5614.

**Comment by PeterKietzmann** [comment]
@miri64 didn't  #6311 solve this issue or are we waiting for #6121???

**Comment by miri64** [comment]
Nope. This was indeed fixed by #6311. #6121 has nothing to do with `netdev_tap`.
