### ISSUE TITLE
core: msg_reply_int() is undocumented and unused

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#2219]
`msg_reply_int()` is undocumented and unused. Do we need it? An ISR cannot receive messages, so how could it reply to messages?

**Comment by PeterKietzmann** [comment]
What's the solution for that? Should we discard it? @kaspar030 what was in your mind when adding `msg_reply_int()`?

**Comment by kaspar030** [comment]
The idea was that a thread could request e.g., a network packet from some network layer thread, which could then defer replying to some ISR. We're not really using the context switch savings from msg_send_receive/msg_reply the way we could. Not sure removing this function is the way to go.

**Comment by PeterKietzmann** [comment]
I also prefer to let it in but therefore to add a documentation

**Comment by authmillenon** [comment]
TBH, I'm still not sure how to use this function.

**Comment by OlegHahm** [comment]
What remains unclear?

**Comment by kaspar030** [comment]
Example:

1. thread A send_receives a "give me data" message to e.g., a UART thread. UART thread doesn't have data available.
2. Data arrives
3. ISR gets triggered, sees thread A is waiting for the data, replies directly to thread A.

**Comment by authmillenon** [comment]
> What remains unclear?

The doc states the ISR can't receive messages, but this function is for the ISR to answer messages (at least I'm interpreting the doc as such). That's contradicting.

> Example:
> 
> 1. thread A send_receives a "give me data" message to e.g., a UART thread. UART thread doesn't have data available.
> 2. Data arrives
> 3. ISR gets triggered, sees thread A is waiting for the data, replies directly to thread A.

At what point and in what context do I call `msg_reply_int()` then?

**Comment by kaspar030** [comment]
@authmillenon Imagine you asked that question directly to me. Oleg might answer. It's possible to answer a message that you didn't receive yourself. That's what msg_reply_int is for.


> At what point and in what context do I call msg_reply_int() then?

The ISR in 3. would call ```msg_reply_int()``` to reply to the message the UART thread received in 1.
This is just an example, but without ```msg_send_int()``` the ISR would send it's data to UART thread first, which would maybe only relay it to thread A. Replying directly from the ISR saves a context switch.
```msg_send_receive()```/```msg_reply()``` is all about minimizing context switches.

**Comment by authmillenon** [comment]
Okay so this is a call this is for the ISR exclusively to answer as a proxy for other answering threads. I think the doc should reflect this behavior better.

**Comment by kaspar030** [comment]
@authmillenon How would you rephrase this?
"An ISR can obviously not receive messages, however a thread might delegate replying to a message to an ISR."
