### ISSUE TITLE
RFC: split TAP and nativenet

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#2242]
Since there were already some discussions about Ethernet support it propably would make sense to make TAP a native-specific low-level driver (and maybe add TUN-support, too) and add nativenet as an optional module in form of a netdev-driver on top of it.

**Comment by LudwigOrtmann** [comment]
I am in favor of creating an Ethernet device for native (which basically means making all tap features available to the network layer).

**Comment by LudwigOrtmann** [comment]
Is this fixed as of https://github.com/RIOT-OS/RIOT/pull/2776 ?

**Comment by OlegHahm** [comment]
@authmillenon, fixed?

**Comment by authmillenon** [comment]
Japp.
