### ISSUE TITLE
core/lpm_arch: Clarification of the lpm arch interface

### ISSUE THREAD

**Issue by fnack** [RIOT-OS/RIOT#2247]
I provided an implementation of the lpm_arch interface for the STM32F4 cpu (see #2246).

During that process, I wondered what the difference behind RIOT's LPM_POWERDOWN and LPM_OFF mode is. From my perspective, I couldn't find a difference and documentation doesn't help either. Maybe someone could explain the intention behind separating these two mode options?

If there is no difference, I'd vote for removing the LPM_OFF mode.

**Comment by fnack** [comment]
Ping @haukepetersen. Here's the discussed new issue report from yesterday.

**Comment by haukepetersen** [comment]
@OlegHahm do you remember the notion behind the different power levels?

**Comment by OlegHahm** [comment]
No, these defines already existed when I started to work with FireKernel. @kaspar030?

**Comment by saurabh984** [comment]
I've used these mappings for SAM D21 LPM if it helps!

```
LPM_ON = Run Mode
LPM_IDLE = SYSTEM_SLEEPMODE_IDLE_0 (Wake up source: Synchronous, (APB, AHB), asynchronous)
LPM_SLEEP = SYSTEM_SLEEPMODE_IDLE_1 (Wake up source: Synchronous (APB), asynchronous)
LPM_POWERDOWN = SYSTEM_SLEEPMODE_IDLE_2 (Wake up source: Asynchronous)
LPM_OFF = SYSTEM_SLEEPMODE_STANDBY (Wake up source: Asynchronous)
```

Datasheet Ref: http://www.atmel.com/Images/Atmel-42223-SAM-R21_Datasheet.pdf (Page: 115)

**Comment by PeterKietzmann** [comment]
So as there are some devices whith multiple idle modes it seems to make sense that there are for example five different power modes. Correct? One could maybe rename them so it becomes clear that they differ in "strengh" but I don't mind staying with the existing solution.

**Comment by gebart** [comment]
The Kinetis devices have even more power modes:

 - RUN
 - WAIT
 - STOP
 - VLPR
 - VLPW
 - VLPS
 - LLS
 - VLLS0
 - VLLS1
 - VLLS2
 - VLLS3

Having five different LPM enums is probably enough for most use-cases though.

**Comment by haukepetersen** [comment]
I had a quick discussion with @OlegHahm about this. The most important transition seems to be the one called by the idle thread. In my opinion we could even go with less modes (as the kernel uses only IDLE and RUN), but put some platform specific code in place, so that each time the system goes into IDLE it will figure out the best mode available (depending on running peripherals and the hardware platform). Does this make sense to you?

**Comment by PeterKietzmann** [comment]
Obsolete  (see #6160)
