### ISSUE TITLE
samr21-xpro: rtc setalarm/getalarm inconsistency

### ISSUE THREAD

**Issue by LudwigOrtmann** [RIOT-OS/RIOT#2259]
Apparently there's a negative one second delta when setting alarms on the samr21-xpro:

```
> rtc setalarm 2015-01-07 12:00:00
> rtc getalarm
2015-01-07 12:00:63
```
```
> rtc setalarm 2015-01-07 12:00:01
> rtc getalarm
2015-01-07 12:00:00
```
The alarm fires at the time displayed by `rtc getalarm`, not at the time specified with `rtc setalarm`.

**Comment by LudwigOrtmann** [comment]
@baclanet: could you look into this?

**Comment by bapclenet** [comment]
Ok I will have a look at it tomorrow
