### ISSUE TITLE
Random number generator for platforms without hardware RNG

### ISSUE THREAD

**Issue by d00616** [RIOT-OS/RIOT#2264]
This looks practicable: https://code.google.com/p/tinkerit/wiki/TrueRandom

This needs an open analog ping with capability switch it to ground and reference voltage.

More to read: http://en.wikipedia.org/wiki/Randomness_extractor

**Comment by phiros** [comment]
Hi, this method might not yield useful random numbers acording to:
http://www.endolith.com/wordpress/2013/06/19/truerandom-is-not-truly-random/

However, we should maybe take a look at the clock drift method the author proposes at the end of the blog post.

**Comment by LudwigOrtmann** [comment]
I would propose to implement this as part of high-level random API.

**Comment by miri64** [comment]
Kind of fixed in #5153 ;-).
