### ISSUE TITLE
rpl: node-to-node communication broken for non-storing mode

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#2266]
When building rpl with non-storing mode it is not possible to send a message from node to node. The msg gets the way up to root and is then dropped, because of #2253 .
So, #2253 fixes this.

**Comment by PeterKietzmann** [comment]
@cgundogan the problems caused by #2253 are fixed in #2253 :-) ? Is this still an issue?

**Comment by cgundogan** [comment]
@PeterKietzmann this issue is unfortunately still unfixed

**Comment by OlegHahm** [comment]
For the record: Probably I won't be working on this anytime soon.

**Comment by cgundogan** [comment]
I will give it a try in the near future

**Comment by cgundogan** [comment]
obsolete, because the former `rpl` implementation vanished
