### ISSUE TITLE
rpl: root-to-node communication in non-storing mode

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#2270]
It seems that the communication from root to node does not happen.
While packets can travel from node to node through the root by adding a source routing header, all packets originating from the root itself bypass RPL (do not enter any RPL relevant code). Thus, no source routing header is added to the packets and they get lost.

EDIT:
Keep in mind that #2266 is necessary for any kind of investigation here.

**Comment by authmillenon** [comment]
I don't know anything about RPL non-storing mode, that's why I reassign.

**Comment by cgundogan** [comment]
I see. The problem lies somewhere within the network layer, more precisely - in ip.c .
Therefore, I thought you might be the right person to choose. I will assign this to me then.

My gut tells me it should be an easy fix. When sending out a packet via `ipv6_sendto` or `ipv6_send_packet`, the packet needs to be intercepted by the RPL implementaton first in order to attach the source routing header.

**Comment by fabianbrandt** [comment]
Shame on me. The logic for that was there, but somehow not in the final version :(. The fix suggestion is right however.

**Comment by PeterKietzmann** [comment]
Is this already fixed somewhere? Or can we reference a PR?

**Comment by emmanuelsearch** [comment]
@cgundogan what's the status on this? Can we close this issue?

**Comment by cgundogan** [comment]
obsolete, because of the introduction of a new network stack
