### ISSUE TITLE
USB Support

### ISSUE THREAD

**Issue by felinira** [RIOT-OS/RIOT#2284]
It could be desirable to support USB and USB OTG which is present on many devices currently running RIOT.

This could have multiple use cases depending on the device support:
- USB serial console
- Sending network and/or other data from/to a computer running control or monitoring software.
- Updating application code (it was discussed on the ML a few days ago to have relocatable? applications that can be loaded in a running RIOT system, circumventing license issues and allowing for easier application updates; is there an issue for this?)

I would like to use this issue to start designing a platform independent API for USB support if other people are interested in having such a feature.

**Comment by gebart** [comment]
I am interested in such a feature as well. Both for serial console as well as a network device.

**Comment by Troels51** [comment]
I've been looking into this as well, knowing nothing about USB i looked for APIs in other systems, here are  the ones i found.
* [ARM CMSIS DRIVER](http://www.keil.com/pack/doc/CMSIS/Driver/html/group__usb__interface__gr.html)
* [TI MSP USB DEV](http://www.ti.com/tool/msp430usbdevpack)
They could be used as inspiration

**Comment by jfischer-phytec-iot** [comment]
@gebart I am on it for kinetis_common, for the beginning bulk transfers only.

**Comment by gebart** [comment]
@jfischer-phytec-iot nice! Looking forward to this. I can assist with testing when you have something you'd like to share. Unfortunately, I do not have time to work on developing this feature for the time being.

**Comment by haukepetersen** [comment]
+1 for USB support! I always wanted to connect old USB-mice or gamepads to micro-controllers to play around with... :-)

**Comment by OlegHahm** [comment]
And keyboard of course.

**Comment by OlegHahm** [comment]
What about VGA? ;)

**Comment by jfischer-phytec-iot** [comment]
but of course via "Cup Heater + 4 Port USB Hub"

**Comment by drasko** [comment]
Any news on this?

**Comment by OlegHahm** [comment]
Please see https://github.com/RIOT-OS/RIOT/issues/3546

**Comment by PeterKietzmann** [comment]
With #10916 and following PRs merged, I think we can close this issue now.
