### ISSUE TITLE
sys/net/include: move to /sys/include/net?

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#2291]
Just thinking out loud: does it make sense to move the network stack headers to `sys/include/net` and reference them in the code like `#include "net/ipv6.h"`?

This has in my opinion two advantages:

1. network layer includes are clearly distinguishable
2. and we would save about ~35 lines stating `*INCLUDE += sys/net/include`

**Comment by gebart** [comment]
:+1: it makes sense to reduce the number of individual `-I{DIR}` include directories. 
Another bonus when writing `#include "net/ipv6.h"` is that it shows clearly which component the included header is supposed to belong to (ipv6.h is quite obvious but there may be others with less obvious names), makes it easier to find the right file while developing without some heavy IDE like Eclipse.

**Comment by OlegHahm** [comment]
Sound very reasonable to me, too.

**Comment by LudwigOrtmann** [comment]
I'm not opposed.

**Comment by cgundogan** [comment]
:+1:

**Comment by authmillenon** [comment]
I'm not opposed, also.

**Comment by authmillenon** [comment]
Though I'm not sure if the `net/` prefix is necessary… I'm thinking of modules that might have submodules: e.g. `net/sixlowpan/hc.h` vs. `sixlowpan/hc.h`

**Comment by haukepetersen** [comment]
I think it does not hurt. This way the `net/` prefix labels consistently everything belonging to the network stack and its only 4 chars...

**Comment by PeterKietzmann** [comment]
That already happened for the new network stuff, right? Is this issue "closable"?

**Comment by authmillenon** [comment]
Yes on new stuff, but No on "closable". There is (and will be until complete deployment of `ng_`) still stuff in `sys/net/include`.

**Comment by haukepetersen** [comment]
Actually I say we can close the issue, as the decision for `sys/include/net/...` was made...

**Comment by PeterKietzmann** [comment]
Ok that is what was in my mind. @authmillenon should do this (at will)

**Comment by authmillenon** [comment]
Fine…
