### ISSUE TITLE
POSIX compliance

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#23]
Implement POSIX layer, particular of interest:

- [ ] Process Creation and Control 
- [x] Thread Creation, Control, and Cleanup as well as Thread Synchronization
- [ ] Signals and Signal Handling
- [ ] Timers
- [ ] File and Directory Operations
- [ ] Pipes
- [x] C Library (Standard C)
- [ ] I/O Port Interface and Control
- [ ] Process Triggers
- [ ] Priority Scheduling
- [ ] Real-Time Signals
- [ ] Clocks and Timers
- [x] Semaphores
- [ ] Message Passing
- [ ] Shared Memory
- [ ] Asynch and Synch I/O

**Comment by OlegHahm** [comment]
I don't think we're really aiming for full POSIX compliance.

**Comment by authmillenon** [comment]
:(

**Comment by authmillenon** [comment]
(not even optionally).

**Comment by LudwigKnuepfer** [comment]
It wasn't even defined which POSIX standard we would have gone for.

**Comment by authmillenon** [comment]
The most current! ;-P
