### ISSUE TITLE
transceiver: set default channel to something sensible

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#2319]
This issue is most likely gonna be solved by the re-designed network stack anyway, but for now some modules (the rpl_udp example, ccn-lite...) set rather arbitrary channels which are not available on some platforms (e.g. does IEEE 802.15.4 not specify a channel 6 or 10).

**Comment by LudwigOrtmann** [comment]
Maybe we want to have the transceiver export some `DEFAULT_CHANNEL`?

**Comment by OlegHahm** [comment]
Transceiver module has been removed.
