### ISSUE TITLE
Segmentation fault when executing hello-world application

### ISSUE THREAD

**Issue by shanthanpalle** [RIOT-OS/RIOT#2334]
Hi ,
   I have cloned RIOT source form git hub and followed basic steps to build and execute.Am able to build and generates .elf but when i execute that am getting
Segmentation fault (core dumped) error
OS : Ubuntu 12.04
gcc version 4.6.4
please get back soon..

**Comment by LudwigOrtmann** [comment]
I can reproduce that his happens on ubuntu-12.04.

**Comment by LudwigOrtmann** [comment]
Please use one of the supported versions of GCC.
https://github.com/RIOT-OS/RIOT/wiki/Family:-native#toolchains
Compare http://lists.riot-os.org/pipermail/users/2015-January/000223.html

**Comment by LudwigOrtmann** [comment]
GCC version 4.6 is not supported.
