### ISSUE TITLE
Vmware ubuntu 14.04 support for riot os support

### ISSUE THREAD

**Issue by syedk01** [RIOT-OS/RIOT#2351]
Is there support for riot is on above os

**Comment by gebart** [comment]
RIOT OS `native` platform works fine on Ubuntu 14.04.

Some links:
https://github.com/RIOT-OS/RIOT/wiki/Family:-native#ubuntu
https://github.com/RIOT-OS/RIOT/wiki/Family:-native#toolchains

If you are targeting an embedded device you need to have a toolchain for said device, see 
https://github.com/RIOT-OS/RIOT/wiki/RIOT-Platforms for a list of platforms and links to more information about them.

This is not really an issue with RIOT which is what this board is used for. You will probably get more answers to any further questions if you post on the mailing lists, see http://lists.riot-os.org/mailman/listinfo/users

I will close this issue now.
