### ISSUE TITLE
samr21 : Problem to read RSSI and LQI values 

### ISSUE THREAD

**Issue by maxencechotard** [RIOT-OS/RIOT#2414]
When I am trying to read RSSI and LQI values after receiving a packet on samr21 with RPL_UDP example, I always get RSSI =0 and LQI with a wide range of values even if the material configuration between my two nodes doesn't change. To read RSSI and LQI vlaues I go to transceiver.c and watch values in :    static void receive_packet(uint16_t type,uint8_t pos)  line 678. Am I in the wrong place to get the right value ?

**Comment by LudwigOrtmann** [comment]
This is already tracked in https://github.com/RIOT-OS/RIOT/pull/2277
