### ISSUE TITLE
ng_sixlowpan: Invert local/universal bit in EUI-64 when forming IPv6 Interface Identifiers

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#2498]
Reminder to @authmillenon to port #2497 to ng_sixlowpan

**Comment by gebart** [comment]
Another related reminder, verify that #2584 does the right thing in ng_sixlowpan

**Comment by authmillenon** [comment]
That's not #2584. This is dependent on the individual `netdev`s ;-)

**Comment by authmillenon** [comment]
I think I did all that. Can you verify @gebart?

**Comment by gebart** [comment]
@authmillenon you mean in #2806 ?
It looks okay, the local bit is inversed when converting l2addr to iid. I did not run it though. Do the packets checksum properly in wireshark?

**Comment by authmillenon** [comment]
Last time I checked, yes.

**Comment by gebart** [comment]
This is working properly in gnrc.
