### ISSUE TITLE
Travis: don't stop analyzing

### ISSUE THREAD

**Issue by LudwigOrtmann** [RIOT-OS/RIOT#2505]
We added `|| exit` suffixes to the static analysis to save Travis resources. Due to the adoption of the build-matrix feature, this is not effective anymore.
Running all the static tests no matter what will actually save resources because it takes (almost?) longer to create the VM than to run the tests. Also, it will make review quicker because all errors can be seen at once.

**Comment by authmillenon** [comment]
See #2506
