### ISSUE TITLE
RPL: use DIO prefix option for stateless address autoconfiguration (SLAAC)

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#2510]
DIO messages can contain prefix information, similar to what is carried by ND RA messages. Currently the prefix option is silently ignored. The prefix should be used for SLAAC, which would improve interoperability with other systems using RPL, e.g. Contiki, which do not send ND RA messages.

**Comment by cgundogan** [comment]
this can be closed, because #2522 got merged
