### ISSUE TITLE
routing: complete documentation in etx_beaconing.h

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#2526]
`sys/net/include/etx_beaconing.h` needs some care.

**Comment by kausthub** [comment]
hi , i am interested in completing this issue , but i am new to this , so what do you meant by needs some extra care ? 
I am sorry if that question was trivial , thanks in advance

**Comment by authmillenon** [comment]
Welcome to RIOT,
as you can see https://github.com/RIOT-OS/RIOT/blob/master/sys/net/include/etx_beaconing.h does not have any doxygen documentation currently and most of the comments are not that helpful either. Most comments must only be reformated to doxygen syntax, however.

**Comment by BigDaddyD** [comment]
Is there a doxygen reference here on the wiki? I can't seem to find one

**Comment by gebart** [comment]
See also #2561

**Comment by authmillenon** [comment]
@BigDaddyD not in the Wiki, but it's generated regularly from the source code at http://riot-os.org/api/

**Comment by OlegHahm** [comment]
If I'm not mistaken this file has gone.
