### ISSUE TITLE
RPL: DAO RPL Target has wrong length and/or data

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#2569]
The RPL Target option on DAO messages has the wrong prefix length. On my rpl_udp tests the prefix length is set to 16 bits, but the complete IP address is sent in the option. I don't know enough about the algorithm for building the DODAG to know what is the correct behaviour, but for reference I have noticed that Contiki sets the length to 128 bits and sends the node's entire IPv6 address to get a route added to that specific node, instead of trying to add a route for the whole network. Additionally, the current behaviour violates the RFC6552 description of the RPL Target option which says that everything after the first prefix_length bits must be set to zero.

Is Contiki doing the right thing here or is there an angle that I have not considered?

RFC6550 6.7.7:

    Target Prefix: Variable-length field identifying an IPv6 destination
         address, prefix, or multicast group.  The Prefix Length field
         contains the number of valid leading bits in the prefix.  The
         bits in the prefix after the prefix length (if any) are
         reserved and MUST be set to zero on transmission and MUST be
         ignored on receipt.

**Comment by cgundogan** [comment]
fixed in #2570
