### ISSUE TITLE
Unittests sometimes hang at ``test_nomac_event_value``

### ISSUE THREAD

**Issue by noshky** [RIOT-OS/RIOT#2577]
When I run all unit-tests several times, quite often the execution hangs at testcase `` test_nomac_event_value`` and never ends. If i set the outputter to OUTPUT=TEXT, i can see that the last executed testcase is
``256) OK test_nomac_set_get_long_address``
The next testcase, when it runs successfully, would be
``257) test_nomac_event_value``.

**Comment by OlegHahm** [comment]
Running on native, I suppose?

**Comment by authmillenon** [comment]
That's okay #2426 will be merged probably today so these tests will be removed :D

**Comment by noshky** [comment]
@OlegHahm Yes running native, forgot to mention.

**Comment by authmillenon** [comment]
#2426 was merged. These tests do not exist anymore.
