### ISSUE TITLE
Homepage License Link is Wrong

### ISSUE THREAD

**Issue by cyounkins** [RIOT-OS/RIOT#2587]
The homepage has a link to http://www.gnu.org/licenses/old-licenses/lgpl-2.0.en.html

But the actual license used it at https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html

Adding to the confusion is in one the L is Library and the other Lesser.

**Comment by LudwigOrtmann** [comment]
Which homepage (URL please) are you referring to?

**Comment by authmillenon** [comment]
It's on riot-os.org. Search for License ;-)

**Comment by LudwigOrtmann** [comment]
fixed.
