### ISSUE TITLE
boards/Makefile.features: one feature per row

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#2611]
Most boards list their feature in one or two rows, e.g.:
```
FEATURES_PROVIDED += periph_uart periph_gpio periph_spi periph_i2c periph_pwm periph_random \
                     periph_adc periph_dac periph_cpuid
```
This leads to conflicts when there are two PR's open simultaneously and both add something to this line. I would actually prefer to have one line per feature, e.g.:
```
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
...
```
This way there won't be any merge conflicts anymore.

Here is the TODO list:
 - [x] airfy-beacon, #2630
 - [x] arduino-due, #2630
 - [ ] ~~arduino-mega2560~~ no need, just one feature
 - [x] avsextrem, #2630
 - [x] cc2538dk, #2630
 - [x] chronos, #2630
 - [x] f4vi1
 - [x] fox, #2630
 - [x] iot-lab_M3, #2630
 - [x] mbed_lpc1768
 - [ ] ~~msb-430~~ no need, no features
 - [ ] ~~msb-430-common~~ no need, no features
 - [x] msb-430h, #2630
 - [x] msba2, #2630
 - [ ] ~~msba2-common~~ no need, no features
 - [x] msbiot, #2630
 - [x] mulle, #2630
 - [x] native, #2630
 - [x] nucleo-f091, #2630
 - [x] nucleo-f334
 - [x] nucleo-l1
 - [x] openmote, #2630
 - [x] pca10000, #2630
 - [x] pca10005, #2630
 - [x] pttu
 - [ ] ~~qemu-i386~~ no need, no features
 - [ ] ~~redbee-econotag~~ no need, just one feature
 - [x] samr21-xpro, #2630
 - [x] spark-core
 - [x] stm32f0discovery, #2630
 - [x] stm32f3discovery, #2630
 - [x] stm32f4discovery, #2630
 - [ ] ~~telosb~~ no need, just one feature
 - [x] udoo, #2630
 - [ ] ~~wsn430-common~~ no need, no features
 - [x] wsn430-v1_3b, #2630
 - [x] wsn430-v1_4, #2630
 - [ ] ~~x86-multiboot-common~~ no need, no features
 - [x] yunjia-nrf51822, #2630
 - [ ] ~~z1~~ no need, just one feature

**Comment by BigDaddyD** [comment]
It seems like an easy fix that with both minimize conflcits and improve readability

**Comment by kushalsingh007** [comment]
So what boards do you suggest then @haukepetersen ?

**Comment by LudwigOrtmann** [comment]
all of them

**Comment by haukepetersen** [comment]
list added, see above

**Comment by Darredevil** [comment]
I wanted to tackle this but I noticed PR #2641 already does that but isn't merged,even Travis CI says everything is ok. Any reason for that?

**Comment by LudwigOrtmann** [comment]
Probably it was lost in the flood of PRs or the assigned maintainer didn't have time to look into it.
