### ISSUE TITLE
Implementation of LwM2M. 

### ISSUE THREAD

**Issue by Otmane123** [RIOT-OS/RIOT#2643]
hello everyone, 
just i ask if someone work in the Project N2: Implementation of LwM2M.
i need further description about the subject 
if someone can help me 

Otmane

**Comment by authmillenon** [comment]
Please use the [developer mailing list](http://lists.riot-os.org/mailman/listinfo/devel) for such requests. It may take a while to receive an answer (because there are currently a lot of request as you may see in the archive), but there will come an answer. Please be patient.
