### ISSUE TITLE
Add support for serial number passing to CMSIS boards, document it

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#2724]
For further information compare https://github.com/RIOT-OS/RIOT/pull/2318

> Hmm, when this gets merged the information on how to use it (i.e. how to discover and set the serial number) should probably be added to the wiki, right? But since this mechanism should work the same way for all CMSIS-DAP devices (?), should it really be added to the Sam R21 page or is there a better place to put it?

(Source: https://github.com/RIOT-OS/RIOT/pull/2318#issuecomment-86467444)

**Comment by OlegHahm** [comment]
@x3ro, care to update the documentation accordingly?

**Comment by x3ro** [comment]
Will do!

**Comment by OlegHahm** [comment]
thx

**Comment by OlegHahm** [comment]
@x3ro, ping!

**Comment by LudwigKnuepfer** [comment]
@x3ro ping!

**Comment by x3ro** [comment]
My bad, have been postponing this for ever. It's first item on my todos list for tuesday!

**Comment by x3ro** [comment]
Here's my draft, will add to the wiki when #4166 is merged.

# Connecting multiple boards

If you have multiple boards connected to the same computer and want to flash, this is what you can do:

First, run `make list-ttys`. This will show you a list of currently connected boards, their serial numbers and the names of their TTYs:

    Atmel Corp. EDBG CMSIS-DAP serial: 'ATML2127031800002124', tty(s): ttyACM0
    Atmel Corp. EDBG CMSIS-DAP serial: 'ATML2127031800002145', tty(s): ttyACM1

knowing your serial number, you can flash, open a terminal or debug a specific board like this:

    BOARD=samr21-xpro SERIAL="<serial>" make flash
    BOARD=samr21-xpro SERIAL="<serial>" make term
    BOARD=samr21-xpro SERIAL="<serial>" make debug

**Comment by OlegHahm** [comment]
#4166 is  merged. @LudwigKnuepfer, @haukepetersen, are you fine with @x3ro's proposal.

@x3ro: maybe you could use the exemplary serial number from the exemplary `make list-ttys` output for the second example, too?

**Comment by LudwigKnuepfer** [comment]
I'm fine, thanks.

**Comment by PeterKietzmann** [comment]
@haukepetersen agree?  I assume we can close this issue then..

**Comment by OlegHahm** [comment]
@PeterKietzmann, well, we should wait until @x3ro comes up with an according PR.

**Comment by x3ro** [comment]
@OlegHahm Ich haette es jetzt einfach ins Wiki zu dem Board eingetragen. Woran hattest du gedacht? :)

**Comment by OlegHahm** [comment]
Whatever feels most natural for you - you were the one asking for documentation first. ;)

**Comment by x3ro** [comment]
Done: https://github.com/RIOT-OS/RIOT/wiki/Board:-SAMR21-xpro#connecting-multiple-boards
