### ISSUE TITLE
nrf51822 - vtimer does not work correctly with TIMER_1

### ISSUE THREAD

**Issue by deepfryed** [RIOT-OS/RIOT#2832]
I'm trying to get RIOT running on the Adafruit BLE friend along with S110 softdevice (which needs TIMER_0). Using TIMER_1 (16 bit), it looks like the timer overflows are not handled correctly in vtimer.  vtimer_gettimeofday and vtimer_usleep do not work as intended as a result.

**Comment by haukepetersen** [comment]
as far as I know this is a known issue: the vtimer in the current state can only handle 32-bit hwtimers (it is even broken when you use `TIMER_0` on the nrf...). But a new timer is in progress - just a matter of days.

**Comment by gebart** [comment]
vtimer was replaced by xtimer, please open a new issue if there are problems with xtimer.
