### ISSUE TITLE
socket_base_sendto function doesn't return the same length as the input message

### ISSUE THREAD

**Issue by joriwind** [RIOT-OS/RIOT#2834]
Hi,

When sending an message, using the socket_base_sendto function, the function returns a greater value of bytes send than the size of the message. 

You can see the difference when using the rpl_udp example if you modify the printf on line /RIOT/examples/rpl_udp/udp.c:150 to:
printf("Successful deliverd %i bytes (message was %i bytes) over UDP to %s to 6LoWPAN\n", bytes_sent,strlen(argv[2]), ipv6_addr_to_str(addr_str, IPV6_MAX_ADDR_STR_LEN, &ipaddr));

OlegH told me on the IRC chat of Riot-os that the function apparently returns the size of the entire packet instead of the transport layer payload.

Kind regards,
Jori

**Comment by cgundogan** [comment]
there is no `socket_base_sendto` function anymore in RIOT's network stack.
The current equivalent could be `conn_udp_sendto`. From looking at the code, the function returns the same length that was passed as an argument (payload size). Or some errno codes in case of an error. So I will close this now. @joriwind feel free to reopen if you object.
