### ISSUE TITLE
Doxygen: Order of modules is arbitrary

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#2838]
The order of the modules on  http://doc.riot-os.org/modules.html is pretty arbitrary (check for instance http://doc.riot-os.org/group__net.html). Looking at doxygen configuration and documentation. There are basically two ways to deal with that:
1. Set `SORT_GROUP_NAMES` to `YES` and let doxygen order stuff alphabetically.
2. Create all groups at central point (directly after `doc/doxygen/mainpage`) and define the order there at a central point.

While I'm not sure that alphabetic ordering is the most meaningful, I think it would be still better than more or less no ordering.

**Comment by phiros** [comment]
I think using the alphabetical ordering is a good idea for now. The other option would essentially add yet another file that has to be edited when adding / changing a module.

**Comment by OlegHahm** [comment]
...ad could lead to discussion about the "best" ordering. I tend to agree.

**Comment by x3ro** [comment]
> While I'm not sure that alphabetic ordering is the most meaningful, I think it would be still better than more or less no ordering. @OlegHahm

> I think using the alphabetical ordering is a good idea for now. @phiros 

Completely agree.

**Comment by OlegHahm** [comment]
And here we go: #2859.

**Comment by phiros** [comment]
Fixed in -> #2859
