### ISSUE TITLE
ng_pktbuf: documentation is confusing

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#2853]
I just tried to understand what happens if I call `ng_pktbuf_add()` when passing the payload of a L2 frame as a first argument. However, the doxygen (particular from [line 72](https://github.com/RIOT-OS/RIOT/blob/master/sys/include/net/ng_pktbuf.h#L72) to 91) are pretty confusing to me. I do not even understand what `result` is referring to.

**Comment by authmillenon** [comment]
The result is the return value. What else is confusing to you? I tried to be as verbose (but not *too* verbose) as possible in the documentation.

**Comment by OlegHahm** [comment]
Aha, that already helps a lot, now the former rather cryptic `ng_pktsnip_t::next of result = pkt->next` makes sense. Maybe that's obvious for some people (apparently not for me), but I think we should make this explicit: The return value of this function is a `ng_pktsnip_t` struct referred to as `result`.

I also do not quite understand the graphic.

All in all, I understand you correctly: when you pass an existing pkgsnip_t to this function (plus some extra conditions are fulfilled) the packet is assumed as receiving and an encapsulated header can be marked. Right?

And to what pktsnip does `@param[in] type      Protocol type of the ng_pktsnip_t.` refer to?

**Comment by authmillenon** [comment]
> All in all, I understand you correctly: when you pass an existing pkgsnip_t to this function (plus some extra conditions are fulfilled) the packet is assumed as receiving and an encapsulated header can be marked. Right?

the extra conditions and not the fact that a given pktsnip_t is passed are what indicate that it is receiving (otherwise it is assumed as sending), but if you meant that, you are correct.

> And to what pktsnip does @param[in] type Protocol type of the ng_pktsnip_t. refer to?

The result.

**Comment by authmillenon** [comment]
> I also do not quite understand the graphic.

Maybe I can help to make things clearer.

**Comment by authmillenon** [comment]
See #2854
