### ISSUE TITLE
How to implement 6lowpan with MSB-A2 temperature sensor nodes?

### ISSUE THREAD

**Issue by saleemrazam** [RIOT-OS/RIOT#2888]

**Comment by OlegHahm** [comment]
You basically need an application that includes the following modules:
* defaulttransceiver
* sixlowpan (or udp)
* sht11

The [Wiki](https://github.com/RIOT-OS/RIOT/wiki) includes basic documentation how to set things up, particular [this how-to](https://github.com/RIOT-OS/RIOT/wiki/Creating-your-first-RIOT-project) should contain the most relevant information for you how to get started.

**Comment by saleemrazam** [comment]
Thanks OlegHahm.... But there is also an example application in the Examples folder that i have downloaded from the gihub and installed on my ubuntu desktop, i can run the other applications like default, hello-world etc but how can i atcually run that sixlowapp from there..

**Comment by OlegHahm** [comment]
You mean https://github.com/RIOT-OS/applications/tree/master/sixlowapp?

**Comment by saleemrazam** [comment]
yes,,  i mean this,,, I am trying to flash sixlowapp but it says make: *** No rule to make target `/home/saleemrazam/RIOT/applications/sixlowapp/../../RIOT/Makefile.include'.  Stop.

**Comment by OlegHahm** [comment]
Then the path is wrong. The `applications` repository expects to be located at the same folder level as `RIOT` itself. It seems that you checked out `applications` inside `RIOT`. In this case you need to remove change `RIOTBASE ?= $(CURDIR)/../../RIOT` to `RIOTBASE ?= $(CURDIR)/../..`.

**Comment by saleemrazam** [comment]
solved,,,,,,,,,,,,,,, lots of thanks..

 cheers
