### ISSUE TITLE
Q: How to use buildtest and build size Makefile targets?

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#2921]
I was wondering if there is a wiki article or README file somewhere in the repo documenting how to use the Makefile targets that generate size comparisons between two builds. 

I have seen the results in some mailing list posts and in some PRs but never actually figured out how to do it myself.

**Comment by OlegHahm** [comment]
There is a link on the [Wiki start page](https://github.com/RIOT-OS/RIOT/wiki) called "Comparing build sizes" to the explanation that @Kijewski gave in his initial [PR](https://github.com/RIOT-OS/RIOT/pull/1033).

**Comment by gebart** [comment]
Thank you, I'll close this now.
