### ISSUE TITLE
stm32f334x8.h missing a closing Doxygen brace

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#2956]
I saw that the file stm32f334x8.h seem to be missing a closing brace somewhere in its Doxygen comments, the initial `@addtogroup ... @{` does not have a matching closing brace. This issue is just a reminder, I don't have the desire to start going through that file in search of the missing brace.

**Comment by OlegHahm** [comment]
Are we parsing the file or is it excluded in the doxygen configuration?

**Comment by haukepetersen** [comment]
Should be excluded.
