### ISSUE TITLE
at8r6rf231/iot-lab_M3: long address is not unique

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#2962]
Using the [at86rf2xx test application](https://github.com/RIOT-OS/RIOT/tree/master/tests/driver_at86rf2xx) results in identical long hardware address: `32:ff:dd:05:33:48:32:36` at least on iot-lab_m3. The short address seems to be okay.

**Comment by haukepetersen** [comment]
Do we actually now, that the CPUID driver is working correctly on the iot-lab_M3 nodes?
I have just one board here, the ID is
```
 CPUID: 0x32 0xff 0xd7 0x05 0x33 0x48 0x32 0x36 0x15 0x60 0x02 0x43
```
Could someone post some more IDs to verify that they are actually unique?

**Comment by haukepetersen** [comment]
never mind, that is not the problem...
