### ISSUE TITLE
nameless stack: possible duplicate entries

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#2965]
In several places in the new, nameless network stack arrays are used to manage lists of information such as IPv6 addresses for a given interface. Whenever an entry is removed from this list, it may happen that the list gets holey. However, the current implementation of the add functions usually only look for the first unused entry. This may lead to duplicate entries in the list.

Example:
List is: `A -> B -> C -> NULL -> NULL`
`remove(B)` =>  `A -> NULL -> C -> NULL -> NULL`
`add(C)` will find the first NULL entry (the second) and add `C` again:  `A -> C -> C -> NULL -> NULL`

~~One concrete occurrence is in [ng_ipv6_netif.c](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/network_layer/ng_ipv6/netif/ng_ipv6_netif.c#L37)~~

Currently known instances:

- [x] `ncache` in [`ng_ipv6_nc.c`](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/network_layer/ng_ipv6/nc/ng_ipv6_nc.c#L28])
- [x] `ipv6_ifs` in [`ng_ipv6_netif.c`](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/network_layer/ng_ipv6/netif/ng_ipv6_netif.c#L32)
- [x] `ipv6_ifs[i].addrs` also there.
- [x] `sixlow_ifs` in [`ng_sixlowpan_netif.c`](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/network_layer/ng_sixlowpan/netif/ng_sixlowpan_netif.c)
- [ ] `ifs` in [`ng_netif.c`](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/crosslayer/ng_netif/ng_netif.c#L36)

**Comment by cgundogan** [comment]
Makes sense.
What would be a good solution regarding this problem in your opinion? Simply iterating over all entries in the array to check for the appropriate ip address? And cache the first empty position encountered to use it in case it is not contained?

**Comment by authmillenon** [comment]
This might be the best solution. Filling the holes on deletion, might lead to problems, since I keep the pointers to both the `ng_ipv6_nc_t` and `ng_ipv6_netif_t` entries in timeout timers in the neighbor discovery e.g. Moving the contents around might break stuff in these cases.

**Comment by cgundogan** [comment]
>Filling the holes on deletion, might lead to problems..

+1 Yes, I am also against moving data around to fill gaps. I would claim that in the typical IoT scenario IP addresses wouldn't be added or deleted that often

**Comment by Lotterleben** [comment]
Just wondering, would it make sense to keep a list of the instances where this occurs in this issue so we have a nice overview and also kind of a “to do” list?

**Comment by authmillenon** [comment]
Added to the top-message

**Comment by OlegHahm** [comment]
:+1:

**Comment by Lotterleben** [comment]
I think ``ifs`` in ``ng_netif.c`` is another occurence...

**Comment by authmillenon** [comment]
This is not done yet ;)

**Comment by Lotterleben** [comment]
Whoops, how did that happen? :o

**Comment by authmillenon** [comment]
Auto-close, becauswle the PRs were somewhere marked as fixing ;) (via the words "fixes #<pr#>" in the comments e. g.)

**Comment by authmillenon** [comment]
But afaik this issue is fixed now. So I close.

**Comment by OlegHahm** [comment]
Great work, @Lotterleben and @authmillenon!

**Comment by authmillenon** [comment]
My biggest contribution was the bug in the first place, so all the honor should go to @Lotterleben ;-)

**Comment by OlegHahm** [comment]
Reviewing is also a valuable contribution.

**Comment by Lotterleben** [comment]
waitwaitwait, what about ``ifs`` in ``ng_netif.c``? I'd reckon this is another instance of that error and would be happy to fix it, but stop me if I'm wrong here. ^^

**Comment by authmillenon** [comment]
Oh yes, you're right.

**Comment by authmillenon** [comment]
Added it to the top.

**Comment by Lotterleben** [comment]
Okay, will take care of it as soon as possible!

**Comment by OlegHahm** [comment]
I guess we won't manage to fix the missing parts for this release?

**Comment by authmillenon** [comment]
Isn't this fixed by now?

**Comment by OlegHahm** [comment]
I have no idea.

**Comment by authmillenon** [comment]
Yapp it is.

**Comment by Lotterleben** [comment]
Pretty sure it is :)
