### ISSUE TITLE
Module `ng_icmpv6` and `ng_icmpv6_echo`

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#2971]
What is the purpose of defining these two modules in `Makefile.dep`? They both include `ng_ipv6`, which again includes `ng_icmpv6`. Smells like a circular dependency.. couldn't we just drop them and use `ng_ipv6` instead?

**Comment by authmillenon** [comment]
`ng_ipv6` and `ng_icmpv6` have a circular dependency. ICMPv6 without IPv6 does not make any sense and IPv6 needs ICMPv6 to function properly (though it is totally fine without it too). But I fail to see why this is a problem. `ng_icmpv6_echo` is only dependent on `ng_icmpv6` not vice versa so there is no circular dependency.

**Comment by cgundogan** [comment]
Right. Am I wrong assuming then that `ng_ipv6` and `ng_icmpv6` are module-wise completely equivalent, because they both have the same (transitive) dependencies?
Why would anyone use `ng_icmpv6` in their Makefile, when `ng_ipv6` also includes the same deps?

**Comment by authmillenon** [comment]
I don't know. Some users do weird stuff ;)

**Comment by cgundogan** [comment]
Therefore, I started this discussion... to prohibit weird stuff by not allowing it in the first place? (:

**Comment by authmillenon** [comment]
How do you want to disallow (mechanically, not conventionally, because rules by convention can be broken easily ;)) this, so a new user would know it is not allowed?

**Comment by kaspar030** [comment]
Why not keep the dependencies as they are (icmpv6 requires ipv6 but not the other way around), and create a pseudo-module for the whole stack, which in turn depends on what 99% of the users will want?

That way users could either USEMODULE += ipv6_full, or hand-pick their components. Keeps most of our Makefiles shorter, too.

**Comment by authmillenon** [comment]
Sounds good. Will open a PR tomorrow.

**Comment by kaspar030** [comment]
or maybe ipv6_default isntead of ipv6_full. Same for sixlowpan + sixlowpan_default (the first depending on ipv6, the latter depending on ipv6_default)?

**Comment by OlegHahm** [comment]
That could also solve #2947.
