### ISSUE TITLE
ng_ipv6/nc: ng_ipv6_nc_get_reachable() does not exist

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#2986]
`ng_ipv6_nc_get_reachable()` is called in [ng_ipv6.c#L449](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/network_layer/ng_ipv6/ng_ipv6.c#L449),
but this function was never defined. This results in a compiler error.

**Comment by authmillenon** [comment]
Oh I replaced this in #2908 and forgot to replace it, since I always tested it with #2910 directly. Will fix.

**Comment by authmillenon** [comment]
See #2987.
