### ISSUE TITLE
ng_inet_csum: incorrect checksum calculation

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#2988]
There are reproducable instances, where the the checksum of ICMPv6 (and probably UDP - though not confirmed) packets is wrong: This includes some echo requests ([see the two last ones here](https://www.cloudshark.org/captures/d0aeb1504620), interestingly enough the 4th has the checksum has the checksum the 3rd was expecting) and echo replies, when testing #2910 with two nodes on `ng_nativenet`: https://www.cloudshark.org/captures/b985f35e13a1 (packet 4).

@sgso also observed echo requests where the checksum will always be off by `0x700`.

**Comment by OlegHahm** [comment]
I'm not sure how I can help...

**Comment by authmillenon** [comment]
TBH I assigned you mainly because I did not know any other one. I might look into it after MobiSys, but I won't be able before next week.

**Comment by authmillenon** [comment]
Just to give a hint: the checksum is definitly calculated incorrectly, it's not one of these "a value is different then before" issues. I checked this.

**Comment by OlegHahm** [comment]
>  it's not one of these "a value is different then before" issues. I checked this.

What do you mean?

**Comment by authmillenon** [comment]
The value `ng_icmpv6_calc_csum()` puts into the header is the same, that Wireshark reports as wrong.

**Comment by authmillenon** [comment]
#2998 should help
