### ISSUE TITLE
ng_ipv6_netif: ng_ipv6_netif_find_best_src_addr() doesn't take mc addresses scope into account

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#3061]
Multicast addresses have a [scope](https://tools.ietf.org/html/rfc4291#section-2.7). Among this the link-local scope. `ng_ipv6_netif_find_best_src_addr()` currently returns just the first fitting unicast address assigned to the interface af the input address is a multicast address and the scope is not taken into account. A fix for that should do that and also consider other prefixes for other multicast scopes.

Marked as minor bug, since we haven't implemented [MLD](https://tools.ietf.org/html/rfc3810) until now and thus only dealing with link-local-only multicast addresses anyways.

**Comment by OlegHahm** [comment]
fixed?

**Comment by authmillenon** [comment]
No.

**Comment by OlegHahm** [comment]
Should be fixed #3561.
