### ISSUE TITLE
Renaming BOARD_INSUFFICIENT_RAM?

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#3065]
A discussion in https://github.com/RIOT-OS/RIOT/pull/2818#issuecomment-105446033 revealed, that renaming `BOARD_INSUFFICIENT_RAM` to something else (maybe `BOARD_INSUFFICIENT_MEMORY` as indicated by @OlegHahm) may be more appropriate.

Any thought on this?

**Comment by authmillenon** [comment]
+1

**Comment by BytesGalore** [comment]
still +1 for `BOARD_INSUFFICIENT_MEMORY`.
We could also split it into `RAM` and `ROM` (or is it YAGNI?)

**Comment by authmillenon** [comment]
I don't think we can rely on the linker's feedback for such a "fine-grained" distinction ;)

**Comment by OlegHahm** [comment]
I think we could (if the linker doesn't know who else will know?), but I don't think that it is necessary.
