### ISSUE TITLE
nhdp: unnecessary microsecond precision

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#3075]
NHDP and DAT are using `timex_t` to store timestamps, but microsecond precision is not required and just increases the struct size.

**Comment by kYc0o** [comment]
wow... very old issue without any addressing. Actually is maybe related to #4211 #2298 #1305

**Comment by miri64** [comment]
Not really.. But yeah this could be fixed somewhat straight forward.

**Comment by miri64** [comment]
Not *that* straight forward.

**Comment by miri64** [comment]
Needs to be postponed again.

**Comment by miri64** [comment]
NHDP is put up for deprecation in #11987.

**Comment by miri64** [comment]
nhdp was removed in #13396.
