### ISSUE TITLE
periph/random: random_read should return unsigned int

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3109]
https://github.com/RIOT-OS/RIOT/pull/3101#discussion_r31214572

The documentation for `periph/random.h` says:

>Reads num or less bytes of randomness from the source, will block until random data is available.
>
>Parameters
>    [in]	buf	destination buffer to write the bytes to
>    [in]	num	number of bytes to get from device, only values >0 are valid
>
>Returns
>    the number of bytes written to buf 
>    0 on error 

so we should not need to have a signed int for return type.

**Comment by OlegHahm** [comment]
@PeterKietzmann, @gebart, untag for this release?

**Comment by PeterKietzmann** [comment]
Yes, let's untag it for this release **but** come to a conclusion here. I think that I am pro API change, even if adapting the documentation might be easier. Any other opinions?

**Comment by thomaseichinger** [comment]
I'd support changing the return type for consistency.
