### ISSUE TITLE
native: improve make targets flash and term

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#314]
Maybe `make flash` could create the tap interface (if it does not already exist) and `make term` could start the elf file?

(migrated from https://github.com/RIOT-OS/boards/issues/33)

**Comment by LudwigKnuepfer** [comment]
I'm not going to work on this anytime soon.

**Comment by OlegHahm** [comment]
If there are no other volunteers, I'd like to close this.
