### ISSUE TITLE
ccn-lite example " simple forward" fails

### ISSUE THREAD

**Issue by wanxili** [RIOT-OS/RIOT#3160]
Hi,
    I am trying to play RIOT with ccn-lite example (ccn-lite-client and
ccn-lite-relay) on ubuntu using native board.

  I follow the instructions in the HOWTO document under ccn-lite-client
folder. For the "simple appserver (all in one shell)" scenario, it succeeds.

    But, for the simple forward (needs two shells) scenario , it failed. I've successfully setup the second shell which is populating /riot/text/... For the first shell, the result of command "interest /riot/text" is "
riot_get returned 0 bytes...aborting! ". I exactly followed the instructions.

    I have tested with the default example(/examples/default) between two nodes. It's successful. Also, for the simple appserver (all in one shell) scenario of ccn-lite example, I tested it with one shell and two shells. Both are successful.
  But, for the simple forward case, advanced forward case and overdosed forward  case, they all failed.

BTW, how to test these examples between two different computers using real ethernet interface?

Thanks

**Comment by OlegHahm** [comment]
The old implementation was removed, a new one will re-imported soon.
