### ISSUE TITLE
sys/crypto: remove our Twofish implementation

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#3195]
I do not know if there is a "IoT optimized" implementation of Twofish, but our implementation is unreasonably big for IoT applications and relies on malloc. The [reference implementation](https://www.schneier.com/twofish-download.html) looks much better at the first glance. 

Our twofish.c is unused and IMO unusable. Better drop it before it hurts someone ...

**Comment by Kijewski** [comment]
Also remove skipjack. WTF is skipjack?

And RC5. RC5 is patented and cannot be used freely.

**Comment by authmillenon** [comment]
According to the log they were imported by @haukepetersen in 05419a5 so I assign him.

**Comment by haukepetersen** [comment]
The actual import was done by @zkasmi. I just pulled them in from some branch as far as I remember. I have no opinion about the twofish implementation - if it does not live up to our quality standards and if nobody is really using it then I would be also in favor of dropping support (at least for now).

Regarding Twofish: feel free to PR the reference implementation to replace the existing one!

**Comment by OlegHahm** [comment]
I think these implementations originate from http://www.mi.fu-berlin.de/inf/groups/ag-tech/publications-old/1__resources/SNA-205.pdf

**Comment by LudwigOrtmann** [comment]
I'm with @haukepetersen .

**Comment by miri64** [comment]
Bump
