### ISSUE TITLE
cpu/stm32f3: PWM frequency is twice as fast as expected

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/RIOT#3197]
In #3165 it turned out that the PWM frequency and the duty cycle is twice as fast as expected on the stm32f3discovery and the nucleo-f303re board. It is not far to seek that the issue is related to the stm32f3 cpu.

**Comment by A-Paul** [comment]
I inspected this issue and found the error(s). Preparing a PR.

**Comment by PeterKietzmann** [comment]
Nice! For the record: the regarding PR is #3400. I will test with nucleo-f303 soon

**Comment by PeterKietzmann** [comment]
This issue has been fixed within #3400
