### ISSUE TITLE
core: simplify the reboot interface!

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#3242]
#3219 made me look at the kernel's reboot interface once more. It seems to me, that it can be simplified to some extend. Here is my proposal:

- remove the `mode` parameter to the reboot function, as it is not used and I don't see any usecase for this
- remove the reboot function from core entirely and just use the `reboot_arch()` in the first place
- add some additional implementation for `reboot_arch()`, that explicitly states that we expect this function never to return (i.e. by implementing it using some kind of loop, etc.).

Any opinions on this?

**Comment by gebart** [comment]
I like this proposal.

+1

**Comment by haukepetersen** [comment]
alright, then I will prepare a small PR for this.

**Comment by OlegHahm** [comment]
1. I think the parameter was originally introduced for POSIX or BSD compatibility reasons. 
2. Calling `*_arch()` from outside the kernel feels wrong for me.

**Comment by haukepetersen** [comment]
lets continue this discussion in the PR I created: #3246

**Comment by cgundogan** [comment]
@haukepetersen since #3246 got closed, is there still a need to have this issue open?

**Comment by haukepetersen** [comment]
nope
