### ISSUE TITLE
802.15.4: centralize default values and ranges

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#3291]
Instead of letting every driver of an 802.15.4 capable radio defining the values for minimum and maximum channel, packet size, address lengths and default values for some of the settings, this should be defined in a centralized manner, i.e. in an 802.15.4 specific header.

**Comment by kaspar030** [comment]
+1

This will probably be part of @haukepetersen and my netdev rework...

**Comment by PeterKietzmann** [comment]
+1

**Comment by authmillenon** [comment]
Not only the values should be defined centrally, but also some functions that are necessary all the time (e.g. netif_hdr to ieee 802.15.4 header and vice-versa).

**Comment by miri64** [comment]
Fixed in #5977.
