### ISSUE TITLE
native: tapsetup script fails on OS X

### ISSUE THREAD

**Issue by emmanuelsearch** [RIOT-OS/RIOT#3320]
When I try to execute tapster-osx.sh I get:

```
$ sudo ./tapsetup-osx.sh create
upping bridge1234
chown: /dev/tap0: No such file or directory
```

**Comment by authmillenon** [comment]
Have you tried #3182 working for you?

**Comment by emmanuelsearch** [comment]
Actually, following the advice of @thomaseichinger, updating tapsetup to the latest version seems to fix the problem I had http://tuntaposx.sourceforge.net/download.xhtml
