### ISSUE TITLE
cpu/native: LPM, should we add a break in switch case?

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/RIOT#3324]
Please compare [this line](https://github.com/RIOT-OS/RIOT/blob/master/cpu/native/lpm_cpu.c#L132). Even if it's an `exit` call, I wonder if we should add a `break;` there for the sake of completeness.

**Comment by PeterKietzmann** [comment]
@LudwigOrtmann any suggestions?

**Comment by kaspar030** [comment]
Wouldn't that just be one unnecessary instruction?

**Comment by PeterKietzmann** [comment]
Maybe yes. But that is what I'd like to figure out. Feel free to close this issue if this is (really) the case

**Comment by A-Paul** [comment]
As long as there exists **no** condition in `real_exit()` that could make it *return*, `break` would be considered "dead code". Code analyzers may give a warning on that sequence.

**Comment by PeterKietzmann** [comment]
Ok, then let's close this issue
