### ISSUE TITLE
Travis doesn't show failing platforms anymore

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3329]
See: https://travis-ci.org/RIOT-OS/RIOT/jobs/69877339#L569

The line
```
Building application: driver_hih6130 (11/89) 
```
should read something like:

```
Building application: driver_hih6130 (11/89) ...
failed: fox, msbiot, (whatever boards) ...
```

**Comment by phiros** [comment]
This is related to my changes in #3314 and ```compile_test.py```.
I will work on this today.
