### ISSUE TITLE
Strider: running test has caption "default"

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3351]
![snapshot1](https://cloud.githubusercontent.com/assets/317506/8607225/c6c865f8-2691-11e5-9fba-05f16f7d8bb2.png)

The text just says "default" for the strider build.

**Comment by phiros** [comment]
Seems like the github-status plugin does not set the context parameter.
I will change this soon.

BTW: Do you have any suggestions for the text? The best I came up with
is "RIOT-OS/Strider-CD".

**Comment by gebart** [comment]
Is it possible/desired to have other types of checks as separate strider
runs?
Strider-CD/compile-test?

Maybe we can use separate runs as a way to get a view of the build matrix
directly inside the PR threads on github, or is that more difficult to
maintain?
Strider-CD/static checks, Strider-CD/compile-test/cortex-m4 etc.

**Comment by OlegHahm** [comment]
If this is possible, I think it would be very helpful.

**Comment by phiros** [comment]
With the current version of strider it is not possible to have multiple projects per github repo.
However, I started to work on a build matrix plugin anyways. Maybe I can integrate your idea for
several status messages.
We just have to keep in mind that there is a rate limit for the Github API end-point.

**Comment by kaspar030** [comment]
> We just have to keep in mind that there is a rate limit for the Github API end-point. 

Github might raise our limit, they say they do if you can explain why
you need it.

**Comment by phiros** [comment]
Cool. That is good to know

**Comment by OlegHahm** [comment]
Strider is gone - for now.
