### ISSUE TITLE
unittests_constants: TEST_STRING8 is 7 chars long

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3371]
https://github.com/RIOT-OS/RIOT/blob/master/tests/unittests/common/unittests-constants.h#L22
is only 7 characters long if not counting the terminating NULL byte because of the double backslashes only resulting in a single backslash in the string.
From looking at the other constants it seems like the string is expected to be 8 chars excluding the terminating NULL.

Also worth mentioning is that the 64 char string is 68 chars + terminating NULL.

**Comment by gebart** [comment]
feel free to close if this is intentional.

**Comment by authmillenon** [comment]
Nope that was definitely not intentionally and explains why ASAN was complaining about in one of the lines I "fixed" in #3369 by not using `TEST_STRING8` ;-). Will do a PR.
