### ISSUE TITLE
Travis: Use caching of toolchain installation

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3379]
Follow up to #3378 
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#How-Do-I-Cache-Dependencies-and-Directories%3F

This could potentially reduce each build-matrix entry by a minute (package installation time) by caching all toolchain related files inside the Travis cloud.

**Comment by phiros** [comment]
I've thought about doing this now for some time. However, I have no idea if there are any restrictions
on the size of the cache. I need to do some experiments on this soon.

**Comment by miri64** [comment]
We don't use travis anymore so let's close this
