### ISSUE TITLE
RPL: add hop-by-hop header RPL option

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3399]
As described in [RFC6553](https://tools.ietf.org/html/rfc6553)

> Datagrams sent between RPL routers MUST include a RPL Option or RPL Source Route Header ([RFC6554]) and MAY include both.

**Comment by smlng** [comment]
@BytesGalore you're working on this, right?

**Comment by BytesGalore** [comment]
@smlng, yup

**Comment by BytesGalore** [comment]
see PR #7231
