### ISSUE TITLE
(Temporarily) lost features after radical cleanup

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#3418]
Here is a list of features, that would be temporarily lost, when doing a radical cleanup by removing all deprecated platforms/drivers and other modules. In the current state we can surely not drop everything in the list (e.g. native, msp430 support)! But this list should give us some guidance on what needs to be done...

Stuff that we get rid of for good:
- sys/uart0
- sys/chardev
- all calls to `dINT`/`eINT` (already done?)

Features that need adjustments (and are candidates to be dropped). Checked items are already being worked on.

CPUs:
- [x] cpu/arm7_common
- [x] cpu/arm7
- [x] cpu/cc430
- [x] cpu/lpc2387
- [x] cpu/mc1322x
- [x] cpu/msp430-common
- [x] cpu/msp430fxyz
- [x] cpu/native (uart peripheral driver is missing, but not needed for stdio)
- [x] cpu/x86 (won't fix)

Boards:
- [x] boards/native
- [x] boards/x86-multiboot-common (won't fix)
- [x] boards/msb-430
- [x] boards/pttu
- [x] boards/msb-430-common
- [x] boards/qemu-i386 (won't fix)
- [x] boards/z1
- [x] boards/avsextrem
- [x] boards/msb-430h
- [x] boards/telosb
- [x] boards/msba2
- [x] boards/redbee-econotag
- [x] boards/chronos
- [x] boards/msba2-common
- [x] boards/wsn430-common
- [x] boards/wsn430-v1_3b
- [x] boards/wsn430-v1_4

Drivers:
- [x] drivers/sht11 (also usable with the `dht` driver?)
- [x] drivers/smb380
- [x] drivers/cc110x_legacy (netdev2 cc110x PR'ed)
- [x] drivers/cc110x_legacy_csma
- [x] drivers/cc2420
- [x] drivers/lm75a  
- [ ] drivers/ltc4150

Others:
- [x] In the current state using desvirt is not possible anymore, because the native executable is missing the `-t` parameter to specify a TCP port for stdout redirection (see #3908) (fixed by https://github.com/des-testbed/desvirt/pull/17)

**Comment by haukepetersen** [comment]
Please edit/extend this list!

**Comment by authmillenon** [comment]
Kindof duplicate of (or overlap with) #1540

**Comment by haukepetersen** [comment]
True. Actually I was looking for #1540 earlier, but could not find it... How about closing #1540 and keep this issue, as this is more detailed and more up-to-date?

**Comment by authmillenon** [comment]
:+1:

**Comment by OlegHahm** [comment]
updated the list

**Comment by kaspar030** [comment]
updated

**Comment by cgundogan** [comment]
added a word about `desvirt`. 0e4386a46fc82e606d466964fcc6c41cd5bc1186 kicked out the `-t` parameter from the native executable that specifies a TCP port for the stdout redirection.

**Comment by miri64** [comment]
Bump

**Comment by OlegHahm** [comment]
This looks actually doable for the release.

**Comment by haukepetersen** [comment]
It seems to me, that everything we didn't (re-)merge until today can't be important. So closing this issue now.
