### ISSUE TITLE
openocd 0.9: OpenOCD closes when pressing CTRL+C in GDB

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3427]
OpenOCD closes when pressing CTRL+C in GDB, when openocd is started by `make debug` (`openocd.sh`) and is running in the background of the same terminal as gdb. GDB still receives the ctrl+c as well.

This is not observed if I downgrade openocd to v0.8.0.

Package versions:
 - cross-arm-none-eabi/gdb-7.9.1
 - dev-embedded/openocd-0.9.0
 - kde-apps/konsole-4.14.3

**Comment by OlegHahm** [comment]
workaround: https://github.com/RIOT-OS/RIOT/wiki/Troubleshooting#question-6
