### ISSUE TITLE
_pktbuf_add_unsafe incorrectly adjusts data pointer

### ISSUE THREAD

**Issue by smee204** [RIOT-OS/RIOT#3461]
I think in ng_pktbuf.c _pktbuf_add_unsafe incorrectly adjusts the pkt->data pointer. I find that the address is invalid after this function has completed.

Currently it does this:
`pkt->data = (void *)(((uint8_t *)pkt->data) + size);`

I think it should do this:
`pkt->data = (void *)(((uint8_t *)pkt->data) + (size*4));`

**Comment by authmillenon** [comment]
What value does `size4` have?

**Comment by gebart** [comment]
(edited to add code formatting)

**Comment by gebart** [comment]
I don't understand why you need `size * 4`

**Comment by smee204** [comment]
Sorry yes now I look at it again the code was correct. I will close this issue.

I think the problem is with my compiler/hardware settings. I must have it setup so pointers have to be 4 byte aligned...
