### ISSUE TITLE
astyle: Update docs

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3469]
According to @authmillenon it should no longer be necessary to run `keyword_space.sed` since #3384

**Comment by authmillenon** [comment]
I did not test that, just conjectured.

**Comment by A-Paul** [comment]
Have been curious about that.

    1  s/\bif(/if (/
    2  s/\bswitch(/switch (/
    3  s/\bcase(/case (/
    4  s/\bwhile(/while (/
    5  s/\bfor(/for (/
    6  s/\bdo(/do (/
    7  s/! /!/

*Lines 1,2,3,4,5* are covered by used astyle parameter `--pad-header`. *Line 6* isn't, as you wouldn't have that in C likes.  
There seems to be nothing in *astyle* which could perform the substitution in *Line 7*.

**Comment by gebart** [comment]
@A-Paul I don't know what you mean with _6_, `do` is a keyword in C.

**Comment by A-Paul** [comment]
@gebart, yes it is. But followed by *left curly bracket* and not by *left parenthesis*. I should have been more specific.

**Comment by gebart** [comment]
Ah, that's a typo. Good job spotting it!

**Comment by OlegHahm** [comment]
obsolete
