### ISSUE TITLE
No shell/uart(?) on iot-lab_M3 boards on current master

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/RIOT#3486]
I wanted to run the `ng_networking` example with an iot-lab_M3 and a samr21-xpro on current master. On samr21-xpro everything is fine, but on the iot-lab_M3 node I can't write to the shell (neither in the shell-example). Shouldn't this have also occurred during testings in #3475 yesterday, or am I doing something wrong?

**Comment by OlegHahm** [comment]
Isn't this the same problem as in https://github.com/RIOT-OS/RIOT/issues/3438?

**Comment by PeterKietzmann** [comment]
Öhm yes, seems so. Somehow I thought it was fixed. Then I'll close this one again
