### ISSUE TITLE
Port RIOT to the ZYNQ7000 FPGA platform (ARM Cortex A9)

### ISSUE THREAD

**Issue by smee204** [RIOT-OS/RIOT#3490]
Add support for the Xilinx ZYNQ7000 FPGA family. The processor in the ZYNQ FPGA is a dual core ARM Cortex A9 processor.

**Comment by OlegHahm** [comment]
Since PRs are actually issues themselves - I don't think we need this issue or do I miss something?

**Comment by smee204** [comment]
I am fairly new to github so assumed an issue was required. Feel free to
close.
