### ISSUE TITLE
USB Device Stack

### ISSUE THREAD

**Issue by jfischer-phytec-iot** [RIOT-OS/RIOT#3546]
For some time now I have been working on the USB Device Stack for RIOT. Currently I have a functioning device stack with CDC ACM device support (loopback).  It is progressing slowly, because I do it only in my free time, but steadily. I plan to open a PR at end of the week.
The stack shall/will be designed to run on built-in USB-Controllers (on ARM SoCs or similar). 

Here I would like to put my ideas on the stack to discussion and track the progress.

I see three steps as the main task:
1.  Implementation of USB Device Stack with CDC-ACM support, thus RIOT can act (inside a USB adapter) as a border router.
2. Implementation of USB HCI protocol, thus RIOT can be used inside a USB BLE adapter (if BLE LL is finished).
3. Since there is no common interface such as HCl for IEEE802.15.4 devices under Linux, it is close to take it from bluez and/or adapt it to use with Linux IEEE802.15.4 subsystem.

I think if it is so far, RIOT will be a universal OS for IoT. Especially the step two may increase the popularity of RIOT and increases the acceptance of IEEE802.15.4 devices.

The TODO list for the stack:
- [x] USB Device Stack,  WIP -> #3890
  - [x] CDC-ACM support
  - [x] CDC-ECM support
  - [ ] netdev support over bulk endpoints (radio on the SoC can be used by the native port)
- [ ] RIOT-OS as Hard-MAC for Linux IEEE802.15.4 subsystem
- [ ] Implementation of USB HCI protocol, -> #4684

Supported hardware:
- NXP Kinetis SoC (k64f, kw2xd, ...)
  - https://github.com/RIOT-OS/RIOT/wiki/Board:-Phytec-phyWAVE-KW22
- Atmel SAMR21, SAMD21 (WIP)
  - https://github.com/RIOT-OS/RIOT/wiki/Board%3A-SAMR21-xpro

**Comment by kaspar030** [comment]
Nice!

**Comment by gebart** [comment]
Thank you for taking care of such a large task in your free time!

**Comment by PeterKietzmann** [comment]
Wow :-) !

**Comment by sgso** [comment]
I'm looking forward to use/test this for the rf231usb.

**Comment by OlegHahm** [comment]
Awesome!

**Comment by jfischer-phytec-iot** [comment]
We need a PID / VID for the stack (maybe more PIDs). Are Openmoko PIDs is a possibility? Can someone please requested a PID for RIOT?

http://wiki.openmoko.org/wiki/USB_Product_IDs

**Comment by gebart** [comment]
@jfischer-phytec-iot good idea!
Do we need more than one Product ID to distinguish different applications (or use cases)?
It would be useful to be able to distinguish between for example SLIP interfaces and debug message TTY ports, but that can also be done via one of the string properties (iSerialNumber, iManufacturer, iProduct).

**Comment by miri64** [comment]
Fixes https://github.com/RIOT-OS/RIOT/issues/2284

**Comment by PeterKietzmann** [comment]
Unfortunately this project has been scrubbed. Closing issue (for now)

**Comment by danpetry** [comment]
Shame, this looks cool

**Comment by aabadie** [comment]
There is a starting work made by @astralien3000 and based on this original PR #3890. This feature is very useful indeed.
