### ISSUE TITLE
ng_at86rf2xx: set radio parameters other than channel

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3554]
Continuing from the discussion in #3434. The radio offers more options than simply setting the channel, we should be able to configure them at run time or compile time.

**Comment by bapclenet** [comment]
Agree with you, we should add the possibility to set the channel page and the channel. This is useful at least for the 212B, I don't know for other 2xx

**Comment by gebart** [comment]
closing in favor of #3452 (I forgot I had already opened an issue)
