### ISSUE TITLE
sys: net: fib is using deprecated net_help

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#3574]
While removing the legacy network stack, I decided not to remove net_help as fib is still depending on it.

A look at the code shows that fib is mainly using net_help's pton function, which could be replaced by gnrc's ipv*_str_to_addr() functions. Also, some defines are taken from net_help.

**Comment by BytesGalore** [comment]
I will change that, so net_help can be finally removed.

**Comment by cgundogan** [comment]
But wouldn't this also make the gnrc independent fib gnrc dependent?
Am 06.08.2015 13:26 schrieb "BytesGalore" <notifications@github.com>:

**Comment by kaspar030** [comment]
> But wouldn't this also make the gnrc independent fib gnrc dependent?

only until we factored out the string-to-address conversion functions.
Maybe we should stick with net-help until we've done that?

**Comment by BytesGalore** [comment]
I will try to remove every dependency to the old- and gnrc stack.
(soon, I'm at work now)

**Comment by authmillenon** [comment]
Should be fixed, since #3878 removed `net_help` and FIB is still compiling.
