### ISSUE TITLE
ipv6: netif: unittest failing

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#3600]
Running `tests/unittests/tests-ipv6_netif` one gets:
```
ipv6_netif_tests.test_ipv6_netif_add__despite_free_entry (/home/oleg/git/RIOT/tests/unittests/tests-ipv6_netif/tests-ipv6_netif.c 77) (entry = ng_ipv6_netif_get(DEFAULT_TEST_NETIF)) was null.
```
Question 1 (to @authmillenon): did anything change here? Isn't it logical that `test_ipv6_netif_add__despite_free_entry()` fails in line 103 because NG_NETIF_NUMOF == 1?

Question 2 (to @phiros): Why does Travis not fail on this?

**Comment by authmillenon** [comment]
Question 1: will investigate.
Question 2: because with `make -C tests/unittests all` it works :/

**Comment by authmillenon** [comment]
See #3601
