### ISSUE TITLE
cpu: k60: not using uart_stdio

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#3636]
The k60 is using it's own newlib implementation.

Just making it use the shared newlib module would drop filesystem/fd support from the port, but the port-specific syscalls.c doesn't use uart_stdio, and also it still offers uart0 support.

Could we either

1. make that implementation use uart_stdio and drop uart0
2. factor out the syscalls into its own module, so the user can chose between the shared newlib implementation and the specific one
3. ?

@jfischer-phytec-iot ideas?

**Comment by gebart** [comment]
I accidentally hid the cleanup commit inside https://github.com/RIOT-OS/RIOT/pull/3485. See https://github.com/gebart/RIOT/commit/ea019b308974f98a281247c5c798ee295df455eb
I'll open a separate pull for that commit.

**Comment by gebart** [comment]
The whole FD stuff should be refactored and introduced properly on system level instead of being board specific. Anyone implementing this on RIOT can always use the k60 syscalls as a base for their implementation.
