### ISSUE TITLE
RFC: Future of gnrc_networking

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#3638]
Thinking about a stack independent connection API (see ~~#3615~~ #5758) and POSIX sockets and the final restructuring of GNRC for the last few days got me thinking about the future of the `ng_networking` app. Basically we have two paths we can go with it:
1. Keep it a pure GNRC example to keep it simple. 
2. Rewrite it as a ~~`conn`~~ `sock` or even socket example, since `netapi` never was meant to be an end-user API. 

For the first case I would rename the app to gnrc or gnrc_networking, for the second I would remove the ng_ prefix.

**Comment by PeterKietzmann** [comment]
I didn't look into #3615 so I can't rate the complexity. But to state my general opinion: I think it is mandatory to have an example that "presents" the whole stack, including the application layer API. Dependent on the parallels between to current "pure" `ng_networking` example and the new one, I would decide if it is reasonable to keep both applications in the master or not.

**Comment by cgundogan** [comment]
What's the current state of this issue? Can it be closed?

**Comment by authmillenon** [comment]
It'd like to have a little more discussion on that. Not just my opinion and @PeterKietzmann's ;)

**Comment by kaspar030** [comment]
+1 for the first route, rename and create a new one using conn.

**Comment by gebart** [comment]
I agree with @kaspar030, create a new example for conn, keep the gnrc_networking example for easier testing of the gnrc stack.

**Comment by miri64** [comment]
Maybe I find some time until the release for this one.

**Comment by miri64** [comment]
Mh somehow it seems that I missread the comments. The rename to gnrc_networking already happened so let's close it :-).
