### ISSUE TITLE
CI: integrate `make scan-build` into build tests?

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#3649]
I wonder if it would make sense to integrate the `scan-build` target, introduced in #3468 and using clang's static code analyzer, into the build tests on the CI system. If yes, would just failing on an error report be enough?

**Comment by phiros** [comment]
Failing on an error because the static code analyzer thinks there is something wrong in the code is IMHO not a good idea. 
I've seen quite a few false positives whilst using scan-build...

**Comment by OlegHahm** [comment]
Well, we have already cpp-check in the build test which has a comparable risk of false positives. Do you have an example for a false positive with the clang-analyzer?

**Comment by phiros** [comment]
Hmm don't remember exactly. Seems like when we got rid of the old network stack we also get rid of some of those issues. I would have to look into some older revs in order to find those issues again. 
However, the [FAQ](clang-analyzer) of clang-analyzer has some examples.
