### ISSUE TITLE
Ping6 on the iotlab-m3 times out for payload sizes >= 2000

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#3672]
Pinging on the testbed (iotlab-m3) w/ and w/o iphc times out for payload sizes `>= 2000`.

`ping6 abcd::x 2000`  => timeout
`ping6 abcd::x 1999`  => works perfectly

**Comment by cgundogan** [comment]
see discussion in #3671

**Comment by OlegHahm** [comment]
Have you tried with size above 2000?

**Comment by cgundogan** [comment]
Yes, ? `2001` and `3000` resulted in the same misbehaviour.

**Comment by OlegHahm** [comment]
Btw. I cannot even ping google.com from my PC with payloads above 1500 bytes.

**Comment by authmillenon** [comment]
@OlegHahm Look at the MTU of your Ethernet interface ;-)

**Comment by authmillenon** [comment]
but speaking of: I think IPv6 isn't currently testing if the packet exceeds the interface's MTU :/

**Comment by OlegHahm** [comment]
Link local works, so I guess its rather a question of the routers in between.

**Comment by authmillenon** [comment]
Maybe they don't allow IPv6 fragmentation ;-)

**Comment by authmillenon** [comment]
> but speaking of: I think IPv6 isn't currently testing if the packet exceeds the interface's MTU :/

We should fix this issue first however, to not let it reappear in the future.

**Comment by cgundogan** [comment]
Debugging enabled in sixlowpan and pinging with a payload size `>=2000`: 
`dispatch e8 ... is not supported`. @authmillenon does it ring a bell to you?

**Comment by authmillenon** [comment]
For some reason 6LoWPAN is receiving NALP frames.

**Comment by authmillenon** [comment]
(maybe even sending them, but why oO)

**Comment by authmillenon** [comment]
Are you receiving any other fragments beforehand?

**Comment by authmillenon** [comment]
Looked it up right now: `0xe8` is a subsequent fragment dispatch, so … I need to investigate further, why this is not recognized.

**Comment by OlegHahm** [comment]
@authmillenon,
> For some reason 6LoWPAN is receiving NALP frames.

That reminds me that the 6LoWPAN unittests revealed that the `is_nalp` function may give wrong results (or the test was broken). Let me check.

**Comment by authmillenon** [comment]
m( I know what is happening.

**Comment by authmillenon** [comment]
I was so focussed on the 2000, I forgot about the IPv6 and ICPMv6 header: With them the total datagram size is 2048, which is 2^11. The datagram size field of 6LoWPAN only fits 2047 at max [1].

[1] https://tools.ietf.org/html/rfc4944#section-5.3

**Comment by authmillenon** [comment]
So 6LoWPAN just does not support `ping6 2000` ;)

**Comment by authmillenon** [comment]
Didn't we had an issue like that a few weeks back?

**Comment by authmillenon** [comment]
It's a bug however, that the frame is send out regardless.
