### ISSUE TITLE
ipv6: Modules.dep not complete?

### ISSUE THREAD

**Issue by A-Paul** [RIOT-OS/RIOT#3695]
In https://github.com/RIOT-OS/RIOT/pull/3349 I experienced that in `Makefile.include`

    USEMODULE += ng_ipv6

was not enough as I got compile error. Using the errors as a hint I added

    USEMODULE += ng_icmpv6
    USEMODULE += ng_ndp

which stopped the errors. Although this worked as a workaround maybe these additions would be better placed in `$RIOTBASE/Makefile.dep`

After trying to update with `s/ng_/gnrc_/` (I haven't pushed those changes now) I get new errors for undefined `gnrc_ndp_internal_sl2a_opt_handle`.

Before beginning to search for missing USEMODULE entries by trial & error again, maybe someone can investigate the situation. At least I'm not shure if the workaround was the correct approach.

**Comment by PeterKietzmann** [comment]
@A-Paul, please add appropriate labels to an issue and assign a maintainer, if you have one in mind :-)

**Comment by authmillenon** [comment]
1) its 'gnrc_ipv6' now
2) I can't really replicate this error. When I make 

```bash
USEMODULE=gnrc_ipv6 make -C tests/unittests/ tests-core
```

I don't get any errors.

**Comment by PeterKietzmann** [comment]
Without looking into details I'd propose to rebase and be aware that #3661 is not merged now. Otherwise, is it a compiler dependant thing (I don't think so)? Which compilers are you using?

**Comment by authmillenon** [comment]
Did it on current master, for native I use `gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4` and `Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final)`, on arm platforms I use `arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 224288]`

**Comment by PeterKietzmann** [comment]
(Was more looking to Paul as `ng_ipv6` seems outdated ...)

**Comment by A-Paul** [comment]
@authmillenon Although I'm one day late: Happy Birthday :cake:

> 1) its 'gnrc_ipv6' now

I know but as I wrote:

> After trying to update with s/ng_/gnrc_/ (I haven't pushed those changes now) I get new errors for undefined gnrc_ndp_internal_sl2a_opt_handle.

Shall I push this despite it's not compiling?

> 2) I can't really replicate this error. When I make

If you check out the PR and remove the additional USEMODULEs you'll see. I added them for a reason.

**Comment by A-Paul** [comment]
@PeterKietzmann : gcc (Debian 4.9.2-10) 4.9.2

**Comment by A-Paul** [comment]
Forgot to mention it. I had rebased before `s/ng_/gnrc_/`.

**Comment by authmillenon** [comment]
Can you please rebase the PR first?

**Comment by authmillenon** [comment]
It should compile without `gnrc_icmpv6` and `gnrc_ndp` then.

**Comment by A-Paul** [comment]
@authmillenon See https://github.com/RIOT-OS/RIOT/issues/3695#issuecomment-133943572.

**Comment by authmillenon** [comment]
What about it? I'm confused. Can you just rebase the PR so I can check out what is going on?

**Comment by A-Paul** [comment]
Sorry, I confused something...

**Comment by A-Paul** [comment]
Pushed.

**Comment by authmillenon** [comment]
Ah saw it now myself. Don't know why it is not showing up in master, but https://github.com/RIOT-OS/RIOT/pull/3698 should fix it in a better way.

**Comment by A-Paul** [comment]
Fixed by #3698.
