### ISSUE TITLE
cpu: Compile time PLL clock selection for STM32L1 series based on board/../periph_conf.h

### ISSUE THREAD

**Issue by DipSwitch** [RIOT-OS/RIOT#3702]
Propose the configure the STM32L1 PLL clock source with the CLOCK_HSE or CLOCK_HSI.

This can be ported to the STM32Fx familie to.

**Comment by PeterKietzmann** [comment]
@DipSwitch, when closing an issue, please always give a short hint why. Or was it per accident?

**Comment by DipSwitch** [comment]
@PeterKietzmann sorry. It's closed because I also created a PR. And double bookkeeping is not my favorit. ^_^
