### ISSUE TITLE
doc: API-Website builder seems not complete

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#3715]
When I go to http://doc.riot-os.org/inherits.html there are no pictures showing up while on my local build there are:
![local_doc_hierarchy](https://cloud.githubusercontent.com/assets/675644/9490432/2c425472-4be8-11e5-8356-81041e832e3c.png)

I think the class hierarchies aren't that essential, but would be nice to have them in there anyways. As far as I know you just need to install `dot` to make that happen.

**Comment by OlegHahm** [comment]
Graphviz was missing. Thanks for the hint. Fixed.
