### ISSUE TITLE
xtimer: tests nrf24l01p delay values

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#3769]
When converting tests/driver_nrf24l01p_lowlevel to xtimer, I stumbled over delays based on "ticks" in ```drivers/nrf24l01p/include/nrf24l01p_settings.h```.

It has to be checked if they can be used as-is in us.

**Comment by kaspar030** [comment]
(changes in #3525)

**Comment by PeterKietzmann** [comment]
They can. IIRC one had to wait a really short time period after the CS line is pulled down and the SPI byte transfer begins.

**Comment by PeterKietzmann** [comment]
And AFAIK Hauke already started to rewrite the driver

**Comment by PeterKietzmann** [comment]
PS: Of course one may wait a bit longer between CS low and byte-transfer start

**Comment by kaspar030** [comment]
Ok, so I can close this?

**Comment by PeterKietzmann** [comment]
Yepp. But let's not forget to check the driver before a merge.

**Comment by kaspar030** [comment]
+1
