### ISSUE TITLE
avr8: assert compile error

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#3770]
I've stumpled over this error a couple of times (in travis builds):

/home/travis/build/RIOT-OS/RIOT/sys/xtimer/xtimer.c: In function '_xtimer_sleep':

```
/home/travis/build/RIOT-OS/RIOT/sys/xtimer/xtimer.c:39:9: error: implicit declaration of function 'abort' [-Werror=implicit-function-declaration]

         assert(!long_offset);

         ^
```

It doesn't show up locally, and it seems to not always pop up in travis. Ideas?

**Comment by cgundogan** [comment]
I had a brief offline discussion with @OlegHahm once .. It could be that travis uses a different toolchain, which does not define the abort function

**Comment by OlegHahm** [comment]
Moving to #3722 could be a solution. ;)

**Comment by authmillenon** [comment]
Is this issue solved, since RIOT has it's own assert now?

**Comment by OlegHahm** [comment]
Haven't seen that recently. Feel free to re-open if you experienced otherwise.
