### ISSUE TITLE
gnrc: Provide generic netapi ping

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#3791]
In the spirit of #3389 and the old layer 2 ping a generic ping application/module for any `gnrc_netapi` enabled module might be of use for testing.

**Comment by miri64** [comment]
@OlegHahm didn't you work on something like this?

**Comment by OlegHahm** [comment]
Hm, yes, it might be, but it's probably horribly outdated.

**Comment by miri64** [comment]
I think this feature could still be interesting. Let's give it another 6 months ;-).

**Comment by maribu** [comment]
I'm not sure if I understand the feature request correctly. Is it ping as in ICMPv6 echo request and reply? Or is it some generic mechanism to check if network stack component is still alive and responsive? Or something else completely?

**Comment by miri64** [comment]
The first: the pre-GNRC network stack had the ability to do (non-standardized) ICMPv6-echo-like behavior on the link layer. The idea was, to provide something generic based on netapi for any (packet based) layer. Not sure if this is something we still want or need though... Especially since the link layer (which started this whole discussion) is technically not part of GNRC anymore...

**Comment by maribu** [comment]
OK, then lets close this and see if someone complaints :)
