### ISSUE TITLE
rpl: RPL Instance ID should be allowed by rpl shell

### ISSUE THREAD

**Issue by DipSwitch** [RIOT-OS/RIOT#3795]
The RPL shell interface blocks the RPL instance 0 while this is a valid RPL instance ID according to the RFC.

This is probabbly done to catch invalid input for atoi, but mabe this can easily be fixed by checking if the argument is `0x30, 0x00` or using `strtol` and check `errno`.

**Comment by cgundogan** [comment]
This already has been addressed with #3726. Can you rebase onto the current master and test again?

**Comment by DipSwitch** [comment]
Just created this patch against master.

**Comment by DipSwitch** [comment]
Fixed with #3797
