### ISSUE TITLE
tftp: client / server implementation

### ISSUE THREAD

**Issue by DipSwitch** [RIOT-OS/RIOT#3832]
Goodmidday,

We would like to implement a TFTP client and/or server in our firmware. Would you like to have it as a module under `sys/net/gnrc/application_layer/tftp*` Or should I implement it as a package?

**Comment by OlegHahm** [comment]
Wouldn't we need a filesystem first?

**Comment by kaspar030** [comment]
why? tftp could be used to download the system's current flash contents, or to store a to-be-flashed new image in memory.

**Comment by OlegHahm** [comment]
Well, I was wondering about the 'f' in the name ;-) and about the question if this is the smartest protocol to exchange software update without ensuring anything (no security, no end-to-end-acknowledgements, no checksum...).

**Comment by DipSwitch** [comment]
It has end-to-end acknowledgement, we always use CRC32 'signing' of the bin file.

**Comment by DipSwitch** [comment]
But I can look for another way to update, I like things to be secure aswell and havn't really thought about that part because we use a dedicated private network. But thats not the default point of view for 6lowpan

**Comment by kaspar030** [comment]
Well, tffp has one thing speaking for it: it is super simple. And actually I think security can easily be applied on top of it. So @DipSwitch, if you feel like implementing tftp, go ahead!

**Comment by DipSwitch** [comment]
Closed in favor of #3911
