### ISSUE TITLE
Cannot make chronos

### ISSUE THREAD

**Issue by jeerakiet** [RIOT-OS/RIOT#3857]
After I typed command "make", I got some errors show as below.
![image](https://cloud.githubusercontent.com/assets/14296135/9880419/b98fe034-5bf5-11e5-9c14-3bf425a5212d.png)

How can I deal with this problem ?

**Comment by DipSwitch** [comment]
I think the header files don't have #ifndef _HEADER #define HEADER

**Comment by kaspar030** [comment]
Hey,

On 09/15/15 17:07, jeerakiet wrote:
> After I typed command "make", I got some errors show as below.
> image
> <https://cloud.githubusercontent.com/assets/14296135/9880419/b98fe034-5bf5-11e5-9c14-3bf425a5212d.png>
> 
> How can I deal with this problem ?

I've just tried building chronos on master and it worked fine.

Which toolchain are you using?

Kaspar

**Comment by jeerakiet** [comment]
I'm using GCC toolchain for MSP430.
Which toolchain are you using ? Kaspar

**Comment by jeerakiet** [comment]
Thank you very much. I can do it :)

**Comment by LudwigOrtmann** [comment]
@jeerakiet @DipSwitch issue resolved? fix available?

**Comment by DipSwitch** [comment]
I don't know if the issue is resolved.

**Comment by OlegHahm** [comment]
Well, since the issue opener didn't come back to us, I would consider this issue as solved.
