### ISSUE TITLE
6lowpan nd: neighbor cache entries stayed stale and timed out

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#3891]
When playing around with a 6LBR and a 6LR on https://github.com/OlegHahm/RIOT/tree/2015.09-RC0 I realized that all entries in both nodes' neighbor caches stayed marked as `STALE` and disappeared from the cache completely after some time. Haven't had the time to investigate further.

**Comment by authmillenon** [comment]
That they just disappear is weird. Sure they did not PROBE first?

**Comment by OlegHahm** [comment]
No, I'm not sure, but they were `STALE` right from the beginning, which shouldn't also not be the case, right?

**Comment by authmillenon** [comment]
For the STALE I've got an idea and am already on it, but the disappearance is still weird...

**Comment by OlegHahm** [comment]
Sorry, I haven't captured any PCAP. :-(

**Comment by authmillenon** [comment]
#3892 fixes 6LoWPAN-ND at least that the entries change to DELAY (and then hopefully to PROBE and then to REACHABLE), but that the 6LR does not has a REACHABLE state is strange. It should be set to it as soon as it reaches https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/ndp/gnrc_ndp.c#L294 on NA reception.

**Comment by authmillenon** [comment]
(maybe the S flag is not set for some reason in the NA?)

**Comment by authmillenon** [comment]
It's to late today to investigate this. Will do tomorrow.

**Comment by authmillenon** [comment]
Ah, of course they are stale. They are set by the NS not by the NA. #3892 is the full fix then (not for the disappearance though... that's still strange and we have to look into it, but my fix makes that harder, since entries are more seldom STALE now ^^)

**Comment by OlegHahm** [comment]
With current state I could indeed neither see NCEs being STALE when they shouldn't be. Also saw no more NCEs disappearing, but have to test more and longer to verify that.
