### ISSUE TITLE
clean up license headers

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#392]
There exist various license headers throughout RIOTs sources. Also some files don't have license headers at all.

* Unify all lgpl license headers.
* Unify all 'other license' headers for each `other license`.
* Identify files without licenses, contact their original authors and get them to explicitly license the respective files under the lgplv2. (see #560)

**Comment by LudwigOrtmann** [comment]
As of today:
```
$ ./dist/tools/licenses/check.sh 
file has an unknown license header: 'boards/x86-multiboot-common/include/multiboot.h'
file has an unknown license header: 'cpu/lpc2387/include/lpc23xx.h'
file has an unknown license header: 'cpu/stm32f1/include/stm32f10x.h'
file has an unknown license header: 'tests/unittests/map.h'
```

**Comment by LudwigKnuepfer** [comment]
I'm not going to work on this anytime soon.

**Comment by LudwigKnuepfer** [comment]
For the record - the state of the issue:
```
$ ./dist/tools/licenses/check.sh
file has an unknown license header: 'boards/x86-multiboot-common/include/multiboot.h'
file has an unknown license header: 'cpu/stm32f1/include/stm32f10x.h'
file has an unknown license header: 'tests/unittests/map.h'
```

**Comment by authmillenon** [comment]
* `boards/x86-multiboot-common/include/multiboot.h` is GPLv2+
* `cpu/stm32f1/include/stm32f10x.h` seems to be a proprietary license digged into the doxygen
* `tests/unittests/map.h` Is just another version of MIT

Nothing that isn't fixable :-)

**Comment by haukepetersen** [comment]
for the `stm32f1` this should be fixed with #4681

**Comment by authmillenon** [comment]
The other ones still remain.

**Comment by authmillenon** [comment]
Regarding `boards/x86-multiboot-common/include/multiboot.h`: according to @Kijewski (https://github.com/RIOT-OS/RIOT/pull/4703#issuecomment-176171634) there is a version with MIT license now: https://www.gnu.org/software/grub/manual/multiboot/html_node/multiboot_002eh.html

**Comment by authmillenon** [comment]
Finally fixed \o/
