### ISSUE TITLE
Assert : wrong LR

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#3920]
Hitting an assert results correctly in a hard fault for the iotlab m3.
But the LR value points to somewhere in the UART implementation (for any assert) and thus renders asserts completely useless, because the origin is not traceable. (Tested with the RC branch)

**Comment by OlegHahm** [comment]
a) I also saw this a couple of times, but not always.
b) The origin is still traceable with the debugger attached.
c) If you erase `core/include/assert.h` you will fall back to Newlib's assert.

But yes, this might be improved.
