### ISSUE TITLE
at86rf2xx: (at86rf212b) Add support for Chinese 780 MHz band

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#3938]
IEEE 802.15.4c-2009

> Part 15.4: Wireless Medium Access Control (MAC) and Physical Layer (PHY) Specifications for Low-Rate Wireless Personal Area Networks (WPANs)
> Amendment 2: Alternative Physical Layer Extension to support one or more of the Chinese 314–316 MHz, 430–434 MHz, and 779–787 MHz bands

channel page 5, channels 0-3

Requires some messing around in the CC_CTRL_0, CC_CTRL_1 registers (CC_BAND and CC_NUMBER)

Just writing down the idea here, I don't have a use case currently.

**Comment by bapclenet** [comment]
True! Add it to your PR you talked about in #3452
