### ISSUE TITLE
gnrc: scan-build finds "Dereference of null pointer" in gnrc_icmpv6.c

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#3960]
[sys/net/gnrc/network_layer/icmpv6/gnrc_icmpv6.c](https://github.com/RIOT-OS/RIOT/blob/6c61266bedc20b8ce9443cc7c099449e64e21f44/sys/net/gnrc/network_layer/icmpv6/gnrc_icmpv6.c), lines 72, 101, 107, and 113.

**Comment by authmillenon** [comment]
For all those there are asserts in line 64 and 70.
