### ISSUE TITLE
RPL: Advertise DODAG only over the assigned interface

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#3970]
`gnrc_rpl` seems to multicast DIOs over all interfaces, though `gnrc_rpl_init` expects an interface as parameter and sets the RPL-nodes multicast address only for that interface. An easy fix would be to set the interface in the `gnrc_rpl_dodag_t` struct and use it in `gnrc_rpl_send()` to generate a `gnrc_netif_hdr` that addresses that interface.

**Comment by OlegHahm** [comment]
Off-topic: what's the difference between the `network` and `NSTF` label these days?

**Comment by authmillenon** [comment]
I generally set `NSTF` for all gnrc related stuff (we might need to rename it), and `network` for all network stuff in general

**Comment by A-Paul** [comment]
Hi @authmillenon, is this fixed by #3972 or is it still an issue.

**Comment by authmillenon** [comment]
AFAIK no. #3972 did not fix this issue, it just made usage of multiple interfaces possible without crashing due to this bug.

**Comment by OlegHahm** [comment]
@cgundogan, is this something that should into the release notes as a known issue?

**Comment by cgundogan** [comment]
@authmillenon this should be fixed now, can you verify?
