### ISSUE TITLE
Hitting assert when disabling `6lo` on interface (iotlab-m3)

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#4027]
When issuing `ifconfig 7 -6lo` on an iotlab-m3 hits the assert in [gnrc_sixlowpan_nd.c#L66](https://github.com/RIOT-OS/RIOT/blob/ae46d5d6a030ff1237d0263da68999f566fb2015/sys/net/gnrc/network_layer/sixlowpan/nd/gnrc_sixlowpan_nd.c#L66)

**Comment by OlegHahm** [comment]
Seems sensible to me.

**Comment by OlegHahm** [comment]
Configuring this at runtime seems rather pointless to me.

**Comment by cgundogan** [comment]
can you elaborate? the `6lo` option should be removed for these cases then .. otherwise this is not user friendly (:

**Comment by OlegHahm** [comment]
Yes, it should be removed.

**Comment by authmillenon** [comment]
I also would vote to remove the `6lo` flag from `ifconfig`

**Comment by authmillenon** [comment]
(it made sense when this wasn't configured automatically. Now it is, so just throw it out.)

**Comment by authmillenon** [comment]
See #4028 in case this was missed.
