### ISSUE TITLE
cpu/atmega2560: gpio_* behaves incorrectly for PORTn addresses > 0xFF

### ISSUE THREAD

**Issue by danielamkaer** [RIOT-OS/RIOT#4046]
Due to truncation of return value in _ddr_addr and _pin_addr in cpu/atmega2560/periph/gpio.c

**Comment by kaspar030** [comment]
@danielamkaer no need to open an issue if you've already got a PR that fixes it. ;)

**Comment by danielamkaer** [comment]
didn't know, thanks :)

**Comment by kaspar030** [comment]
I'll close this in favor of #4047.
