### ISSUE TITLE
Timer for ek-lm4f120xl are not working correctly

### ISSUE THREAD

**Issue by dkm** [RIOT-OS/RIOT#4077]
Using timer (directly or though xtimer) on this board always ends up with deadlock immediately.
Hardware timers are incorrectly configured, leading to incorrect interface implementation (eg. us_per_tick in timer_init).

I'll send a PR that should hopefully fix this (at least, my few tests are OK).

**Comment by Mouatez** [comment]
+1

**Comment by gebart** [comment]
Also, see #4040 when refactoring the timer periph implementation. I hope the proposed API change will be merged soon.

**Comment by dkm** [comment]
@gebart I'll hapilly adapt the code when the interface change. I've opened a PR for the branch in its current state.

**Comment by Mouatez** [comment]
cool!
