### ISSUE TITLE
vtimer: Replace vtimer usage in existing code by xtimer

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4093]
This will eliminate the vtimer_compat module.

**Comment by lebrush** [comment]
@gebart this can be closed, right? There are no more references to `vtimer` in the code...

**Comment by gebart** [comment]
Yeah, finally! :)

**Comment by miri64** [comment]
Whoop whoop :smile:

**Comment by kaspar030** [comment]
Over half a decade of bad design finally gone! :smile:
