### ISSUE TITLE
error : No source available for "0x1fff37b8

### ISSUE THREAD

**Issue by ksdperera** [RIOT-OS/RIOT#4105]
Hi All,

I just follow this tutorial : https://github.com/…/Using-the-Eclipse-IDE-for-C-and-CPP-De…

for stm32f4discovery board.
flashing work fine but when I'm trying to debug I got this error : No source available for "0x1fff37b8".

Plz someone who are familiar about RIOT OS use with Eclipse IDE,
I need a big favor from you!

Thank you

**Comment by OlegHahm** [comment]
@BytesGalore, @josephnoir, any ideas?

**Comment by DipSwitch** [comment]
Please validate the BOOT0 and BOOT1 configuration, it seems the processor is running from the System memory + OTP section.

**Comment by BytesGalore** [comment]
@DipSwitch thx for the hint, I will try to reproduce the misbehaviour as you described tomorrow (I don't have the (no) board around now)

**Comment by ksdperera** [comment]
@DipSwitch thanx for the solution, It was debug without error after done the following BOOT0 and BOOT1 configuration. 
BOOT1 = x BOOT0 = 1  Main flash memory selected as boot space.
![boot_pins_select](https://cloud.githubusercontent.com/assets/5366557/10671965/ffe1543c-790a-11e5-993c-fafb73f58b4d.jpg)
