### ISSUE TITLE
udp: possible unaligned acces in gnrc_udp_hdr_build()

### ISSUE THREAD

**Issue by daniel-k** [RIOT-OS/RIOT#4185]
```c
gnrc_pktsnip_t *gnrc_udp_hdr_build(gnrc_pktsnip_t *payload,
                                   uint8_t *src, size_t src_len,
                                   uint8_t *dst, size_t dst_len)
```

has `uint8_t *` arguments that will be dereferenced as `uint16_t *` which can lead to an unaligned access and the documentation doesn't warn the user.

**Comment by authmillenon** [comment]
dccp:

**Comment by authmillenon** [comment]
I would prefer if the header build function would use the actual types BTW.

**Comment by miri64** [comment]
Fixed in https://github.com/RIOT-OS/RIOT/pull/5118
