### ISSUE TITLE
tests/xtimer_*: add README

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/RIOT#4204]
It would be nice to have a small README for all xtimer tests. Something like the idea about the test and a rough overview of the happening as well as a short description about outcome.

**Comment by PeterKietzmann** [comment]
@A-Paul AFAIK you spend a lot of time on testing timers the last weeks. You think it's useful to have a small README or it it documented by now? Didn't check it but I think you know best what to say about these tests

**Comment by miri64** [comment]
Ping?

**Comment by OlegHahm** [comment]
@A-Paul, @PeterKietzmann, any progress?

**Comment by PeterKietzmann** [comment]
Well, it was more meant as a feature **request** ;-)

**Comment by PeterKietzmann** [comment]
This issue is rather old and was opened in the initial days of xtimer where documentation wasn't barely in place. Nowadays nearly all tests have a README. Tests that don't provide one have clear statements about success/failure by their testrunner -> I'm closing this issue now
