### ISSUE TITLE
timex: macro names are misleading

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#4211]
Am I the only one that thinks the name of `SEC_IN_USEC`, `SEC_IN_MS`, `MS_IN_USEC`, and `USEC_IN_NS` are somewhat missleading?
1. They are inconsistent in itself. Some abbreviate "seconds" with `SEC`, some with `S`
2. Their values reflect the opposite of their name: there are 1000000 microseconds in a second, not 1000000 seconds in a microsecond; there are 1000 milliseconds in a second, not 1000 seconds in a microsecond; etc.

**Comment by BytesGalore** [comment]
I think it means **unit** representation in **other unit**, 
e.g. second represented in microseconds => `SEC_IN_USEC`

**Comment by authmillenon** [comment]
If you have to make something up (that's what I'm interpreting from your "I think it means …" ;-)) it isn't intuitive ;-).

**Comment by BytesGalore** [comment]
It felt correct for me but I was uncertain if I found the right terms to describe it :). 
But I agree with `S` vs `SEC` either the one or the other.
I vote to use the SI unit representation of time [1], so just `S`.

[1] http://physics.nist.gov/cuu/Units/units.html

**Comment by OlegHahm** [comment]
:+1: for renaming `USEC` to `US`, everything else is intuitive for me and renaming `SEC` to `S` seems to be more ambiguous to me.

**Comment by authmillenon** [comment]
Though the SI says otherwise I would prefer SEC, MSEC, USEC, NSEC, since US_IN_S looks a bit non-descriptive. @oleghahm can you explain the intuition? I still read it as SEC_IN_USEC = seconds in microseconds.

**Comment by gebart** [comment]
@authmillenon if you write it in code as
```c
123 * SEC_IN_USEC
```
you can read it aloud as "123 seconds in microseconds"

**Comment by OlegHahm** [comment]
exactly

**Comment by authmillenon** [comment]
I find that less intuitive and less mathematically sound than "123 times microseconds in seconds"

**Comment by Kijewski** [comment]
I'm with @authmillenon. In my head SEC_IN_USEC evaluates to 10^-6. There is 0.000001 seconds in a microsecond. But there are 10^6 microseconds in a second, so USEC_IN_SEC = 1000000.

I'd say: `#define CONV_S_US(X) (1000000ull * (X))`, convert seconds to microseconds.

**Comment by OlegHahm** [comment]
Can you find something less speaking? ;)

**Comment by OlegHahm** [comment]
Seems to be a personal thing: in my thinking a second is no container to be filled with mili- or microseconds.

**Comment by Kijewski** [comment]
@OlegHahm, `#define WOULD_YOU_PLEASE_BE_SO_KIND_AS_TO_CONVERT_SECONDS_TO_MILLISECONDS_FOR_ME(…) …`?

**Comment by OlegHahm** [comment]
awesome

**Comment by kaspar030** [comment]
I'm with @Kijewski and @authmillenon here.

I think we've gotten used to the old defines, but it hard to argue that

```123 * USEC_PER_SEC``` would less intuitive than ```123 * SEC_IN_USEC```.

**Comment by OlegHahm** [comment]
I'm fine with both as long as we don't go back to macro functions here.

**Comment by kaspar030** [comment]
@Kijewski @authmillenon would you also prefer ```USEC_PER_SEC``` over ```USEC_IN_SEC```?

**Comment by authmillenon** [comment]
I'm fine with either.

**Comment by Kijewski** [comment]
I like `USEC_PER_SEC` :+1:

**Comment by haukepetersen** [comment]
ongoing discussion, will hopefully be solved by 2016.07

**Comment by kYc0o** [comment]
@gebart I have the impression that on one of your PRs you addressed this issue. Am I wrong?

**Comment by gebart** [comment]
@kYc0o I don't remember changing this

**Comment by kYc0o** [comment]
Ok let's postpone it then.

**Comment by miri64** [comment]
Clearing milestone because there doesn't seem to be much traction behind this family of issues.

**Comment by OlegHahm** [comment]
Was there a consensus?
