### ISSUE TITLE
ping6 missing from Routing/Networking Examples

### ISSUE THREAD

**Issue by msolters** [RIOT-OS/RIOT#4214]
Due to the replacement of `vtimer` with `xtimer` in https://github.com/RIOT-OS/RIOT/commit/5fb104160edae3e0fe0d40c33268d3dff28d57a5, the `ping6` command is not being included in applications that expect it (such as the gnrc_border_router, gnrc_networking examples).  This is due to the module checking logic [here](https://github.com/RIOT-OS/RIOT/blob/7797bb438d6c421d2fd96afaa1011eb2195782be/sys/shell/commands/shell_commands.c#L93) and [here](https://github.com/RIOT-OS/RIOT/blob/7797bb438d6c421d2fd96afaa1011eb2195782be/sys/shell/commands/shell_commands.c#L185).

If I understand this correctly, we need to change those rules to rely on `MODULE_XTIMER`, and therefore then we must refactor [sc_icmpv6_echo.c](https://github.com/RIOT-OS/RIOT/blob/master/sys/shell/commands/sc_icmpv6_echo.c) in terms of XTIMER rather than VTIMER.

I suppose this is just a subset of https://github.com/RIOT-OS/RIOT/issues/4093.

**Comment by authmillenon** [comment]
Should be fixed by #4210.

**Comment by authmillenon** [comment]
In the meantime: just add vtimer to your application's modules.

**Comment by msolters** [comment]
:100:

**Comment by PeterKietzmann** [comment]
#4210 was merged so I'll close this one
