### ISSUE TITLE
xtimer: xtimer_msg_receive_timeout() defined but not implemented

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#4219]
Though it is defined in `xtimer.h`, there is no implementation for `xtimer_msg_receive_timeout()` in `xtimer.c`.

**Comment by DipSwitch** [comment]
Double #3999 I'll close mine.

**Comment by authmillenon** [comment]
Can someone poke @kaspar030 then to finally fix this ;-)

**Comment by DipSwitch** [comment]
Still waiting =)
