### ISSUE TITLE
POSIX sockets: implement (p)select

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4222]
For the sake of ease porting libraries based on POSIX sockets (e.g. libcoap, ccn-lite...) an implementation of the `select()` function for synchronous I/O multiplexing would be very helpful.

**Comment by Kijewski** [comment]
I would rather say [`poll()`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/poll.html), because the API of [`select()`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/select.html) is very difficult to use or even understand.

**Comment by OlegHahm** [comment]
Nevertheless it is required for the above mentioned examples.

**Comment by kaspar030** [comment]
#4103 might be used to efficiently implement this.

**Comment by authmillenon** [comment]
Might it make sense to have that of conn, too?

**Comment by OlegHahm** [comment]
@kaspar030, maybe.

@authmillenon, I sense that we need to rethink conn a little bit, but in general, yes.

**Comment by kaspar030** [comment]
Closed in favour of #7801.
