### ISSUE TITLE
toolchain directory

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#4254]
Just stumbled once more over the `RIOTDIR/toochain` folder. Does anyone use this and/or is the included toolchain tested and up to date? 

I'd like to propose the following: Let's remove this folder (together with the compile scripts in `dist/tools/toolchains/` from RIOT master and dependent if they are still used either move them to a separate toolchain repo or drop support for them.

Any opinions on this?

**Comment by OlegHahm** [comment]
Sounds good to me.

**Comment by gebart** [comment]
It has something to do with the qemu-i386 platform, I don't remember the details.

**Comment by OlegHahm** [comment]
That's why I assigned [Mr. x86](https://github.com/kijewski)

**Comment by Kijewski** [comment]
Used in the precompiled newlib: [boards/x86-multiboot-common/Makefile.include](https://github.com/RIOT-OS/RIOT/blob/7b10e59ef3ef37cde032ddcc4c25b74f781d7428/boards/x86-multiboot-common/Makefile.include).

**Comment by haukepetersen** [comment]
I see, in this case I think it makes sense to keep it. I consider this solved -> closing the issue.
