### ISSUE TITLE
Create NTP client

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4260]
NTP is widely used for synchronizing clocks over the Internet. Many IoT applications need a valid system time in order to coordinate with other nodes and to organize data.

An NTP client needs to be able to precisely measure and adjust the system time in order to achieve a good synchronization. It may also be worthwhile to investigate gettimeofday etc.

**Comment by OlegHahm** [comment]
I think NTP is a poor choice for constrained node networks that operate mostly over low-power wireless links. A lof of work has been done in this domain for designing more efficient (and most of the time more precise) protocols, such as gtsp or pulsesynch. See also: https://github.com/RIOT-OS/RIOT/pull/1538

**Comment by miri64** [comment]
An [SNTP](https://tools.ietf.org/html/rfc5905#section-14) implementation is our project for the [Ladies that FOSS hackathon](https://www.wikimedia.de/wiki/Ladies_that_FOSS)

**Comment by miri64** [comment]
Fixed ;-)

**Comment by miri64** [comment]
(see #6020)
