### ISSUE TITLE
Performance of random numbers 

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/RIOT#4263]
I don't know if this is known behaviour, neither I looked at the algorithm.  This is just reporting! The computation time of [`genrand_uint32`](https://github.com/RIOT-OS/RIOT/blob/master/sys/random/mersenne.c#L121) has peaks sometimes. While it takes mostly about some us, one or two of 1000 computations take like hundreds (~300) of us. As @kaspar030 presented  an alternative in #4079, I assign him.

Please note that the code is not developed especially for RIOT. Feel free to close the issue!

**Comment by gebart** [comment]
Mersenne twister will have to perform some more computations once every 625 iterations IIRC.

**Comment by PeterKietzmann** [comment]
Seems to be a known issue. Alternative is on its way.

**Comment by OlegHahm** [comment]
At least for me that was an unknown fact and since @kaspar030's PR is not yet merged I would prefer to keep this open.

**Comment by PeterKietzmann** [comment]
It is and `minstd` acts quite efficient
