### ISSUE TITLE
auto_init_netif_* modules always use the 'nomac' module

### ISSUE THREAD

**Issue by rousselk** [RIOT-OS/RIOT#4275]
When using the `auto_init_gnrc_netif` module, this one initialize the radio transceiver, but also automatically starts the `gnrc_nomac` module.

This is quite annoying for testing new MAC protocols, since you have to initialize the network machinery in your own application to be able to use your own MAC protocol module. (See the test applications I made in PR #4180 and #4184.)

A way to configure which MAC layer to initialize with `auto_init_gnrc_netif` and use would be a very useful addition.

Unfortunately, I won't have the time to design and implement such a mechanism now.

**Comment by haukepetersen** [comment]
Agreed, the mac layer should be configurable through auto_init. I think we should be able to find a concept here...

**Comment by haukepetersen** [comment]
postponed as we won't solve this for this release

**Comment by kYc0o** [comment]
and postponed again... maybe @zhuoshuguo or @miri64 can have an idea?

**Comment by miri64** [comment]
`gnrc_nomac` isn't a thing anymore
