### ISSUE TITLE
shell: shell commands for random module(s)?

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#4291]
Just has this thought when looking through the code of #4287:

Why again has the random module(s) its/their own shell command? Having them in a test app might make sense, but having these (on its own rather useless) shell commands in all apps that use shell commands seems like wasted memory to me... 

I would tend to move the shell commands to a specific test application!

**Comment by kaspar030** [comment]
totally +1.

**Comment by kaspar030** [comment]
But assigning me - so you want me to do this? :)

**Comment by authmillenon** [comment]
I talked with @mehlis about this way back. The reason is, that there is no seed-initialization currently. #3425 would remove the need for the shell commands.

**Comment by kaspar030** [comment]
We should come up with a way to use random events (button presses, incoming network replies, ...) to seed our randomness...

**Comment by OlegHahm** [comment]
You're talking about https://github.com/RIOT-OS/RIOT/issues/3221?

**Comment by authmillenon** [comment]
That's why I started #3425 do give a starting point for that (hardware-randomness if available, xtimer + cpuid if available, etc.). It's better than nothing (or a shell command, that only can be called after start-up).

**Comment by OlegHahm** [comment]
Well, actually, I remember that we discussed this question already a couple of times back in good ol' µkleos days - but always without finding a good answer to the question how to determining a good seed.

**Comment by kaspar030** [comment]
@OlegHahm I was thinking of something like #4294.

**Comment by haukepetersen** [comment]
ok, initializing the seed via shell is something I did not think of, so there we have a right to exist for the shell command - that was the answer I was looking for. 

How about to close this issue for now and remove the shell command once we have agreed on a 'seed'-concept?

**Comment by kaspar030** [comment]
Yeah, one more solved issue is a good thing. :)
