### ISSUE TITLE
Uncrustify all files for release?

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#4363]
Should we run uncrustify over the whole repo before the release? This would have the advantage, that we can make style checks in CI afterwards.

**Comment by kaspar030** [comment]
Not sure I like all of the uncrustify settings. E.g., it uses tabs to align static array initializers.

**Comment by gebart** [comment]
Let's fix those settings first so it doesn't mess up the code style.

**Comment by OlegHahm** [comment]
Actual, I'm against major code formatting changes. Most of the code is in good shape anyway and it will just screw up git blame results.

**Comment by x3ro** [comment]
@authmillenon does have a point though. We'd have to do this at some point if we ever want to do automated style checks. If we manage to configure uncrustify such that it mostly matches the style of the current code, the changes might be relatively few, right? 

I'm not advocating this for the next release, but maybe we should check the impact of running uncrustify over all the source and then decide on whether or not automated style checks are worth it :)

**Comment by OlegHahm** [comment]
>  if we ever want to do automated style checks

I'm still not convinced if this is a reasonable goal. There are many good reasons to deviate from style conventions.

Nevertheless, I won't object if someone wants to spend some time in improving uncrustify's config (or proposes a different tool).

**Comment by OlegHahm** [comment]
I removed the milestone, because I consider the probably very huge changeset for this proposal as undoable within the given timeframe. Also, there is no urgency here.

**Comment by haukepetersen** [comment]
if I remember the discussion in #4792 correctly, there were not too many friends (me included) in just running uncrustify over `core`, as there are some places, where manual fomatting just yield better readable results. So can we take the outcome of that discussion and apply it to this issue also?

**Comment by authmillenon** [comment]
I would say yes, but maybe it is a good idea to look over the code regardless. I think some issues are still in core.

**Comment by haukepetersen** [comment]
> I think some issues are still in core.

I completely agree, but I am just not a big fan of simply trusting automated tools to do the job better than a manual review :-)

**Comment by authmillenon** [comment]
Dito :D. But doing it and looking at the output is still something we could do for a release.

**Comment by A-Paul** [comment]
@haukepetersen, they can do better at certain tasks because tools don't get tired/bored or lack concentration. But their use should be *well* prepared. So, I agree that "simply trusting automated tools" isn't a good idea.

Before producing such a massive impact to the whole code base, if ever, we have to have an almost complete and unambiguous set of rules all can stick to. That is the part a tool can't solve for you.

Style check maybe nice at some point but it is not essential. So, no hurry.

**Comment by haukepetersen** [comment]
> we have to have an almost complete and unambiguous set of rules all can stick to

Yepp, and that is the problem :-)

But I agree, let's work toward this, but not for this release.

**Comment by kYc0o** [comment]
And not for this one either... :/ hopefully the next?

**Comment by jia200x** [comment]
> if I remember the discussion in #4792 correctly, there were not too many friends (me included) in just running uncrustify over core, as there are some places, where manual fomatting just yield better readable results. So can we take the outcome of that discussion and apply it to this issue also?

Maybe a dist/tools/uncristify command with several blacklist entries? (e.g core or specific files that won't need uncrustify)
Since most reviews are style issues, running uncrustify on most PRs could help to reduce reviewing time and merge faster.

**Comment by miri64** [comment]
See https://github.com/RIOT-OS/RIOT/pull/8519#issuecomment-529812982
