### ISSUE TITLE
periph/timer: API inconstency

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4371]
Reviewing #4089 I realized that `periph/timer` API seems to be inconsistent. `timer_init()` returns 0 on success, while all other functions return 1 on success. I think all periph functions which just return a boolean value should return the same one. Ideally this would be rather a macro like `PERIPH_SUCCESS` than a literal.

**Comment by dkm** [comment]
same kind of inconsistency exists in nrf24l01p driver : some functions return 0 (preload, unregister, ...) on success, some return 1 (set_channel, ...).

**Comment by PeterKietzmann** [comment]
@dkm you're right. As stated in #4389 I think the whole driver could need some rework. But it's not part of this issue :-)

**Comment by PeterKietzmann** [comment]
@dkm you're right. As stated in #4389 I think the whole driver could need some rework. But it's not part of this issue :-)

**Comment by haukepetersen** [comment]
all driver interfaces except `spi` and `i2c` have been reworked, and including these two they all have the same return values.

@OlegHahm: is this enough to close this PR, or do you insist on some macro on top of this?

**Comment by A-Paul** [comment]
It may be a surprise, ;-) but I still recommend using macros. Not sure if there is need to list all the advantages...
I might help finding names and applying them.
Preferably after this release.

**Comment by haukepetersen** [comment]
I don't care (though I am not a fan of it). So lets keep this issue open.

**Comment by OlegHahm** [comment]
1. I don't see the initial issue solved. `timer_init()` still returns 0 on success, while the other functions return 1 on success.
2. I agree with @A-Paul here, that macros would be preferable (and would help to avoid such a confusion).

**Comment by kYc0o** [comment]
Still inconsistent. Let's move it for the next release.

**Comment by miri64** [comment]
This somehow flew under my radar. Postponed.
