### ISSUE TITLE
POSIX sockets: open socket is bound to a specific thread

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4388]
With the `gnrc_conn` based implementation of POSIX sockets the socket is bound to a specific thread, e.g. reading from it will only work for the the thread that performed the binding (implicitly or explicitly). I think the most promising solution to solve this would be a thread-decoupled message queue as @kaspar030 or @authmillenon proposed.

**Comment by haukepetersen** [comment]
postponed, same as #4474

**Comment by kYc0o** [comment]
Sadly, postponed again.

**Comment by miri64** [comment]
Fixed by #5772 and my [currently WIP posix socket port to sock](https://github.com/miri64/RIOT/tree/posix/enh/use-sock-for-sockets)

**Comment by OlegHahm** [comment]
wontfix

**Comment by miri64** [comment]
Shouldn't we at least wait until #5772 got merged?

**Comment by OlegHahm** [comment]
No strong opinion. I saw this issue as conn related (part of the description) and hence as a wontfix.

**Comment by miri64** [comment]
Closed via #6004.
