### ISSUE TITLE
gnrc_sixlowpan: Header order or UDP and IPv6 swapped

### ISSUE THREAD

**Issue by DipSwitch** [RIOT-OS/RIOT#4397]
One would expect that when you receive a packet the header order would be like: `data -> UDP -> IPv6`

However the header is sometimes swapped to: `data -> IPv6 -> UDP`
To search the proper header one must `LL_SEARCH_SCALAR`

I can't reproduce this behavior on my development board STM32F1xx with an AT86RF212B but on the SAM R21 Xpro this seems to happen more often.

More info about this issue can be found on: https://github.com/RIOT-OS/RIOT/pull/3911#issuecomment-157683297

Work around for the problem can be found here: https://github.com/OlegHahm/RIOT/commit/41569b9657e61266aebc6f8590c75c37b0a10cf3

**Comment by authmillenon** [comment]
Correct me if I'm wrong, but wasn't that a problem related to #4189? Shouldn't this be fixed there before it got merged?

**Comment by OlegHahm** [comment]
I think it's not 100% clear if it is related to #4189, but we should definitely check.

**Comment by authmillenon** [comment]
Found the bug: https://github.com/RIOT-OS/RIOT/pull/4189/files#r47666253

**Comment by OlegHahm** [comment]
Nice job!

**Comment by DipSwitch** [comment]
Whoohoo, good going! :D

**Comment by DipSwitch** [comment]
So this can be closed?

**Comment by authmillenon** [comment]
No, the PR isn't merged yet.
