### ISSUE TITLE
unsigned char casting in uart_getchar() implementations 

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#4409]
The signature is `int uart_getchar(FILE *)`. The result value should not be casted to an `(int)` (the automatic cast), but `(int) (unsigned char)` == `(unsigned char)`. Otherwise problems with UTF-8 or binary input may occur.

**Comment by authmillenon** [comment]
As far as I can see this is an Arduino-related issue, right?

**Comment by authmillenon** [comment]
```
$ git grep uart_getchar
boards/arduino-mega2560/board.c:static int uart_getchar(FILE *stream);
boards/arduino-mega2560/board.c:static FILE uart_stdin = FDEV_SETUP_STREAM(NULL, uart_getchar, _FDEV_SETUP_READ);
boards/arduino-mega2560/board.c:int uart_getchar(FILE *stream)
```

**Comment by Kijewski** [comment]
Actually, I don't know anymore. The only occurrence of `uart_getchar()` is implemented correctly: [board.c#L80](https://github.com/RIOT-OS/RIOT/blob/b5497c3be43bdfecb0fb10e84bffbbd76d7a1ca1/boards/arduino-mega2560/board.c#L80).

Closed because obsolete.
