### ISSUE TITLE
doc: gnrc netapi: get/set documentation unclear

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4416]
The documentation for `gnrc_netapi_get()` and `gnrc_netapi_set()` states for the return value: `value returned by the @ref GNRC_NETAPI_MSG_TYPE_ACK message`. This seems to be a rather useless information for netapi user. IMO the documentation should clear state which values one can expect and how to interprete them.

**Comment by authmillenon** [comment]
See #4425
