### ISSUE TITLE
Enable CCA updating on OpenMote board

### ISSUE THREAD

**Issue by aeneby** [RIOT-OS/RIOT#4432]
Currently, UPDATE_CCA is not defined in the board header file for the OpenMote, which means the memory structure for the cc2538's Customer Configuration Area will not be included in the resulting binary when building for this platform. This means that flashing an image may disable the bootloader, making it impossible to flash a new image via the OpenBase board (without first erasing the flash via JTAG).

UPDATE_CCA is already defined for the ReMote and cc2538dk boards; it should be a simple matter of doing the same thing for the OpenMote.

**Comment by hexluthor** [comment]
Was fixed a while ago. Closing the issue.
