### ISSUE TITLE
OpenMote Makefile should support flashing via cc2538-bsl tool during "make flash"

### ISSUE THREAD

**Issue by aeneby** [RIOT-OS/RIOT#4434]
The cc2538dk board supports flashing via the dist/tools/cc2538-bsl/cc2538-bsl.py script directly from the Makefile. In fact, it's the default flashing method for this platform - you need to explicitly specify if you want to flash via JTAG instead using "PROGRAMMER=jlink".

This capability (and default behaviour) should be carried across to the OpenMote Makefile too.

**Comment by thomaseichinger** [comment]
@aeneby Thanks for bringing this up. For consistency I certainly prefer your proposal, last time I checked though, the OpenMote on my desk was not flashable with this script although I used the "pin-magic". Do you know if there are different versions of the platform?

**Comment by aeneby** [comment]
@thomaseichinger I have successfully flashed RIOT to my OpenMote using the cc2538-bsl script manually, via the OpenBase board. AFAIK there is only one version of the OpenMote platform right now. I will try to provide a patch for you.

**Comment by thomaseichinger** [comment]
Fixed by #4460.
