### ISSUE TITLE
core: add power management functions

### ISSUE THREAD

**Issue by punchcard60** [RIOT-OS/RIOT#4449]
The idle thread should take the MCU to the lowest power state consistent with the wakeup requirements of all running threads. Threads could change their default requirements through lpm_set_wakeup(int max_wakeup_time_microseconds).

**Comment by OlegHahm** [comment]
Thanks for bringing this up, but I believe this is a duplicate of https://github.com/RIOT-OS/RIOT/issues/2927.

If you object, we can reopen.
