### ISSUE TITLE
Consider renaming "openmote" board in-tree to something less generic

### ISSUE THREAD

**Issue by aeneby** [RIOT-OS/RIOT#4459]
According to the developers[1], OpenMote will be coming out with new versions of their hardware during 2016. This means there will be several different versions of OpenMote hardware, so "openmote" is probably too generic to use in-tree. I would suggest "openmote-cc2538" for the current (and so far only) model. Perhaps it might even be worth including the board revision letter.

[1] http://permalink.gmane.org/gmane.os.contiki.devel/24657

**Comment by emmanuelsearch** [comment]
Sounds good to me.

**Comment by OlegHahm** [comment]
No objections either.

**Comment by hexluthor** [comment]
Agree and the change has already been merged, so I'm closing this issue.
