### ISSUE TITLE
conn: Wishlist for Redo

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#4474]
After a few month of working with `conn` we found some short-comings to it that need to be fixed in later iterations. This issue tries to collect these.

- connection-less support for connection-less protocols (goal: easy integration of simple lightweight stacks)
- connection-bound support for connection-less protocols if stack requires connections (goal: easy integration of full-featured stacks (e.g. lwIP))
- thread-shared connections (see https://github.com/RIOT-OS/RIOT/issues/4388)
- asynchronous send/receive (select)
- non-blocking read/write
- options

... Feel free to add to this

**Comment by DipSwitch** [comment]
Non-blocking read/write would be nice aswell :) although this could also be solved with select.

I think however that epoll would be simpler to implement than select, and could also be faster. Aswell as in the kernel / stack implementation as in application implementation.

**Comment by authmillenon** [comment]
`epoll` sounds indeed nice (and could be implemented as well), but the problem is that most libraries still use `select()`. So purely from a porting perspective we need to implement it at some point anyway.

**Comment by authmillenon** [comment]
The discussion regarding epoll was also held in #4222.

**Comment by kaspar030** [comment]
- remove redundant address family / address length parameters (former implies the latter)
- UDP needs a way to specify source / target interface for link-local and multicast

**Comment by authmillenon** [comment]
> * remove redundant address family / address length parameters (former implies the latter)

Only valid for IP-only protocols AFAWK, but true.

> * UDP needs a way to specify source / target interface for link-local and multicast

That might be do-able with options for a conn object (setsockopts style). Another feature we might need.

**Comment by haukepetersen** [comment]
postponed.

**Comment by kYc0o** [comment]
Postponed again...

**Comment by miri64** [comment]
Realized in #5758.
