### ISSUE TITLE
pkg: tlsf: initialize memory pool early

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4490]
TLSF and should be initialized with a memory pool for its heap early on. Preferably this could be done inside the CPU startup. This would allow using TLSF's malloc implementation for basically every other module (including BSP or libc stuff) and choosing an appropriate size for the heap (i.e. RAM minus stack usage).

**Comment by authmillenon** [comment]
That's also interesting in regards to lwIP. However, they bring their own version of pool-based memory allocation. We need to look into this, especially if we want to use e.g. CCN-lite together with lwIP.

**Comment by OlegHahm** [comment]
I think in the long-run we should do something similar to PRNG for malloc and offer various alternative dynamic memory allocations. For CCN-Lite I was even thinking about reusing (misusing) pktbuf.

https://github.com/emeryberger/Malloc-Implementations may be a good starting point.

**Comment by haukepetersen** [comment]
wont be done for this release -> postponed

**Comment by kYc0o** [comment]
And postponed again...

**Comment by kaspar030** [comment]
+1

Maybe using the linker variables to find out about unused memory areas?

**Comment by OlegHahm** [comment]
Yes, if I remember correctly that was also an approach that @haukepetersen and me discussed some time ago.

**Comment by jcarrano** [comment]
Please see https://github.com/jcarrano/RIOT/blob/tlsf-init-experiments/examples/tlsf-init-test/main.c.
It seems to solve the problem in both embedded (only tried the samr21) and native. ATM it's a rough sketch.

Interestingly, newlib's `preinit_array` is a cross file array!!

**Comment by jcarrano** [comment]
Duplicate of #5796
