### ISSUE TITLE
core: mutex_t::val could memorize holding thread id, not a boolean

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#4494]
For debugging purposes it would be nice if `mutex_t::val` stored the current thread id, not a boolean. The test if the mutex is held would remain the same: `mutex_t::val == 0` → `mutex_t::val == KERNEL_PID_UNDEF` (`KERNEL_PID_UNDEF == 0`), so I see no extra overhead. The locking would be no more difficult either: `atomic_set_to_one(&mutex.val)`(which uses atomic_cas)  → `atomic_cas(&mutex.val, KERNEL_PID_UNDEF, sched_active_pid)`.

**Comment by OlegHahm** [comment]
Makes sense to me. I think to remember that it was like that in older versions.

**Comment by kaspar030** [comment]
It was. I don't remember why we changed that.

ISR's would need special handling when locking a mutex.

**Comment by Kijewski** [comment]
Tracked it down to this "ancient" pre-RIOT diff: https://github.com/RIOT-OS/RIOT/commit/8b242c74a800a1281466179ec8e682b13fff1178#diff-bade665089346285998d082f3857199aL49

**Comment by Kijewski** [comment]
Closed. Obsolete.
