### ISSUE TITLE
6lo: Implementation of LOWPAN_BC0

### ISSUE THREAD

**Issue by DipSwitch** [RIOT-OS/RIOT#4526]
I was looking for the 6LowPAN broadcast header. Is it currently implemented to avoid flooding of the network? 

https://tools.ietf.org/html/rfc4944#page-23

**Comment by authmillenon** [comment]
No, currenlty it is not. AFAIK this is only used in mesh-under mode (which isn't implemented either). Correct me if I'm wrong.

**Comment by DipSwitch** [comment]
Wait that makes sense, with mesh-over you can use the TTL of the IPv6 packet... I'll get some more coffee and close this in the mean time ;)
