### ISSUE TITLE
native: more periph timers

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4561]
Currently native supports only one periph timer using POSIX interval timers. In order to run, e.g., the OpenWSN TiSCH implementation on native, more timers are required.

**Comment by kaspar030** [comment]
@OlegHahm So xtimer is not accurate enough? Are you sure about that? The overhead of xtimer on native is waaay less than native's periph timer inaccuracy (caused by linux' scheduling).

**Comment by OlegHahm** [comment]
The current implementation needs to reset the timer, that's why it uses a dedicated periph timer.

**Comment by kaspar030** [comment]
> The current implementation needs to reset the timer

Could you elaborate? Maybe we can improve the API of xtimer.

**Comment by OlegHahm** [comment]
Maybe @thomaseichinger can.

**Comment by haukepetersen** [comment]
@OlegHahm: the `timer_reset` function is not part of the periph interface anymore. Seems that is also a problem for OpenWSN?

**Comment by miri64** [comment]
Soooooo how is the situation?

**Comment by OlegHahm** [comment]
I still think that multiple periph timers would be a nice feature for native, but the urgent need for this feature vanished for now.

**Comment by kaspar030** [comment]
IMO there's no need for this, applications should use high-level timers (xtimer). The use case for direct periph timers (very high precision timers) is moot on native anyways, no software timer can beat the host scheduler...
