### ISSUE TITLE
kinetis/rtc: move to periph_common?

### ISSUE THREAD

**Issue by basilfx** [RIOT-OS/RIOT#4565]
It seems that [kinetis/rtc](https://github.com/RIOT-OS/RIOT/blob/master/cpu/kinetis/periph/rtc.c) is generic and reusable for CPUs with only an RTT. I need the same implementation for the efm32 port. Would it be an idea to move it to drivers/periph_common, in a similar way it was done for the generic SPI methods?

I could create a PR if needed.

**Comment by gebart** [comment]
Good idea!

**Comment by kaspar030** [comment]
+1!

Please see  #2538. Maybe we could even move it into sys/? Or drop it completely in favour of a simple epoch-like "real time" and rely on standard C library functions?

IMHO the whole "struct tm" based interface is way to inefficient for our little machines...

**Comment by basilfx** [comment]
I created a PR for now. Since it was not much work I don't care what happens with it :-)

**Comment by miri64** [comment]
Since #4572 was closed I guess this is still an issue?

**Comment by gebart** [comment]
Yes
