### ISSUE TITLE
Is RIOT hard realtime and does it have a graphics stack?

### ISSUE THREAD

**Issue by UnixJunkie** [RIOT-OS/RIOT#4582]
Minix fails on both of these.

**Comment by kaspar030** [comment]
Hey,

On 01/06/2016 10:57 AM, Francois Berenger wrote:
> Minix fails on both of these.

Depending on the definition, the core of RIOT is hard realtime, and it
is possible to build hard realtime applications.

There's no graphic stack.

Kaspar

**Comment by LudwigKnuepfer** [comment]
@UnixJunkie If you have follow-up questions don't hesitate to post them (either here or on the mailing list `users@riot-os.org`). Closed because question was answered.
