### ISSUE TITLE
pkg: building relic with clang fails

### ISSUE THREAD

**Issue by thomaseichinger** [RIOT-OS/RIOT#4590]
To successfully build relic with clang these additional flags work as a workaround. `-Wno-gnu-zero-variadic-macro-arguments -Wno-newline-eof -Wno-unused-function` I did however didn't figure out how to introduce them without touching the boards Makefile or CMakeLists.txt. Adding them in `generate-cmake-xcompile.perl` didn't work.

**Comment by kYc0o** [comment]
Is this issue still present?

**Comment by kYc0o** [comment]
Well let's see for the next release if we can solve it.

**Comment by smlng** [comment]
was fixed by #6105 and is so again by #7785 (or #7780), so if one of the latter is merged this can be closed.
