### ISSUE TITLE
pkg ccn-lite: rebuild for different platforms

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4611]
Since ccn-lite uses its own Make system, it doesn't get recompiled when building the same application for different platforms, but requires a `make distclean`.

**Comment by authmillenon** [comment]
One reason more to use RIOT's build system ;)

**Comment by OlegHahm** [comment]
Which would require patch files. I try to avoid this as much as possible.

**Comment by authmillenon** [comment]
But with distclean that would mean to re-download the sources everyone. That's way worse IMHO.

**Comment by OlegHahm** [comment]
Agreed, a better workaround is on the way.
