### ISSUE TITLE
bug: destination-address error found with Samr21-xplained-pro experiments

### ISSUE THREAD

**Issue by ghost** [RIOT-OS/RIOT#4634]
Dear all, the attachment is a technical/experimental report for describing the Bug we found with RIOT wireless communication experiment on Samr21-xplained-pro boards.

In short, the bug is a “destination-address” error that will put the wrong destination address into the MAC layer head field when sending out, thus the intended receiver will disregard/drop the packet from the sender, resulting in communication fault.

But, after executing '''ifconfig'' to the RIOT shell, the outcome ''inet6 addr'' of the node is different to the ''Long HWaddr'' of the node. Is that normal? If the we use the ''inet6 addr'' of the receiver instead of the ''Long HWaddr'' for sending the packet, then, everything is normal.

Thus, if the ''inet6 addr'' of a device should be (is required to be) different to its ''Long HWaddr'', then, this founding shouldn't be called a bug. 

[RIOT communication Bug found with Samr21-xplained-pro experiments.pdf](https://github.com/RIOT-OS/RIOT/files/88672/RIOT.communication.Bug.found.with.Samr21-xplained-pro.experiments.pdf)

**Comment by cgundogan** [comment]
Could be related to #4215 but I cannot check right now
Am 13.01.2016 10:54 schrieb "shuguo" <notifications@github.com>:

**Comment by zhuosg** [comment]
In the experiment we conducted, the communication stack used the long MAC address, as indicated in the sniffer.

**Comment by thomaseichinger** [comment]
@zhuosg What you observed here is mentioned [in this section](https://tools.ietf.org/html/rfc4944#section-6). Namely the change of the "Universal/Local" when constructing the interface identifier.

**Comment by OlegHahm** [comment]
@zhuosg, are you okay with @thomaseichinger's explanation?

**Comment by cgundogan** [comment]
Did anyone else encounter this problem? The user is not available anymore.

**Comment by OlegHahm** [comment]
From the discussion I guess that @zhuoshuguo was the asking user. Am I correct?

**Comment by zhuoshuguo** [comment]
Yes, I am the asking user (asked by another account of mine, which has been deleted),  and I am OK  with @thomaseichinger's explanation. Thanks a lot!  Sorry for the late reply (didn't check emails related to the deleted account).
