### ISSUE TITLE
USB BLE HCI protocol

### ISSUE THREAD

**Issue by a3zzat** [RIOT-OS/RIOT#4684]
contributing to : "  USB Device Stack #3546 " 
RIOT don't have HCI for Bt\BLE so I will work on that.

![hci ble](https://cloud.githubusercontent.com/assets/15834509/12560246/ee8f7720-c399-11e5-828c-790f5a64b1ae.png)

**Comment by jfischer-phytec-iot** [comment]
Hello a3zzat, I refactor #3890 and have added support for multiple interfaces and samr21 (samd21), the new version is not published, so let me know please before you start with the work.

**Comment by a3zzat** [comment]
I will start working on implementing the HCI commands and events until you finish then we can link the code

**Comment by phani2410** [comment]
I am interested to work on BLE Protocols. Can you please suggest me, what are the relevant things to be learnt for working on this issue.

**Comment by PeterKietzmann** [comment]
@a3zzat, @phani2410 was there any progress since early 2016?

**Comment by PeterKietzmann** [comment]
No progress since Feb. '16 nor feedback since Nov. '17. Closing this one. Please re-open when planning to take up work again
