### ISSUE TITLE
sema: move volatile int to atomic_int_t

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#4689]
See https://github.com/RIOT-OS/RIOT/pull/4551#issuecomment-175105352

**Comment by authmillenon** [comment]
Not a bug, but an enhancement => moved to next release.

**Comment by kYc0o** [comment]
@miri64 this issue was solved by #4551 isn't it?

**Comment by miri64** [comment]
Nope, still volatile int.

**Comment by kYc0o** [comment]
ok let's postpone it then.

**Comment by miri64** [comment]
I overlooked this on Monday => Postponed.

**Comment by lebrush** [comment]
@miri64 is this still relevant?

**Comment by miri64** [comment]
Nope, your port removed this altogether
