### ISSUE TITLE
Eliminate redundant functions

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#469]
There are a lot of redundant functions in the code. Especially the ones concerning transceivers are multiple defined (in shell_command and several times in the network stack e. g.). PR #460 should stream line these multiple definitions into one module (among other things). But for the basic functionalities it may be makes sense to at least implement a get_set_handler for the transceiver communication similar to the one provided in #460 in the transceiver module itself.

**Comment by OlegHahm** [comment]
Pong.
