### ISSUE TITLE
drivers/lm75a: does not build

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4694]
This driver does not have any tests or demo application and is not compile tested by Travis. The driver itself contains a small main function that could be used as a test, but it won't compile for any platforms except lpc2387 because of an `#include "lpc2387.h"` line.

The driver does compile with the lpc2387 platforms if I add `USEMODULE += lm75a` to `examples/default/Makefile`

**Comment by miri64** [comment]
#3418 might be related.
