### ISSUE TITLE
stm32f4: UART DMA causes lockup in xtimer_drift test

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4716]
Current tests/xtimer_drift in master does not run for me on stm32f4discovery, it hangs after trying to start the first slacker thread.
Disabling DMA in the UART TX by commenting out code seem to make the problem go away.

I suspect there is a race between the main thread using printf/puts right before the thread_create call and the newly created thread also using printf immediately after creation.

**Comment by OlegHahm** [comment]
Related to https://github.com/RIOT-OS/RIOT/issues/4488?

**Comment by gebart** [comment]
no, after looking into this a bit further it seems like the problem is that periph/uart is not thread safe, it is just that we have not seen any symptoms until DMA was implemented in a driver.
