### ISSUE TITLE
net: gnrc: incorrect icmp reply checksum

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#4723]
Somehow an echo reply has incorrect checksum.

Setup: <linux ethos> <-> <6lbr ethos> <6l0> <-> <6lr>

PCAP: `http://www.schleiser.de/~kaspar/incorrect-checksum.pcapng`

**Comment by OlegHahm** [comment]
Can you upload to cloudshark?

**Comment by kaspar030** [comment]
https://www.cloudshark.org/captures/51a3ef392796

**Comment by OlegHahm** [comment]
thx

**Comment by OlegHahm** [comment]
So, this only happens when pinging IPv6 <-> 6LoWPAN (i.e. including a 6LBR)?

**Comment by kaspar030** [comment]
Yes, both pinging between linux<->6lbr and 6lbr<->6lr is working fine.

**Comment by OlegHahm** [comment]
Hm, ok, in this case I'm currently unable to test. Sorry.

**Comment by kaspar030** [comment]
Sometimes it happens with just linux<->ethos:

https://www.cloudshark.org/captures/28ec6d114009

(linux as fe80::1, RIOT as fe80::2, on riot "ifconfig <n> add fe80::2, fibroute add :: via fe80::1 dev <n>". 
Unfortunately, this doesn't always happen...

**Comment by gebart** [comment]
Maybe an uninitialized checksum variable or similar which just happens to
have the correct initial value most of the time?

**Comment by kaspar030** [comment]
Ok, this one really tricked me.

Turned out that in ethos on the linux side, I didn't disable all character conversion done by the serial driver. That made ethos replace all incoming 0x0A with 0x0D. That didn't really cause problems, other than that the source address of my 2001:db8:... was replaced with 2001:ad8:..., which I totally didn't spot in the wireshark dumps...

(bug found, bug killed, closing issue)

**Comment by OlegHahm** [comment]
hehe, nice catch
