### ISSUE TITLE
pkg/micro-ecc: Makefile patch race

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4788]
There's a race condition in the Makefile which means that running multiple builds of tests/pkg_micro-ecc (e.g. Travis buildtest) will fail with "file already exists" errors or similar because the patch has been applied already.

I don't know how to fix this, but it is very annoying when Travis fails unrelated to the actual change..

**Comment by OlegHahm** [comment]
https://github.com/RIOT-OS/RIOT/blob/master/pkg/micro-ecc/Makefile#L25 looks strange and unnecessarily complex to me.

**Comment by haukepetersen** [comment]
+1 for being annoyed...

**Comment by Kijewski** [comment]
Maybe use [flock](http://manpages.ubuntu.com/manpages/raring/man1/flock.1.html) like in [libfixmath/checkout.sh](https://github.com/RIOT-OS/RIOT/blob/60d44724199ee9ae9312f899bcf8fe4f22f39de5/pkg/libfixmath/checkout.sh)?

**Comment by Kijewski** [comment]
Oops.

**Comment by kaspar030** [comment]
I have a fix in #5018 (includes a commit that builds micro-ecc in BINDIR).

**Comment by kaspar030** [comment]
#5018 is in. @gebart this should be fixed then?

**Comment by gebart** [comment]
I guess so.
Does #5018 make the build system check out a fresh copy for every platform in make buildtest?

**Comment by kaspar030** [comment]
Yes... Working on it.

**Comment by miri64** [comment]
This should be fixed with #5018.
