### ISSUE TITLE
saul: Missing tests

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4817]
SAUL is currently not found anywhere in the tests directory. The only test we have today are the manual shell commands in examples/default

**Comment by haukepetersen** [comment]
how about this for starters: #4829

**Comment by haukepetersen** [comment]
#4829 does not provide unit tests, so providing these is still a todo...

**Comment by haukepetersen** [comment]
we wanted to leave this open until there are unit-tests for SAUL...
