### ISSUE TITLE
can I use the eclipse in windows to build the RIOT?

### ISSUE THREAD

**Issue by JayYangSS** [RIOT-OS/RIOT#4845]
I'd like to use the windows-OS to build RIOT in eclipse, what should I do? Do I must use Linux?

**Comment by OlegHahm** [comment]
Have you checked if https://github.com/RIOT-OS/RIOT/wiki/Build-RIOT-on-Windows-OS and https://github.com/RIOT-OS/RIOT/wiki/Using-the-Eclipse-IDE-for-C-and-CPP-Developers%2C-Howto answer your questions? In principle RIOT development is not tight to Linux and there are at least some developers using Mac OS, but using Linux as an development environment makes things easier. You may consider using a virtual machine for that.
