### ISSUE TITLE
Feature request: 6lo over Ethernet

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4857]
I just stumbled across https://tools.ietf.org/html/draft-droms-6lo-ethertype-request-00 and thought that transmitting 6lo directly over Ethernet (as opposed to ZEP encapsulation) might indeed be interesting to support for debugging. Now that we support Ethernet devices, this should actually be very easy to implement, I guess.

**Comment by authmillenon** [comment]
As far as I understand the draft this is just defining a ethertype for 6Lo and then use it. Pretty easy indeed.

**Comment by miri64** [comment]
Implemented in #4861 ;-)
