### ISSUE TITLE
Feature request: support IEEE 802.15.4 frame version 2

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#4858]
Since the IEEE 802.15.4-2015 standard is released a new frame format for 802.15.4, tagged as frame version 2, is defined. This is, e.g., required for the TSCH mode of 802.15.4 (or at least for 6TiSCH). Unfortunately, to the best of my knowledge, this frame version is not supported by any transceiver yet, so we would have to implement it in software. Since, AFAIK, the 2015 version of the standard is still not available for free, one might look into the [802.15.4e-2011](https://standards.ieee.org/findstds/standard/802.15.4e-2012.html) amendment.

**Comment by gebart** [comment]
The standard has been made available for free at http://standards.ieee.org/about/get/802/802.15.html in case anyone is interested in taking on this task.

**Comment by miri64** [comment]
With `gnrc_netif2` this can be handled GNRC-internally (as our frame building is at the moment as well), with a netopt to determine the frame version.

**Comment by benpicco** [comment]
Sci-Hub has all the standards btw :wink:

**Comment by maribu** [comment]
Ping?

**Comment by maribu** [comment]
PingyMcPingface?

**Comment by miri64** [comment]
@jia200x?

**Comment by jia200x** [comment]
I think this is not relevant anymore, as openDSME and openWSN already handle the new versions.

**Comment by maribu** [comment]
Then let's close this.
