### ISSUE TITLE
improve real-time documentation, find coding conventions

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#4872]
While it is certainly possible to create real-time applications with RIOT, depending on the definition and requirements, actual documentation and coding conventions are lacking.

We should come up with

a) conventions like "disabling IRQ's for less than N instructions is tolerable" (example)
b) document side effects caused by a)
c) document algorithmic implications on real-time requirements (e.g., "locking a mutex might traverse the list of currently locked threads")

...

**Comment by LudwigKnuepfer** [comment]
> Maybe it's more purposeful to provide some tool for the task of identifying the possible side-effects anyways.

**Comment by kaspar030** [comment]
> Maybe it's more purposeful to provide some tool for the task of identifying the possible side-effects anyways.

Interesting. You mean e.g., a static code analyzer beefed up to count critical section cycles?

**Comment by LudwigKnuepfer** [comment]
Something like that, yes.

**Comment by kYc0o** [comment]
any news on this? There's no milestone but a current issue is referencing this one, so maybe we need to put a milestone on this too.

**Comment by LudwigKnuepfer** [comment]
Do as you please.

**Comment by kaspar030** [comment]
Not much discussion here.
