### ISSUE TITLE
Using single RSSI_BASE_VALUE for all Atmel radios

### ISSUE THREAD

**Issue by kb2ma** [RIOT-OS/RIOT#4874]
Presently RSSI_BASE_VALUE is defined as -91 dBm in at86rf2xx.h. However, the [datasheets](http://www.atmel.com/products/wireless/802154/default.aspx?tab=documents) show some variation:

-91: RF230, RF231, RF232
-94: RF233 and SAMR21
-97 to -100: RF212 and RF212B (actual value depends on modulation)

**Comment by miri64** [comment]
Bump
