### ISSUE TITLE
SAUL: missing DAC support

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4875]
Add periph/dac support to SAUL.

**Comment by gebart** [comment]
I will likely work on implementing this right after #4430, #4431, #4860, #4863, #4814 are merged.

**Comment by miri64** [comment]
They are ;-)

**Comment by OlegHahm** [comment]
Still willing?

**Comment by gebart** [comment]
I did not have time to fix this, but it is still a request to add the functionality to SAUL.
