### ISSUE TITLE
stm32: GPIO driver implementation uses magic numbers

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4880]
Example: https://github.com/RIOT-OS/RIOT/blob/df996044e2286ec0f5d24ada065520f98d03c2c5/cpu/stm32f0/periph/gpio.c#L119

These can lead to hard to find bugs and should be changed to preprocessor constants.

**Comment by PeterKietzmann** [comment]
That looks like a task for @A-Paul :-) ???

**Comment by A-Paul** [comment]
@PeterKietzmann, do you want me to be assigned to this issue?

**Comment by PeterKietzmann** [comment]
@A-Paul no matter about the assignment. IIRC you once wanted to start an offensive to eliminate all magic numbers :-)

**Comment by A-Paul** [comment]
@PeterKietzmann, in my opinion the use of numeric literals leads to some problems and should be *avoided*. Although I'm not feeling to be in charge of cleaning them up... ;)

**Comment by A-Paul** [comment]
This issue has been announced in #4862 as a reminder for @haukepetersen. Are you going to address this?

**Comment by DipSwitch** [comment]
I'm gonna regret this... But I think I know fix the magic numbers using the STM32 header files... Only for STM ofcourse =)

**Comment by haukepetersen** [comment]
I am not going to address this anytime soon, as I personally don't have that strong opinions against magic numbers at certain places...

**Comment by aabadie** [comment]
This is still an issue and could be fixed with new CMSIS. I think all STM32 cpu uses the new CMSIS versions now.
