### ISSUE TITLE
Test for random number generation distribution missing

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#4882]
It would be interesting to see if [TestU01](http://simul.iro.umontreal.ca/testu01/tu01.html) would be possible to run on RIOT. BOARD=native would be a good starting point, but running the test on the hardware random number generators on the different boards would also be an interesting test.

**Comment by kaspar030** [comment]
My entropy collector PR (#4294) includes a test harness that can run tests on numbers generated by our prng's in a mostly automated way, but with the code running on the host system, so it wouldn't work for the hwrngs.

**Comment by kaspar030** [comment]
I'll look into adding TestU01.

**Comment by basilfx** [comment]
I've spend an hour to see how TestU01 could be used, but it requires serious patching before it even compiles (missing externs, lots of errors). @kaspar030, my guess is that you didn't continue either?

Maybe, for on-target testing, we could use something simple (but commonly used) FIPS 140-2 testing (like used in [rngtest](https://linux.die.net/man/1/rngtest)). That would be easy enough to re-implement from scratch (there are existing sources, but GPL).

Shall I look into that?
