### ISSUE TITLE
drivers/ethos/ethos.c:343:13: error: initialisation from incompatible pointer type

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#4908]
Someone can explain me this?

https://github.com/RIOT-OS/RIOT/blob/master/drivers/ethos/ethos.c#L294 != https://github.com/RIOT-OS/RIOT/blob/master/drivers/include/net/netdev2.h#L143

There is no new commit changing this and I was able to build the gnrc_border_router example until this afternoon... How it was possible?

@kaspar030 @authmillenon any hints?

**Comment by OlegHahm** [comment]
Strange indeed. https://github.com/RIOT-OS/RIOT/pull/4648 which changed this interface, got merged four days ago.
