### ISSUE TITLE
docker: cmake missing?

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#4961]
Seems like cmake is missing in our current riotbuild:latest docker image, which makes relic builds fail.
Where can I add it?
Is the dockerfile in riotdocker's root the main docker file?

**Comment by gebart** [comment]
Yes, the Dockerfile at the root of the riotdocker repository is the one used for the "latest" tag. It contains the toolchains for all RIOT supported platforms and CPUs.
This issue was fixed by https://github.com/RIOT-OS/riotdocker/pull/12
