### ISSUE TITLE
pkg: building in pkg/ is suboptimal

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#4962]
I'm running a lot of parallel builds, e.g., building unittests for two platforms from the same directory at the same time.

This totally breaks with how packages are currently build, as the two compiles would use the same build directory.

**Comment by authmillenon** [comment]
Kind-of a super-set of #4511 only that it also includes ccn-lite, cmsis-dsp and possibly others (basically every package that does not contain an "add RIOT makefiles" patch probably).

**Comment by kaspar030** [comment]
Yeah... I have a workaround for parallel builds in #4963.

**Comment by authmillenon** [comment]
Wasn't this fixed already?

**Comment by kaspar030** [comment]
Yes, fixed by #5138 and #5174.
