### ISSUE TITLE
thread_t is already defined by OS X

### ISSUE THREAD

**Issue by Yonezawa-T2** [RIOT-OS/RIOT#4973]
Compiling native platform on OS X (10.11.3) results in the following error:

```
~/src/RIOT/core/include/sched.h:98:24: error: typedef redefinition with different types
      ('struct _thread' vs 'mach_port_t' (aka 'unsigned int'))
typedef struct _thread thread_t;
                       ^
/usr/include/mach/mach_types.h:119:22: note: previous definition is here
typedef mach_port_t             thread_t;
```

#4578 renames `tcb_t` to `thread_t`.

Dependency graph:

`cpu/native/periph/timer.c → mach/mach_host.h → mach/mach_types.h`

Possible fixes:

- rename to `tcb_t`
- rename to `riot_thread_t`
- rename to `thrd_t`
- rename to `process_t`
- `#define thread_t riot_thread_t` in sched.h
- other?

**Comment by LudwigKnuepfer** [comment]
Just a thought: isn't it possible to use OSX Jenkins installations as well? I guess this could have been caught... Other than that: I'd just kick support for OSX, let them use vagrant or something.

**Comment by kaspar030** [comment]
@emmanuelsearch Could you check milhouse? I can't reach it... Is it still running?

**Comment by kaspar030** [comment]
> other?

factor out mac os functions into a different compilation unit...
I'm reluctant to give up the name "thread_t" for mac os :)

**Comment by Kijewski** [comment]
Wouldn't `#define thread_t riot_thread_t` in the offending .c file, just after the Mach includes, solve the problem? Other than that: what Ludwig said.

**Comment by OlegHahm** [comment]
Which Jenkins?

**Comment by LudwigKnuepfer** [comment]
Jenkins, Travis, what's the difference...

**Comment by LudwigKnuepfer** [comment]
(Just to be clear: I meant Travis and typed Jenkins instead.)

**Comment by Yonezawa-T2** [comment]
> Wouldn't #define thread_t riot_thread_t in the offending .c file, just at the end of the Mach includes, solve the problem?

It seems to be working, at least compiler is happy. `timer.c` does not use `thread_t`.

**Comment by Yonezawa-T2** [comment]
Created PR #5056.
