### ISSUE TITLE
RIOT CI webui wishlist

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#4982]
Whishlist for probably coming RIOT CI web interface.

**Comment by kaspar030** [comment]
Dipswitch wrote:
> Don't know if I've time. But to help the process speed-up. What would be the requirements for the web
 > interface? 
> - Pending jobs
> - Job results
> - (Re)queue / run 
> - Mail developer on failed run (not really web)
> Suggestions are more then welcome :)

**Comment by kaspar030** [comment]
> Pending jobs
> Job results

Yes, basically a nice view of https://ci.riot-labs.de/api/pull_requests.



> (Re)queue / run

Yeah, and also cancel, for multiple PR's. Nice would be if the web interface would do oauth against github, so we don't need to deal with a user database. The browser side could manage all that and then just send a json rpc post with a list of PR's to restart/cancel, and the github username + auth token. Then it's supersimple to do on the server side.

> Mail developer on failed run (not really web)
I'm not sure github exposes the user email addresses. If yes, piece of cake. If not, we'd have to manage the github user -> email mapping somehow.

**Comment by authmillenon** [comment]
I was fed-up with looking at JSON output so I wrote a simple viewing HTML: http://authmill.spline.de/pull_requests.html. Maybe someone wants to put that on the server. It's basically the JSON stuff in fancy bootstrap view.

It's my first JS coding in years so be nice ;-) (hope I handled the queued entries right since at the time of coding no queuing occured).

**Comment by DipSwitch** [comment]
Looks good!

**Comment by kaspar030** [comment]
@authmillenon Nice!

I made it available at https://ci.riot-labs.de/. If you feel like, you could PR it at https://github.com/kaspar030/murdock.

**Comment by authmillenon** [comment]
My HTML file isn't on this repository ;-)

**Comment by miri64** [comment]
Weeks later I realize

> I made it available at https://ci.riot-labs.de/.

Shouldn't that rather be https://ci.riot-labs.de/RIOT-OS/RIOT/

**Comment by miri64** [comment]
Ping?

**Comment by OlegHahm** [comment]
Do we still need this issue?

**Comment by aabadie** [comment]
I think we can close this one. @kaspar030 ?

**Comment by kaspar030** [comment]
Nope, I'll close.
