### ISSUE TITLE
move includes to riot/

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#5010]
How about we move our include hierarchy one level deeper, into "riot/"?
That way, common names like "thread.h" and "timer.h" wouldn't clash.

**Comment by kaspar030** [comment]
```
#include "riot/core/thread.h"
#include "riot/sys/xtimer.h"
```

**Comment by gebart** [comment]
I don't see how that would fix the naming collision between thread_t in RIOT and OSX?

**Comment by kaspar030** [comment]
Seems like I'm just waking up, it wouldn't help at all. I'll fix the issue description.

**Comment by miri64** [comment]
Did not seem to have happened ;-)

**Comment by OlegHahm** [comment]
Could be worth a discussion on the mailing list or in a meeting, but here it seems to be stalled. Please re-open if you disagree.
