### ISSUE TITLE
boards: Unify LED_(.*)_(ON|OFF|TOGGLE)

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#5028]
See https://github.com/RIOT-OS/RIOT/issues/5027#issuecomment-194821145.

Basically every board choses the colours as they like to.

I'm not advocating however to remove or replace them. Maybe a unifying API macro alá `LED_ON(color)` that is the solution here.

**Comment by haukepetersen** [comment]
I would actually rather get rid of the colors all together and go with a numeric naming, LED1_xx and so on.

**Comment by OlegHahm** [comment]
Sounds good for me.

**Comment by haukepetersen** [comment]
done: #5045
