### ISSUE TITLE
core: irq: wrong prefixes

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#5041]
The prefixes of all functions in `core/include/irq.h` are wrong. Should be `irq_disable()`, `irq_restore()` etc.

**Comment by gebart** [comment]
Would it be enough to do a scripted sed replace to rename these functions? I guess the API is OK as-is and only the names need changing?

**Comment by OlegHahm** [comment]
I guess so.

**Comment by DipSwitch** [comment]
I think it is a good idea to make most (if not all) API changes in 2016.04 so people don't get mad having to update there board port after every release :)
