### ISSUE TITLE
shell ifconfig: Addresses added with ifconfig add should have lifetime infinite

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#5062]
Currently the valid and preferred lifetimes of addresses added via the ifconfig shell command gets set to zero. This can be seen in packet dumps from a manually configured RPL root node, e.g. the packet dump in #5061 
See packet number 3 in https://www.cloudshark.org/captures/5331a75b9497

Somehow the RPL child nodes still manage to parse this into a lifetime of infinite, which may be another bug (or maybe an intentional fallback?)

**Comment by gebart** [comment]
@authmillenon ping with relation to #4304

**Comment by gebart** [comment]
the manual test in the cloudshark dump was run from gnrc_networking example, without USEMODULE border router.

**Comment by cgundogan** [comment]
@gebart can this be closed as #4304 was merged a week ago?

**Comment by gebart** [comment]
Yes
