### ISSUE TITLE
AVR8: Reboots after `return 0;`

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#5083]
While testing `tests/xtimer_usleep_until` I noticed that the Arduino MEGA does not print the tests results, but only `Min/max error: xx/xxx`.
If the UART baud rate is increased to 115200 the complete test is printed, but then the platform reboot and this happens infinitely.

I'm porting another device ( [Waspmote PRO v1.2](http://www.libelium.com/products/waspmote/hardware/) ) which is based on rather the same MCU and I'm also experiencing this behaviour but at any baud rate.

Any hits to solve this mystery? 

Thanks RIOTers!

Paco.

**Comment by kYc0o** [comment]
Still an issue. Postponed for the next release.

**Comment by kYc0o** [comment]
This test has changed by `xtimer_periodic_wakeup` and now it succeeds. I think it was solved by #5763 .

**Comment by miri64** [comment]
At this stage of the release cycle: Please, please, please remove the issue from the "Release 2016.10" project and the release note drafts!

**Comment by kYc0o** [comment]
Ok ok ok... Sorry, will do it asap.

**Comment by miri64** [comment]
Already done. ;-) Just a reminder for next time
