### ISSUE TITLE
hashes: hmac_sha256 should take input message of type "const unsigned char*"

### ISSUE THREAD

**Issue by wentaoshang** [RIOT-OS/RIOT#5108]
`const unsigned char *hmac_sha256(const unsigned char *key,
                                 size_t key_length,
                                 const unsigned *message,
                                 size_t message_length,
                                 unsigned char *result)` defined in sys/hashes/sha256.c should take input "message" of type `const unsigned char*` or `const uint8_t*`, instead of `const unsigned*`, to be consistent with the `unsigned char *sha256(const unsigned char *d, size_t n, unsigned char *md)` API.

It is more common for the messages to be stored in unsigned char arrays. This suggested change would avoid extra type casting in many cases.

**Comment by BytesGalore** [comment]
I proposed #5690

**Comment by miri64** [comment]
I guess this was fixed (though differently than proposed) in #5690.
