### ISSUE TITLE
cpuid: why is the parameter a void pointer?

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#5114]
Is there any reason why the parameter of `cpuid_get(id)` is a void pointer (instead of *uint8_t or something similar)?

**Comment by authmillenon** [comment]
I guess to not put any constraints on the type, but uint8_t pointer might also work :-)

**Comment by miri64** [comment]
@OlegHahm did this answer your question?

**Comment by miri64** [comment]
Related to #5497?

**Comment by OlegHahm** [comment]
If I understand the outcome of #5497 correctly, it should be changed, right?
