### ISSUE TITLE
CI: notify PR's that need rebase

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#5161]
Murdock is monitoring all PR changes anyways, so it would be possible to make it somehow notify if a PR needs a rebase.

What do you think?

**Comment by OlegHahm** [comment]
Hm, why not?

**Comment by kaspar030** [comment]
What would be the preferred way? As comment, so interested parties get an email?

**Comment by OlegHahm** [comment]
I guess that makes sense and would reflect the current state of the art in an automagic manner.

**Comment by kaspar030** [comment]
And it is less controversial than a "automerge" function. ;)

**Comment by miri64** [comment]
Is this still required with the new rebase/squash feature of GitHub?

**Comment by OlegHahm** [comment]
@kaspar030, are you still interested in this or should we close?

**Comment by kaspar030** [comment]
We agree on "nice to have", thus the discussion can be considered conclusive. ;)
