### ISSUE TITLE
make clean is deleting package code

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#5172]
It used to be `distclean` that did that, while `clean` just removed binaries and other files not in any commit.

**Comment by kaspar030** [comment]
Why is that a bug?

**Comment by authmillenon** [comment]
Because it requires an unnecessary download/copy (with git-cache) action. `distclean` for forcing re-cloning should suffice.

**Comment by authmillenon** [comment]
PR to out it from an engineer's perspective: because it is an unexpected behavior from a previous state that was not solicited => a bug.

**Comment by kaspar030** [comment]
> Because it requires an unnecessary download/copy (with git-cache) action. distclean for forcing re-cloning should suffice.

No way around that, as our normal "make clean" cleans the bin/$BOARD directory, unless we keep the pkg sources in a seperate directory. (bin/pkg/$board)? Will look into it.

**Comment by kaspar030** [comment]
(with git-cache, the increased complexity is not worth the hassle...)

**Comment by kaspar030** [comment]
> Or to out it from an engineer's perspective: because it is an unexpected behavior compared to a previous state that was not solicited => a bug.

Debatable, if the previous behaviour was, e.g., desastrous.

**Comment by kaspar030** [comment]
I would prefer maybe automatic git-caching (without the need for manual setup/update). That way, all the ephemeral stuff stays in one board directory.

**Comment by authmillenon** [comment]
Since when and why is a package cloned into an application's bindir?

**Comment by kaspar030** [comment]
Since people and machines are trying to build multiple boards in parallel, in the same RIOTBASE.
