### ISSUE TITLE
boards/avsextrem/smb380: Excessive irq_disable and irq_restore usage in driver.

### ISSUE THREAD

**Issue by DipSwitch** [RIOT-OS/RIOT#5173]
Due to refactoring the `irq_disable` and `irq_restore` functionallity we (Oleg) noticed excessive (33 disables and 33 restores) usage of the two in the driver implementation for the smb380.

https://github.com/RIOT-OS/RIOT/pull/5109#issuecomment-199530714

Just putting it here as a reminder. And feel free to have a look at it if you feel like it :)

**Comment by kYc0o** [comment]
Well... it seems the issue wasn't addressed. Let's try to solve it for the next release.

**Comment by miri64** [comment]
Wrongly labeled as question. Maybe it was ignored because of that ;-)?

**Comment by PeterKietzmann** [comment]
This driver has been removed with #6592 as it was pretty much outdated
