### ISSUE TITLE
CI: disconnect Travis

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#5183]
Now that Murdock is our main CI and way better than Travis: Do we want to disconnect from Travis?

**Comment by OlegHahm** [comment]
I would say: let's wait until after the release.

**Comment by haukepetersen** [comment]
I am with Oleg here -> let's keep Travis attached for now, it does not hurt and we have a live fallback in case anything unexpected happens to Murdock...

**Comment by cgundogan** [comment]
>I am with Oleg here -> let's keep Travis attached for now, it does not hurt and we have a live fallback in case anything unexpected happens to Murdock...

+1

**Comment by authmillenon** [comment]
Though I don't want to invalidate your arguments I still would vote to disconnect Travis at some point in the future, to make successful builds again easy to find with https://github.com/RIOT-OS/RIOT/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+status%3Asuccess (when travis is producing noise)

**Comment by authmillenon** [comment]
It's after the release and Travis seems only to fail now. Shall we disconnect it?

**Comment by OlegHahm** [comment]
Fine with me.

**Comment by authmillenon** [comment]
Done.
