### ISSUE TITLE
Board z1: Fix problem with UART port

### ISSUE THREAD

**Issue by Joelfp** [RIOT-OS/RIOT#5209]
After recieving the new changes from #5072 I have problems with the UART port. While flashing the "hello world" program I recieve nothing from the UART. After viewing the UART port assign values in the file "RIOT/boards/z1/include/periph_conf.h" I noticed that `UART_RX_PORT` , `UART_TX_PORT` , `UART_TX_PIN` and `UART_RX_PIN` had assigned the incorrect values (lines 62-65). According to Zolertia z1 datasheet the UART TX is assigned to pin P3.4 and UART RX to pin P3.5.
After correcting these values I recieve the hello world message.

**Comment by OlegHahm** [comment]
Do you care to open a PR for that?

**Comment by Joelfp** [comment]
OK I will open a PR

**Comment by OlegHahm** [comment]
Great!

**Comment by haukepetersen** [comment]
did #5210 solve this issue? It seems like it can be closed, right?

**Comment by Joelfp** [comment]
Yes, It solved the problem for me. I will close this issue
