### ISSUE TITLE
drivers/periph: default UNDEF constants are negative but type is unsigned

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#5217]
e.g. uart_t is defined unsigned int and UART_UNDEF is defined -1.

**Comment by gebart** [comment]
a proper unsigned value with the same bits would be `~0`

**Comment by haukepetersen** [comment]
yepp, notices (and partly fixed) this, too. Will provide a fix.

**Comment by haukepetersen** [comment]
fixed with #5224
