### ISSUE TITLE
some use of asm keyword might be missing volatile

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#5218]
See #5059.

**Comment by kYc0o** [comment]
#5059 has solved this?

**Comment by kYc0o** [comment]
Well until having  an answer I'll move it for the next release.

**Comment by gebart** [comment]
there's still some in the tree.
There are also a few occurrences of `asm` (instead of `__asm__`)

**Comment by kYc0o** [comment]
Ok so let's try to fix them for the next release.

**Comment by DipSwitch** [comment]
It could also miss a memory barrier depending on what you mean, __asm__("instruction" : R : W : clobbers )

Where clobbers is, "memory" can be placed, this means the C lines above and below the assembly lines may never be moved over the assembly lines.

**Comment by kaspar030** [comment]
I feel this is mostly done.
