### ISSUE TITLE
Outdated M3 documentation on the wiki page

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#5241]
Just a reminder to update IoT-Lab M3 node on the wiki page

https://github.com/RIOT-OS/RIOT/wiki/Board%3A-IoT-LAB-M3

**Comment by aabadie** [comment]
Here are (minor) requested changes (I still can't push to the wiki repository): 
```
diff --git a/Board:-IoT-LAB-M3.md b/Board:-IoT-LAB-M3.md
index 555aae6..64f720d 100644
--- a/Board:-IoT-LAB-M3.md
+++ b/Board:-IoT-LAB-M3.md
@@ -35,11 +35,11 @@
 |              | RNG           | no            | no HW module |
 |              | Timer         | full          ||
 | Radio Chip   | AT86RF231     | partly                | will be remodelled soon |
-| Accelerometer        | L3G4200D      | yes           | planned |
-| Magnetometer | L3G4200D      | yes           | planned |
-| Gyroscope    | LSM303DLHC    | yes           | planned |
-| Pressure Sensor      | LPS331AP      | yes           | planned |
-| Light Sensor | ISL29020      | yes           | planned |
+| Accelerometer        | L3G4200D      | yes           |  |^M
+| Magnetometer | L3G4200D      | yes           |  |^M
+| Gyroscope    | LSM303DLHC    | yes           |  |^M
+| Pressure Sensor      | LPS331AP      | yes           |  |^M
+| Light Sensor | ISL29020      | yes           |  |^M
 
 ##### Note on at86rf231 radio driver
```

**Comment by haukepetersen** [comment]
updated the wiki page. @kYc0o: please check if you find this sufficient...

@aabadie: Everyone should be able to push to the wiki, did you try editing it using the web interface directly, too?

**Comment by OlegHahm** [comment]
> @aabadie: Everyone should be able to push to the wiki, did you try editing it using the web interface directly, too?

I'm not sure about the Git access to the Wiki, but indeed, everyone should be able to *edit* the wiki using the web interface. (Just checked with another account.)

**Comment by aabadie** [comment]
@OlegHahm, @haukepetersen, I can indeed edit using the web interface. Thanks !

**Comment by kYc0o** [comment]
@haukepetersen Yeah those changes should be enough, @aabadie maybe you can fix the images that are not shown?

**Comment by aabadie** [comment]
@kYc0o : fixed. There were outdated links to the `devgrenoble.senslab.info` host. I replaced them with  `www.iot-lab.info`

**Comment by haukepetersen** [comment]
@aabadie, @kYc0o: are you happy with the updated board wiki page for now so we can close this issue?

**Comment by aabadie** [comment]
Yes !

**Comment by kYc0o** [comment]
Yes it's OK for me too
