### ISSUE TITLE
cpu/atmega2650/periph/timer: timer_irq_enable not implemented

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#5252]
While testing some network interfaces on arduino-mega2650 I have the following output:
```
timer_irq_enable not implemented
```
Looking at the code, on cpu/atmega2650/timer.c
```
void timer_irq_enable(tim_t dev)
{
    (void) dev;
#ifdef DEVELHELP
    printf("timer_irq_enable not implemented\n");
#endif
}
```

However, `timer_irq_disable` is implemented, so my question is: is there a lack of implemetation of IRQ enable for this cpu?

**Comment by haukepetersen** [comment]
solved with  #5254
