### ISSUE TITLE
periph/timer: Remove timer_irq_enable, timer_irq_disable?

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#5265]
AFAICS timer_irq_enable, and timer_irq_disable are only ever called from within the timer periph implementations themselves. Do we really need to keep them in the public API?
What is the use case for disabling the IRQ of a timer without stopping it?

**Comment by kYc0o** [comment]
Is this still an issue? If so, let's try to address it for the next release.

**Comment by gebart** [comment]
yes, still an issue. This thread has been awfully silent since I posted it.

**Comment by OlegHahm** [comment]
Oops, yes, this one slipped through somehow. Could it be that the old hwtimer module needed this API somehow? For now, I would support this RFC.

**Comment by miri64** [comment]
Any news?

**Comment by haukepetersen** [comment]
the functions were used from the old `hwtimer`. Since that code path does not exist anymore, I would be happy if we would just remove those functions.

**Comment by miri64** [comment]
I just closed #5979 since this functions are still very entangled on the boards that implement them, so I postpone.

**Comment by smlng** [comment]
fixed by #6360
