### ISSUE TITLE
documentation: drivers/include/net/netdev2.h references non-existent function netdev2_event_handler()

### ISSUE THREAD

**Issue by aeneby** [RIOT-OS/RIOT#5273]
Should read `netdev->event_callback` instead perhaps? Or `netdev2->event_callback`? I'm not sure which is considered more "correct", but if it's the former,the call flow description in the same file should be updated too.

**Comment by authmillenon** [comment]
If it is a reference you are talking about, the correct way to spell it would be `netdev2_t::event_callback()`

**Comment by authmillenon** [comment]
Fixed in #5276.
