### ISSUE TITLE
examples: default is broken on native

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#5278]
The packet buffer of the default example is too small for native's tap driver. Possible solutions are #5229 and #5238.

In general this issue affects all applications that reduce the packet buffer to a size smaller than 1500 bytes.

**Comment by OlegHahm** [comment]
Folks, the default example is broken on native for almost two months now - any reason not to fix it?

**Comment by haukepetersen** [comment]
see comment in #5238

**Comment by authmillenon** [comment]
Fixed by #5229.
