### ISSUE TITLE
gnrc ipv6: sending over loopback is broken

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#5279]
Receiving an IPv6 datagram requires a netif header. This header is missing for loopback packets and will thus cause a failing assertion which leads to a kernel panic.

Possible solutions are #5247 or reverting #5179. See also the discussion on the mailing list: https://lists.riot-os.org/pipermail/devel/2016-April/003808.html.

**Comment by authmillenon** [comment]
Fixed by #5326.
