### ISSUE TITLE
feature: implement NETOPT_ACK_REQ

### ISSUE THREAD

**Issue by aeneby** [RIOT-OS/RIOT#5287]
Currently, there is a flag for toggling the "Acknowledge Request" bit of the FCF (`NETDEV2_IEEE802154_ACK_REQ`), but no NETOPT for getting/setting it via netdev. Perhaps there should be.

**Comment by authmillenon** [comment]
This was originally introduced the way it is right now by @haukepetersen in the original `at86rf2xx` driver so I reassign to him, because I did not know his original intention.

**Comment by aeneby** [comment]
See #5297

**Comment by haukepetersen** [comment]
actually, this was intended to be covered by `AUTOACK` if I remember correctly... So what is the diff between `NETOPT_AUTOACK` and `NETOPT_ACK_REQ` now?

**Comment by aeneby** [comment]
I think you're misinterpreting `AUTOACK`, which is not the same thing as `ACK_REQ` (IMO [this define](https://github.com/RIOT-OS/RIOT/blob/6c817c888ea8ba93618e2eca736d29c88a042453/drivers/include/at86rf2xx.h#L119) is incorrect, for example). `AUTOACK` should tell the driver to automatically acknowledge frames which have the "acknowledge request" (AR) bit set in the FCF, whereas `ACK_REQ` should be used to set the AR bit in outgoing frames. We need two options to handle these two cases, hence the patch.

**Comment by aeneby** [comment]
@haukepetersen any feedback on the referenced PR?

**Comment by authmillenon** [comment]
He is on holiday now for a while. I fear this has to wait for now.

**Comment by authmillenon** [comment]
(maybe if I find some time I can look into it).

**Comment by aeneby** [comment]
Okay - thanks, @authmillenon

**Comment by PeterKietzmann** [comment]
@thomaseichinger is pretty experienced with that device. Would you mind taking that issue/PR over? In that case, please self-assign as Hauke won't be available for the next months.
