### ISSUE TITLE
Integer width errors

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#529]
Some headers define prototypes that should return unsigned values of a certain width, but return signed values for error handling. This in itself is not bad practice, but sometimes the signed width equivalent of the unsigned value (``int16_t`` for ``uint16_t`` i. e.) is defined as return value.
Here an example that I found in [cc2420.h](https://github.com/RIOT-OS/RIOT/blob/903ec54a43e19526197fd2f411ea5c520494fec2/drivers/cc2420/include/cc2420.h#L131) (in this case it is not that much of a problem, since 65535 (which in two's compliment is -1) is an illegal value anyways, but I know there are more incidents of this case that might not be so unproblematic, since I've seen them before, but ignored them :-/):

```C
/**
 * @brief Set the channel of the cc2420.
 *
 * @param[in] chan The desired channel, valid channels are from 11 to 26.
 *
 * @return The tuned channel after calling, or -1 on error.
 */
int16_t cc2420_set_channel(uint16_t chan);
```

(should be since channel 65535 would also be -1)

```C
int32_t cc2420_set_channel(uint16_t chan);
```

**Comment by OlegHahm** [comment]
I think that this issues has been solved at least partly. Is anyone aware of any open problems regarding this issue or can we close this?

**Comment by PeterKietzmann** [comment]
I'd vote for closing this.
