### ISSUE TITLE
tests: Fletcher test vectors are too short

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#5299]
https://github.com/RIOT-OS/RIOT/pull/4938#issuecomment-198878721

It might be a good idea for the fletcher tests to have a test input vector which accumulates enough to "wrap around" the modulo part of the algorithm. The current test vector is quite short and containing small numbers.

**Comment by miri64** [comment]
Might be fixable for this release.

**Comment by miri64** [comment]
I tried to implement it, but it seems that either I'm failing to get a correct value for a long array at http://www.nitrxgen.net/hashgen/ or fletcher32 is broken :-/

**Comment by miri64** [comment]
Ah, should have read the comments for the `atof` test ^^ "`XXX: not verified with external implementation yet`" and putting in that data also yields a different hash than the one expected in the test.
