### ISSUE TITLE
buildtest: CI does not cover any of the tools in `dist/tools`

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#5319]
currently, Murdock is not building any of our supporting tools. I think it would actually make sense to also include tools like `ethos` or `uhcp`, also with the same demands on documentation, licensing, code style and compile warning.

**Comment by kaspar030** [comment]
Partly fixed by #5329.

**Comment by kYc0o** [comment]
Let's try to completely fix it for the next release.
