### ISSUE TITLE
native debugging on osx fails

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#534]
Using valgrind or gdb with a nativenet target in OSX leads to "the network" being stuck (gdb) or the whole process being stuck (valgrind).

**Comment by cgundogan** [comment]
@LudwigKnuepfer and now? @thomaseichinger ?

**Comment by LudwigKnuepfer** [comment]
Nothing.

**Comment by kYc0o** [comment]
Maybe [this](https://github.com/RIOT-OS/RIOT/wiki/Family:-native#os-x) can be useful to find out what's happening. I'm trying to reproduce this bug error.

**Comment by OlegHahm** [comment]
Any news?

**Comment by kYc0o** [comment]
I'll try to see what's happening... @LudwigKnuepfer can you describe the commands are you using? do you have a working library providing a `tap0` interface?

**Comment by LudwigKnuepfer** [comment]
@kYc0o The link you provided here (https://github.com/RIOT-OS/RIOT/issues/534#issuecomment-212399010) contains information on where to obtain tap interfaces. The commands used are mentioned in the issue description (https://github.com/RIOT-OS/RIOT/issues/534#issue-25984803).

**Comment by kYc0o** [comment]
Yes, my question was if you had installed such tap driver. I'll test it asap.

**Comment by LudwigKnuepfer** [comment]
I do not use OSX.

**Comment by kYc0o** [comment]
I'm afraid I won't have time to work on it for this release... I need to postpone it.

**Comment by miri64** [comment]
Can confirm that this is still an issue.

**Comment by LudwigKnuepfer** [comment]
I have no interest in working on OSX problems, I'd rather ditch OSX support.
Therefore I am unassigning myself from this issue.

**Comment by Yonezawa-T2** [comment]
I can debug RIOT with LLDB on macOS. I suggest closing this issue and reopening if anyone found a problem.

**Comment by kYc0o** [comment]
Great! Let's close it...

**Comment by miri64** [comment]
Is anyone rewriting the make target for that? ;-)

**Comment by kYc0o** [comment]
maybe @Yonezawa-T2 can provide it? I don't have experience with LLDB.

**Comment by Yonezawa-T2** [comment]
Made PR #5991

**Comment by miri64** [comment]
Fixed via #5991
