### ISSUE TITLE
cpu/cc26x0: timer broken

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#5361]
The `timer` implementation on the `cc26x0` is not working a 100% reliable. Most of the `xtimer_` tests fail at the moment. See also discussion in #4675

**Comment by kYc0o** [comment]
The issue is still present AFAIK, so postponed for the next release.

**Comment by shaolinkhoa** [comment]
Hi,
Are there any news ?
I tested timer_periodic_wakeup with cc2650 launchpad and it didn't work correcly. 
regards,
khoa

**Comment by PeterKietzmann** [comment]
@A-Paul can you check if the issue still persists?

**Comment by smlng** [comment]
should be fixed by #7335  and #7343

**Comment by smlng** [comment]
closing, resolved by #7335 and followups
