### ISSUE TITLE
Support for IP packet fragmentation/reassembly

### ISSUE THREAD

**Issue by oberstet** [RIOT-OS/RIOT#5371]
As from a discussion on IRC, I learned that RIOT currently does not support IP packet fragmentation/reassembly.

RFC4944 though seems to [suggest](https://tools.ietf.org/html/rfc4944#section-5.3) not to have IP fragmentation/reassembly independent of the link layer fragmentation of 6LoWPAN, but to "collapse" that:

> If an entire payload (e.g., IPv6) datagram fits within a single
>    802.15.4 frame, it is unfragmented and the LoWPAN encapsulation
>    should not contain a fragmentation header.  If the datagram does not
>    fit within a single IEEE 802.15.4 frame, it SHALL be broken into link
>    fragments.

As it stands, the lack of that in RIOT makes it impossible to use a full UDP datagram payload (64k), but limits the latter to <1280 (the IPv6 required minimum MTU).

**Comment by authmillenon** [comment]
Should be `<= 1280` (did not check), since 1280 is the [defined MTU for 6LoWPAN](https://tools.ietf.org/html/rfc4944#section-4.

**Comment by authmillenon** [comment]
But regardless, yes: IPv6 fragmentation should be implemented at one point.

**Comment by oberstet** [comment]
@authmillenon "IPv6 fragmentation should be implemented" cool!

rgd "<" vs "<=": what's the _theoretical_ usable UDP datagram payload left when there is no support for IP frag/reas? I thought that necessarily would be strictly less than 1280 because of headers?

Also (from IRC):

> <eintopf> Most people says maximum 4-5 fragments, nothing more for 802.15.4 6lowpan networks

So that would make up even less _practically_ usable UDP datagram payload. Something like 500-1000 octets ..

And does above IRC comment suggest at that IP frag/reas. would be _practically_ useless anyway?

Because:

> <eintopf> I transmitted one day 64k over 2.4 Ghz 802.15.4 6lowpan
 <eintopf> took 10 seconds
 <eintopf> rtt

**Comment by kYc0o** [comment]
Maybe this could be addressed on the next release?

**Comment by miri64** [comment]
Since @Lotterleben wants to do more with RIOT again, I asked her if she wants to handle this issue, and she said yes.

**Comment by J4ken** [comment]
Hi! Is there any updates on this issue?

**Comment by miri64** [comment]
I'm currently working on it. #11593 is a starting point for this and I plan to provide initial support for reassembly today.

**Comment by miri64** [comment]
#11596 and #11623 were merged a while back, so this is fixed.
