### ISSUE TITLE
Nucleo F446RE

### ISSUE THREAD

**Issue by wilhelmmatilainen** [RIOT-OS/RIOT#5382]
Could Nucleo STM32F446RE (http://www.st.com/web/en/catalog/mmc/SC1169/SS1577/LN11875/PF260537) be added to supported boards?

I would do this myself, if I knew what exactly should be done.
Maybe I could get it running for myself, but creating then a pull request for something that "seems" to work probably isn't the right way.

I just bought this board and would like to use Riot OS on it.

**Comment by toonst** [comment]
Porting to a new board is pretty straight forward. Have a look here:
https://github.com/RIOT-OS/RIOT/wiki/Porting-Guide

There's already support for nucleo-f401, so you can start from that.

**Comment by DipSwitch** [comment]
Sorry for the delay! This is een Nucleo 64 or 144? If its a 64 the board
port is identical to the nucleo-f4 if it's an 144 it would need some
tweaking if i'm correct, but not that much. I'll try to find some time this
week to have a look.

Cheers!

**Comment by wilhelmmatilainen** [comment]
It is 64.

So, all the different parameters are identical?

2016-04-26 10:40 GMT+03:00 DipSwitch <notifications@github.com>:

**Comment by DipSwitch** [comment]
I think it would suffice to copy. You could try this branch: https://github.com/DipSwitch/RIOT/tree/pr/add_nucleo_f446

**Comment by OlegHahm** [comment]
Any news?

**Comment by aabadie** [comment]
I was not aware that this issue was already opened. I initiate a port to nucleo f446 in #5706, feel free to have a look.

**Comment by miri64** [comment]
#5706 was merged, so close?
