### ISSUE TITLE
pkg: OpenWSN does not compile

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#5390]
There are references to very old modules (like hwtimer.h) in `openwsn` so it does not compile. Test setup: compile https://github.com/RIOT-OS/applications/tree/master/openwsn.

**Comment by kYc0o** [comment]
Do you refer only that the package does not compile or that the application openwsn does not compile? if that's the case, it is not an issue that would be better to discuss in the applications repo? It actually exists an [issue](https://github.com/RIOT-OS/applications/issues/27) pointing to the same.

**Comment by kYc0o** [comment]
The issue about old modules is not present anymore, however the package is still not building. Postponing and I'll try to open another issue pointing to the new problem, afterwards we can close this one.

**Comment by miri64** [comment]
> The issue about old modules is not present anymore, however the package is still not building.

Here at least it's still the hwtimer problem.

**Comment by OlegHahm** [comment]
Depends on how you want to handle this, but I always preferred to keep unsolved issues tagged for the release in order to easily gather them for the "known issues" list.

**Comment by PeterKietzmann** [comment]
OpenWSN ahs been removed #6359
