### ISSUE TITLE
doc: periph/gpio, periph/adc data member docs are overpopulated

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#5391]
Due to custom definitions for many platforms the members of enums in the ADC and GPIO docs are filling the Doxygen page.

http://riot-os.org/api/group__drivers__periph__gpio.html
http://riot-os.org/api/group__drivers__periph__adc.html

**Comment by hexluthor** [comment]
Does anyone know how to fix this? Because I don't.

**Comment by gebart** [comment]
One solution would be to eliminate all the custom definitions from the Doxygen docs by enclosing them in `#ifndef DOXYGEN`.

**Comment by kaspar030** [comment]
Fixed by #5586.
