### ISSUE TITLE
RIOT and Cooja - $ make cooja

### ISSUE THREAD

**Issue by AppleInside** [RIOT-OS/RIOT#5438]
Hi all,
I'm following this guide for simulating a 6LowPan network on cooja.
https://github.com/RIOT-OS/RIOT/wiki/RIOT-and-Cooja

But when i try to download cooja (in the RIOT path) with the command "make cooja", it doesn't work.
Is there anyone who has already done this?

Thank u all.

**Comment by authmillenon** [comment]
Hi @AppleInside,
please consider using one of the maliling lists for questions? Here you will only reach active developers, while e.g. over the [devel mailinglist](https://lists.riot-os.org/mailman/listinfo/devel) you also reach developers less active and over the [users mailinglist](https://lists.riot-os.org/mailman/listinfo/users) you also reach other users (though from experience its not as active).

Cheers,
Martine

**Comment by AppleInside** [comment]
Thank you @authmillenon for the tip, i'll do it asap!

br,
Alesssandro

**Comment by miri64** [comment]
In case you never got an answer: I realize now, that Cooja (https://github.com/RIOT-OS/RIOT/pull/1921) was never merged. I'm deleting that article because of that.

**Comment by kYc0o** [comment]
But does it mean that RIOT and Cooja does not work? In my opinion this is a MUST...

**Comment by miri64** [comment]
> But does it mean that RIOT and Cooja does not work?

Not at the moment, but I don't see any reason against it.

> In my opinion this is a MUST...

Feel free to adapt #1921 :-)
