### ISSUE TITLE
core: msg: msg_send_receive() when receiver is not waiting

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#5443]
It seems there was a reason for #879 after all: if the receiving thread B is not waiting, but sending thread A uses `msg_send_receive()` A's `thread_t::wait_data` is overwritten, because it is used for both: storing the sent message until B gets into receiving mode **and** the reply.

A simple show case to illustrate this is https://github.com/OlegHahm/miniature-dangerzone/tree/master/msg_snd_rcv

A case where this bug shows in practice is `gnrc_netapi_get/set()` if the receiver's queue is full.

**Comment by OlegHahm** [comment]
I wonder if checking for the receiver's state inside `msg_send_receive()` would be tolerable.

**Comment by OlegHahm** [comment]
Something like:
```diff
diff --git a/core/msg.c b/core/msg.c
index 7bbb2cd..7d2a144 100644
--- a/core/msg.c
+++ b/core/msg.c
@@ -212,6 +216,17 @@ int msg_send_receive(msg_t *m, msg_t *reply, kernel_pid_t target_pid)
 {
     assert(sched_active_pid != target_pid);
     unsigned state = irq_disable();
+
+    thread_t *target = (thread_t*) sched_threads[target_pid];
+    if (target->status != STATUS_RECEIVE_BLOCKED) {
+        int res;
+        if ((res =_msg_send(m, target_pid, true, state)) >= 0) {
+            res = msg_receive(reply);
+        }
+        irq_restore(state);
+        return res;
+    }
+
```

**Comment by authmillenon** [comment]
Wouldn't that make `msg_send_receive()` very insecure?

**Comment by authmillenon** [comment]
Wouldn't it be better to `SEND_BLOCK` when target is blocked?

**Comment by OlegHahm** [comment]
> Wouldn't that make msg_send_receive() very insecure?

Why?

> Wouldn't it be better to SEND_BLOCK when target is blocked?

What do you mean by `SEND_BLOCK`?

**Comment by authmillenon** [comment]
>> Wouldn't that make msg_send_receive() very insecure?
>
> Why?

Because if the receiver isn't receive-blocked the message will get lost.

>> Wouldn't it be better to SEND_BLOCK when target is blocked?
> 
> What do you mean by SEND_BLOCK?

This state https://github.com/RIOT-OS/RIOT/blob/master/core/include/thread.h#L55

**Comment by OlegHahm** [comment]
I still don't understand, why should the message get lost and which thread would you set to `THREAD_SEND_BLOCKED`? The caller of `msg_send_receive()` calls `_msg_send()` with `block == true` in both versions.

**Comment by authmillenon** [comment]
> I still don't understand, why should the message get lost

Because there is no alternative path for `if (target->status != STATUS_RECEIVE_BLOCKED) {`. If the target is not receive blocked the function does nothing, right?

> and which thread would you set to `THREAD_SEND_BLOCKED`? The caller of msg_send_receive() calls _msg_send() with block == true in both versions.

The caller of `msg_send_receive()` I would set to `THREAD_SEND_BLOCKED`, in for that else case and unblock it, as soon as `(target->status != STATUS_RECEIVE_BLOCKED)` is the case (by the scheduler).

**Comment by authmillenon** [comment]
Wait ... shouldn't it be `(target->status == STATUS_RECEIVE_BLOCKED)`.

**Comment by OlegHahm** [comment]
> Because there is no alternative path for if (target->status != STATUS_RECEIVE_BLOCKED) {. If the target is not receive blocked the function does nothing, right?

No, if the receiver is `STATUS_RECEIVE_BLOCKED` `msg_send_receive()` will do the same as before, if not it will send and receive separately.

**Comment by authmillenon** [comment]
Ahhhh, sorry, then I just missread the code >.<
