### ISSUE TITLE
RFC: shell: split WLAN/WPAN specific options into own command

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#5487]
`ifconfig` is starting to get really complicated and I'm thinking about splitting some radio specific options into their own command (similar to Linux' `iwconfig` and `iwpan`). Opinions?

**Comment by jfischer-phytec-iot** [comment]
``iwpan`` for ``802.15.4`` and ``iwconfig`` for ``802.11`` ?

**Comment by OlegHahm** [comment]
iwconfig was deprecated alredy 5 years ago - we should rather go for `iw` then.

**Comment by jfischer-phytec-iot** [comment]
then ``iwpan`` for ``802.15.4`` and ``iw`` for ``802.11``

**Comment by miri64** [comment]
Yes, for example.

**Comment by jfischer-phytec-iot** [comment]
What about not ieee std devices like cc110x?

**Comment by OlegHahm** [comment]
Do we really need to split this up for different radio technologies? Most properties (channel, TX power, network identifier) should be rather similar for most technologies.

**Comment by miri64** [comment]
Yes most, but as #5469 already shows, there are some that can even be very specific for vendors.

**Comment by OlegHahm** [comment]
But that's (as you wrote yourself) vendor specific, not specific to the technology and would prefer to keep the number of shell commands small. Even for 802.11 chips on Linux you'll find a broad variety of available options, but (fortunately) only one tool.

**Comment by jfischer-phytec-iot** [comment]
I am on iwpan, will add it to  #5485

**Comment by miri64** [comment]
@jfischer-phytec-iot can you please introduce it in a seperate PR and just adapt it in #5485? It will make the review more focused this way.

**Comment by miri64** [comment]
Also, when push comes to shove I'm for `iw` instead of `iwpan` ;-).

**Comment by jfischer-phytec-iot** [comment]
@miri64 ok

**Comment by PeterKietzmann** [comment]
#5750 was closed 2 years ago. Since then, there were no efforts for a change. Furthermore, we continued caring about `ifconfig`. Personally I think we could close this issue (maybe set memo label) and admit we stay with `ifconfig`. @miri64 any objections?

**Comment by miri64** [comment]
Seeing the amount of new information added to ifconfig, I'm still of the opinion that we actually should factor out certain options that are only of importance for certain devices. However, since this is a low priority (at least to me), we should keep this issue open as a reminder for that / opportunity for a newcomer to implement that. What do you think @PeterKietzmann?

**Comment by PeterKietzmann** [comment]
Personally I don't think this will ever happen, although it might be worth it. But I'm fine leaving the issue open. However, I don't think this is something that should be done by a newcomer.

**Comment by miri64** [comment]
#12295 gave some new precedence to this. @jia200x @benpicco what do you think?

**Comment by benpicco** [comment]
#12171 will add even more radio commands to `ifconfig`.

I too agree that it would be a good idea to have separate commands for layer 2 and layer 3.

**Comment by jia200x** [comment]
+1. Indeed!
