### ISSUE TITLE
cpu/lpc11u34: ADC broken

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#5489]
It looks like the lpc11u34 ADC implementation is broken with regards to the resolution.

https://github.com/RIOT-OS/RIOT/commit/575659cd1cfce7d018e90b4b9d24daee6d6f4a44 broke it.

Given the definition of `adc_res_t` in `periph_cpu.h`: The check at
https://github.com/RIOT-OS/RIOT/commit/575659cd1cfce7d018e90b4b9d24daee6d6f4a44#diff-50f14e4c5c396b6989e259ec75fac8c0R83
will always be true and the function will return -1.

I don't have the board to test and no time to fix it, just adding this as a reminder.

**Comment by haukepetersen** [comment]
should be fixed with #6959
