### ISSUE TITLE
cpu: Implement thread_arch_isr_stack_usage() for missing platforms

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#5494]
#5491 introduced the capability to print the stack-usage of the ISR. Currently, this feature is only provided  for Cortex-M platforms and needs to be provided for all other platforms:
- [ ] `atmega2560`/`atmega_common`
- [ ] `msp430_common`
- [ ] `lpc2387`/`arm7_common`
- [ ] `native`
- [ ] `qemu-i386`

**Comment by kYc0o** [comment]
Postponing for the next release.

**Comment by madokapeng** [comment]
Hi, I am a new comer to RIOT OSS. 
This issue is assigned to me. I realize it was created a year ago. any updates?

**Comment by miri64** [comment]
First of all, a warm welcome to the RIOT community @madokapeng.

This isn't really my strong suit, but I would suggest to look into the current implementation in `cortexm_common` and go from there from the platform you are working on.

Out of interest: who assigned you to this issue?

**Comment by madokapeng** [comment]
@miri64 
Hi, I got this issue from codetriage email. I should not say "assign to me" :)
what is the procedure to solve issues?
is just by looking at open Issues list and pick up one?

Thanks
