### ISSUE TITLE
gnrc_rpl: broken doc?

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#5514]
There seems to be something wrong in the RPL documentation, but I can't exactly find what. The symptom can be seen on http://doc.riot-os.org/:
![rpl_doc_err](https://cloud.githubusercontent.com/assets/675644/15805213/7aea2800-2b23-11e6-86d9-a9d84b5fed94.png)
Those two groups should not be at the top level.

**Comment by cgundogan** [comment]
nice catch! fixed by #5516
