### ISSUE TITLE
Murdock does not build PRs against non-master branches

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#5518]
Currently, Murdock fails for each backporting PR.
I have no log message at hand right now (can't reach the log files), but @kaspar030 you have access to them, right?

**Comment by miri64** [comment]
See also https://github.com/kaspar030/murdock/issues/1

**Comment by kaspar030** [comment]
Should be fixed by #5630 and a fix to Murdock's build scripts. Will keep open until the first release branch build completes.

**Comment by cgundogan** [comment]
Looks fine now, Murdock builds non-master PRs (see https://ci.riot-labs.de/RIOT-OS/RIOT/5741/fb46a1dfc4fa6867e553ffeab38af2d61abd5a84/output.html)
