### ISSUE TITLE
shell: support sending data frames with zero-length payloads via txtsnd

### ISSUE THREAD

**Issue by aeneby** [RIOT-OS/RIOT#5530]
Currently it is not possible to send data frames with zero-length payloads via ~~the GNRC stack~~ `txtsnd`, due to the check [here](https://github.com/RIOT-OS/RIOT/blob/e9bbd54f5825c6fddedf2030ecddae7a5703cbc1/sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c#L97). Data frames with zero-length payloads are still valid 802.15.4 packets (PAN coordinators are required to be able to send them in response to data request commands, for example), and therefore ~~RIOT's network stack~~ the shell should support sending them.

**Comment by miri64** [comment]
GNRC supports sending of zero-length data frames: it uses NULL pointers for that (see e. g. ping6 command).

**Comment by aeneby** [comment]
Okay, perhaps I misunderstood something - I did eventually manage to send a zero-length payload directly from a test application. My initial test case however was via the shell:

```
txtsnd 4 bcast ""
2016-06-08 20:14:18,300 - INFO # > txtsnd 4 bcast ""
2016-06-08 20:14:18,302 - INFO # error: packet buffer full
```

I would have expected that to send out a zero-length packet.

**Comment by aeneby** [comment]
So if I understand you correctly, what you're saying is that the bug is actually in `_netif_send()` rather than `gnrc_pktbuf_add()`, since [here](https://github.com/RIOT-OS/RIOT/blob/e9bbd54f5825c6fddedf2030ecddae7a5703cbc1/sys/shell/commands/sc_netif.c#L1076) we should be checking if the data is zero-length, and if so, creating a packet with a NULL data pointer?

**Comment by miri64** [comment]
Yes :)

**Comment by aeneby** [comment]
Okay, I've changed the issue's title and description to reflect the actual problem. Will submit a new PR.
