### ISSUE TITLE
sam3: RTC implementation

### ISSUE THREAD

**Issue by dondonprad** [RIOT-OS/RIOT#5566]
i tried compile main.c in tests/periph_rtc 
i using arduino-due board  
i think rtc.h not compiled in main.c, i ask how fix it?? 

![screenshot from 2016-06-22 23 25 55](https://cloud.githubusercontent.com/assets/15816634/16274657/bf18bc52-38d0-11e6-878c-493f6d49966c.png)

**Comment by PeterKietzmann** [comment]
@dondonprad it seems there is currently no rtc implementation for the SAM3x controller in RIOT. One could fix it by writing an appropriate driver to the [peripheral rtc interface](https://github.com/RIOT-OS/RIOT/blob/master/drivers/include/periph/rtc.h.

**Comment by iia** [comment]
Hi,

I'm interested to fix this issue. What is the current state of this issue ?

Cheers.

**Comment by aabadie** [comment]
Still valid issue
