### ISSUE TITLE
Do RIOT support Raspberry pi 3 B

### ISSUE THREAD

**Issue by SoonSYJ** [RIOT-OS/RIOT#5585]
Hi, I am working on IoT based on Raspberry Pi 3. Can anyone please tell me weather it is supported by RIOT. Thank you.

**Comment by PeterKietzmann** [comment]
Hi @SoonSYJ. Short answer: no. With RIOT we are targeting microcontrollers with orders of magnitudes less memory and cpu speed than a Pi. Why not running Linux on it? You could use Raspian with WPAN support (check out [this guide](https://github.com/RIOT-Makers/wpan-raspbian/wiki)) and communicate to a RIOT node via 802.15.4 (+6Lo/IPv6/UDP/COAP)

**Comment by SoonSYJ** [comment]
Hi @PeterKietzmann . Thank you so much. I have followed this tutorial [https://github.com/RIOT-OS/RIOT/wiki/How-to-install-6LoWPAN-Linux-Kernel-on-Raspberry-Pi#get-a-new-raspberry-pi-kernel-on-a-linux-host](url) . But is it suitable for RPi3? Anyway, I will follow the guide provided by you.

**Comment by SoonSYJ** [comment]
Hi @PeterKietzmann , I have taken a look at your guide. And I got a question. I am working on CC2500 transceiver neither openlabs nor microchip. Is that means that I have to create a device by myself? Is there any guide for doing this?

**Comment by PeterKietzmann** [comment]
Hi. I didn't try it on a Pi 3 but someone else recently did. You might want to follow [this conversation](https://lists.riot-os.org/pipermail/devel/2016-June/003998.html). As it seems linux-wpan supports a cc2531 driver (compare [this overview](https://github.com/linux-wpan/wpan-tools/wiki/Driver-Features)). I don't know if an overlay exists. But anyway you can find helpful informations about about how to do so in the RIOT makers repo
