### ISSUE TITLE
doc: Doxygen group core_util is cluttered

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#5651]
The group `core_util` has grown and become very cluttered.
I propose we introduce a new top level group beside Kernel name "Core library".
The core_util functions don't really depend on the kernel and are mostly pure portable C implementations of useful algorithms and techniques.

Existing layout:
- Kernel
  - IRQ Handling (irq.h)
  - Kernel utilities (everything else)
  - Messaging / IPC (msg.h)
  - Power Management (lpm.h)
  - Scheduler (sched.h, native_sched.h)
  - Startup and Configuration (kernel_defines.h, kernel_init.h, reboot.h, config.h)
  - Synchronization (mutex.h)
  - Threading (thread.h)

Suggested new layout:
- Kernel
  - IRQ Handling (irq.h)
  - Kernel data types (kernel_types.h)
  - Crash handling (panic.h)
  - Messaging / IPC (msg.h)
  - Power Management (lpm.h)
  - Scheduler (sched.h, native_sched.h)
  - Startup and Configuration (kernel_defines.h, kernel_init.h, reboot.h, config.h)
  - Synchronization (mutex.h)
  - Threading (thread.h)
- Core library
  - Atomic operations on variables (atomic.h)
  - Bit arithmetic (bitarithm.h)
  - Byte order (byteorder.h)
  - Buffers, lists and queues
    - Circular integer buffer (cib.h)
    - Circular list (clist.h)
    - LIFO stack (lifo.h)
    - Linked list (list.h)
    - Priority queue (priority_queue.h)
    - Ring buffer (ring_buffer.h)
  - Logging (log.h)
  - Debug output (debug.h)

This is an open request for comments

**Comment by miri64** [comment]
:+1:
