### ISSUE TITLE
CI: Murdock start with other labels than "Ready for CI build"

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#5689]
I noticed that Murdock starts to build when I set the label "new feature" in any PR. I didn't test with other labels but if you experience something similar please report it.

**Comment by miri64** [comment]
Is this still an issue? Did anybody else see this? @kaspar030 e.g.?

**Comment by miri64** [comment]
I take it out of the release however this this concerns https://github.com/kaspar030/murdock, not RIOT ;-)

**Comment by kaspar030** [comment]
Never experienced this. And @miri64 is right, if this happens the bug should reported in the murdoc repo.

@kYc0o ok to close?

**Comment by gebart** [comment]
This happened to me this morning when adding the hacktoberfest label to one
pr which was already green and ready for merging.

**Comment by kaspar030** [comment]
> This happened to me this morning when adding the hacktoberfest label to one
> pr which was already green and ready for merging.

Ok, that helped, I found it.

When murdock stops, it currently doesn't save the state of the PR's it
knows. Every change to a PR then makes it reload that state. So after a
label change following a murdock restart, murdock thinks the head commit
has changed and thus rebuilds.

Will fix...

**Comment by kYc0o** [comment]
Ok to close when the fix comes :P

**Comment by OlegHahm** [comment]
Does this bug still exist?

**Comment by kaspar030** [comment]
Nope, fixed.
