### ISSUE TITLE
test/msg_send_receive: fails on samr21-xpro

### ISSUE THREAD

**Issue by BytesGalore** [RIOT-OS/RIOT#5699]
Found during release 2016.07 testing https://github.com/RIOT-OS/Release-Specs/issues/24#issuecomment-235584801
The test fails on samr21-xpro board because of a wrong value present in [`msg_resp.content.ptr`](https://github.com/RIOT-OS/RIOT/blob/master/tests/msg_send_receive/main.c#L55) in the last iteration.
Printing the values of `counter` and `msg_resp.content.ptr (resp val)` for each iteration revealed:
```
# main(): This is RIOT! (Version: 2013.08-10643-gb5cb6-user01-LLED-E6410)
# Incremented counters to 1 and 1
# resp val: 1, counter: 1
```
... all ok until the last one:
```
# Incremented counters to 10 and 10
# resp val: 841, counter: 10
# Test failed.
```

**Comment by kYc0o** [comment]
any hint @kaspar030 ?

**Comment by OlegHahm** [comment]
Try to revert https://github.com/RIOT-OS/RIOT/pull/5444

**Comment by BytesGalore** [comment]
@OlegHahm reverting #5444 didn't help

**Comment by OlegHahm** [comment]
Have you tested on other platforms?

**Comment by kaspar030** [comment]
Looks to me like the threads are sending around pointers to their stacks, and in the last iteration, one of the threads already exited.

Could you try to add ```thread_sleep()``` before the return in thread2()?

**Comment by BytesGalore** [comment]
@kaspar030 that did it

**Comment by BytesGalore** [comment]
(I mean the test succeeds now)

**Comment by kaspar030** [comment]
I'll prepare a PR.

**Comment by BytesGalore** [comment]
nice

**Comment by kaspar030** [comment]
#5701
