### ISSUE TITLE
transport layer poorly initializes the PRNG

### ISSUE THREAD

**Issue by mehlis** [RIOT-OS/RIOT#570]
currently destiny uses the current time: https://github.com/RIOT-OS/RIOT/blob/master/sys/net/transport_layer/destiny/destiny.c#L58

and the port of a socket as initialization for the PRNG: https://github.com/RIOT-OS/RIOT/blob/master/sys/net/transport_layer/destiny/socket.c#L551

I think that this code is harmful on an embedded device, because:
in case 1.: start destiny on 2 devices, the function is called to the same time -> results in the same initialization
2. use the same connect logic on 2 devices -> results in the same initialization

also calling srand more than one time doesn't make the situation better

**Comment by cgundogan** [comment]
anyone any idea about the current state of this issue?

**Comment by authmillenon** [comment]
Not transport layer related anymore, but the PNRG is still not initialized with a non-zero value.

**Comment by OlegHahm** [comment]
Destiny is gone, the PRNG discussion can be continued in #5150.
