### ISSUE TITLE
Compile atmega_common

### ISSUE THREAD

**Issue by romainvause** [RIOT-OS/RIOT#5722]
Hi,

I have an error when it compiles the cpu/atmega_common/periph/spi.c file.
At the line 64,
> PRR0 undeclared (first use in this function)
> PRR0 &= ~(1 << PRSPI);

I'm just make the Makefile from `Tutorials/task-01`, to try with arduino-uno
Any idea ?

Thanks.

**Comment by aabadie** [comment]
As reported in  #5723, arduino-uno is not officially supported by RIOT. Also, there are pending PRs about this: see #5451 and #5590. Please comment there instead of creating new issues.
