### ISSUE TITLE
gnrc: nodes crashing with too small packet buffer

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#5748]
I just ran into a problem, when I manually configured the packet buffer too small in the `gnrc_networking` example. In fact, I copied the size from the `gnrc_minimal` example (512 bytes). Testing this on the iotlab testbed with ~350 nodes (Neighbor cache size set to 100, FIB size to 350) I ran into several crashes. Nodes were dying with hard faults after some time.

(On the pro side: with the default packet buffer size, I was able to transmit a UDP datagram from the one end of the testbed to the other without problems. :))

**Comment by miri64** [comment]
I think I have the same problem at the moment. Will look into that.

**Comment by miri64** [comment]
@OlegHahm are you on native or other platform? (native resets `GNRC_PKTBUF_SIZE` to 2048)

**Comment by OlegHahm** [comment]
I tested only on iotlab.

**Comment by miri64** [comment]
My problem was unrelated (see #5749), but nevertheless: will look into this ASAP.

**Comment by OlegHahm** [comment]
I figured that you will probably get more debug information if you revert #5665.

**Comment by miri64** [comment]
@OlegHahm its really just a hunch, but can you check if https://github.com/RIOT-OS/RIOT/pull/5694 fixes the problem?

**Comment by OlegHahm** [comment]
Just tested on master with same settings and 220 nodes on Lille site: nodes are still crashing.

**Comment by kYc0o** [comment]
Maybe this would be solved by #6083 ?

**Comment by kYc0o** [comment]
Ups sorry, didn't refresh the page and this was already referenced.

**Comment by miri64** [comment]
#6086 sadly did not fix this

**Comment by kYc0o** [comment]
Does anyone know if this is still an issue?

**Comment by kYc0o** [comment]
So far, I only found issues with the kw2x driver. With at86rf2xx everything works like a charm. Thus, I conclude there's no problem with gnrc.

Ok to close?

**Comment by miri64** [comment]
Might be that #9434 fixed this issue as well.

**Comment by kYc0o** [comment]
I'll remake the tests to configure the cases you mention and give a more complete feedback.

**Comment by miri64** [comment]
@cgundogan can you maybe retest this for the release?

**Comment by obgm** [comment]
Not sure if this is related: Testing via tap on native, after some successful UDP transmissions, `_gnrc_netif_thread` always gets stuck. DEBUG says: 
```
gnrc_netif: waiting for incoming messages
gnrc_netif: GNRC_NETDEV_MSG_TYPE_EVENT received
gnrc_netif: event triggered -> 2
gnrc_netif_ethernet: cannot allocate pktsnip.
gnrc_netif: waiting for incoming messages
gnrc_netif: GNRC_NETDEV_MSG_TYPE_EVENT received
gnrc_netif: event triggered -> 2
gnrc_netif_ethernet: cannot allocate pktsnip.

```

Increasing  `GNRC_PKTBUF_SIZE` increases the number of successful transmissions but sooner or later, the same error will occur.

**Comment by miri64** [comment]
> Not sure if this is related: Testing via tap on native, after some successful UDP transmissions, `_gnrc_netif_thread` always gets stuck. DEBUG says:
> 
> ```
> gnrc_netif: waiting for incoming messages
> gnrc_netif: GNRC_NETDEV_MSG_TYPE_EVENT received
> gnrc_netif: event triggered -> 2
> gnrc_netif_ethernet: cannot allocate pktsnip.
> gnrc_netif: waiting for incoming messages
> gnrc_netif: GNRC_NETDEV_MSG_TYPE_EVENT received
> gnrc_netif: event triggered -> 2
> gnrc_netif_ethernet: cannot allocate pktsnip.
> ```
> 
> Increasing `GNRC_PKTBUF_SIZE` increases the number of successful transmissions but sooner or later, the same error will occur.

This hints at a leak in the packet buffer. So it might be interesting which modules you are including and what your scenario it is so we can reproduce it. I don't see the relation to a smaller packet buffer however.

**Comment by miri64** [comment]
Ping @obgm?

**Comment by obgm** [comment]
Sorry for the delay: I wanted to re-test with my code and up-to-date fork. I will hopefully be able to provide recent data within the next days.

**Comment by miri64** [comment]
I'm swamped in work anyways, so I won't be able to fix this immediately, but it's good to keep the issue rolling ;-).

**Comment by miri64** [comment]
I was trying to reproduce this issue but I was not able to. Here is an detailed account of what I did:
- [still uploading]
