### ISSUE TITLE
cpu: cortexm_common: context switching code breaks when compiling with LTO

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#5774]
```
/tmp/ccLE0ZTV.s: Assembler messages:
/tmp/ccLE0ZTV.s:327: Error: invalid offset, value too big (0x00001078)
/tmp/ccLE0ZTV.s:377: Error: invalid offset, value too big (0x0000103C)
lto-wrapper: fatal error: arm-none-eabi-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/arm-none-eabi/6.1.1/../../../../arm-none-eabi/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
m
```

To get this error, merge #5742, remove the "SRC_NOLTO" line from `cpu/cortexm_common/Makefile` and compile with `LTO=1`.

**Comment by miri64** [comment]
I don't understand... did #5742 introduce this error or did it fix it...

**Comment by kaspar030** [comment]
#5742 allows selectively excluding files from being compiled with LTO, and does so with the cortexm context switching code.

**Comment by miri64** [comment]
That did not answer my question, just described things I don't understand :)

**Comment by kaspar030** [comment]
Well, see, the answer is not in the set you gave. The problem existed before and still does.

**Comment by kaspar030** [comment]
Sorry, is that clear enough? Before #5742, LTO compiles were not possible at all for most platforms. That PR includes many fixes originally made by @gebart, plus a way to exclude files if they still pose problems when compiling with LTO, like the hand-written assembler code in cortexm's ctx switching code. I opened this issue so we don't forget about that.

**Comment by kaspar030** [comment]
As LTO is quite effective without fixing this issue, and it's still optional and shouts "EXPERIMENTAL!" when enabled, this can be postponed...

**Comment by miri64** [comment]
So, since this is optional it's not a known issue? (that's all I want to know ;-))

**Comment by kaspar030** [comment]
I'd say, no. I mean, thanks to the workaround in #5742, LTO works fine on cortex-m, just the one file will not be link time optimized...

**Comment by miri64** [comment]
"No, it's not a known issue" or "No, it is a known issue"? (Double negatives are always tricky in natural languages ;-))

**Comment by kaspar030** [comment]
No need to mention this anywhere else but in this issue. ;)

**Comment by OlegHahm** [comment]
This is still an issue, right?

**Comment by kaspar030** [comment]
Yep, the problematic file is still excluded from LTO.

**Comment by kYc0o** [comment]
@kaspar030 can you confirm that #7776 was the fix for this?

**Comment by kaspar030** [comment]
Seems like gcc 9.1 has fixed this.

**Comment by kaspar030** [comment]
> Seems like gcc 9.1 has fixed this.

Let's wait until our Docker container uses a recent enough version of gcc, then remove the workaround.
