### ISSUE TITLE
iotlab-term: make tmux optional

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#5777]
This issue is two-fold:

1) I don't really understand the `iotlab-term` target in `Makefile.iotlab` anymore since the `tmux` logging feature was introduced in #5351 (main reason why I can't provide a fix myself). Considering that `make term` should be the simplest command of all that is a little disquieting.
2) Not everyone uses `tmux` and not everyone knows how to use it. The `iotlab-*` targets should simplify the usage of the IoT-Lab, so adding knowledge about another tool reduces the usability of these targets in my opinion.

**Comment by cgundogan** [comment]
>Considering that make term should be the simplest command of all that is a little disquieting.

Why should `term` be the `simplest` command? The idea of this makefile is to abstract and hide complex command executions.

>Not everyone uses tmux and not everyone knows how to use it.

See https://github.com/RIOT-OS/RIOT/blob/master/dist/testbed-support/README.iotlab.md#iotlab-term

One of the incentives of using the aggregator within tmux is that a user can now de-/attach from a running experiment. This was not possible before. I.e. you can start an experiment without the `iotlab-term` first, and just attach whenever desired and still see the full output (with or without logging enabled).

If you have discomfort with scrolling (I think we had an offline discussion about this once), then just put `setw -g mode-mouse on` in your `.tmux.conf` on the remote server. This could be put into the README as an improvement of the doc, but I don't see why we should drop tmux.

**Comment by OlegHahm** [comment]
While I mostly agree with @cgundogan here, I understand @miri64's concerns. How about offering a simple `iotlab-term` and an advanced `iotlab-tmux` target (maybe with different names)?

**Comment by miri64** [comment]
It's not like I don't know how to handle tmux, but as @OlegHahm states: it hightens the entry bar in my opinion.
