### ISSUE TITLE
make: Changing between LTO=1, LTO=0 does not trigger rebuild

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#5780]
`make LTO=1` followed by `make` does not trigger a complete rebuild.
Any CFLAGS changes should trigger a rebuild IMO.

**Comment by kaspar030** [comment]
This can be generalized: any changes to any Makefile (-variables) should trigger a rebuild.

I don't think there's an elegant way of doing this in make. Even making everything depend on all Makefiles won't fix commandline supplied variables.

I resorted to using ccache and always rebuild everything.

**Comment by kaspar030** [comment]
One way would be to add CFLAGS and LINKFLAGS to riotbuild.sh (as comment), so changing them causes a rebuild.

**Comment by kaspar030** [comment]
> CFLAGS and LINKFLAGS to riotbuild.sh (as comment), so changing them causes a rebuild.

Actually the whole CFLAGS are part of riotbuild.h, and every OBJC depends on it.

**Comment by kaspar030** [comment]
Ok, I'm getting there. Sorry for the noise. :)

As LTOFLAGS are only added to CFLAGS on a per-file basis, changing them doesn't change global CFLAGS and thus not riotbuild.sh.

**Comment by kaspar030** [comment]
Fixed by #5781.
