### ISSUE TITLE
kw2x: 15.4 duplicate transmits

### ISSUE THREAD

**Issue by smlng** [RIOT-OS/RIOT#5799]
I found that the kw2x is transmitting each 15.4 message twice with an interval of 2ms. 

I first thought my sniffer has some problems, but then I started samr21 node which does not exhibit this behavior. But I saw this behavior with different kw2x nodes. I put a small wireshark capture in my dropbox [here](https://dl.dropboxusercontent.com/u/19629108/kw2x_sniff.pcapng) shows it.

Note: source addresses ending on `3016` and `600a` are kw2x boards, the one with `47ee` is the samr21. Though this capture only shows RA this also applies to other messages (and types), too.

**Comment by smlng** [comment]
FYI: @cgundogan and @PeterKietzmann

**Comment by jfischer-phytec-iot** [comment]
short: in the current driver some things were not done properly :smile:. #5469 should fix it, testers are welcome.

**Comment by kYc0o** [comment]
I think this should be fixed by #6453. Can you @smlng try it again?

**Comment by smlng** [comment]
seems to be fixed with the adaption of netdev2 in #6453. I made some test and wireshark sniffs and cannot observe any duplicates anymore. So closing this!
