### ISSUE TITLE
[RFC] Global constant header

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#5805]
At the moment many (user-editable) constants are scattered in form of macros over the code base (e.g. address timeouts, thread priorities and stack sizes, packet buffer size, maximum link-layer address length, etc.). How about we collect them together in one single header file, that then gets included by those who need those constants?

**Comment by OlegHahm** [comment]
This goes in the direction of something like a `config.h` as discussed several times ago, right?

**Comment by miri64** [comment]
Did we? I didn't find an issue for that. But in general: yes.

**Comment by OlegHahm** [comment]
We had something like this back in old Firekernel days.

**Comment by miri64** [comment]
Why was it removed then?

**Comment by miri64** [comment]
To be clear I would like to have this header be optional for applications or - alternatively - in a central spot like `sys/include/` on `core/include`

**Comment by kaspar030** [comment]
I don't like it. If the constants are magic numbers belonging into one module, that's where they should be defined. If there's anything user configurable, it should still be there, just possibly enclosed by "#ifndef X, #define X <reasonable default>, #endif".

**Comment by OlegHahm** [comment]
Maybe this is rather a topic for the mailing list or a meeting?

**Comment by miri64** [comment]
Somewhat superceded by the efforts of the config TF.
