### ISSUE TITLE
xtimer: implement xtimer with 1s resolution or better over RTC on stm32l151

### ISSUE THREAD

**Issue by Cr0s** [RIOT-OS/RIOT#5841]
Hello,

It's possible to make a module that implements xtimer interface over an RTC to be able to wake-up the chip even from lowest power mode?

**Comment by immesys** [comment]
Just FYI I have done this on SAMR21 using #5608 and then switching the xtimer to the RTC. We have reliable wakeups from the lowest power mode (2.5uA)

**Comment by kYc0o** [comment]
Can anyone check if this was actually fixed by #5608 already merged? It does add support for 32768Hz for RTC clocks, but I didn't check.
