### ISSUE TITLE
Compiling outside of a git repo fails

### ISSUE THREAD

**Issue by vincent-d** [RIOT-OS/RIOT#5859]
Because of the `RIOT_VERSION` variable not available, the compilation outside of a git repo (for instance from the zip file downloaded fron github) fails.

```
Building application "hello-world" for "native" with MCU "native".

/bin/sh: 4: Syntax error: "(" unexpected
/home/vincent/Documents/RIOT-master/Makefile.base:64 : la recette pour la cible « /home/vincent/Documents/RIOT-master/examples/hello-world/bin/native/hello-world/main.o » a échouée
make[1]: *** [/home/vincent/Documents/RIOT-master/examples/hello-world/bin/native/hello-world/main.o] Erreur 2
/home/vincent/Documents/RIOT-master/examples/hello-world/../../Makefile.include:262 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```

I found that using the `RIOT_VERSION_OVERRIDE` fixes the issue, but the message is not clear. Is it known / a feature ?

**Comment by OlegHahm** [comment]
Interesting. A similar problem was fixed in #2241, but this seems to be a strange reincarnation. As a matter of facts, removing the white spaces from `RIOT_VERSION` in `${RIOTBASE}/Makefile.include` eliminates the error, but I failed to figure out how to escape them properly.
