### ISSUE TITLE
missing newlines in DEBUG output

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#5876]
```git grep 'DEBUG(".*);' | grep -v '\\n'``` shows many uses of DEBUG that are missing a final newline (```\n```).

**Comment by OlegHahm** [comment]
I have the impression that most of these lines were introduced by you. ;)

**Comment by kaspar030** [comment]
> I have the impression that most of these lines were introduced by you. ;)

Naaah. I count less than 10%. ;)

**Comment by OlegHahm** [comment]
Since I'm a good Newbie. :wink:
