### ISSUE TITLE
xtimer: usage in board_init() crashes

### ISSUE THREAD

**Issue by basilfx** [RIOT-OS/RIOT#5928]
Initializing and using xtimer before the kernel has initialized leads to a crash (no output, corrupted stack in gdb). I verified this for the Thunderboard Sense (EFM32) target and Seeeduino Arch Pro (LPC1768). I use it exactly the same as the Mulle board (#4133).

The problem does not happen when the delay is less than the backoff. So my workaround for sleeping 1ms is sleeping 100 times 10 µs.

Use case: The Thunderboard Sense has a I2C GPIO expander that needs 1ms of wakeup time. I address this GPIO expander to enable the sensors so they get initialized before `auto_init()`.

**Comment by miri64** [comment]
Why not use `periph/timer` for that?

**Comment by basilfx** [comment]
I don't have timers available, because the only timer available is reserved for xtimer.

Furthermore, it would be a workaround. Take #4133 as an example: if it would depend on `periph/timer`, it would make the nvram driver not less portable.

**Comment by kaspar030** [comment]
xtimer as is expects threading to be initialized, and that can only be changed with unacceptable runtime overhead.

> The problem does not happen when the delay is less than the backoff. So my workaround for sleeping 1ms is sleeping 100 times 10 µs.

That's because with these short delays, xtimer spins instead of issuing a task switch.

Why not work around the issue?

At startup time, using a simple ```volatile unsigned N = <number of ticks>; while(N--)``` for 1ms is IMHO perfectly acceptable. Or, move the expander initalization into auto_init() after xtimer.

**Comment by basilfx** [comment]
I'll go with the while-loop, as auto_init() would add board-specifics to the RIOT-OS's system.

But then again, #4133 is wrong (cc @gebart). If one would change the timings in the nvram driver, the mulle board would also crash.

**Comment by kYc0o** [comment]
Can we close this issue then?

**Comment by basilfx** [comment]
Yes :-)
