### ISSUE TITLE
native: `ncache add` shell command results in segfault

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#5930]
Found a way to cause a segfault in 'native': run the default example and simply call `ncache add` without any further argument -> segfault:
```
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: )
RIOT network stack example application
All up, running the shell now
> ncache add
ncache add
make: *** [term] Segmentation fault
```

I don't have time to look into this right now, but maybe we should fix this?! :-)

**Comment by LudwigKnuepfer** [comment]
@miri64  So this was not an issue with native but with the shell, right?

**Comment by miri64** [comment]
Yapp, @haukepetersen just encountered it on native.
