### ISSUE TITLE
libcoap pkg Makefile wrong link?

### ISSUE THREAD

**Issue by Lightertu** [RIOT-OS/RIOT#5935]
I notice that RIOT-OS has a fork of libcoap Which contains files, coap_io.c/h. However the link is being used in pkg/libcoap/Makefile is "https://github.com/OlegHahm/libcoap", which does not contain coap_io.c/h. After checked the libcoap's documentation, I assume that the RIOT-OS's fork is version 4.1.2 and the link used in the Makefile is 4.1.1. Also there is a "riot-port_new" branch in that RIOT-OS forked libcoap. Since There isn't any example application that uses libcoap pkg in RIOT/examples which link should be used in the Makefile?
Thank you

**Comment by OlegHahm** [comment]
@Lightertu, https://github.com/RIOT-OS/RIOT/blob/master/pkg/libcoap/Makefile contains a link to the upstream version of libcoap on Github. The revision in the package's Makefile should be the latest that is known to be working with RIOT.

**Comment by Lightertu** [comment]
thank you
