### ISSUE TITLE
Wifi on arduino mega2560

### ISSUE THREAD

**Issue by ThanasisArvas** [RIOT-OS/RIOT#5953]
Hello, I am working on a project using an arduino-mega2560 and a wifi shield ( https://www.arduino.cc/en/Main/ArduinoWiFiShield ). I am using riot-os and I am trying to enable wifi networking, but I was unsuccessful until now. Is there any example code that i can use? Any suggestions or directions on where to look for information will be greatly appreciated.

**Comment by PeterKietzmann** [comment]
Hi @ThanasisArvas we don't have support for that device. To use it one needs to write a device driver before. Do you intend to provide one for RIOT?

**Comment by OlegHahm** [comment]
Timeout
