### ISSUE TITLE
overflow in implicit constant conversion

### ISSUE THREAD

**Issue by sinkarharshad** [RIOT-OS/RIOT#5986]
I am trying to run a program from RIOT examples "arduino_hello-world" on arduino-uno. 

I am using "make BOARD=arduino-uno flash" command to run the code given in example. 

and I am getting this following error. 

![screen shot 2016-10-23 at 14 13 17](https://cloud.githubusercontent.com/assets/18270841/19626146/e4ea4634-992a-11e6-894c-50eeaec1b74c.png)

Kindly help me to resolve this issue. Thank you in advance.

**Comment by aabadie** [comment]
@sinkarharshad, I issued this [PR](#5987) to fix your issue. Feel free to try it and give some feedback.

**Comment by sinkarharshad** [comment]
@aabadie Thank you for your efforts sir, saw the issue #5987 : To try this updated changes .. do I need to trash my old RIOT and clone updated RIOT again to my system using "git clone git://github.com/RIOT-OS/RIOT.git" ? 

Thank you in advance.

**Comment by aabadie** [comment]
From your local RIOT repository, you can fetch my RIOT remote and checkout in the PR's branch:
```
$ git remote add aabadie git@github.com:aabadie/RIOT.git
$ git fetch aabadie
$ git checkout arduino_sketch_on_arduino
```

**Comment by sinkarharshad** [comment]
I tried, and getting following error: 
![screen shot 2016-10-24 at 11 22 13](https://cloud.githubusercontent.com/assets/18270841/19640264/2b43c180-99dc-11e6-99b6-ea6a606ab9ed.png)

**Comment by miri64** [comment]
@sinkarharshad use `git://github.com/aabadie/RIOT.git` or `https://github.com/aabadie/RIOT.git` instead.

```bash
git remote set-url aabadie git://github.com/aabadie/RIOT.git
```

**Comment by sinkarharshad** [comment]
@aabadie  @miri64  Thank you. 
I followed all the steps, and successfully run the code. But LED's did not flash on uno :! 
What exactly I am missing ): .. Kindly help!! Thank you in advance.
![screen shot 2016-10-24 at 11 32 54](https://cloud.githubusercontent.com/assets/18270841/19640606/ca728e2a-99dd-11e6-9673-285292b7a403.png)

**Comment by aabadie** [comment]
>  But LED's did not flash on uno :! 

Just checked that and in fact it does but too fast. This is because the sleep(500) has no effect. Looks like the xtimer doesn't work with this board.

**Comment by sinkarharshad** [comment]
@aabadie Hello Sir, I just observed that after running any program I am getting this 
main(): This is RIOT! (Version: 2016.10-devel-449-g51a0-Harshads-MacBook-Air.local-**arduino_sketch_on_arduino)**

Why there is "arduino_sketch_on_arduino" this thing coming? :! 
Kindly help and thank you in advance.

![screen shot 2016-10-24 at 22 55 45](https://cloud.githubusercontent.com/assets/18270841/19665407/2bd4e2be-9a45-11e6-8489-f341b95fda03.png)

**Comment by taher143** [comment]
> Looks like the xtimer doesn't work with this board.
how can we use delay for arduino code? timer? what is Xtimer? is it same as Timer0/1/2 in AVR ATmega328P?

**Comment by OlegHahm** [comment]
Did anyone open an issue for the xtimer problem?

**Comment by mali** [comment]
@OlegHahm : issue #6358 for xtimer problem

**Comment by OlegHahm** [comment]
Thanks!
