### ISSUE TITLE
How to get process ID in RIOT? 

### ISSUE THREAD

**Issue by sinkarharshad** [RIOT-OS/RIOT#6027]
I am trying to get the process ID in RIOT. But not able to do it and getting the following attached error :! . Same program is working fine in C++. 
![screen shot 2016-10-31 at 02 28 28](https://cloud.githubusercontent.com/assets/18270841/19841872/5e00c7c2-9f12-11e6-9eeb-552ff7e686da.png)

My code is as follows:

```C++
#include <iostream>
#include <sys/types.h>
#include <unistd.h>
#include <lpm.h>

using namespace std;

int main ()
{
    pid_t pidorzero = fork ();
    int x = 1;

    if(pidorzero < 0)
    {
        perror("fork () error");
    }

    if (pidorzero > 0)
    {
        cout << "I am the Parent Process with x: " << x << endl;
        cout << "ParentPID: " << getpid ()<< endl;  
    }

    else
    {
        cout << "I am the Child Process with x: " << x << endl;
        cout << "ChildPID: " << getpid() << endl;   
    }
    lpm_set(LPM_OFF);
    return 0;
}
```

**Comment by miri64** [comment]
(I allowed myself to edit your post to make the code more readable)

`fork()` is not implemented in RIOT yet and it is highly unlikely that it ever will be (every new process would need a memory stack which costs memory of which we only have little ;-)). Also consider to post your questions to the [devel@riot-os.org](https://lists.riot-os.org/mailman/listinfo/devel) or the [users@riot-os.org](https://lists.riot-os.org/mailman/listinfo/users) mailing list or the [IRC chat (chat.freenode.org #riot-os)](http://webchat.freenode.net?channels=%23riot-os). You are usually reaching a bigger, more diverse group of people there. The issue tracker is primarily used for reporting bugs so you will primarily find developers here ;-).

**Comment by miri64** [comment]
(if you want to get the process ID of your `native` instance: it is accessable through the [CPUID driver](http://doc.riot-os.org/group__drivers__periph__cpuid.html))
