### ISSUE TITLE
Question: how to write to a file in native mode 

### ISSUE THREAD

**Issue by lahmer** [RIOT-OS/RIOT#6125]
HI, I am trying to use riot in simulation in native mode and i want to write all the events to a log file how do i proceed by this ?

**Comment by miri64** [comment]
I'm not sure what you mean by "event" and if you just want to log stuff or if you want to log some internal behavior (e.g. ISR triggers, etc). For the latter I would recommend using the `real_open()`, `real_write()`, `real_close()` system calls to the host system in e.g. `cpu/native/irq_cpu.c` to write stuff into your log file. For the first I would suggest to wait for the file system support which is hopefully coming soon-ish to master (see #5616). It hopefully won't be long until we have some shared files with the host system then (if you want to do it hacky you can of course use the system calls mentioned above anywhere else too of course, but I would not recommend merging this to master ;-)).

**Comment by PeterKietzmann** [comment]
Have a look at the latest progress in #6072

**Comment by LudwigKnuepfer** [comment]
@lahmer if this does not answer your question, please clarify.

**Comment by OlegHahm** [comment]
Please shout if your question was not answered.
