### ISSUE TITLE
native: system reboots on SIGTRAP

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#6145]
To be honest, I'm not quite sure what happens, but at least it is reproducible.

**How to reproduce**
Call `core_panic()` from an application in native with `DEVELHELP` set.

**Expected result**
The application terminates with a segfault and coredump, because `panic_arch()` on native calls ` kill(_native_pid, SIGTRAP)` if `DEVELHELP` is set.

**Observed result**
The application reboots 81 times, before it finally segfaults.

**Additional observation**
If I kill the process with `kill -SIGTRAP` it dies immediately as expected.

Bisecting revealed that this behavior was introduced with a678e868e9487116228a2996880c6aded4dd590a.

**Comment by smlng** [comment]
Cannot observe this behaviour with `2018.01-RC2` not on Linux native nor on macOS native.
