### ISSUE TITLE
Sema dropping messages

### ISSUE THREAD

**Issue by lebrush** [RIOT-OS/RIOT#6151]
When a thread uses semaphores (concretely [`sema_wait_timed`](https://github.com/RIOT-OS/RIOT/blob/master/sys/sema/sema.c#L131)) messages are dropped from the message queue. This causes a thread acting on messages to lose events due to the use of a semaphore. Imagine a thread receiving events from [drivers, other threads, ...] and depending on the message it send a message using lwip. Since the current implementation of [lwip](https://github.com/RIOT-OS/RIOT/blob/master/pkg/lwip/contrib/sys_arch.c#L79) relies on the `sema_wait_timed` method, messages are just dropped. This is a kind of non obvious behaviour and difficult to track. I guess it's also a non desired behaviour.

Has anyone dealt with a similar situation already?

One option would be to modify the `sema` API to avoid this case. However, I rather suggest the following change in the `msg` API in order to be more consistent with the handling of messages.

 - Add `msg_receive_type(msg_t *m, uint16_t mask)` and similar `msg_try_receive_type(...)` where the receiving thread can specify a mask for the messages it is interested in. The other messages are not dropped and keep the same position in the queue.
 - Tackle #1749

This would allow a much finer control of the communication between threads and a starting point to define a reserved range to be used by the system and libraries as in #1749.

If you agree, I'd prepare a PR for the first point.

**Comment by miri64** [comment]
Adding kaspar due to the change request to `msg`'s API.

**Comment by miri64** [comment]
I'd rather prefer to have semaphore implementation with no IPC whatsoever btw.

**Comment by miri64** [comment]
(maybe using thread flags? ;-))

**Comment by lebrush** [comment]
Good point @miri64, I'll have a look at it :+1:

**Comment by lebrush** [comment]
@miri64 please have a look at #6155

**Comment by lebrush** [comment]
#6155 got merged
