### ISSUE TITLE
 You need help to advance support for Teensy 3.x

### ISSUE THREAD

**Issue by RndMnkIII** [RIOT-OS/RIOT#6161]
I dont see any advances in Teensy 3.x since I saw the work in progress in supported platforms some months ago. Any technical problem with the freescale cpu?

**Comment by OlegHahm** [comment]
@thomaseichinger, do we?

**Comment by thomaseichinger** [comment]
I am not actively working on this and haven' been in a while so there was a lot of interface changes in the meanwhile. 
@RndMnkIII Every helping hand is always welcome. In that case it'd be more starting over I guess.

**Comment by RndMnkIII** [comment]
Sorry, I've concentrated in another project that requires me to full time

**Comment by DipSwitch** [comment]
The only technical problem I have, is that I technically don't have enough spare time to finish what I started ;) But there is light at the end of the tunnel =)

**Comment by gebart** [comment]
Closing since Teensy 3.1 and 3.2 support was added by #8210
