### ISSUE TITLE
base64_encode calculates wrong output size

### ISSUE THREAD

**Issue by nikosft** [RIOT-OS/RIOT#6166]
The formula of base64_encode  for calculating base64_out_size is wrong (RIOT/sys/base64/base64.c  lines 62,63). For example for data_in_size = 16 it outputs 26, whereas the correct size is 24.

**Comment by x3ro** [comment]
For easier reference here's [a link to the file](https://github.com/RIOT-OS/RIOT/blob/1e8d76870140c2ab76ed3cebb9e5980bcfc77856/sys/base64/base64.c#L62) at the current point in time.

**Comment by x3ro** [comment]
This observation appears to be correct, and a bug in our base64 implementation. [This C implementation I've found](http://stackoverflow.com/a/6782480) appears to calculate the correct output size result using the formula

    4 * ((input_length + 2) / 3)

Comparison to the Wikipedia example values: [Wikipedia example values](https://en.wikipedia.org/wiki/Base64#Output_Padding)

| Input Length | Output (correct) | Output (ours) |
|--------------|------------------|---------------|
| 20           | 28               | 29            |
| 19           | 28               | 30            |
| 18           | 24               | 27            |
| 17           | 24               | 25            |

**Comment by BytesGalore** [comment]
@nikosft thx for the pointer on this!
@x3ro I changed the used formula to: `((4 * n / 3) + 3) & ~3` which should fix the wrong calculation.

**Comment by x3ro** [comment]
@BytesGalore We should definitely add a test for this, though, right? Does fixing this interfere w/ the rest of the algorithm as it stands?

**Comment by BytesGalore** [comment]
> We should definitely add a test for this, though, right?

yup will add some tests, mom.

> Does fixing this interfere w/ the rest of the algorithm as it stands?

not I'm aware of.

**Comment by BytesGalore** [comment]
@x3ro now uses your proposed formula and I added a small test to check the encoding size determination based on the wikipedia lengths.
