### ISSUE TITLE
Try to run "include-what-you-use" over our code?

### ISSUE THREAD

**Issue by Kijewski** [RIOT-OS/RIOT#6167]
I just came across https://github.com/include-what-you-use/include-what-you-use:

> "Include what you use" means this: for every symbol (type, function, variable, or macro) that you use in `foo.cc` (or `foo.cpp`), either `foo.cc` or `foo.h` should include a .h file that exports the declaration of that symbol. (Similarly, for `foo_test.cc`, either `foo_test.cc` or `foo.h` should do the including.)  Obviously symbols defined in `foo.cc` itself are excluded from this requirement.
>
> This puts us in a state where every file includes the headers it needs to declare the symbols that it uses.  When every file includes what it uses, then it is possible to edit any file and remove unused headers, without fear of accidentally breaking the upwards dependencies of that file.  It also becomes easy to automatically track and update dependencies in the source code.

Sounds good, doesn't it?

PS. as of 2016-11-29 18:05 CET the project has [1000 "stars"](https://github.com/RIOT-OS/RIOT/stargazers)!

**Comment by tfar** [comment]
It sounds good, but it's not trivial to use on larger projects. At least if you want to have it to use the right headers (public headers, instead of private ones where stuff is specified). But don't let that stop you from giving it a shot. It's pretty easy to build though.
