### ISSUE TITLE
New board suggestion: nRF52840 DK

### ISSUE THREAD

**Issue by kbumsik** [RIOT-OS/RIOT#6180]
Hello,
There is a new MCU board just came out: [nRF52840 Preview DK](https://www.nordicsemi.com/eng/Products/nRF52840-Preview-DK).
It looks almost same as nRF52 DK currently being developed in this repo, but it has much nicer radio: IEEE 802.15.4 with Bluetooth 5-ready (nRF52 DK doesn't support 802.15.4 as far as I know).
Of course it just came out and may not be a mature hardware, but I am just wondering if RIOT would  consider this board a strong candidate for future hardware?

**Comment by emmanuelsearch** [comment]
Thanks for the tip.
Looks like a nice candidate indeed. 
The triple-mode radio looks great.
However, I would not list this as an issue (hence I close this "issue" ;).
To continue the conversation on this topic, either go to the devel mailing list, or, if someone starts porting (you?) and encounter issues, then open another issue.

**Comment by Zhiyi-Zhang** [comment]
So do we have the support for nRF52840 DK in RIOT now?

**Comment by marrakchino** [comment]
@Zhiyi-Zhang yes. You can find it in `boards/nrf52840dk`
