### ISSUE TITLE
stm32x unified timer not applied to all Boards periph_config.h

### ISSUE THREAD

**Issue by fjmolinas** [RIOT-OS/RIOT#6227]
During the last release a unified version on the timers was built for all STM32x, changing the config structures for a bunch of them put not all board had there periph_config.h changed accordingly. For example the  LimiFrog v1 using the STM32L151RC uC, still implements the old timer config structure witch doesn't work in the new format.

**Comment by OlegHahm** [comment]
The title of this PR looks a bit misleading. Could you modify it?

**Comment by haukepetersen** [comment]
Hm, i wonder how this slipped through Murdock...

**Comment by haukepetersen** [comment]
Hmm, just re-checked: I could not find any STM32 based board that still uses the old timer configuration... The limifrog builds just fine on the current master...

@fjmolinas could you maybe give some more concrete example where you run into trouble?

**Comment by fjmolinas** [comment]
If you look at the new timer structure, defined in periph_cpu_common.h this is the format:
 `/**
 * @brief   Timer configuration
 */
typedef struct {
    TIM_TypeDef *dev;       /**< timer device */
    uint32_t max;           /**< maximum value to count to (16/32 bit) */
    uint32_t rcc_mask;      /**< corresponding bit in the RCC register */
    uint8_t bus;            /**< APBx bus the timer is clock from */
    uint8_t irqn;           /**< global IRQ channel */
} timer_conf_t;`

Where as, if you look at the limifrog the timer structure is:

`/**
 * @brief Timer configuration
 * @{
 */
static const timer_conf_t timer_config[] = {
    /* device, RCC bit, IRQ bit */
    {TIM5, 3, TIM5_IRQn},
};`

So even if it builds I would find it weird if it works right since it's missing elements and they aren't in the right order in the struct.

**Comment by haukepetersen** [comment]
I see, have only tried to build it without looking at the code... Fixed with #6256

**Comment by haukepetersen** [comment]
and thanks for pointing this out!

**Comment by PeterKietzmann** [comment]
#6256 was merged, I'll close this issue. @fjmolinas please ping me if you don't see this issue solved
