### ISSUE TITLE
Port RIOT for specific device

### ISSUE THREAD

**Issue by juttTechnology** [RIOT-OS/RIOT#6246]
is there any tutorial or easy way to port the code for the specific device (e.g Nrf52).
i would like to use the Visualgdb. i Really do not like that all the files will compile in background, Means
i like to add all the files into the Visualgdb.so i can compile and debug step by step. ofcouse then i will not use the make file from the RIOT OS.
as for as i know.
i need to follow the makefiles rules and add the all required files into the project.but this  took too much time.
any easy workout to use the RIOT files into the Visualgdb.

thank you

**Comment by mali** [comment]
Have you take a look at the wiki ?
There is a [Porting Guide](https://github.com/RIOT-OS/RIOT/wiki/Porting-Guide) and lot more informations. 
You cans use `make QUIET=0` to have a full compilation log, I think that's what you mean by : 

> i Really do not like that all the files will compile in background

Nothing to say about VisualGDB, I don't know nor use it.
