### ISSUE TITLE
Add External Library 

### ISSUE THREAD

**Issue by ciolo** [RIOT-OS/RIOT#6275]
Hello everyone.
I have to use this library with RIOT on open mote CC2538:
https://github.com/bro/broccoli
I installed the library with "./configure, make and make install", i moved the broccoli library in to pkg folder of RIOT. Then, I added the USEPKG macro in my application's Makefile but when i use "include <broccoli.h>" in main.c of my test program i have this error: /home/user/RIOT/examples/hello-world/main.c:23:22: fatal error: broccoli.h: No such file or directory
 #include <broccoli.h>.
Why?

Thank you very much.

**Comment by kYc0o** [comment]
Hi! Sorry for the delay, have you found the answer to your problem?

If not, you might want to take a look [here](http://api.riot-os.org/group__pkg.html).
