### ISSUE TITLE
#include "board.h" in hashes/sha256.c

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#6280]
Anyone knows why [this](https://github.com/RIOT-OS/RIOT/blob/master/sys/hashes/sha256.c#L50) line is necessary?

I see that is included in a commit which checks for endianess but maybe there's another way to know it? Without this include this library is more portable (which is my need).

If no objections, I'd like to remove it.

**Comment by kYc0o** [comment]
I explored a bit the reason and seems safe to remove it...

**Comment by OlegHahm** [comment]
I could imagine that the `#ifdef __BIG_ENDIAN__` is the reason for that line. Since none of the supported boards is big endian, this wouldn't change a thing for now.

**Comment by kYc0o** [comment]
See #6288
