### ISSUE TITLE
Hello world with Eclipse IDE 

### ISSUE THREAD

**Issue by juttTechnology** [RIOT-OS/RIOT#6281]
i am working with eclipse IDE to build the hello world example.
i am blocked on the setp Number 5 of this tutorial. [Link](https://github.com/RIOT-OS/RIOT/wiki/Using-the-Eclipse-IDE-for-C-and-CPP-Developers,-Howto)
when i try to run this command 
make BOARD=nrf52dk eclipsesym
i got the following error.
![shell](https://cloud.githubusercontent.com/assets/20758400/21596341/475db976-d13a-11e6-86f1-06d6e47da014.png)

thank you

**Comment by OlegHahm** [comment]
Well, my first guess, looking at the output, would be that you will have to install wget or curl.

**Comment by juttTechnology** [comment]
i am using windows 10. when i try to install the curl, i was unsuccessful.
i seems like, he is working on linux or ubuntu.
on windows its not easy to put this working.

**Comment by gebart** [comment]
On Thu, Jan 5, 2017 at 1:49 PM, juttTechnology <notifications@github.com> wrote:
>
> i am using windows 10. when i try to install the curl, i was unsuccessful.
> i seems like, he is working on linux or ubuntu.
> on windows its not easy to put this working.
>

Most RIOT developers are using some variant of Linux or MacOS for
development. There are some people writing on the mailing lists about
working with RIOT in Windows, but I haven't followed the developments.
