### ISSUE TITLE
sys: net: gnrc: performance regression

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#6299]
Using @PeterKietzmann's l2 reflector, we've identified a couple of inefficiencies in gnrc_netdev2_ieee802154, mostly through unnecessary but expensive pktbuf alllocations:

- [ ] always calls gnrc_pktbuf_realloc_data() (fix in #6294)
- [ ] iovec for pktsnip is allocated in pktbuf
- [ ] allocate whole pkt, allocate header, mark payload, throw away header is inefficient.

**Comment by miri64** [comment]
@kaspar030 could you please update the description?

**Comment by miri64** [comment]
This should be fixed to my knowledge. @kaspar030 please reopen if you disagree.
