### ISSUE TITLE
emb6 on native

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#6353]
By building all the tests for native I found that emb6 requires SPI to work... IIRC emb6 is the implementation of the Contiki's IPv6 network stack is it? Shouldn't it build (and run) in native too?

```console
There are unsatisfied feature requirements: periph_spi


EXPECT ERRORS!


Building application "emb6" for "native" with MCU "native".
```

**Comment by miri64** [comment]
emb6 only is the 6LoWPAN part of UIP, so without socket_zep it doesn't make much sense to port it to native.

**Comment by kYc0o** [comment]
OK! Thanks!
