### ISSUE TITLE
examples/gnrc_border_router README.md is outdated

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#6354]
I tried to understand how to configure an Ethernet based border router and the first thing it said I would need to do is this:
> ... replacing the line
>```
> USEMODULE += gnrc_slip
> ```
> with something like
> ```
> USEMODULE += encx24j600
> ```
There is no `USEMODULE += gnrc_slip` in the Makefile, however.

Maybe it would make sense to split this off into a new section while fixing it?

**Comment by kYc0o** [comment]
Opened #6964 

I also remove the bug label since it's not really a bug, but a quality defect in my opinion.

**Comment by kYc0o** [comment]
Fixed in #6964
