### ISSUE TITLE
Clean up module 'posix' 

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#637]
The module `posix` mixes several not necessarily related features like POSIX I/O and file descriptors. This should be split up and named accordingly. Furthermore, the fd implementation relies on uart0, but this should be optional and configurable.

**Comment by authmillenon** [comment]
Is this still an issue or was this fixed by stuff like `uart_stdio`,  `sema`,  etc.

**Comment by OlegHahm** [comment]
`fd.c` still seems to reside outside a module, but otherwise this looks rather good in the mean time.

**Comment by miri64** [comment]
This should be fixable for the release.

**Comment by miri64** [comment]
Though... considering #5616, I'd like to wait for @gebart answer there.

**Comment by miri64** [comment]
After some consideration I came to the conclusion that `fd` would be removable with #5616 merged. Until then I would like to keep it for the sockets.

**Comment by lebrush** [comment]
@miri64 Heads up here: #5616 got merged :-)

**Comment by miri64** [comment]
I know ;-). I'll look into it.
