### ISSUE TITLE
Proposal:  Use Gitter to allow users and developers easier and simpler chat functionality

### ISSUE THREAD

**Issue by antmerlino** [RIOT-OS/RIOT#6416]
I am a relatively new user to Riot OS.  I understand that this type of proposal from a new user may be frowned upon or unwarranted.  So I understand if this idea gets shot down and closed.  However, I would like to see if there is any interest in using Gitter rather than freednode and the mailing lists (or maybe the mailing lists stay in parallel) for developers and users to chat.  

I have worked with other open source projects (ardupilot for one) that use Gitter for real-time interactions between developers and with users.  The interface is clean and easy to use, integrates with GitHub nicely, and has infinite message persistence.  

Does anyone else think this would be a big improvement in helping the community grow?

**Comment by kaspar030** [comment]
Please ask again on the mailing list!
