### ISSUE TITLE
Jenkins: Show status of each individual build group as red/green

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#6426]
I don't know Jenkins very well, so excuse me if this already exists somewhere.
I would like to have a status page where we can see the status of each build group in the CI build, something like what Travis used to show when we used the build matrix feature to select settings.
I have seen this page: 
https://riot-ci.inet.haw-hamburg.de/job/RIOT/view/change-requests/job/PR-3263/2/flowGraphTable/
but it only shows success on everything until the last step where it shows a red ball "Error signal - (1 ms in self)"

**Comment by miri64** [comment]
In general some parsed output of the log files would be nice. Oftentimes they are not really helpful in finding the error unless you use `Ctrl+F`

**Comment by miri64** [comment]
(To my knowledge there are plugins to parse GCC's output, so this shouldn't be that much of a deal [baring the usual config hell of Jenkins of course])

**Comment by smlng** [comment]
Jenkins is no more 😢 hence, closing
