### ISSUE TITLE
Jenkins: Shows unrelated commits under "Changes" heading

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#6439]
Change list shows commits which have been added to master after the PR was branched. It should only show the commits on the PR branch, not the master changes.

Example: https://riot-ci.inet.haw-hamburg.de/job/RIOT/view/change-requests/job/PR-5688/8/

![image](https://cloud.githubusercontent.com/assets/317506/22151008/6551f4a2-df1c-11e6-850c-47f6b3df0b8b.png)

**Comment by smlng** [comment]
it shows changes between consecutive builds of that specific PR, **not** between PR and master. Mostly after a rebase you see lots of changes ... so its (only) a bit counter-intuitive what _changes_ means (or what Jenkins refers to) here

**Comment by smlng** [comment]
Jenkins is no more 😢 so closing
