### ISSUE TITLE
cpu/lpc2387: periph interrupt do not yield thread (?)

### ISSUE THREAD

**Issue by lebrush** [RIOT-OS/RIOT#6443]
I observed that the IRQ handlers of the peripherals of this cpu do not include a `thread_yield_higher`. Is this handled somewhere else?

**Comment by OlegHahm** [comment]
ARM7 is a special case (it was the first platform supported by RIOT's kernel). The context switch should be done here:
https://github.com/RIOT-OS/RIOT/blob/master/cpu/arm7_common/common.s#L139

**Comment by kaspar030** [comment]
@OlegHahm is right, ARM7 does the check on every context switch.

**Comment by lebrush** [comment]
Thanks! :-)
