### ISSUE TITLE
cpu/stm32x: timer driver wrongly asserts 4 CC channels

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#6495]
Currently, the shared timer driver for the STM32 CPUs expects the used timer to have exactly 4 capture-compare channels. This is not true for all hardware timers on these CPUs, leading to some constraints when configuring the timer that is used.

It might make sense to alter the timer driver so that it can cope with a different number of cc channels...

**Comment by RichardH92** [comment]
This is referencing the TIMER_CHAN definition in /cpu/stm32_common/include/periph_cpu_common.h? Would it be best to add this as a parameter in the Makefile?
