### ISSUE TITLE
cpu/stm32l1: RTC broken

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#6502]
Seems like #6448 broke the RTC for the `stm32l1` (at least on the `nucleo-l1`): the CPU is stuck when calling `rtc_init()`. Investigating this now...

**Comment by haukepetersen** [comment]
seems like they are all related...

**Comment by haukepetersen** [comment]
the `l1` was somehow broken really really bad -> we need to work on our regression testing!

**Comment by haukepetersen** [comment]
found the error: my `nucleo-l1` does not have an external low-speed oscillator equipped... Time for some more granular configuration I guess...

**Comment by vincent-d** [comment]
@haukepetersen I was about to ask if there was a LSE. I remember when reading the nucleo user manual, that some parts number have small differencies regarding the LSE.

It's not easy to solve, but I can imagine different options:
- duplicate the boards for the different part numbers: definititely not optimal
- improve the periph_conf.h comments, it's then up to the developper to update the file: maybe the easiest
- improve the rtc driver to avoid looping infinitely waiting for the LSE to be ready, and return an error (but rtc_init is `void rtc_init(void)`) or fallback to the LSI, but the LSI might not be precise enough to run the rtc correctly: more complicated and we're not sure to cover every corner case

**Comment by haukepetersen** [comment]
The solution is IMHO simple:  #6504

**Comment by aabadie** [comment]
This one can be closed since #7504 was merged.
