### ISSUE TITLE
UART_NUMOF confliction with stm32_common/periph/uart.c

### ISSUE THREAD

**Issue by antmerlino** [RIOT-OS/RIOT#6522]
I am currently working on an STM32 board that does not have any available UARTS broken out.  Looking at stm32_common\periph\uart.c there is a header guard around all code that basically eliminates all code if UART_NUMOF has not been defined.  So I tried removing the define from my periph_conf.h file.  

But then, uart.h in drivers\include\periph\ checks to ensure that the define UART_NUMOF has been defined.  Otherwise, it throws an error.  

This is an easy fix that I'll put up a PR for, but I'd like to get feedback on what the better fix is. 

Solution 1)  Change the check in stm32_common\periph\uart.c to
```
#if UART_NUMOF > 0
```

Solution 2) Remove the UART_NUMOF check from uart.h

I think overall solution 1 is better.  It forces people writing board drivers to explicitly state the number of UARTs still.

Let me know if anyone has any suggestions, otherwise I'll do solution 1 and put up a PR

**Comment by haukepetersen** [comment]
I opt for solution 2): I don't like having these 'void' statements (`#define UART_NUMOF 0`) in the boards config. IMHO the config should be as compact as possibly -> only define whats there vs define also what's not there...

Fixed in #6607
