### ISSUE TITLE
tests/thread_cooperation doesn't work on 8 and 16 bit platforms

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#6527]
While testing some threading on 8 and 16 bit boards I noticed that something is wrong with the calculation of the result on this example. The rest of the test runs correctly so it's certainly due to integer sizes but I didn't find how to fix it quickly.

This is the output:

```console
2017-01-31 10:54:51,339 - INFO # Factorial: -1024
2017-01-31 10:54:51,371 - INFO # [!!!] Error, expected: 12!= 479001600.
2017-01-31 10:54:51,388 - INFO # finished
```

**Comment by kaspar030** [comment]
> I didn't find how to fix it quickly.

See #6528.
