### ISSUE TITLE
Objcopy not found error

### ISSUE THREAD

**Issue by alexiss03** [RIOT-OS/RIOT#6793]
Hi RIOT team,

I am having this error when running the command **make all BOARD=iotlab-m3** inside the _/examples/default_ directory.

```
RIOT/cpu/Makefile.include.gnu:14: objcopy not found. Hex file will not be created.
Compiler arm-none-eabi-gcc is required but not found in PATH.  Aborting.
```

What do you I need to do this remove this error? Am I missing a package? 

Thanks,
Lexi

**Comment by gebart** [comment]
You need to install a compiler and tool chain. See https://github.com/RIOT-OS/RIOT/wiki/Family:-ARM for some more information on toolchains for Cortex-M
See also the guides on the wiki https://github.com/RIOT-OS/RIOT/wiki

Closing this ticket because it's not a problem in RIOT

**Comment by alexiss03** [comment]
Thanks!
