### ISSUE TITLE
doc: `@ingroup` tags in *.c files

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#6830]
Throughout the code-base some (but not all) c-files contain a Doxygen `@ingroup` tag. First of all, shouldn't it be an `@addtogroup` tag instead (since it does not define a new group). Second, why is it there in the first place? C-files are not compiled by Doxygen.

**Comment by miri64** [comment]
I would prefer to remove them, since there is no way to check if they are correct anyways (other than compiling the c-files with doxygen).

**Comment by smlng** [comment]
mhm, from the doxygen docu one either uses `@defgroup` together with `@ingroup` tags **or** `@addtogroup` *instead* of the other two

**Comment by miri64** [comment]
> mhm, from the doxygen docu one either uses @defgroup together with @ingroup tags or @addtogroup instead of the other two

That's what I said ;-) "First of all, shouldn't it be an @addtogroup tag instead (since it does not define a new group)."

**Comment by smlng** [comment]
do we have any _rules_ when to use which variant for documentation?

**Comment by miri64** [comment]
Nope.

**Comment by smlng** [comment]
as expected, then ... its inconsistent all over the place, even if `@defgroup` is used its not clear where to define it first. 

For instance:

- `sys/include/hashes.h` has an `@ingroup sys_hashes`, the group is defined in `sys/hashes/doc.txt`
- `sys/include/fmt.h` has `@defgroup sys_fmt` and `@ingroup sys` in itself, no extra `doc.txt`
- `sys/include/fd.h` simply uses `@addtogroup posix`

**Comment by smlng** [comment]
might be something for the DocTF, if still active?

**Comment by miri64** [comment]
> might be something for the DocTF, if still active?

sporadic activeness :rofl:

**Comment by miri64** [comment]
I don't care about this anymore
