### ISSUE TITLE
make buildtest broken

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#6833]
I have a weird problem with `make buildtest`: it fails since some time with the following error:
```
/home/hauke/dev/riot/RIOT/boards/nucleo-f302/Makefile.features:1: *** missing separator.  Stop.
```

When I delete the first line from `boards/nucleo-f302/Makefile.features`, it works fine. If I put something like `FOO = 123` in the first line, it builds fine. If I put an empty newline in the first line, it gives the error above. If I put any random comment (starting with `#`) in the first line, the error above appears. Anyone any idea?

**Comment by gebart** [comment]
Try looking at the location where the file is included from. Perhaps there are some weird constructs around the include line.
