### ISSUE TITLE
[xtimer] count down mode timer

### ISSUE THREAD

**Issue by kamejoko80** [RIOT-OS/RIOT#6841]
I'm porting RIOT to ARM cortex-A9, the CPU has 32bit timers with count down mode only, it will generate interrupt when timer reaches to Zero. Now I'm stuck at xtimer wrapper layer implementation, almost another platform are using count up mode timer.
Please show me some hints. My porting task is almost done except xtimer.

Thank you very much.

**Comment by gebart** [comment]
The kinetis hardware lptmr (periph/timer.c) only support down counting mode, you could look there for ideas.

**Comment by kamejoko80** [comment]
Hello Gebart,

Thanks so much for your reply, let me check.
