### ISSUE TITLE
nrf52dk status

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#6865]
I'm currently trying to use this board for some development but I found that is broken since release 2016.07.

It is certainly due to the nordic softdevice library which was broken since some time ago, but was never fixed. Since then, several changes to RIOT can also make difficult to fix it.

So, my proposition is to disable the softdevice for this board and enable it when it gets fixed.

Any suggestions?

**Comment by PeterKietzmann** [comment]
Related to #6379?

**Comment by kYc0o** [comment]
Certainly. Should we close this one since it's a duplicate?

**Comment by PeterKietzmann** [comment]
Maybe close one of both, don't know which one. Depends on the issue you describe here. Is you issue more generic? Just close the one you think makes more sense.

**Comment by kYc0o** [comment]
I think the best idea should be to find why it's broken, open an issue describing it and close both, since the board it actually works without the softdevice enabled (as @haukepetersen did for nRF52840dk in #6863).

**Comment by kb2ma** [comment]
Forgive my ignorance, but does the absence of softdevice mean the device is incapable of 6lo and IP?

**Comment by haukepetersen** [comment]
@kb2ma yes and no, depends on how you look at it: when falling back to the `nrfmin` driver, the board is able to run 6lo and IPv6, but on it's own prorietary link layer, so it won't be compatible with BLE or 15.4...

**Comment by kYc0o** [comment]
So I propose to close this issue and move into #6379.
