### ISSUE TITLE
doc: HTML docs broken with Doxygen >=1.8.12

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#6910]
https://github.com/doxygen/doxygen/commit/8480d35beef57ed08139b58972bfb83a3b37422c
seem to break the new design from #6878 
Screenshot:
![screenshot_20170414_104035](https://cloud.githubusercontent.com/assets/317506/25039072/2d3944da-2102-11e7-96e8-636b371e4cc3.png)

Web browser console shows:
```
Uncaught TypeError: $(...).smartmenus is not a function
    at initMenu (menu.js:25)
    at HTMLDocument.<anonymous> (modules.html:83)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.K (jquery.min.js:2)
```

**Comment by miri64** [comment]
Can you send me the html directory zipped?

**Comment by gebart** [comment]
Try this link: https://www.dropbox.com/sh/8elyl6kb6at1j9k/AABuCBA7XS7DZDOTLhvjXbQwa?dl=0

**Comment by miri64** [comment]
Ah okay, the use this one https://github.com/vadikom/smartmenus now for the menus instead of handcrafting them. I will look into that. For now since this isn't in the auto-gernerated doc, let's keep this issue open.

**Comment by miri64** [comment]
@gebart can you try with https://github.com/RIOT-OS/RIOT/pull/6914?

**Comment by axelosorio** [comment]
this solution work for me
https://www.smartmenus.org/forums/topic/conflicting-jquery/
