### ISSUE TITLE
Port RIOT to SAM4 family

### ISSUE THREAD

**Issue by yennhan1211** [RIOT-OS/RIOT#6941]
Thanks for great working and beautiful OS. Is there any plan or schedule to port Riot to Atmel sam4 family.
If this question is duplicate, pls help me to remove it.

Thanks in advance.

**Comment by PeterKietzmann** [comment]
@yennhan1211 there are no current plans or ongoing efforts, which does not mean that there is generally no interest in that. If you consider contribution a port, #7622 might have simplified things. If you didn't start yet but you plan to, please ask around on the developers mailing list before. And don't hesitate to open new issues, if you find some. This one I'm going to close now
