### ISSUE TITLE
Segger GDB with TUI has bad newlines.

### ISSUE THREAD

**Issue by kbumsik** [RIOT-OS/RIOT#6985]
Hello, I am porting Arduino MKR1000. I am sorry this question is not directly RIOT-OS related.
I am currently flashing/debugging the device using Segger EDU connected via SWD.

To run the debugging session, I run `TUI=1 BOARD=arduino-mkr1000 make debug` (I made a new board directory for MKR1000.) And the terminal shows me this screen:

![untitled picture](https://cloud.githubusercontent.com/assets/7823583/25569239/285e4ba4-2de1-11e7-9906-a007c05be573.png)

As you can see, the command line catches newlines badly. I cannot keep debugging because the screen will become totally unreadable over time. Did anybody have this problem before? I posted this question because I am not sure where to ask... The programming environment is Ubuntu GNOME3 16.04.2 LTS and the terminal is GNOME terminal.

**Comment by aabadie** [comment]
Hi @kbumsik,

Good to hear that someone else is interested in mkr1000. Some times ago, I opened #6666 to add support for this board.
Maybe you can have a look/review it ?
My port doesn't use the SWD programming but [Bossa](https://github.com/shumatech/BOSSA) like in Arduino IDE: so I don't have debugging facility with it.

**Comment by kbumsik** [comment]
Hi @aabadie ,
Great. I am happy that someone is working on it. I quickly looked through your PR, and it looks like there are some codes that I could add :). I will make a PR to your branch when I finish reviewing it.

**Comment by aabadie** [comment]
> I will make a PR to your branch when I finish reviewing it

That would be nice !
do you also plan to add the wifi driver ?

**Comment by kbumsik** [comment]
@aabadie 
Yes. I already have experience in porting ATWINC1500's wifi driver on a bare-metal MCU. But I worried it won't be compatible with RIOT's network stack...

**Comment by aabadie** [comment]
@kbumsik, if you can first provide the driver on its own PR with a usable API it would be great and mergeable fast. We'll see later how to integrate it in RIOT network stack.

**Comment by kbumsik** [comment]
I found a perfect alternative to GDB TUI debugging. Segger provides [Ozone](https://www.segger.com/ozone.html) a perfect GUI debugging program. It doesn't require complicated configuration. Just put an `.elf` file and it works! Closing the issue.
