### ISSUE TITLE
Better document how to use devices that support auto_init

### ISSUE THREAD

**Issue by aabadie** [RIOT-OS/RIOT#7001]
As raised in #6982, we need to better explain newcomers how to build applications using the auto_init modules.
This is the case for `examples/default` and for the networking specific examples (gnrc_networking, microcoap, nanocoap, gcoap, etc).

The idea is to create a common doxygen page explaining the principles of auto_init and listing all devices that support it. Then in the README files of concerned examples, add a link to this page.

**Comment by miri64** [comment]
@aabadie could you maybe write-up a page? Just have a look at the *.md files in the `doc/doxygen/src/` directory for a template (not the mainpage.md though ;-)) and add it to the [`INPUT` configuration variable](https://github.com/RIOT-OS/RIOT/releases)

**Comment by aabadie** [comment]
> @aabadie could you maybe write-up a page?

I'll see what I can do
