### ISSUE TITLE
Any working example for attaching at86rf233 with a stm32f4 board?

### ISSUE THREAD

**Issue by kbumsik** [RIOT-OS/RIOT#7017]
Hi, 
I just got two at86rf233 modules (zigbit and openlabs). I am trying to follow networking examples using Nucleof401 boards or a Discovery F4 board with the rf modules. But I am stuck at the beginning: I cannot found any working example (e.g. example/default pinmap and best practice attaching module hardware) attaching them from the source code and the documentation. Each tutorials in the wiki is nice but the whole wiki documentation seems a little bit sparse...

It looks like someone are already done it but I am having hard time finding full working example...I would appreciate if someone tell me where I can find it.

**Comment by aabadie** [comment]
Hi,

I never tried myself but this is what I would try first:
* load the corresponding module, in your case add `USEMODULE += at86rf233` in the application Makefile
* in the default Makefile, add nucleo-f401 to the boards providing a net interface, this is required to load the gnrc stack commands (ifconfig).
* then, since default uses auto_init, define the required pins for the module in [at86rf2xx_params.h](https://github.com/RIOT-OS/RIOT/blob/master/drivers/at86rf2xx/include/at86rf2xx_params.h#L34). I think that this file can also be copied locally in the application directory.
* verify that the configuration corresponds to the module wiring and build the application (and keep fingers crossed :) )

**Comment by kbumsik** [comment]
@aabadie Thank you so much. I have one question,
> in the default Makefile, add nucleo-f401 to the boards providing a net interface, this is required to load the gnrc stack commands (ifconfig).
What are you referring 'default Makefile' to?

**Comment by aabadie** [comment]
> What are you referring 'default Makefile' to?

I'm referring to the `examples/default/Makefile` file.

**Comment by haukepetersen** [comment]
Hi, to get your configuration working just do the following:
- take your target board (e.g. some nucleo as the  `nucleo-f401`) and connect the radio module to it (I guess you use jumper wires?) For a working configuration have a look into the board's `periph_conf.h` file to see the pin mapping for e.g. SPI pins etc
- go to the GNRC networking example (`examples/gnrc_networking`). This is the best base to get started with...
- Now you simply have to do two more steps: you have to tell the makesystem that you want to use the `at86rf2xx` radio driver, and you have to tell auto_init the pin configuration you are using for this radio. Both can be done right through environment variables. So simply build the application using:
```
BOARD=nucleo-f401 USEMODULE=at86rf2xx CFLAGS="-DAT86RF2XX_PARAM_SPI=SPI_DEV\(0\) -DAT86RF2XX_PARAM_CS=GPIO_PIN\(2,9\) -DAT86RF2XX_PARAM_INT=GPIO_PIN\(1,0\) -DAT86RF2XX_PARAM_SLEEP=GPIO_PIN\(0,12\) -DAT86RF2XX_PARAM_RESET=GPIO_PIN\(1,7\)" make
```
Note: you need to adapt the pins and SPI device to whatever configuration you will chose...

Regarding documentation: you are right, we need to add some more infos on how to use externally connected devices with boards... Will look into this.

**Comment by haukepetersen** [comment]
Oh, and when you plan to use this configuration more often, you have of course some more options to make this config a little more persistent: 
- you can edit the applications Makefile and add these variables there
- you can export those env vars in your shell (so they stay for the session)
- you can copy the `at86rf2xx_params.h` file into your application folder and edit the pin config to your needs (this will override the default configuration)

**Comment by kbumsik** [comment]
Thank you for all detail!
I will try this out this weekend :)

**Comment by PeterKietzmann** [comment]
I consider this issue as outdated/solved, especially because I have a running configuration on my desk. @kbumsik please give a sign if you need further help.
