### ISSUE TITLE
tests: unittests buildtests skipping

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#7033]
When trying to run `make buildtest` on `tests/unittests` nothing is done. A bisect revealed a2b4c42c28425554a1c8083c3365be33016a77a7 to introduce that bug. BTW: how was this missed during testing for the release?

**Comment by kaspar030** [comment]
> When trying to run make buildtest on tests/unittests nothing is done.

True that. Looking through the logs, Murdock1 didn't build the unittests since that commit.

> how was this missed during testing for the release?

Honestly, I didn't run the compile tests, as I relied on Murdock2, which correctly built everything for the corresponding commit. I guess I loosely misinterpreted the spec entry as "everything compiles", not "make buildtest works".

**Comment by miri64** [comment]
@kaspar030 are you sure the unittests are compiling on Murdock? Because as far as I can tell they are currently broken for msp430-based platforms.

**Comment by miri64** [comment]
(ah they are currently blacklisted via the `cbor` tests).

**Comment by kaspar030** [comment]
@gebart The commit in question was yours, and honestly I don't understand it. Maybe you could take a look?

**Comment by gebart** [comment]
The intention of the commit in question was to add FEATURES_REQUIRED += cpp when the unittests are built containing at least one C++ test module. For the platforms which don't support C++ we need to filter out the C++ test modules when building the complete test suite, to avoid dependencies on missing C++ compilers etc.

**Comment by gebart** [comment]
I am not sure what part of it causes the problem though, possibly the FEATURES_REQUIRED part?

**Comment by smlng** [comment]
FYI: when I run `make buildtest` in `tests/unittests` using latest master  on macOS it does compile for all boards, though all are reported as `failed`. Nevertheless, the original issue (*does nothing*) seems to be resolved?

**Comment by gebart** [comment]
What is the failure? (run with BUILDTEST_VERBOSE=1)

**Comment by smlng** [comment]
`BUILDTEST_VERBOSE=1` still only one line output

**Comment by smlng** [comment]
the error is with the usage of `strptime` in `cbor.c`, if I change the Makefile for cbor to set `_XOPEN_SOURCE` for all (not only macOS) it works for all but AVR based MCUs. However, that is a separate issue - maybe cross compiling on macOS related?

**Comment by kYc0o** [comment]
Is this issue still exists?

**Comment by miri64** [comment]
I think not. Don't have a machine to test, but if `make buildtest` chose boards + status it should be ;)

**Comment by miri64** [comment]
Yes, issue is fixed.
