### ISSUE TITLE
when using module saul_adc: fatal error adc_params.h

### ISSUE THREAD

**Issue by raticate** [RIOT-OS/RIOT#7045]
when I try to use the saul_adc module I get the following error:
fatal error: adc_params.h: No such file or directory
 #include "adc_params.h"

**Comment by dylad** [comment]
I tested and got the same error message. 
I think this feature has not been implemented yet.

**Comment by gebart** [comment]
Not all boards have a configuration file yet. You should write your own adc_config.h and place it in the boards/<BOARD>/include directory. You can copy the adc_config.h in boards/mulle/include for an example of what it is expected to contain.

**Comment by smlng** [comment]
so the actual task would be: provide SAUL ADC adaption for all boards with feature `periph_adc`, right?

**Comment by haukepetersen** [comment]
> so the actual task would be: provide SAUL ADC adaption for all boards with feature periph_adc, right?

not necessarily... We don't need to map everything just because we can, these mapping should be made in a sensible way I would say. So I'd say we go as we need them, makes sense?

**Comment by haukepetersen** [comment]
@raticate which board are you using?

**Comment by kYc0o** [comment]
Can we close this issue?
