### ISSUE TITLE
Use of fd_new in posix_sockets.c

### ISSUE THREAD

**Issue by samkumar** [RIOT-OS/RIOT#7054]
Take a look at https://github.com/RIOT-OS/RIOT/blob/master/sys/posix/sockets/posix_sockets.c#L445.

In posix_sockets.c, the accept() function calls fd_new(), even though it seems that fd_new has been eliminated.

@immesys

**Comment by samkumar** [comment]
See also Pull Request #7055.

**Comment by miri64** [comment]
I think this is resolved by now (the PR you mentioned is merged). Reopen if you disagree.
