### ISSUE TITLE
tools: pyterm: EOF not handled correctly

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#7058]
pyterm passes the EOF char (e.g., ctrl-d) as string "EOF" to the connected serial.
That causes problems with pexpect, which sends EOF e.g., when closing the spawned ```make term```.
I don't know exactly when it does that, but pyterm's behaviour breaks running pexpect scripts in a row.

```
/home/kaspar/src/riot.timers/dist/tools/pyterm/pyterm -p "/dev/ttyACM3" -b "115200"
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2017-05-14 13:53:35,199 - INFO # Connect to serial port /dev/ttyACM3
Welcome to pyterm!
Type '/exit' to exit.
2017-05-14 13:53:36,965 - INFO # main(): This is RIOT! (Version: 2017.04-devel-1000-g5226a-booze)
2017-05-14 13:53:36,969 - INFO # RIOT network stack example application
2017-05-14 13:53:36,971 - INFO # All up, running the shell now
> 2017-05-14 13:53:55,532 - INFO #  EOF
2017-05-14 13:53:55,535 - INFO # shell: command not found: EOF
```

(I pressed CTRL-D at some point).

IMO pyterm should either ignore EOF, or send the EOF character, or exit, but definitely not send "EOF" as string.

**Comment by OlegHahm** [comment]
If I remember correctly, the twisted package introduced this behavior.

**Comment by kaspar030** [comment]
> If I remember correctly, the twisted package introduced this behavior.

Do you think it can be fixed?

**Comment by aabadie** [comment]
I'm having a look, not sure if I can fix it

**Comment by aabadie** [comment]
Opened #8970 to tackle this issue
