### ISSUE TITLE
Change Shell Handler Signature Completely

### ISSUE THREAD

**Issue by LudwigOrtmann** [RIOT-OS/RIOT#708]
To increase similarity with regular shells, the handler signature could be changed to 
`int handler(int argc, char **argv);`.

The return value `0` would indicate success, anything else would be treated as an error.

The shell would need to be changed to iterate over the whole string with strtok, counting the parameters and to check the return value of the handler. If an error occurred the shell could print a message.

All shell commands would need to be updated for the new signature.

Pros:
* shell commands can communicate errors more easily (just return 1)
* no need for use of the unfamiliar strtok within the commands
* easier portability of existing commands

Cons:
* commands loose the ability to sscanf through parameters expecting spaces

**Comment by kushalsingh007** [comment]
Hi , I am a newbie. Could you tell me what all fixes still need to be implemented. From what I see one for backslashes and one for return values. Apart from those two are there still more things that need to be done here ?

**Comment by authmillenon** [comment]
Hi, I guess wit backslashes you mean parsing for quotes? Currently, for arguments we only use whitespaces as token divider, regardless if they are escaped or in a pair of quotation marks. The real challenge is to get this into a size acceptable for small devices. For return values compare #1243 and the discussion above. Here the most tedious part is finding all the already implemented she'll handlers and change them accordingly ;).

**Comment by kushalsingh007** [comment]
@authmillenon : Just a few questions I encounterd .
1) Currently native does not have support for commands like echo so how should I go about for testing , i.e which command should I try this thing on.
2)the PR created by @Kijewski  #760 says that tokenization of input is now done , so doesn't that mean that the problem with pair of quotation marks has been solved. 
3) I had the look at the PR at #1243 , and it looks like most of them ( if not all ) have been finished.

I am confused :confused: , can you please explain again what needs to be done here ?

**Comment by authmillenon** [comment]
> 1) Currently native does not have support for commands like echo so how should I go about for testing , i.e which command should I try this thing on.

Huh? What do you trying to say with that? Do you mean an `echo` shell command?

> 2) the PR created by @Kijewski #760 says that tokenization of input is now done , so doesn't that mean that the problem with pair of quotation marks has been solved.

Ah right. Totally forgot about that one :D

> 3) I had the look at the PR at #1243 , and it looks like most of them ( if not all ) have been finished.

The problem is, that it is pretty deprecated (there are new commands e.g. and it is not mergable anymore). I have currently no time at hand to fix this, but you can take my PR as a starting point.

> I am confused :confused: , can you please explain again what needs to be done here ?

Hope I could clear this up for you a little.

**Comment by kushalsingh007** [comment]
>The problem is, that it is pretty deprecated (there are new commands e.g. and it is not mergable anymore). I have currently no time at hand to fix this, but you can take my PR as a starting point.

Just a final clarification:
1. What are the new commands and the example that you speak of.
2. The reason why it is not mergable anymore (what exactly is depricated)?.

**Comment by authmillenon** [comment]
> 1. What are the new commands and the example that you speak of.

That's part of the exercise to find this out ;-) I honestly lost track about that.

> 2. The reason why it is not mergable anymore (what exactly is depricated)?.

Because there were changes made to master since my last update of the PR that are in conflict with the PR. What exactly the problem is will be come clear if you try to rebase it to current master, I would guess. But in general even simple stuff like the removal of a command can cause this.

**Comment by kushalsingh007** [comment]
Ok , so I have started working on this one ;) ( Just to make sure that effort does not get repeated )

**Comment by OlegHahm** [comment]
So, what is still missing?

**Comment by authmillenon** [comment]
I think this issue can be closed now :-)
