### ISSUE TITLE
cpu: implement the stmclk interface for all STM32 CPUs

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#7123]
Lately, we introduced an interface for controlling the internal clocks for all STM32 CPUs (`stm32_common/include/stmclk.h`). This is however only implemented for the STM32F1 and STM32F7 so far and should be implemented for all members of that family. As result, problems like the one in #6504 are trivial to solve...

This issue is created to track and synchronize the porting effort.

Todo:
- [x] stm32f0 (#7500)
- [x] stm32f1
- [x] stm32f2 (#7159)
- [x] stm32f3 (#7500)
- [x] stm32f4 (#7158)
- [x] stm32f7
- [x] stm32l0
- [x] stm32l1
- [x] stm32l4 (#7469)

**Comment by haukepetersen** [comment]
As explicit reference: we should watch the outcome of #7477 to make sure there is no redundant work done when implementing this interface...

**Comment by aabadie** [comment]
All stm32s cpus now support stmclk interface (#8735 did that for L0/L1), so we can close this one.
