### ISSUE TITLE
SAUL: add full support for PhyNode (pba-d-01-kw2x)

### ISSUE THREAD

**Issue by smlng** [RIOT-OS/RIOT#7152]
The following table gives an overview and work in progress on the state of SAUL support for peripherals of the PhyTec PhyNode (board `pba-d-01-kw2x`), looks quite good already 😄 

Device | Driver | SAUL support
------ | ------ | ----
Humidity Sensor | HDC1000 | ✅ 
Magnetometer | MAG3110 | ✅ 
Accelerometer | MMA8x5x | ✅ 
Pressure (+Temp) | MPL3115A2 | ✅  (#7120)
IR Temperature | TMP006 | ✅ (#7168)
Color Light Sensor | TCS37727 | ✅ 
Capacative Sensor (Button) | periph_gpio | ✅   (#7147)
RGB LED | periph_gpio | ✅  (#7147)

**Comment by smlng** [comment]
all done! Full SAUL support for board `pba-d-01-kw2x`! Closing this issue!

**Comment by smlng** [comment]
@aabadie might be something for the release notes?

**Comment by aabadie** [comment]
> might be something for the release notes?

sure, I'll put this in shape once we reach feature freeze.
