### ISSUE TITLE
Missing support for building position independent code

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#7189]
Adding support for building position independent code would make it easier to build images for online firmware updates, since the binary can be relocated by the bootloader to a suitable location depending on available memory. Running binaries from RAM should also be possible without any special linker scripts.  

I have not investigated the details but the a rough draft of the changes needed are:
- Add -fPIC to CFLAGS, possibly -fpie as well. 
- add linker script handling of .got (global offset table) and .got.plt (procedure linkage table) 
- fill GOT during boot (I don't know if gcc provides code for this or if we need to write our own)

**Comment by gebart** [comment]
Maybe relevant #6450 #7167 #6922 #7081

**Comment by miri64** [comment]
@kaspar030 @kYc0o isn't this fixed via your work?

**Comment by kYc0o** [comment]
Unfortunately not. This is about dynamic loading of position independent code during compile time, if I'm not mistaken. Our approach is rather to boot images at a fixed position given by a specific linker script, which the method discussed here would avoid.
