### ISSUE TITLE
sys/fmt: Missing tests for fmt_float, fmt_lpad

### ISSUE THREAD

**Issue by jnohlgard** [RIOT-OS/RIOT#7220]
See title.
Also, fmt_float has a bug where it will skip over a byte before the decimal point in the middle of the output string if the number is negative because of a mistake in the output pointer advancement.

**Comment by kaspar030** [comment]
+1, but fmt_lpad() does have some unittests?

**Comment by gebart** [comment]
Maybe I missed it while I was scanning the source. But fmt_float needs some tests at least

**Comment by maribu** [comment]
lpad is covered in the unit tests, tests/fmt_print tests `print_float()` which indirectly tests `fmt_float()`.
