### ISSUE TITLE
edbg: tool fails to automatically build

### ISSUE THREAD

**Issue by emmanuelsearch** [RIOT-OS/RIOT#7226]
trying to flash a SAMR21 on via Vagrant (Ubuntu 16.04.2 LTS) I get the following error while (automagically) building edbg before flashing:

```
[INFO] edbg binary not found - building it from source now
CC= CFLAGS= make -C /home/vagrant/RIOT/dist/tools/edbg
"make" -C /home/vagrant/RIOT/dist/tools/edbg/bin
gcc  -W -Wall -Wextra -O2 -std=gnu99 dap.c edbg.c target.c target_atmel_cm0p.c target_atmel_cm3.c target_atmel_cm4.c target_atmel_cm7.c dbg_lin.c -ludev -o edbg
dbg_lin.c:42:21: fatal error: libudev.h: No such file or directory
compilation terminated.
```

**Comment by miri64** [comment]
You need to update your vagrant image. This was solved in https://github.com/RIOT-OS/RIOT/pull/7105

**Comment by miri64** [comment]
[For future references](https://github.com/RIOT-OS/RIOT/pulls?utf8=%E2%9C%93&q=libudev-dev) ;-)

**Comment by cgundogan** [comment]
@emmanuelsearch can you try if `vagrant box update` is enough to resolve this issue for you?

**Comment by emmanuelsearch** [comment]
I had already done the update. Vagrant box update gives currently: 

```
$ vagrant box update
==> default: Checking for updates to 'RIOT/ubuntu1604'
    default: Latest installed version: 0.0.2
    default: Version constraints: 
    default: Provider: virtualbox
==> default: Box 'RIOT/ubuntu1604' (v0.0.2) is running the latest version.
```

**Comment by emmanuelsearch** [comment]
(hence: reopened the issue)

**Comment by cgundogan** [comment]
hm, then a complete destroy might help: `vagrant halt` `vagrant destroy` `vagrant up`

**Comment by cgundogan** [comment]
oh and in case there are some older versions around: could you open the virtualbox GUI and delete them manually?

**Comment by emmanuelsearch** [comment]
OK, with this it works thanks ;)
