### ISSUE TITLE
msp430: use tlsf instead of oneway_malloc

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#7235]
The `oneway_malloc` module looks more like temporary solution and we have a working alternative (`tlsf`). The benefit would be that we could remove the `oneway_malloc` module.

**Comment by kaspar030** [comment]
> we have a working alternative (tlsf).

tlsf was too fat, last time I checked. Does it even work on 16bit platforms?

**Comment by miri64** [comment]
> Does it even work on 16bit platforms?

Ah right. I knew I missed something. Nevermind then. Then someone(TM) actually needs to fix `oneway_malloc` ;-)
