### ISSUE TITLE
samr21-xpro: unable to ping another node

### ISSUE THREAD

**Issue by thomaseichinger** [RIOT-OS/RIOT#7268]
git bisect hints to #7115 having introduced an regression, pinging between two samr21-xpro nodes doesn't work on current master as of 524f2e57b.

@aabadie can you confirm?

**Comment by miri64** [comment]
Can confirm for `iotlab-m3` and `samr21-xpro` (did not check when the regression was introduced though)

**Comment by miri64** [comment]
For some reason it already fragments 38 byte packets with lots of duplication oO.

**Comment by miri64** [comment]
Of course, when I add debug output it works -.-
