### ISSUE TITLE
Feature request : support TSCH mode in MAC

### ISSUE THREAD

**Issue by Adu143** [RIOT-OS/RIOT#7278]
Is the current implementation supporting TSCH mode ? If not, is there a roadmap on when it shall be included.

**Comment by PeterKietzmann** [comment]
Have a look at #7893. There have been some efforts as you can see, all seem to be stuck somehow. But don't hesitate to ask for details in respective issues. There are also some (none-yet-visible) efforts to integrate the OpenWSN stack into RIOT. If you consider to provide help, send me a private message.
