### ISSUE TITLE
Support for ST X-NUCLEO IKS01A2

### ISSUE THREAD

**Issue by smlng** [RIOT-OS/RIOT#7282]
This issue documents the state of driver support for sensors on the [ST X-NUCLEO Shield IKS01A2](http://www.st.com/en/ecosystems/x-nucleo-iks01a2.html), plus to coordinate the efforts and synchronize work on distinct drivers. It is a follow up to #6629 and has similar intention as #7152.

Device/Sensor Type | Driver | state
------ | ------ | ----
Humidity and Temperature | HTS221 | ✅ see #7280  
Accelerometer and Gyroscope | LSM6DSL | ✅ (#6835)
Accelerometer and Magnetometer| LSM303AGR | ❓ maybe adapt LSM303DLHC
Pressure and Temperature | LPS22HB | ❓ maybe adapt LPS331AP

**Comment by miri64** [comment]
If they are one shield, unifying them under one driver (in addition to the individual device drivers) like we did with the `io1_xplained` extension board for `samr21-xpro` might make sense.

**Comment by smlng** [comment]
mhm, I rather thought about introducing a pseudomodule `iks01a2` which has the respective drivers as a dependency.

**Comment by miri64** [comment]
Also thinkable. But don't you have to configure the periphs used by the shield somewhere?

**Comment by smlng** [comment]
could be done with a distinct `<DRIVER>_PARAMS_IKS01A2` in `drivers/<driver>/include/<driver>_params.h` and then using `#ifdef MODULE_IKS01A2` I guess? But again: first things first, i.e. getting all drivers ready and afterwards we care about the shield config.

**Comment by miri64** [comment]
> But again: first things first, i.e. getting all drivers ready and afterwards we care about the shield config.

Yes, just wanted to bring this up.

**Comment by smlng** [comment]
duly noted, thanks for the pointer to `io1_xplained` - wasn't aware of that.

**Comment by smlng** [comment]
closing this, its just a tracking issue.
