### ISSUE TITLE
Ethos does not compile

### ISSUE THREAD

**Issue by nikosft** [RIOT-OS/RIOT#7330]
When USEMODULE += ethos is included in an app's Makefile, compiling the app fails with error "comparison between signed and unsigned integer expressions" in RIOT/drivers/ethos/ethos.c: lines 303 and 311.

To solve this problem line 303 of RIOT/drivers/ethos/ethos.c should be changed from
``if (len < (int)dev->last_framesize)``
 to
``if (len < dev->last_framesize)``

and line 311 from
``if ((tsrb_get(&dev->inbuf, buf, len) != len))``
to
``if ((tsrb_get(&dev->inbuf, buf, len) != (int)len))``

Moreover, Readme.md in RIOT/dist/tools/ethos should be updated to mention that app's Makefile should also include USEMODULE += uart_stdio

**Comment by smlng** [comment]
thanks for reporting, are you willing to provide a fixing PR?

**Comment by miri64** [comment]
I will look into that after the release.

**Comment by kYc0o** [comment]
I tried to reproduce this error but it works ok so far. Though it's true that `USEMODULE += uart_stdio` is necessary (a dependency).

I did it by typing:

```console
BOARD=samr21-xpro USEMODULE+=ethos USEMODULE+=uart_stdio make
```

on the default example.

@nikosft can you confirm if your issue persists?

**Comment by kYc0o** [comment]
I retested on current master and found that it compiles right with the configuration provided on the README. I'll close it for now, reopen if you find the error again.
