### ISSUE TITLE
samd21: DFLL configuration

### ISSUE THREAD

**Issue by Hyungsin** [RIOT-OS/RIOT#7334]
DFLL CTRL register setting at https://github.com/RIOT-OS/RIOT/blob/master/cpu/samd21/cpu.c#L163 
may flush the previous register setting at https://github.com/RIOT-OS/RIOT/blob/master/cpu/samd21/cpu.c#L158, because it renews the whole register again.

How about "SYSCTRL->DFLLCTRL.bit.ENABLE = 1" instead?

**Comment by smlng** [comment]
the questions is, if it is a bug or whether this might be intentional? Did you observe any problems? In general you right, codewise current implementation this will flush/overwrite the DFLL register setting - but again, might be on purpose.

**Comment by photonthunder** [comment]
It is a bug, the |= got dropped somehow.  I will get a PR going to add it back in.  The change means that you are running in open loop mode, meaning you are not taking advantage of the external crystal to calibrate the DFLL.

**Comment by smlng** [comment]
okay, where was it dropped - was there a PR introducing the regression or already when the CPU got ported for RIOT? Otherwise I'd rather got for your suggested:

```
SYSCTRL->DFLLCTRL.bit.ENABLE = 1;
```

instead of using '|=', the above is consistent with the rest of the code and more explicit.

**Comment by photonthunder** [comment]
PR #7130 added the option of using DFLL and in my initial code the |= existed, but at some point it was dropped.  I will push a PR with the one line fix.

**Comment by Hyungsin** [comment]
@photonthunder, Cool. Go for it! :)

**Comment by photonthunder** [comment]
PR #7359 created, thanks for catching this bug.

**Comment by Hyungsin** [comment]
This is closed thanks to PR #7359.
