### ISSUE TITLE
Buffered printf()

### ISSUE THREAD

**Issue by travisgriggs** [RIOT-OS/RIOT#7418]
I would like our printfs to run in the background, or rather the feeding of them out the serial port. Is there a general recipe for how to accomplish this in the RIOT framework?

**Comment by gebart** [comment]
If you still want the messages to be printed on the UART you will need to modify the UART driver for your CPU to use interrupts or DMA and it will probably need an extra internal buffer to keep while the UART is working.

**Comment by travisgriggs** [comment]
Thanks @gebart.

**Comment by kaspar030** [comment]
A simple way would be to create a thread reading from an isrpipe writing to uart, then modifying the newlib write() implementation to write to that isrpipe. The isrpipe would double as buffer. The cost would be an additional thread stack and the buffer, and still, as uart writes are synchronous, after the buffer is full, printf's would block. Might still be useful for debugging.

**Comment by travisgriggs** [comment]
Regarding "... then modifying the newlib write() implementation to write to..." I've never done that before, can you give a pointer on how one does that? From what little I can glean from Google, newlib is the version of libc used for RIOT?

**Comment by gebart** [comment]
@travisgriggs the interface between newlib and RIOT are called syscalls, and are implemented in https://github.com/RIOT-OS/RIOT/blob/master/sys/newlib_syscalls_default/syscalls.c (Also note that there are two implementations of the file-related syscalls, one with the vfs module and one without it, which one you are using depends on whether you have USEMODULE+=vfs in your application, or not)
