### ISSUE TITLE
riot-os.org: missing hardware

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#7493]
The list of supported platforms on the website should be expanded (http://riot-os.org/#usage)

- Cortex-M7 missing from the list of architectures (and Cortex-M0+ if that counts as separate from Cortex-M0)
- Lots of device drivers and boards are missing from the lists

It might be easier to just add links with the text "and more..." or similar that points to the boards and drivers directories on Github, since it will be very demanding to keep the page up to date at all times.

**Comment by emmanuelsearch** [comment]
Updated the website as suggested. Note: a full revamp of the website is pending, so I will close this issue for now.
