### ISSUE TITLE
core: thread_flags: THREAD_FLAG_MUTEX_UNLOCKED, THREAD_FLAG_TIMEOUT are not used

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#7543]
Follow up to #7533. I found that there are two other predefined constants which are not used in the tree.

- `THREAD_FLAG_MUTEX_UNLOCKED`
- `THREAD_FLAG_TIMEOUT`

I think the constants may be intended for `xtimer_msg_timeout`, which mentions core_thread_flags in the documentation, but does not in fact use thread flags for the implementation.

**Comment by kaspar030** [comment]
#7558 implements a simple timeout function using THREAD_FLAG_TIMEOUT, which I think will be used in many timeout variants of existing functions.

When adding THREAD_FLAG_MUTEX_UNLOCKED, I thought it might be useful to wait for multiple mutexes at the same time. IMO supporting this would mess up the mutex code, so I propose to remove the define.

**Comment by gebart** [comment]
#7558 was merged, waiting for #7717 then this will be fixed.
