### ISSUE TITLE
samr21-xpro uart broken in master

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#7546]
#7260 seems to have broken uart output on my samr21-xpro... does anyone else see this?

**Comment by haukepetersen** [comment]
I confirm it to be broken -  weird, tested it yesterday on the sam with #7260... Will look into this now.

**Comment by dylad** [comment]
Sorry, Seems to be my fault. I should buy a samd21 based board in a near future to avoid this kind of thing.

**Comment by haukepetersen** [comment]
no problem, also my fault as I seem to have messed up when testing...
