### ISSUE TITLE
cortexm-common: minimal configuration grew by 200 bytes

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#7575]
Checking our minimal configuration I noticed that it grew by 200 bytes (at least on IoT-LAB-M3, for Cortex-M0 boards even more IIRC) since we last checked and documented it (in this case in some paper draft ;-)). After some bisecting I found 4bfce89 to be the commit that significantly made it bigger (though there are others that always made it bigger some bytes). This particular commit unified the periph initialization. Due to that SPI is included, though it isn't really needed. Just another example of our messed-up build system maintenance ;-).

(This is just a note for @haukepetersen, we discussed this already offline)

**Comment by roberthartung** [comment]
True.. I also came upon the periph_init() call in cpu_init and thought if there was a better solution to this.
