### ISSUE TITLE
How to test enc28j60 driver?

### ISSUE THREAD

**Issue by maitysubhasis** [RIOT-OS/RIOT#7591]
@haukepetersen how to test enc28j60 driver?

**Comment by smlng** [comment]
For starters, you could use `tests/driver_enc28j60` with your favourite board, it has a SPI interface so wire it accordingly and adapt INT (interrupt) and RST (reset) pins in the test Makefile.

**Comment by smlng** [comment]
any progress?

**Comment by kbumsik** [comment]
Hi, I am working on #7433 and have a question too.
So while I run the test application and connect the two boards with a enc28j60 to a IPv6-enabled router then a board should be able to ping the other board in within the same subnet? And can the board also ping a Linux PC too?

**Comment by maitysubhasis** [comment]
I have ensured that the SPI communication is working properly for my board (Openmote-cc2538).
Still the MAC address is showing 00:00:00:00:00:00. I am trying figure out what's the problem. Any have an idea what is going wrong?

**Comment by haukepetersen** [comment]
This issue should be covered by #7745, so closing it.
