### ISSUE TITLE
samd21-xpro doesn't compile if gclk_src is not 0

### ISSUE THREAD

**Issue by photonthunder** [RIOT-OS/RIOT#7605]
In the latest version or RIOT, uart.c was merged from SAML21 and SAMD21.  If you change the gclk_src from GCLK_CLKCTRL_GEN_GCLK0 to any other generic clock source it will not compile since the definitions in gclk.h are 32 bit rather than 8 bit.  @dylad any insight on the best way to fix this?

**Comment by dylad** [comment]
@photonthunder The solution is to change `uint8_t gclk_src` -> `uint32_t gclk_src` in the file `cpu/sam0_common/include/periph_cpu_common.h`
I was able to reproduce this bug and this solution seems to fix it.
I'll open a PR to fix it right now. Thanks a lot for spotting this :)

**Comment by photonthunder** [comment]
@dylad, happy to help.  Maybe it will help me get PR #7405 through, I tried to rebase it off your combination of uart.c.  Makes it nice to wake a board from sleep via uart.

**Comment by dylad** [comment]
Nice effort, I'll take a look at it tomorrow ! I'll update my rework of I2C driver #7588 to prevent this issue too.
I just propose #7606 to fix the issue

**Comment by photonthunder** [comment]
Perfect, closing...
