### ISSUE TITLE
atmega/periph: gpio.c does not implemented pin change interrupts.

### ISSUE THREAD

**Issue by roberthartung** [RIOT-OS/RIOT#7609]
While preparing the changes for #7604 I found out that I missed to add my PinChange interrupt implementation. Is there any reason why this was not implemented yet?

Feedback by @haukepetersen @kaspar030 @lebrush much appreciated. Should I create a different PR, or can I use the one for the INGA boards, because it will be introduced along with that platform?

**Comment by kYc0o** [comment]
AFAIK there is no strong reason why they're not implemented, I guess it's just that nobody made use of it until now, besides context switching on which only the needed PCINT is implemented for that exclusive use.

**Comment by roberthartung** [comment]
Will be solved by #11122

**Comment by fjmolinas** [comment]
@roberthartung I gues we can close since #11122 is merged?

**Comment by roberthartung** [comment]
@fjmolinas yes! closed.
