### ISSUE TITLE
buildtest starts too many parallel processes

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#7626]
The `make buildtest` command used to limit the number of parallel make jobs to the number of cores, or number of cores + 1. When I run a buildtest now I get about 50-100 parallel cc1 processes, which make my quad core quite unresponsive until it is over... I don't have any time to look into this right now, but I think it had to be reported at least.

**Comment by kaspar030** [comment]
I see why. Will fix.

**Comment by kaspar030** [comment]
See #7627.
