### ISSUE TITLE
issue with #ifdef NUMOF set to 0 

### ISSUE THREAD

**Issue by dylad** [RIOT-OS/RIOT#7639]
While addressing some comments from @lebrush for #7588 I noticed an issue.
In fact, we use a common struct in order to init peripheral driver within `periph_conf.h` file
NUMOF are defined using `sizeof(struct) / sizeof(element)`. This line is fine but only process by compiler. So we cannot use `#if NUMOF`.
The problem is : if the board does not define this peripheral (e.g NUMOF = 0) **AND** the driver uses mutexes (`mutex_t locks[NUMOF]`) this line will failed to compile which is not the desired behaviour. We want the driver to be disabled.
(see sam0 i2c driver or stm32_common spi driver).

Maybe someone has an idea to solve this ? :)

**Comment by smlng** [comment]
I think the new approach ( @haukepetersen , please step in here) is to use `#ifdef <PERIPH>_NUMOF` and omit any definition of that in `periph_conf` if no such periph device is present. For instance, in the past we set something like `#define ADC_NUMOF (0)` and now use `#define ADC_NUMOF (sizeof(adc_config) / sizeof (adc_config[0])`, but only if at least one ADC line is configured. Further we guard the adc periph implementation with `#ifdef ADC_NUMOF` as well, so the code will not be compiled or used when no ADC is available. 

Did I make sense?

**Comment by dylad** [comment]
@smlng yes you're right.
So now, the #define PERIPH_NUMOF (0) is forbidden except for some old periph_conf.h board ?
User must remove this define if he wants to disabled this feature ?

**Comment by basilfx** [comment]
With #7241 merged, this isn't an issue anymore, right? If the MCU doesn't support/provide `*_NUMOF`, it shouldn't list it, and the driver doesn't get compiled.

**Comment by haukepetersen** [comment]
At least it shouldn't be.

So the concept now is the following: if a board does not provide configuration for a certain peripheral (e.g. this would be the `XX_NUMOF := 0` case described above), it **must not** define the corresponding feature. This way, the periph driver is never even touched be the compiler. Makes sense?

**Comment by dylad** [comment]
Yes it does, thanks to everyone. I'm closing this issue then.
