### ISSUE TITLE
Vrefint stm32l1

### ISSUE THREAD

**Issue by paula75** [RIOT-OS/RIOT#7657]
Hi,

I'm working on a project where my VDD is variable using a nucleo-l1 and i need to estimate according to vrefint on the board. According to the datasheet i could estimate it from Vrefint_cal (data acquired at a specific vdd=3V and is in the memory address) and the read of the adc in vrefint pin with the actual vdd supply, according to V_DD = 3* VREFINT_CAL/adc_sample(vrefint_pin). The problem i have is that the adc read is about 4LSB different from the theoretical value, that makes about 60mV of error between estimated vdd and real vdd.

I have a few questions: 
1. How can i improve the reading of the adc for DC values? 
2. Where do i change the sampling rate of the adc? 
3. Where should i implement the function for enable vrefint on the board?

Thanks in advance for your help!

**Comment by aabadie** [comment]
The ADC interface in RIOT is common to all supported MCU so it's possible that some features of a given MCU are missing. I'm not an expert with ADC but I'll try to answer for the STM32L1.

> How can I improve the reading of the adc for DC values?

You can only tweak the ADC resolution. See available values [here](https://github.com/RIOT-OS/RIOT/blob/master/cpu/stm32l1/include/periph_cpu.h#L56) for this CPU.

> Where do I change the sampling rate of the adc?

I'm not sure, but I would say that this is [hard coded in the driver](https://github.com/RIOT-OS/RIOT/blob/master/cpu/stm32l1/periph/adc.c#L33). Correct me if I'm wrong.
If true, maybe this is something that could be defined in the board configuration and if not defined here use this default value there.

> Where should I implement the function to enable vrefint on the board?

This should be done in the board configuration normally. You have an example for Modtronic [NZ32-SC151](https://github.com/RIOT-OS/RIOT/blob/master/boards/nz32-sc151/include/periph_conf.h#L233) board.

Hope this helps.

**Comment by aabadie** [comment]
Maybe @fjmolinas or @jia200x can also give some information, they have experience with ADC on the STM32L1 IIRC.

**Comment by paula75** [comment]
Hi,

Thanks for your reply!
> You can only tweak the ADC resolution. See available values here for this CPU.

Indeed the resolution improve the accuracy, but i had to modify the periph_cpu.h file. I have a board to test it and the 6_BIT, 8:BIT and 10_BIT is not well implemented, all of them are set to 4095
> I'm not sure, but I would say that this is hard coded in the driver. Correct me if I'm wrong.
If true, maybe this is something that could be defined in the board configuration and if not defined here use this default value there.

Yes, i belive that in that file this should be implemented, i'm working on it now
>This should be done in the board configuration normally. You have an example for Modtronic NZ32-SC151 board.
Perfect! i'll follow this convention

**Comment by PeterKietzmann** [comment]
Question was answered.
