### ISSUE TITLE
Configuring another uart instance does not print any data on tera term or py-term

### ISSUE THREAD

**Issue by shreeharsha22** [RIOT-OS/RIOT#7702]
Hi when I try to configure two uarts am not getting any logs on pyterm or teraterm

**Comment by dylad** [comment]
Hello @shreeharsha22,
Could you provide more information : 

- Which CPU/board are you using ?
- Could you show us your UART configuration ? (extracted from periph_conf.h)

**Comment by PeterKietzmann** [comment]
No further information about the problem and no response since 1,5 years.
