### ISSUE TITLE
sixlowpan: udp: Message queues for IP and UPD are too big

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#773]
The message queues introduced in https://github.com/RIOT-OS/RIOT/pull/680 are too big to fit for all platforms. Having a board dependent size is probably more sensible.

**Comment by authmillenon** [comment]
Is this still an issue in the new network stack or does only #2851 apply here?

**Comment by OlegHahm** [comment]
Well, 8 appears to be a much more reasonable number than 64. ;)
