### ISSUE TITLE
CI: Errorneous Makefile passed Murdock somehow

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#7741]
When https://github.com/RIOT-OS/RIOT/pull/7014 was merged its errorneous Makefile somehow got pass all checks and the PR got merged (see https://github.com/RIOT-OS/RIOT/pull/7740).

**Comment by miri64** [comment]
(searching the log reveals that they did not seem to be build at all...)

**Comment by kaspar030** [comment]
Seems like murdock's get_jobs stage doesn't fail if one of the makefiles is broken. Will come up with a fix...

**Comment by kaspar030** [comment]
Fixed by #7742.
