### ISSUE TITLE
nrf52dk ?

### ISSUE THREAD

**Issue by bnjroos** [RIOT-OS/RIOT#7744]
Is nrf52dk working with nrf52832 sdk ?

TIA

**Comment by haukepetersen** [comment]
I don't quite understand the question, do you mean if the `nrf52dk` port works with the nrf52832 development kit (meaning the hardware)? Or is the question if the port for the `nrf52dk` is using the Nordic SDK?

**Comment by PeterKietzmann** [comment]
@bnjroos please rephrase!

**Comment by PeterKietzmann** [comment]
No response since > 1,5 years.
