### ISSUE TITLE
tests/posix_semaphore: fails

### ISSUE THREAD

**Issue by A-Paul** [RIOT-OS/RIOT#7792]
While testing on 2017.10-RC1 with native the following error showed up.

> ######################### TEST4:
> first: sem_init s1
> first: wait 1 sec for s1
> first: timed out
> first: waited only 1000105 usec => FAILED
> ######################### DONE
> Timeout in expect script

**Comment by miri64** [comment]
Isn't that fixed in https://github.com/RIOT-OS/RIOT/pull/7782?

**Comment by miri64** [comment]
@A-Paul ping? Please test if #7782 fixes this issue and close it if so.

**Comment by A-Paul** [comment]
Tested on *2017.10-branch* (including backported fix https://github.com/RIOT-OS/RIOT/pull/7808).
No errors anymore.
