### ISSUE TITLE
tests/pkg_fatfs *mkfs* not functional

### ISSUE THREAD

**Issue by A-Paul** [RIOT-OS/RIOT#7795]
Testing 2017.10-RC1:
In the shell *mkfs* always returns ``[FAILED] error 1 ``. Even if an image file has been created.
All other functions are O.K.

**Comment by A-Paul** [comment]
> Which platform?
@miri64, it came up on native. But the error may be more general.
@MichelRottleuthner, can you set the *native* label this is platform specific?

**Comment by MichelRottleuthner** [comment]
The error is specific to native. I'll provide a fix.
