### ISSUE TITLE
CI: build native with clang as well

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#7869]
Lots of our contributors use clang instead of gcc. However clang has a few different error behavior in some places. In the early days of CI I included the clang builds, Murdock however does not. Is this somehow possible?

**Comment by aabadie** [comment]
Murdock is now building with gcc and clang, for native and other platforms. @miri64 do you think we can close this one ?

**Comment by miri64** [comment]
Yepp.
