### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#7886]
RNG unified (secure, or basic), seeding easy TinyDTLS integration in sock, with CoAP etc.
  - Related issues:
    - [x] #2264
    - [x] #3221
    - [x] #4882
    - [ ] #5150
    - [ ] #5659
    - [x] #7397 
    - [x] #7649
 - Related PRs
    - [x] #4294
    - [x] #5675

RIOT default configuration = secure configuration (that's our goal/motto)
  - Related issues
    - [ ] 

802.15.4 link layer security (gaps in RFCs? How to update keys?)
  - Related issues
    - [ ]

**Comment by miri64** [comment]
I don't really get what the purpose of this issue is... can it be closed? Some issues and PR mentioned in OP were either closed or merged (I ticked them because :woman_shrugging:).
