### ISSUE TITLE
Low-level Hardware Support

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#7888]
Improved MIPS support
  - Related issues
    - [ ] #6588
    - [ ] #6802
    - [ ] #7753

Radio support for TI SensorTag
  - Related issues - none
  - Related PRs
    - [ ] #5496
    - [ ] #5746

Radio support for Silab Thunderboard (EFM32)
  - Related issues
    - [ ] #1123
  - Related PRs
    - [ ] #5652

Improve x86/Quark support (e.g. Arduino 101) via QMSI (deprecated)
  ~~- Related issues~~
    - ~~[ ] #1504~~
    - ~~[ ] #3630~~

Radio support for Arduino MKR1000
  - Related issues - none
  - Related PRs
    - [ ] #7433

ST Nucleo support
  - Related issues
    - [ ] #6629
    - [ ] #6669
    - [ ] #7282
    - [ ] #7440
  - Related PRs
    - [ ] #7491
    - [ ] #7085
    - [ ] #7354

LoRa drivers
  - Related issues - none
  - Related PRs
    - [ ] #6645
    - [ ] #7356
    - [ ] #7482
    - [ ] #7505
    - [ ] #7584
    - [ ] #7697
    - [ ] ~~#6165~~  (closed)
    - [ ] #7592

**Comment by kbumsik** [comment]
FYI, [Intel discontinued the whole IoT products](https://www.cnx-software.com/2017/07/26/intel-curie-module-arduino-101-boards-are-being-discontinued-too/), including Curie, Quark, and Arduino 101, meaning Intel left the IoT devices market and not willing to release new products anymore.

**Comment by kYc0o** [comment]
Yeah I was aware of that so I suppose we need to erase that from our roadmap.

**Comment by PeterKietzmann** [comment]
This issue was never used or maintained, so IMO it didn't help tracking development process. I guess there are others of this type. @emmanuelsearch how do you think about it? Should we update or close? Personally I think that especially hardware support is so fast that tracking it would only introduce overhead.

**Comment by kaspar030** [comment]
IMO ok to close.
