### ISSUE TITLE
Software Updates

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#7890]
Prototype of firmware swapping, assuming the internal flash can contain 2 images and the bootloader, demoed on IoT-Lab_M3
  - Related issues - none
  - Related PRs
    - [ ] #7457
    - [ ] #7396

Firmware loading through serial using ethos, when no image is flashed on the node.
  - A firmware server can be started with the address and the firmware to flash.
  - Related issues
    - [ ]

Firmware update through UDP.
  - A module is included on any updatable firmware, able to deal with firmware requests.
    - Related issues - none
    - Related PRs
      - [ ] #7398

  - The node asks for a new firmware and the server answers with the correct image.
    - Related issues - none
    - Related PRs
      - [ ] #7398

Interpreted language support (js and python) with dynamically updatable scripts
  - Related PRs
    - [ ] #2968

Prototype for secure bootloading enhancements (authentification, integrity, confidentiality, bootstrap of keys)
  - Related PRs
    - [ ] #7181
    - [ ] #7396
    - [ ] 

Firmware distribution enhancements (firmware metadata refinements, automatic discovery/push/pull from server or nearby node caching newer firmware)
  - Related PRs
    - [ ]

Partial firmware update (Dynamic linking and loading of ELF files).
  - Related PRs
    - [ ] #3686 (closed)

**Comment by waehlisch** [comment]
Is this issue still needed or can we close because of #9342.

**Comment by danpetry** [comment]
All of the linked issues are closed, apart from micropython (which currently has tenuous link to software updates) and MCUBoot support for FRDM-K64F, which is linked on the OTA project (here)[https://github.com/RIOT-OS/RIOT/projects/11]. Closed.
