### ISSUE TITLE
Network Stack Low layers

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#7893]
BLE link-layer support (below HCI, port from MyNewt?) towards fully open source support of 6LoWPAN over BLE
  - Related issues
    - [ ] #4684
    - [ ] #7154

LoRa & LoRaWAN driver and MAC layer integration
  - Related issues - none
  - Related PRs
    - [ ] #5496
    - [ ] #7107
    - [ ] #7419

Duty Cycling Radio: finalize and merge lwMAC
  - Related issues
    - [ ] #3039
  - Related PRs
    - [ ] #7442

Traffic adaptive MAC protocol: finalize and merge iQueue -> GoMacH?
  - Related PRs
    - [ ] #5618

Retransmissions by MAC: finalize and merge netdev_retrans
  - Related issues - none
  - Related PRs
    - [ ] #4795

Point-to-Point Protocol (PPP): finalize and merge gnrc_ppp
  - Related issues - none
  - Related PRs
    - [ ] #5470
    - [ ] #5471
    - [ ] #5473

Re-integrate and clean-up 802.15.4 TSCH integration
  - Related issues
    - [ ] #3039
    - [ ] #4858
    - [ ] #7278

**Comment by dkazantzas** [comment]
Hi, I would love to help with that. How could I acccomplish that?

**Comment by kYc0o** [comment]
@dkazantzas we started a thread on our mailing list to discuss about this topic. You can subscribe at [devel@riot-os.org](https://lists.riot-os.org/mailman/listinfo/devel).

**Comment by PeterKietzmann** [comment]
@kYc0o personally I have the impression this issue does not help. And obviously it hasn't been updated or used since opening. Browsing through the referenced PRs/issues it seems that (i) many projects have been canceled and closed and (ii) I'm missing the red thread. Of course it's about "lower layers" but for example, one finds further tracking issues for MCU hardware support next to outdated radio driver PRs or protocol feature requests. What do you think about this issue, candidate for closing or would you mind updating?

**Comment by kYc0o** [comment]
@PeterKietzmann I agree with you. My aim was to track the progress of the things highlighted on our roadmap, in order to know where the efforts were needed. I don't know if we're actually following the roadmap anymore of if it's still up to date. I can try to update all my issues and (try to) give again a global view of the progress made in our most important directions. But if the need doesn't exist, or needs to be tackled differently, I can close all my issues.

**Comment by PeterKietzmann** [comment]
> My aim was to track the progress of the things highlighted on our roadmap

Yepp I see and the idea seems reasonable. But now -half a year later - it seems as if the tracking mechanism was not used by the community and thus only introduces management overhead. However, I won't close the issue, just wanted to raise the question...
