### ISSUE TITLE
Network Stack High layers

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#7894]
Fix lingering NDP issues
  - Related issues
    - see https://github.com/RIOT-OS/RIOT/projects/6

ICN stack support clean-up
  - Related issues - none
  - Related PRs
    - [ ] #5648
    - [ ] #5914

Discuss mid- and long-term plans for network stack maintenance & development (GNRC vs other supported stacks)
  - Related issues
    - [ ] 

Support for CoAP blockwise transfer, observe
  - Related issues
    - [ ] #7192
  - Related PRs
    - [x] #6469
    - [ ] #7237
    - [ ] #7548
    - [ ] #7699
    - [ ] #7700

Revisit network time synchronization
  - Related issues
    - [ ]

**Comment by miri64** [comment]
What is this issue? Is this a copy of the Roadmap? I'm confused :-/

**Comment by kYc0o** [comment]
Yes, it's a step forward the organisation for the meetings.

**Comment by miri64** [comment]
I'm not sure if having 9 issues for 1 meeting is scaling so well...

**Comment by miri64** [comment]
One point is actually outdated (sorry for not updating the Roadmap): conn was deleted in April.

**Comment by miri64** [comment]
(adapted the issue and the roadmap)

**Comment by kYc0o** [comment]
> I'm not sure if having 9 issues for 1 meeting is scaling so well...

No that's not the point,  I'll send an email to explain.

**Comment by tcschmidt** [comment]
I guess we can close this one - correct?

**Comment by kYc0o** [comment]
I'm not sure, I need to check if all issues are solved, though I guess there are more... I need rather to update all the related issues to reflect the ongoing work.

**Comment by kb2ma** [comment]
I maintain some pages for CoAP, which are referenced from the overall [Roadmap page](https://github.com/RIOT-OS/RIOT/wiki/Roadmap). #9309 is a pretty good summary of current state.
