### ISSUE TITLE
forced uncrustify

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#7942]
I've noticed that uncrustify does some things that I don't like, e.g., some variable alignment.

Can we maybe come up with an (additional) uncrustify config that only fixes the style issues we'd be enforcing anyways?

We could then cleanup our codebase once, then make the CI force these issues.

**Comment by miri64** [comment]
Kind-of duplicate of #4363...

**Comment by kaspar030** [comment]
> Kind-of duplicate of #4363...

True! will close.
