### ISSUE TITLE
chronos: Debouncing of gpio interrupts

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#8]
Node sometimes stuck in a loop when due to possible erroneous implementation of gpio interrupt debouncing.

**Comment by authmillenon** [comment]
Still an issue with the msp430 rewrite?

**Comment by OlegHahm** [comment]
Probably yes.

**Comment by haukepetersen** [comment]
By reading this again: I would say this issue is true for almost all borads that have buttons, but I'd say that this is not really a board issue but an application issue.

I opened a generalized issue (#5151). @OlegHahm are you okay with closing this issue?

**Comment by OlegHahm** [comment]
Definitely. Good idea!
