### ISSUE TITLE
stm32/pwm: timer multiplier not taken into account

### ISSUE THREAD

**Issue by george-hopkins** [RIOT-OS/RIOT#8000]
On some platforms (e.g. STM32F103xE), the clock for the timers is multiplied by 2 whenever the APBx prescaler is not 1. As far as I can see, the multiplication is currently not taken into account by the PWM driver (the APBx frequency is used directly). This results in a wrong calculcation of the timer prescaler (PSCx) and a PWM frequency which is too high.

#### Example (frequency set to 500 Hz)
![pwm-example](https://user-images.githubusercontent.com/552590/32664899-e47321cc-c632-11e7-8e47-b757ebffbf1c.png)

#### Clock Tree for STM32F103xE
![](https://user-images.githubusercontent.com/552590/32664842-bd4ef7a6-c632-11e7-8409-795f63138882.png)

**Comment by haukepetersen** [comment]
yapp, this is indeed an issue - I think we had the same for the `timer` implementation. Would you be so kind and provide a fix for the `pwm` driver? Thx.

**Comment by haukepetersen** [comment]
I think the solution here would be to generalize the `apbmul[]` part from the `timer.c` driver and use it for both the `pwm` and the `timer` driver...

**Comment by miri64** [comment]
With #8001 merged, is this issue fixed?

**Comment by aabadie** [comment]
Yes, I'm closing it.
