### ISSUE TITLE
diskio: failed assertion in send_cmd() on lpc2387

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#8028]
When running `examples/default` on `msba2` it runs pretty much immediately into a [failed assertion (link refers to version of master at writing of this issue)](https://github.com/RIOT-OS/RIOT/blob/0792a5d7cb86c61bd4881dea664f4e8c3e211e71/cpu/lpc2387/mci/lpc2387-mci.c#L383). I did not further investigate where this assertion is coming from.

**Comment by maribu** [comment]
@miri64: Did this fix the issue? https://github.com/RIOT-OS/RIOT/pull/9232

**Comment by maribu** [comment]
OK, I guess this was fixed with #9232, as I'm unable to reproduce the issue after it was merged.
