### ISSUE TITLE
mips: several issues

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#8052]
Apart from the issues in #6588, there are some more:

- [x] the mips CPU makefiles have quite a lot of code duplication
- [x] the mips flash targets are empty. They should fail and explain why ("No flash tool available. See https://..." ...).
    - [x] pic32-wifire #9259
    - [ ] pic32-clicker
    - [x] mips-malta => support dropped
- [x] the mips board wiki-pages lack information on how to flash.

**Comment by neiljay** [comment]
@kaspar030 (and everyone else),

I will  attempt to address these issue, but it may take a couple of weeks, things are very busy at the moment, In case you had not heard:

https://www.electronicsweekly.com/news/business/imagination-press-ahead-mips-sale-us-group-tallwood-2017-09/

Neil

**Comment by cladmi** [comment]
This PR fixed some of the code duplication in the makefiles: https://github.com/RIOT-OS/RIOT/pull/8032
Some more cleanup can be done by making `mips_pic32_common` depend on `mips32r2_common` which would depend on `mips.inc.mk`.

**Comment by gebart** [comment]
Some more issues popped up:
 - [ ] The MIPS CPUs never call the common periph_init during boot as far as I can tell.
 - [ ] The MIPS CPUs do not have a cpu_init function which is called by the board_init to initialize things in the CPU, (this function in the other CPUs is sometimes very simple with only a call to periph_init)

**Comment by neiljay** [comment]
item 2 now resolved in #9259. I think this can be closed ?

**Comment by cladmi** [comment]
It is only flashing `pic32-wifire` and not `pic32-clicker`, also it is currently not merged :)
But we are getting closer to closing this.

**Comment by kaspar030** [comment]
This is still being worked on.
