### ISSUE TITLE
Update solicited node multicast groups on IPv6 address addition/deletion

### ISSUE THREAD

**Issue by bergzand** [RIOT-OS/RIOT#8085]
Currently, no extra solicited node multicast addresses are added when an extra IPv6 address that is not derived from the L2 address is added to an interface. This breaks NS/NA.

Steps to reproduce:
1. Start two instances of gnrc_networking
2. Add an extra IPv6 address to the interface of the first node (for example 2001:db8::1/64)
3. Add same prefix to the second node (for example 2001:db8::2/64).
4. Try to ping the address from the second node.

**Comment by miri64** [comment]
Are you talking about 6Lo-based interfaces or Ethernet interface? On 6Lo-based interfaces [this is on purpose](https://tools.ietf.org/html/rfc6775#section-5.2). On Ethernet interfaces this would be a bug.

**Comment by miri64** [comment]
>  On 6Lo-based interfaces this is on purpose.

That a global address wouldn't be reachable in that case, might be due to a different reason.

**Comment by bergzand** [comment]
This was tested on native, so with ethernet interfaces.

**Comment by miri64** [comment]
Ok. Will investigate tomorrow! :-)

**Comment by miri64** [comment]
Should be fixed with #8089.

**Comment by bergzand** [comment]
Is fixed with #8089
