### ISSUE TITLE
gnrc_rpl_p2p: port to nib and fix compile errors

### ISSUE THREAD

**Issue by cgundogan** [RIOT-OS/RIOT#8086]
Currently, `gnrc_rpl_p2p` is not compiling due to trickle API changes. Further, the nib and netif adaptations have to be reevaluated.

I will investigate at the end of next week.

=> #7925

**Comment by miri64** [comment]
Since RPL P2P did not seem to have been used for a while, I wouldn't say this is issue is blocking for #7925.

**Comment by kYc0o** [comment]
@cgundogan is this still an issue?

**Comment by roberthartung** [comment]
ping @cgundogan still an issue?

**Comment by miri64** [comment]
@cgundogan, with https://github.com/RIOT-OS/RIOT/pull/13379 merged, is this issue still on the table?

**Comment by cgundogan** [comment]
:+1: issue can be closed (fixed by #13379)
