### ISSUE TITLE
cc110x: NETOPT_ADDR_LEN

### ISSUE THREAD

**Issue by hahchenchen** [RIOT-OS/RIOT#8105]
when i run the ccn-lite-relay via cc110x, came out an error:
`  error: unable to determine address length for if=<3>
Error registering at network interface!`

The error cames from: ccn-lite-riot.c
`res = gnrc_netapi_get(if_pid, `NETOPT_ADDR_LEN`, 0, &(i->addr_len), sizeof(i->addr_len));
    if (res < 0) {
        DEBUGMSG(ERROR, "error: unable to determine address length for if=<%u>\n", (unsigned) if_pid);
        return -ECANCELED;
    }`

the `NETOPT_ADDR_LEN` is not defined in cc110x-netdev.c.
So anyone can help me?

**Comment by miri64** [comment]
> the NETOPT_ADDR_LEN is not defined in cc110x-netdev.c.
So anyone can help me?

I guess that is the problem ;-). Will provide a fix soonish.

**Comment by PeterKietzmann** [comment]
#8111 solves the issue
