### ISSUE TITLE
at86rf2xx: netdev reset 

### ISSUE THREAD

**Issue by fjmolinas** [RIOT-OS/RIOT#8118]
While using the gnrc_networking example on master I try to send a pkt after resetting the radio by using `ifconfig 7 set state reset`, after resetting UDP packet's don't go out anymore. This doesn't happen when using other radios,  for example mrf24j40. I used samr21-xpro for this.

**Comment by PeterKietzmann** [comment]
Intentions to fix it :-)?

**Comment by kYc0o** [comment]
@bergzand I think you've fixed this isn't it?

**Comment by bergzand** [comment]
Nope, issue still exists

**Comment by bergzand** [comment]
The other thing I noticed is that the radio switched to using the short 802154 mac address.

**Comment by bergzand** [comment]
> The other thing I noticed is that the radio switched to using the short 802154 mac address.

So this one is a bit more troublesome. On initialization, `nib.c` issues a netopt set call to set the used source MAC address to the long address. In the netdev layer this is just a flag. On a `NETOPT_STATE_RESET` call, this flag is cleared again. the `nib.c` never received the netopt call, and thus the address length is never reapplied.

I think the best fix here is to have the `NETOPT_STATE_RESET` call reset the radio device to the current settings/flags, independent of how the radio is configured when the netopt call is submitted.

**Comment by miri64** [comment]
Arghs... Mh... Maybe move the re-initialization to long addresses into a common reset call (#9531) iff `gnrc_sixlowpan` is present?

**Comment by miri64** [comment]
From the comments there I'm not sure #9616 actually fixed it, so I'm reopening for now

**Comment by PeterKietzmann** [comment]
It does fix the issue described above. However, there are still other issues currently which look similar. I opened a new issue for that #9656. Agree to close this again?

**Comment by PeterKietzmann** [comment]
Furthermore, this is not atrf2xx specific (anymore)

**Comment by miri64** [comment]
> Agree to close this again?

Ok, closing in favor of #9656.
