### ISSUE TITLE
doxygen: riot.css modified by 'make doc'

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#8122]
Calling ```make doc``` modifies riot.css in-place, making it show up in git's changed files list.
That's a little annoying. Can that be avoided?

**Comment by aabadie** [comment]
> Can that be avoided?

I had the same problem and I fixed it by uninstalling lessc from npm and install python-lesscpy via apt-get instead.

**Comment by miri64** [comment]
> Can that be avoided?

An alternative would be to switch over from Bootstrap 3 to Bootstrap 4, which uses SASS instead of LESS (which does the compilation live in-browser). Would need some time however.

**Comment by jcarrano** [comment]
See #10249 for a fix to this issue.

**Comment by aabadie** [comment]
Is this still an issue ?

**Comment by miri64** [comment]
We did not change how the `riot.css` is generated, so I'd say, yes. Unless people don't see this as an issue anymore :-D.

**Comment by aabadie** [comment]
I also had this problem in the past but now it doesn't show up anymore. That's why I'm asking.

**Comment by miri64** [comment]
Do you still have LESS compiler installed? Does it incidentally generate the same CSS as the one at hand?

**Comment by aabadie** [comment]
> Do you still have LESS compiler installed?

Ah, that might be that: I don't have LESS compiler :)
