### ISSUE TITLE
gnrc: RA PIO lifetimes are added as milliseconds instead of seconds

### ISSUE THREAD

**Issue by bergzand** [RIOT-OS/RIOT#8134]
Lifetimes [here](https://github.com/RIOT-OS/RIOT/blob/gnrc_netif2_integration/master/sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c#L102) are added as milliseconds, while [rfc 4861, sec 4.6.2](https://tools.ietf.org/html/rfc4861#section-4.6.2) specifies seconds. I have not yet confirmed whether the receiving side of the RIOT code has the same (inverted) issue.

**Comment by miri64** [comment]
Also fixed in #8135.

**Comment by bergzand** [comment]
#8135 is merged
