### ISSUE TITLE
pkg: port LittleFS

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#8204]
Offline @benpicco told me very excited how much faster and smaller than SPIFFS [LittleFS](https://github.com/geky/littlefs) is. A quick glance at the project's README let's me think that this might be a nice file system to support for RIOT. Anyone wants to port it to RIOT with a `vfs` wrapper?

**Comment by gebart** [comment]
Certainly an interesting project. It seems quite new based on the commit history. Is there anyone in the community who is involved in the development of that project?

**Comment by miri64** [comment]
> Is there anyone in the community who is involved in the development of that project?

Seems to be only one [contributor so far](https://github.com/geky/littlefs/graphs/contributors). @benpicco used to be quite active in the community (he used to be a student at FU Berlin), but apart from being a user for his work he doesn't seem to be involved in the project directly.

**Comment by gebart** [comment]
LittleFS was featured on Phoronix today: https://www.phoronix.com/scan.php?page=news_item&px=LittleFS-ARM-Embedded-FS
