### ISSUE TITLE
Fix common issues with shell scripts

### ISSUE THREAD

**Issue by bergzand** [RIOT-OS/RIOT#8212]
shellcheck is an application to statically check shell scripts for common errors. Most of these consists of small issues with the shell scripts where the problem might only appear in certain edge cases.

As an example, one of the issues is that shellcheck warns for is not having quotes around `${VAR}`. This issue leads in the headerguards check to vague errors as soon as there are spaces in `$PWD`.

I think this could also be a useful addition to the CI to check the shell scripts for common mistakes.

[1]: https://github.com/koalaman/shellcheck

**Comment by gebart** [comment]
I like, more static tests 👍

**Comment by aabadie** [comment]
Indeed, very nice. Would be great to have something similar for Makefiles ;)

**Comment by Lotterleben** [comment]
Since both PRs are merged, can this issue be closed?

**Comment by PeterKietzmann** [comment]
It seems so. @bergzand please reopen if I'm mistaken
