### ISSUE TITLE
periph/rtc breaks nucleo-l152

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#8240]
While re-testing #7712 I realised that it didn't work at all, then I tested other examples and nothing seems to work.

After bisecting and looking everywhere, I realised that #6900 was the culprit. Unfortunately I didn't have time to dig more into the issue, so I don't know exactly with commit is the real cause of the crash.

Even if I revert the changes, my PR still not work, but I'm investigating if there are more bugs related to this platform.

**Comment by aabadie** [comment]
Yes nucleo-l152 doesn't work actually, as reported in #7687, see [comment](https://github.com/RIOT-OS/RIOT/pull/7687#issuecomment-343956480). Maybe your problem is related to this ?

**Comment by aabadie** [comment]
Also realized that there's already an issue here: #8024. Duplicate ?

**Comment by kYc0o** [comment]
Definitely this is a duplicate... however I realised that reverting #6900 actually solves the problem for the basic examples. I'll try to move the discussion in those PR/issues. Please don't close this one until that's done.

**Comment by kaspar030** [comment]
duplicate

**Comment by kYc0o** [comment]
I just made the reference on #8024, I didn't want to close this without having it related to it. Now it's ok.
