### ISSUE TITLE
Bit Mask fixes in INA220.h

### ISSUE THREAD

**Issue by troyholt** [RIOT-OS/RIOT#8262]
I just noticed these two lines and thought I would flag them for someone to fix:
   72     INA220_BRNG_32V_FSR = 0x0200, // should be 0x2000
  122     INA220_BADC_AVG_1_SAMPLE    = 0x0400, // should be 0x0000 if you are ORing the ADCBIT bit
                                                                  // mask with the SAMPLE bit mask

**Comment by gebart** [comment]
Thank you @troyholt for the report. Do you have an updated branch somewhere that you would like to contribute (Pull request)?
