### ISSUE TITLE
emlib: warnings when using GCC 7

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#8266]
#### Description
This error occurs when building the default example for the ikea-tradfri board when using GCC 7.2.0:

#### Steps to reproduce the issue

Use GCC 7.2.0
`make BOARD=ikea-tradfri -C examples/default`

#### Expected results

No compilation errors

#### Actual results

```
/home/jgn/work/src/riot/examples/default/bin/pkg/ikea-tradfri/emlib/emlib/src/em_cmu.c: In function ‘CMU_ClockSelectSet’:
/home/jgn/work/src/riot/examples/default/bin/pkg/ikea-tradfri/emlib/emlib/src/em_cmu.c:3463:14: error: this statement may fall through [-Werror=implicit-fallthrough=]
       selReg = (selReg == NULL) ? &CMU->LFACLKSEL : selReg;
       ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jgn/work/src/riot/examples/default/bin/pkg/ikea-tradfri/emlib/emlib/src/em_cmu.c:3480:5: note: here
     case CMU_LFECLKSEL_REG:
     ^~~~
/home/jgn/work/src/riot/examples/default/bin/pkg/ikea-tradfri/emlib/emlib/src/em_cmu.c:3481:14: error: this statement may fall through [-Werror=implicit-fallthrough=]
       selReg = (selReg == NULL) ? &CMU->LFECLKSEL : selReg;
       ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jgn/work/src/riot/examples/default/bin/pkg/ikea-tradfri/emlib/emlib/src/em_cmu.c:3488:5: note: here
     case CMU_LFBCLKSEL_REG:
     ^~~~
cc1: all warnings being treated as errors
```

#### Versions

arm-none-eabi-gcc (Gentoo 7.2.0 p1.1) 7.2.0

#### Issue references

#8265

**Comment by miri64** [comment]
Potential fixes: either add a patch with the according comments to the switch-case (`/* falls through intentionally */`) or deactivate `-Werror=implicit-fallthrough` for `emlib`.

**Comment by nmeum** [comment]
This seems to have been fixed, at least I can't reproduce this anymore with gcc 7.2.0. The switch statements contain `/* Fall through and [...] */` comments now which should stop gcc from emitting a warning.
