### ISSUE TITLE
pkg/libcoap: patching fails with newer version of git

### ISSUE THREAD

**Issue by smlng** [RIOT-OS/RIOT#8289]
#### Description

While the libcoap package still works when compiled by murdock, patching fails with new versions of GIT, e.g., on Arch Linux and macOS with git 2.15.x. Using older git version, e.g., 2.11.x on Raspbian still works.

#### Steps to reproduce the issue

Try to build `tests/pkg_libcoap` with GIT version 2.15.x.

#### Expected results

builds

#### Actual results

patching fails, starting with patch 0004*

#### Versions

* GIT version 2.15.x does not work
* GIT version 2.11.x still works.

**Comment by miri64** [comment]
My machine currently only has `git` 2.7 (Ubuntu 16.04)... So I can't work on this at the moment :(

**Comment by smlng** [comment]
I discovered this only very recently myself, when running compile tests on macOS, but I never used libcoap with RIOT. And Murdock didn't hit this issue yet, but might in the future, when we update the worker images - so its good to be prepared, I guess.

**Comment by kYc0o** [comment]
I can confirm the issue, I experienced it while testing #7737.

**Comment by smlng** [comment]
fixed by #8396
