### ISSUE TITLE
Feature request: File system example

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#8339]
Now that `vfs` supports a few file systems, it might be time to provide an example of how to access files in the `examples/` directory. I know that you can just use the newlib syscalls, so I think that is something we should showcase.

**Comment by aabadie** [comment]
It would be great if this example was using the `sd_card_spi` driver. It could be a good data logger example for Adafruit Feather-M0 and Arduino MKRZERO boards.

**Comment by miri64** [comment]
I don't think its a good idea to have the example use a specific device, especially since flash-based storages are way more common in IoT scenarios.

**Comment by MichelRottleuthner** [comment]
I agree with @miri64 that we should not tie the example to a specific device. But it won't hurt to keep an eye on making it easy to switch the example to use *some_storage_dev_supported_by_riot*.
>...especially since flash-based storages are way more common in IoT scenarios.

the last time I checked sd-cards were flash based ;)

**Comment by miri64** [comment]
> the last time I checked sd-cards were flash based ;)

I meant the thingies you solder to your board ;-)
