### ISSUE TITLE
task: implement dns client

### ISSUE THREAD

**Issue by mehlis** [RIOT-OS/RIOT#841]
implement getaddrinfo (only IPv6 part needed)

dns servers: ~~ff02::1:2 and ff05::1:3~~ `FF01::FB` is a priori known

takes a hostname as string, creates valid dns packet, sends it out to dns multicast group.

receives a valid answer, parses it, returns IP adress(es)

**Comment by DipSwitch** [comment]
Can be closed because with #3823

**Comment by OlegHahm** [comment]
But #3823 hasn't been merged yet.

**Comment by authmillenon** [comment]
Fixed by #3823 (for auto-close)

**Comment by miri64** [comment]
The title would indicate that, but the description also asks for an `getaddrinfo()` implementation and is marked as a posix feature request, so I would not yet close it.

**Comment by kaspar030** [comment]
Closed in favour of #7801.
