### ISSUE TITLE
release test 2018.01 RC1: tests/periph_hwng, device not initialized

### ISSUE THREAD

**Issue by A-Paul** [RIOT-OS/RIOT#8443]
#### Description
Running the test fires a lot of messages: **random device not initialized, failing**

#### Steps to reproduce the issue
"make clean all term" in *tests/periph_hwrng*

#### Actual results
> RIOT native interrupts/signals initialized.
> LED_RED_OFF
> LED_GREEN_ON
> RIOT native board initialized.
> RIOT native hardware initialization complete.
> 
> main(): This is RIOT! (Version: 2018.04-devel-17-ga78b-mobi31-2018.01-branch)
> 
> HWRNG peripheral driver test
> 
> This test will print from 1 to 20 random bytes about every second
> 
> generating 1 random byte(s)
> bin/native/tests_periph_hwrng.elf: hwrng_read: random device not initialized, failing
> 
> Got: 0x00
> generating 2 random byte(s)
> bin/native/tests_periph_hwrng.elf: hwrng_read: random device not initialized, failing
>
> Got: 0x00 0x00
> generating 3 random byte(s)
> bin/native/tests_periph_hwrng.elf: hwrng_read: random device not initialized, failing

and so on ...

#### Versions
```
----------------------------
          native gcc: gcc (Debian 6.3.0-18) 6.3.0 20170516
          msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
             avr-gcc: avr-gcc (GCC) 4.9.2
   arm-none-eabi-gcc: arm-none-eabi-gcc (15:5.4.1+svn241155-1) 5.4.1 20160919
    mips-mti-elf-gcc: missing/error
../../dist/tools/ci/print_toolchain_versions.sh: 92: ../../dist/tools/ci/print_toolchain_versions.sh: clang: not found
arm-none-eabi-newlib: "2.4.0"
 mips-mti-elf-newlib: missing/error
            avr-libc: "1.8.0svn" ("20111229")
            cppcheck: missing
          coccinelle: missing
                 git: git version 2.11.0
```

**Comment by miri64** [comment]
Fixed by #8466
