### ISSUE TITLE
CCN Lite: Add "no 8-Bit support" to documentation

### ISSUE THREAD

**Issue by Citrullin** [RIOT-OS/RIOT#8598]
I tried one CCN Lite example. While compiling I got many errors. I fixed some of them, until I reached the following point:
```
ccnl-pkt-ccntlv.c:508:5: error: left shift count >= width of type [-Werror]
```
ccntlv line 508
```
    if ( (unsigned int)len >= ((1 << 16) - sizeof(struct ccnx_tlvhdr_ccnx2015_s)))
        return -1;
```

Since CCN Lite shifts 16 bits, I guess 8-Bit MCUs are not supported. I recommend to add this somewhere to the documentation. :) There are also other places where CCN Lite shifts 16 bits.

**Comment by gebart** [comment]
I guess ccn lite assumes int is 32 bit. This should be fixed upstream, but I guess you should be able to add a cast to uint32_t on the left shift to fix it.

**Comment by mfrey** [comment]
CCN-lite lacks precision in the length of types. My assumption is that this is partially due to the fact that it supports multiple message formats. We've already discussed this briefly and it is already part of the [todo list](https://github.com/cn-uofbasel/ccn-lite/wiki/TODO)

**Comment by Citrullin** [comment]
@mfrey Of course, it would be nice to get a fix for it :) But for now, I think a short notice in the documentation is just fine. So, user know that 8-Bit MCUs are not supported at the moment. (just for networking with CCN Lite).

**Comment by PeterKietzmann** [comment]
It's documented [here](https://github.com/cn-uofbasel/ccn-lite/wiki/Frequently-asked-questions) in the ccn-lite FAQ. @Citrullin, @cgundogan would you provide that information in the RIOT doc? I'm adding the Hack'n'ACK label for that.

**Comment by miri64** [comment]
Ping @Citrullin @cgundogan?

**Comment by Citrullin** [comment]
@miri64 I don't really care about this.

**Comment by cgundogan** [comment]
see https://github.com/cn-uofbasel/ccn-lite/pull/363. Once merged, this issue should resolve.

**Comment by miri64** [comment]
Merged, so I guess all we need now is a version bump of CCN-lite to close this issue ;-).

**Comment by mfrey** [comment]
> Merged, so I guess all we need now is a version bump of CCN-lite to close this issue ;-).

Afair, last time this broke a few things with the shell commands. But I might be wrong.

**Comment by miri64** [comment]
> Afair, last time this broke a few things with the shell commands. But I might be wrong.

For this we have testing.

**Comment by cgundogan** [comment]
@Citrullin just out of curiosity: which AVR board did you use to compile ccn-lite?

**Comment by Citrullin** [comment]
> @Citrullin just out of curiosity: which AVR board did you use to compile ccn-lite?

Some Arduino clone as I remember. Some ATMEGA328P.
