### ISSUE TITLE
adxl345.h MCU Pin Definition in module header.

### ISSUE THREAD

**Issue by Josar** [RIOT-OS/RIOT#8658]
https://github.com/RIOT-OS/RIOT/blob/2cab4292d57cd6ec5d16752cfc60ee8030ed423d/drivers/include/adxl345.h#L95

This should not be defined here. IMHO.
Collision with iom256rfr2.h

I don't see where they are used anyhow.

https://github.com/RIOT-OS/RIOT/pull/8643#discussion_r171176311

**Comment by dylad** [comment]
Hi @Josar 
I think this declaration is at the perfect place, this enum is here for select the interrupt type output for the ADXL345's interrupts pins as this accelerometer have two pins dedicated to interrup. Thus there are not related to any CPU.
One solution for your issue would be to rename this to : 
```
enum {
ADXL345_INT1,
ADXL345_INT2
}
```
I can open a PR to change it if you want.

**Comment by Josar** [comment]
@dylad  OK thanks.

**Comment by Josar** [comment]
What si with stream and fifo would it be better to prepend them also to avoid future collision?

**Comment by dylad** [comment]
@Josar #8661 should solve your issue.
I've renamed the two enums to avoid any conflict in the future.

**Comment by dylad** [comment]
Oh sorry I didn't see you send a PR just before mine. I'll drop mine then.

**Comment by dylad** [comment]
Can we close this issue now that #8696 is merged ?
