### ISSUE TITLE
nucleo-l152: LSE broken

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#8662]
#### Description

On nucleo-l152 rev C-03 or newer, there's a problem using the on-board 32.768KHz crystal. #8545 proposes to use the internal low speed oscillator to avoid the problem, but it doesn't solve it.
#### Steps to reproduce the issue

Compile any example with LSE set at 1 (CLOCK_LSE define) for BOARD=nucleo-l152.
#### Expected results

Any example works properly.
#### Actual results

It hangs.

**Comment by aabadie** [comment]
To be complete, #8545 changes should be updated with a reference on this issue (see [here](https://github.com/RIOT-OS/RIOT/pull/8545/files/f35edcacf1663d05fcb494e3da85d053660aa1e0#diff-5d69d844a724995a1e1add8ee4bbca0c))

**Comment by kaspar030** [comment]
What'S the state here?

**Comment by aabadie** [comment]
Ok, I don't understand why (maybe #8735 ?), but I just switched CLOCK_LSE to 1 in the nucleo-l152 peripheral configuration and it works like a charm.

So I would say that this issue can be closed.

**Comment by aabadie** [comment]
This is issue will be closed automatically when #8961 is merged.
