### ISSUE TITLE
/sys/random/seed: why not use hwrng if available?

### ISSUE THREAD

**Issue by MichelRottleuthner** [RIOT-OS/RIOT#8663]
#### Description
When using modules like gcoap (and probably others - gcoap is just an examle here) that use random_uint32() within their init phase this leads to always the same message IDs at startup even if the target comes with hwrng capability. This is at least not what I expected to happen when looking at gcoap_init() which calls `atomic_init(&_coap_state.next_message_id, (unsigned)random_uint32());`, while I am taking care that `FEATURES_REQUIRED += periph_hwrng` and `USEMODULE += random` are added to my applications makefile.
Manually adding something like `random_init(hwrngseed);` to the beginning of my application also won't help in this case, because gcoap (and potentially other modules) are grabbing their random in auto_init phase.
Is there a specific reason for not using hwrng as seed for /sys/random/?
For deterministic testing this is really nice but for me this doesn't make sense as default.

#### Steps to reproduce the issue
Starting from RIOT base dir:
```
dist/tools/tapsetup/tapsetup
cd examples/gcoap/
make
```
Then calling the following mutlipe times:
```
./bin/native/gcoap_example.elf tap0 -i 1234
coap get ::1 5683 /.well-known/core
^C
```
The executable is called directly with `tap0 -i 1234` instead of `make term`, because otherwise the following code from cpu/native/startup.c is masking the static random init by effectively creating a new CPUID each startup:
```
_native_pid = real_getpid();
/* will possibly be overridden via option below: */
_native_id = _native_pid;
```
#### Expected results
riot terminal output by two consecutive executions:
<pre>
<i>gcoap_cli: sending msg ID <b>some random ID</b>, 23 bytes
gcoap: response Success, code 2.05, 26 bytes
&lt/cli/stats&gt,&lt/riot/board&gt
^C</i>
<i>gcoap_cli: sending msg ID <b>aother random ID</b>, 23 bytes
gcoap: response Success, code 2.05, 26 bytes
&lt/cli/stats&gt,&lt/riot/board&gt
</i>
</pre>

#### Actual results
<pre>
<i>gcoap_cli: sending msg ID <b>28607</b>, 23 bytes
gcoap: response Success, code 2.05, 26 bytes
&lt/cli/stats&gt,&lt/riot/board&gt
^C</i>
</i>
<i>gcoap_cli: sending msg ID <b>28607</b>, 23 bytes
gcoap: response Success, code 2.05, 26 bytes
&lt/cli/stats&gt,&lt/riot/board&gt
^C</i></pre>
#### Versions
current master
related: #7547

**Comment by PeterKietzmann** [comment]
#10974 solves this issue. @MichelRottleuthner please reopen if I'm mistaken.
