### ISSUE TITLE
dist: header guard checker too nit-picky

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#8737]
In #7881 I found myself stumped when both CI servers still complained about the header guards, though at least to me they looked alright. Turns out the header guard script expects there to be an *exact* number of spaces (1) between the `#endif` and the comment. I think this is very nit-picky and especially annoying since the script doesn't show (at least on the CI servers) on its own what the actual problem is.

My proposed fix would be to either just output the problem so a contributor is able to react quickly or even better make the number of whitespaces variable when applicable.

**Comment by bergzand** [comment]
Would adjusting the `headercheck.py` script to output something like:

```
expected: "#endif /* HASHES_SHA3_H */" 
found     "#endif  /* HASHES_SHA3_H */"
```

solve this issue?

**Comment by mtausig** [comment]
Yes. This I way I could fix the issues myself instead of waiting for someone else to do some extra work to tell me what I need to do.

**Comment by smlng** [comment]
mhm, the script in `dist/tools/headerguards/headerguards.py` already does that, i.e., it prints a diff when executed locally, but it seems that `static-tests` suppresses the output.
