### ISSUE TITLE
wiki: Broken MIPS toolchain links

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/RIOT#8755]
#### Description

I just noticed all links pointing to MIPS toolchain are broken, as seen [in the wiki entry](https://github.com/RIOT-OS/RIOT/wiki/Family%3A-MIPS). They are pointing to the root site, so it seems the site changed the URL format.

**Comment by aabadie** [comment]
Would it make sense to use the following link ?
https://codescape.mips.com/components/toolchain/2017.10-08/downloads.html

**Comment by gebart** [comment]
For the latest version, go to https://www.mips.com/develop/tools/codescape-mips-sdk/ and select "Codescape GNU Toolchain" (which is the same link that @aabadie posted above)

**Comment by aabadie** [comment]
Thanks @gebart. I edited the wiki page with new instructions. If it's ok, we can close this issue.

**Comment by gebart** [comment]
Looks good to me, closing
