### ISSUE TITLE
fibroute command not working

### ISSUE THREAD

**Issue by carlotapares** [RIOT-OS/RIOT#8783]
Hi,
I've just tried this tutorial [https://github.com/RIOT-OS/RIOT/wiki/Tutorial:-RIOT-and-Multi-Hop-Routing-with-RPL]() and when I get to the step of issuing the _fibroute_ command my shell says command not recognized. 
I have cloned the RIOT repository and compiled the gnrc_networking example [https://github.com/RIOT-OS/RIOT/tree/master/examples/gnrc_networking]() as it is. Do I have to make any modification for this command to work?

Thanks in advance,
Carlota

**Comment by miri64** [comment]
Hi, the tutorial seems to be out-dated. Please use `nib route` instead.

**Comment by carlotapares** [comment]
Great! Just tried it!
Thanks a lot!!
