### ISSUE TITLE
Call msg_send_receive before target is in RX

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#879]
The documentation of `msg_send_receive()` says that one must not call this function if it is not ensured that the target thread is already in receiving state. However the example `ipc_pong` calls `msg_send_receive()` before the second thread is even started - and seems to be working anyway. So, I'm not sure if the documentation is still right.

**Comment by PeterKietzmann** [comment]
Still present? Newbie task?

**Comment by OlegHahm** [comment]
Not a newbie task, more a digging in the past. @kaspar030, do you recall the reason for this line of documentation?

**Comment by OlegHahm** [comment]
Looking at this again and writing a little [test application](https://github.com/OlegHahm/miniature-dangerzone/tree/master/test_msg_receive) for this, I cannot thing of a reason why this shouldn't be allowed. The only problem I see if sender and receiver are the same thread. @kaspar030, would you agree to remove this line from the documentation?

**Comment by kaspar030** [comment]
Yes! Will open a PR.

**Comment by kaspar030** [comment]
Fixed through #4362.
