### ISSUE TITLE
gnrc_networking program

### ISSUE THREAD

**Issue by harisatyasrinivas** [RIOT-OS/RIOT#8849]
when i compile the gnrc_networking program for z1 , its prompting the below error how to resolve ??

"make" -C /home/user/RIOT/sys/tsrb
"make" -C /home/user/RIOT/sys/uart_stdio
"make" -C /home/user/RIOT/sys/xtimer
/usr/lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: /home/user/RIOT/examples/gnrc_networking/bin/z1/gnrc_networking.elf section `.text' will not fit in region `rom'
/usr/lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: /home/user/RIOT/examples/gnrc_networking/bin/z1/gnrc_networking.elf section `.bss' will not fit in region `ram'
/usr/lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: section .vectors loaded at [0000ffc0,0000ffff] overlaps section .text loaded at [00003100,0001584d]
/usr/lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: region `ram' overflowed by 306 bytes
/usr/lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: region `rom' overflowed by 35342 bytes
/usr/lib/gcc/msp430/4.6.3/mcpu-430x/mmpy-16/libcrt0.a(_copy_data.o): In function `__do_copy_data':
/build/buildd/gcc-msp430-4.6.3~mspgcc-20120406/./gcc-4.6.3/gcc/config/msp430/crt0.S:195: relocation truncated to fit: R_MSP430_16_BYTE against symbol `__data_load_start' defined in *ABS* section in /home/user/RIOT/examples/gnrc_networking/bin/z1/gnrc_networking.elf
/home/user/RIOT/examples/gnrc_networking/bin/z1/application_gnrc_networking.a(main.o): In function `main':
/home/user/RIOT/examples/gnrc_networking/main.c:41: relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/home/user/RIOT/examples/gnrc_networking/main.c:41: relocation truncated to fit: R_MSP430_16 against symbol `puts' defined in .text section in /usr/lib/gcc/msp430/4.6.3/../../../../msp430/lib/mcpu-430x/mmpy-16/libc.a(puts.o)
/home/user/RIOT/examples/gnrc_networking/main.c:44: relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/home/user/RIOT/examples/gnrc_networking/main.c:44: relocation truncated to fit: R_MSP430_16 against symbol `puts' defined in .text section in /usr/lib/gcc/msp430/4.6.3/../../../../msp430/lib/mcpu-430x/mmpy-16/libc.a(puts.o)
/home/user/RIOT/examples/gnrc_networking/main.c:46: relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/home/user/RIOT/examples/gnrc_networking/bin/z1/application_gnrc_networking.a(main.o):(.rodata.shell_commands+0x0): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/home/user/RIOT/examples/gnrc_networking/bin/z1/application_gnrc_networking.a(main.o):(.rodata.shell_commands+0x2): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/home/user/RIOT/examples/gnrc_networking/bin/z1/application_gnrc_networking.a(main.o):(.debug_info+0x1df): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/home/user/RIOT/examples/gnrc_networking/bin/z1/msp430_common/startup.o: In function `startup':
/home/user/RIOT/cpu/msp430_common/startup.c:36: relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
/home/user/RIOT/cpu/msp430_common/startup.c:36: additional relocation overflows omitted from the output
collect2: ld returned 1 exit status
/home/user/RIOT/examples/gnrc_networking/../../Makefile.include:328: recipe for target 'link' failed
make: *** [link] Error 1

**Comment by miri64** [comment]
`gnrc_networking` is way to big for your board. Try `gnrc_minimal`.
