### ISSUE TITLE
test/periph_i2c: cannot use init_master command for nrf5x_common and EFM32 families

### ISSUE THREAD

**Issue by dylad** [RIOT-OS/RIOT#8851]
#### Description
Cannot use `init_master` command from `test/periph_i2c` on NRF52 based board.

#### Steps to reproduce the issue
call `init_master 0 1` (0 is first I2C bus available and 1 stand for `I2C_SPEED_NORMAL` so 100kbits/s)

#### Expected results
I2C is properly initialized.

#### Actual results
```
init_master 0 1
Error: Init: Unsupported speed value
```

#### Versions
current RIOT master

Current I2C implementation from NRF52 supports `I2C_NORMAL_SPEED` and `I2C_FAST_SPEED`.
From what I understand, nrf52 defines its own i2c_speed_t enum
```
typedef enum {
    I2C_SPEED_LOW       = 0xff,                         /**< not supported */
    I2C_SPEED_NORMAL    = TWIM_FREQUENCY_FREQUENCY_K100,    /**< 100kbit/s */
    I2C_SPEED_FAST      = TWIM_FREQUENCY_FREQUENCY_K400,    /**< 400kbit/s */
    I2C_SPEED_FAST_PLUS = 0xfe,                         /**< not supported */
    I2C_SPEED_HIGH      = 0xfd,                         /**< not supported */
} i2c_speed_t;
```
When we use ` test/periph_i2c`, this app expects 1 for `I2C_SPEED_NORMAL`, 2 for` I2C_SPEED_FAST` etc.
But since nrf52 has its own enum with custom value in order to ease the init in the driver I guess, this test app failed.

As far as I can see, we can either change the behaviour of the `test/periph_i2c` or rewrite the driver.

Additional notes :
This issue may also exists for efm32  and nrf51 family since they define their own `i2c_speed_t`

**Comment by dylad** [comment]
@basilfx Could you confirm this issue also exists on EFM32 please ?

**Comment by basilfx** [comment]
This would also affect EFM32, since it maps the enum values to speed values.

**Comment by dylad** [comment]
Thanks @basilfx ! I've update the tittle.
What's the best workaround for now ? modify the driver or the test app ?

**Comment by basilfx** [comment]
I've created #8852 to fix this issue. 

Since you may override `i2c_speed_t`, I went for modifying the test application.
