### ISSUE TITLE
missing error handling in 6LoWPAN fragmentation

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/RIOT#890]
In `sys/net/network_layer/sixlowpan/lowpan.c` the function `handle_packet_fragment()` checks if the lowpan_transfer thread is sleeping and accordingly calls `thread_wakeup()` to notify this thread that a new packet has been reassembled. However, there's nothing done if the target thread is not sleeping and thus, lowpan_transfer won't get informed until the next packet will arrive.

**Comment by authmillenon** [comment]
Won't fix due to new network stack
