### ISSUE TITLE
[Feature Request] doc: create top-level module checker

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#8972]
#### Description
It appears to be every week or so that someone breaks the [top-level module view](http://doc.riot-os.org/modules.html) of our nice rendered doc (see #8973 for the most current example). Main culprit most of the time is that they set `@ingroup` to a group that does not exist.

How about we provide a checker script that checks `modules.html` directly after the doc was build by the CI, if the list of modules is in line with a given list provided with that checker? If the author of a PR really intends to add a new top-level module (which should rarely happen anyway) they can just append there new module to that list.

**Comment by aabadie** [comment]
Maybe having a per PR overview of the generated documentation would also help (see #8729 for example)

**Comment by miri64** [comment]
This would help a little, but then again: I think a warning is also of need I think. Far to often we let things slip we are technically informed about, but not warned about (see missing runs of unittests last week)

**Comment by aabadie** [comment]
> I think a warning is also of need I think

+1

**Comment by miri64** [comment]
(before anyone does unnecessary work: I checked: there is sadly no way to configure Doxygen to warn on itself if a group referenced by `@ingroup` does not exist :()

**Comment by kaspar030** [comment]
[Here](https://gist.github.com/78b6a26e710a03ae1d28cae5c38f3cbe)'s a prototype that someone could turn into a CI check.

Both ```git grep '@defgroup$'``` and ```git grep '@ingroup$'``` are also insightful. @miri64 those smell like your editor template? ;)

**Comment by aabadie** [comment]
Just in case, I'm working on it based on @kaspar030's gist. The checker works, now I'm fixing the reported issues (and there are quite a few!)
