### ISSUE TITLE
doc: CoAP-RD modules appear on top level

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#8973]
#### Description
All CoAP-RD sub-modules currently appear at the top-level of the module list:

![image](https://user-images.githubusercontent.com/675644/38929195-d8b52a64-430b-11e8-93cb-a8444dc98046.png)

This is due to them being assigned to a group `net_rdcli` (via `@ingroup`) that does not exist.

#### Steps to reproduce the issue
Go to http://doc.riot-os.org/modules.html and have a look ;-).

#### Expected results
The CoAP-RD modules should be in there own sub-group under `Networking`

#### Actual results
They appear on the top-level

#### Versions
—

**Comment by cladmi** [comment]
Should be fixed when the doc is rebuilt.

**Comment by bergzand** [comment]
Doc is rebuild, CoAP RD doesn't appear in the top level anymore
