### ISSUE TITLE
Received packets processing and thread change Timing

### ISSUE THREAD

**Issue by Josar** [RIOT-OS/RIOT#8979]
I ping from an RPI to the jiminy and see that the timings are somehow getting bigger and then jumping back to smaller and again getting bigger.

Thus i added pin toggels to xtimer and to the transciever interrupts. What i can see is that the requested ping is only processed after a xtimer overflow. I would assume that the packet is proccessed as soon as possible.

The timings from received and transmitted can be seen at the right side of the second figure.

So my question would be why does the thread not change imidiatly after the packet is recieved?

Any Ideas? 

![whatsapp image 2018-04-19 at 09 58 06](https://user-images.githubusercontent.com/6164061/38980045-153c268a-43bc-11e8-85a6-4116788fdd99.jpeg)
![whatsapp image 2018-04-19 at 09 56 50](https://user-images.githubusercontent.com/6164061/38980049-16af3f66-43bc-11e8-948d-895ba6a4feb6.jpeg)

**Comment by gebart** [comment]
Does your problem still occur if you apply #8951?

**Comment by Josar** [comment]
Yes atmega based. Thanks for the hint, i will look into it.

**Comment by Josar** [comment]
@gebart could not find `cortexm_isr_end `, but you made me thinking in the right direction.
Compared the timer isr with my isr implementation and found missing information in sched.h

The interrupt has to call the scheduler to execute the thread change.
```
    if (sched_context_switch_request) {
        thread_yield();
    }
```

Now the ping time is at 20ms.
Thanks a lot.

**Comment by gebart** [comment]
No problem :+1:

**Comment by Josar** [comment]
As i see it in `msp430_common` this is included in `__exit_isr` as i would have expected it to be, in `atmega_common` it is not. Instead it is redundatnly written in every isr

**Comment by gebart** [comment]
IMO the msp430 and cortex approach is preferable. This is something that was refactored for the Cortex-M platforms in #6171. Feel free to provide a similar PR for the atmega if you feel like you have the time to do it.
