### ISSUE TITLE
Some make rules are hidden

### ISSUE THREAD

**Issue by rfuentess** [RIOT-OS/RIOT#9009]
#### Description

It's seems that since daa277b36e414188584b44485b970fddf1b82c60 at least three rules for make are not displayed by `make help` : `buildtest`, `info-boards-features-missing` and `info-buildsizes-diff`.

I originally was looking for `buildtest` but at diff thrown the other two rules. 

#### Steps to reproduce the issue

In any example run: 

```
$ make help | grep buildtest
```

#### Expected results

With V. 2017.07
```
$ make help | grep buildtest
buildtest
$
```
#### Actual results

In the current master:

```
$ make help | grep buildtest
$
```

#### Versions

O.S.: ubuntu 16.04 LTS

```
Installed compiler toolchains 
-----------------------------
             native gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
      arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
                avr-gcc: avr-gcc (AVR_8_bit_GNU_Toolchain_3.5.4_1709) 4.9.2
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
                  clang: clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "2.5.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
               avr-libc: "2.0.0" ("20150208")

Installed development tools
---------------------------
                  cmake: cmake version 3.5.1
               cppcheck: Cppcheck 1.72
                doxygen: 1.8.11
                 flake8: 3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.12 on Linux
                    git: git version 2.7.4
             coccinelle: spatch version 1.0.4 with Python support and with PCRE support

```

**Comment by cladmi** [comment]
Hi @rfuentess, that is because the makefiles generating these rules are not included unless specified as command line goal: 
https://github.com/RIOT-OS/RIOT/blob/daa277b36e414188584b44485b970fddf1b82c60/Makefile.include#L75-L83

I think we could always include these file, but make them only define the `.PHONY: global-rules` if `BOARD==none` or something like that.
