### ISSUE TITLE
core/debug: deal with in-isr use of DEBUG

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#904]
Compare (outdated diff) discussions #834.

**Comment by haukepetersen** [comment]
I am not sure this is still an issue. At least the stacksize for cortex based CPUs is now configured in one place (`cortexm_common/include/cpu_conf_common.h`) and when using the nano specs (which is done by default), the isr stacksize is quite sufficent for using printf...

**Comment by miri64** [comment]
But what about other platforms?

**Comment by OlegHahm** [comment]
I would vote for disabling DEBUG in ISR context completely.

**Comment by kaspar030** [comment]
Wit DEVELHELP, we now have a stack space check in ISRs. I consider this done. Feel free to reopen if you disagree.
