### ISSUE TITLE
Support for Kinetis KE02 based FRDM-KE02Z board

### ISSUE THREAD

**Issue by iia** [RIOT-OS/RIOT#9053]
Hi,

Is there any ongoing work to port Kinetis KE02 based FRDM-KE02Z board? I'm interested to port this variant of Kinetis CPU and board.

Cheers.

**Comment by gebart** [comment]
I am not aware of any current ports to the Kinetis KE02. If you want to create your own port, you may find it useful to start from my KL43Z port in #9012 which adds support for the Kinetis L series. I believe the ke0x series may have much in common with the KL series. One challenge with the KE02 is the tiny RAM size, but I think it should be possible to at least run simple applications on it.

**Comment by iia** [comment]
Hi @gebart,

I made the board work with UART using RIOT's interface and could compile and run the hello world example. Should I create a PR? Or support for this board has no chance to be merged into RIOT base because of its low memory and other limitations ?

Cheers.

**Comment by gebart** [comment]
You can open a PR. There are no rules or limits for the supported boards, as long as it is at least possible to run a subset of the examples on the board, and we already have the nucleo32-031 and Arduino Uno which have tiny RAM. You will have to go through all the examples and tests and add the board to `BOARD_INSUFFICIENT_MEMORY` for the applications which fail to link, or else Murdock will complain.
