### ISSUE TITLE
flashpage_write broken on iotlab-m3

### ISSUE THREAD

**Issue by cladmi** [RIOT-OS/RIOT#9065]
#### Description

`flashpage_write` broken on `iotlab-m3`

#### Steps to reproduce the issue

In `tests/periph_flashpage`:

execute:
* dump 255
* test 255
* dump 255

#### Expected results

```wrote local page to flash page 255 at addr 0x807f800```
And having `a b c d...`.

For reference with ENABLE_DEBUG (1) its working properly:

```
test 255
...
1521049756.371371;m3-380;[flashpage_raw] writing s to 0x807fffe
1521049756.372367;m3-380;[flashpage] write: done writing data
1521049756.373414;m3-380;flashpage_raw] now locking the flash module again
1521049756.373651;m3-380;[flashpage] locking the flash module
1521049756.375369;m3-380;wrote local page to flash page 255 at addr 0x807f800
dump 255
1521050605.346219;m3-380;> dump 255
# a b c d... as expected
````
#### Actual results

```
dump 255
1521050271.397776;m3-380;> dump 255
# 0xff everywhere
test 255
1521050275.361341;m3-380;> test 255
     # need to type enter to see the error
1521050278.902577;m3-380;error verifying the content of page 255: >  
dump 255
1521050290.161453;m3-380;> dump 255
# 0xff everywhere
```

#### Versions

Introduced by https://github.com/RIOT-OS/RIOT/pull/8768

**Comment by aabadie** [comment]
I'm on it and I think I have a fix: the calls to lock/unlock functions cause problems with iotlab-m3. In fact, it's the only difference introduced by #8768 regarding iotlab-m3.
I'm testing other boards to check nothing else is broken.
