### ISSUE TITLE
EFM32 (sltb001a) is missing FEATURES_PROVIDED=cpp

### ISSUE THREAD

**Issue by Mario0x1** [RIOT-OS/RIOT#9093]
#### Description
FEATURES_PROVIDED=cpp is not set in cpu/efm32/Makefile.features despite being able to build and run examples/riot_and_cpp 

#### Steps to reproduce the issue
```
cd examples/riot_and_cpp
make BOARD=sltb001a flash
```

#### Expected results

>make BOARD=sltb001a

informs that

>...
> There are unsatisfied feature requirements: cpp
> 
> 
> EXPECT ERRORS!
> 
> 
> Building application "riot_and_cpp" for "sltb001a" with MCU "efm32".
> ...

It should fail if RIOT-gecko-sdk does not support cpp.

#### Actual results
example/riot_and_cpp can be build and flashed and returns

> main(): This is RIOT! (Version: 2018.04-devel-1009-g4f4e-hoss-214)
> 
> ************ RIOT and C++ demo program ***********
> 
> ******** Hello, you're in thread #2 ********
> We'll test C++ class and methods here!
> Instanciating Object [constructor called]
> Im starting!
> 
> -= Test overloading functions =-
> Hello!
> Hello![int: 42]
> Hello![float: ]
> 
> -= Test namespace =-
> typing std::vector is obsolete when 'using namespace std;'
> The vector vInts has been filled with 3 numbers.
> 
> -= Test iterator =-
> The content of vInts = { 1 3 2 }
> Destroying Object [destructor called]
> Im shutting down!
> ******** Hello, you're in thread #3 ********
> We'll test some C functions here!
> 
> -= hello function =-
> Hello world in a C function
> 
> -= day_of_week function =-
> day 13, month 6, year 2014 is Friday
> 
> This demo ends here, press Ctrl-C to exit (if you're on native)!

#### Versions
SEGGER J-Link Commander V6.22a
Gecko_sdk: https://github.com/basilfx/RIOT-gecko-sdk d381e526d68a2d0c951f37040c1c2e168ac66cd6

@basilfx

**Comment by basilfx** [comment]
I've created #9097 to address this bug.
