### ISSUE TITLE
cpu/atmega_common: external interrupts not usable

### ISSUE THREAD

**Issue by TorbenPetersen** [RIOT-OS/RIOT#9094]
In `cpu/atmega_common/periph/gpio.c` external interrupts are not usable for the atmega1284p CPU. The reason is this if clause:

`(_port_num(pin) != PORT_D && _port_num(pin) != PORT_D)`

Any INT on pins that are *not* on port D will therefore be wrongly excluded. It was wrongly introduced by #8829 by @ZetaR60 

I will provide a fix shortly.

**Comment by ZetaR60** [comment]
@TorbenPetersen I have a PR to fix this and many other problems with ATmega external interrupts. See #8951

**Comment by ZetaR60** [comment]
#8951 has been merged. This issue should be fixed now.

**Comment by tcschmidt** [comment]
@TorbenPetersen do you see it fixed? Then please close the issue.

**Comment by TorbenPetersen** [comment]
Jupp, its fixed. Thanks @ZetaR60
