### ISSUE TITLE
gcoap Observe registration woes

### ISSUE THREAD

**Issue by kb2ma** [RIOT-OS/RIOT#9180]
Presently the gcoap Observe implementation limits registration for a resource, for example '/sensorData', to a single token from a single endpoint. However, @miri64 reports that this approach is problematic when the link layer is lossy:

> Say we send a [non-confirmable] GET with OBSERVE option to a server, it is successfully received, but then the reply gets lost. To the client this just looks like the server did not reply so it will try to re-register [with a different token], with no previous de-registering, because from its perspective the registration did not happen (also the deregistration packet also might get lost).

Specifically, gcoap allows re-registration using the same token. However, some CoAP tools expect to generate a new token internally for a new GET request. gcoap itself works this way. This means that the client cannot easily re-register.

So, the question then is how can gcoap accommodate this need.

Also there is another problem, as shown in the message below from the IETF core mailing list [1]:

>> "A client MUST aggregate such requests and MUST NOT register more than once
>> for the same target resource. The target resource is identified by all
>> options in the request that are part of the cache-key."
>>
>> For a restarting client this is hard to fulfill. It’s seems to be common in
>> that case to use the same target resource (including the same "cache-key"
>> options) but with a different random token. So, if such a request would be
>> denied (caused by violating 3.1) , a client would not be able to reregister
>> without storing the original token "restart save".
>
> When the client restarts, it's fine to "forget" the old token and
> register with a new token. The old observation will be cleaned up when
> the server sends the next notification. There is only a short overlap
> of the two observations, not two long-term observations running at the
> same time (which is what the 'MUST' prevents).

Ken

[1] https://www.ietf.org/mail-archive/web/core/current/msg06356.html

**Comment by kb2ma** [comment]
First, thanks for the report @miri64. I agree this problem needs a solution.

The message above from the core ML advises temporarily allowing for two registrations for the same endpoint+resource. I suggest taking this a step further to short circuit the process -- add the ability to re-register based on endpoint+resource, as well as the current ability to re-register based on endpoint+token.

In other words, assume a registration exists for an endpoint E and resource R1 with a token T1. Then, assume a new registration request is received (GET request with Observe = 0) from endpoint E with resource R1 but token T2. In this case the solution is to update the existing registration to replace T1 with T2. 

@miri64, does this sound like a reasonable solution?

**Comment by miri64** [comment]
> @miri64, does this sound like a reasonable solution?

Sounds reasonable for now and still in line with the RFC IMHO (due to the token being replaced there is still one registration), but I need to think about it a little first to give a definite answer.

**Comment by miri64** [comment]
> I need to think about it a little first to give a definite answer.

Specifically, we need to make sure, that there is no way, the old registration isn't used anymore afterwards. Is this the case automatically (i.e. if there is a new registration, can we assume only the newer one is the legal one or is there some edge case [malicious or not] where an older registration *can* still be legal)?

**Comment by miri64** [comment]
Can it be considered an attack to constantly send new registrations with different tokens? If yes, is that a problem for us? Can this risk be lessened by only replacing the token if the first response was already sent (i.e. the response might have gotten lost)?

**Comment by miri64** [comment]
> Can this risk be lessened by only replacing the token if the first [non-confirmable] response was already sent (i.e. the response might have gotten lost)?

For the CON case: if an ACK for first response wasn't received or if still waiting for an ACK in subsequent response.

Sorry for the spam btw... Just brainstorming.

**Comment by kb2ma** [comment]
> Specifically, we need to make sure, that there is no way, the old registration isn't used anymore afterwards.

Yes, this happens automatically. The old registration is replaced. gcoap_obs_init() and gcoap_obs_send() generate and send the notification. They look in the list of registrations for the token and endpoint for the message.

**Comment by miri64** [comment]
>> Specifically, we need to make sure, that there is no way, the old registration isn't used anymore afterwards.
>
> Yes, this happens automatically. The old registration is replaced. gcoap_obs_init() and gcoap_obs_send() generate and send the notification. They look in the list of registrations for the token and endpoint for the message.

I was talking more from the client's perspective. Or to pose the question somewhat differently: Is there a legitimate edge case, were just replacing the token might be harmful?

**Comment by kb2ma** [comment]
> Can it be considered an attack to constantly send new registrations with different tokens?

Yes, no question. See the quote below from the Security section of 7641.

> As with any protocol that creates state, attackers may attempt to
   exhaust the resources that the server has available for maintaining
   the list of observers for each resource.  Servers may want to apply
   access controls to this creation of state.  As degraded behavior, the
   server can always fall back to processing the request as a normal GET
   request (without an Observe Option) if it is unwilling or unable to
   add a client to the list of observers of a resource, including if
   system resources are exhausted or nearing exhaustion.

By accepting only a single registration per resource, gcoap has implemented an access control. Yes, it would be annoying to repeatedly update the registration, but at least we're not exhausting RAM.

As the quote suggests, we certainly can degrade to ignore the Observe registration, and just provide the response to the GET. I also read your suggestion on the condition to use to trigger the degraded response. Let me think that through.

**Comment by kb2ma** [comment]
> I was talking more from the client's perspective.

I see your point now. The client already is a little confused because a previous registration apparently failed. Can an attempt by the client to re-register compound the problem? For example, if the registration response from the server is lost, and the server sends a notification with the original token while the client is attempting to re-register with a new token, what happens then? Good questions. More food for thought.

**Comment by kb2ma** [comment]
> Specifically, we need to make sure, that there is no way, the old registration isn't used anymore afterwards. Is this the case automatically (i.e. if there is a new registration, can we assume only the newer one is the legal one or is there some edge case [malicious or not] where an older registration can still be legal)?

I cannot think of a scenario where a server replacing the token will be a problem for the client. The scenario I was thinking about is this:

1. `Client GET Obs=0 Tok=a ---> Server`

2. `XXX <--- Server 2.xx Obs=123 Tok=a`

[Client timeout, MUST forget about Tok=a]

3. `Client GET Obs=0 Tok=b ---> Server`

[Client waiting for response for Tok=b]

4. `Client <--- Server 2.xx Obs=124 Tok=a`

[State of resource has changed.
 Server sends before receiving Client request for Tok=b]
[Client ignores Observe aspect because Tok=a]
[Server replaces Tok=a with Tok=b]

5. `Client <--- Server 2.xx Obs=125 Tok=b`

[Client records successful registration]

Alternatively, after step 4, the Client may send a Reset message to the server. Presently gcoap does not handle a Reset, so the server ignores it. This result is fine for this scenario. gcoap documentation states it does not handle Reset.

This scenario assumes Client forgets about Tok=a when its request times out. It also assumes that at step 4 the Client recognizes either that it does not have a confirmed registration yet, or that it has a pending registration with Tok=b.

**Comment by kb2ma** [comment]
> Can it be considered an attack to constantly send new registrations with different tokens? Can this risk be lessened by only replacing the token if the first [non-confirmable] response was already sent (i.e. the response might have gotten lost)?

Not sure I understand the scenario you suggest here. I think you mean this: 

1. Server receives initial registration request and saves Tok=a.
2. But before initial 2.xx response with Observe value sent, another request arrives with a different token.

I don't see this scenario as a problem because the response is written synchronously when the request is received. So, the handling continues with:

3. Server sends response to initial request.
4. Server reads next request, saves Tok=b, and sends response.

If I've got this wrong, please explain in more detail. Also, we can worry about CON handling when working on that PR. :-)

However, maybe a good approach to a client sending many registration requests in series is to limit the rate of change to the registration token. We could record the time at which registration was processed. Then we would require some minimum interval before allowing another change to the registration. Of course this interval can't be too long, so we can handle the legitimate scenario that started this issue. Maybe use 5 seconds? 

This sort of rate limiting will be useful also for congestion control when sending Observe notifications. We don't want the server to send too many notifications with a given time period no matter how quickly the resource changes. This issue is called out specifically in the RFC.

Personally, I don't think it's necessary to implement rate limiting yet with the other more fundamental  work going on with CoAP right now. However, I expect you are more aware of the project requirements in this area, and I'm happy to implement this idea.
