### ISSUE TITLE
Logic errors in nanocoap_get()

### ISSUE THREAD

**Issue by kb2ma** [RIOT-OS/RIOT#9191]
#### Description
Two issues in nanocoap_get():

1. miscounts retries for a confirmable message
1. includes unnecessary gotos

The easiest way to reproduce the retry problem is to disable the server you're testing with. You should see nanocoap_get() attempt only three retries, not the expected four.

The retry loop is problematic -- it counts up, but stops one retry short. The loop counts up, but also includes a test for remaining tries equal to zero. Not gonna happen. :-) Also, the gotos presently in the while loop are unnecessary; a break will suffice.

**Comment by smlng** [comment]
someone working on this, otherwise I could?

**Comment by kb2ma** [comment]
Go for it, @smlng! I'd be happy to review.
