### ISSUE TITLE
CI: unittests not run on master anymore

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#9249]
#### Description
While reviewing #9242 I noticed, that the unittests don't seem to run on Murdock at the moment (neither for native nor any other board). Is that known or even intended?

#### Steps to reproduce the issue
Look at Murdock log of any given PR.

#### Expected results
Unittests run should appear in log

#### Actual results
Unittests do not appear in log

#### Versions
Murdock ;-)

**Comment by smlng** [comment]
Not true, see at the bottom of https://ci.riot-os.org/RIOT-OS/RIOT/8988/d41cc36bcc8111cdb4f1d3f5b7b71daeebd101ef/output/compile/tests/unittests/native.txt

**Comment by miri64** [comment]
Ah okay... but that's quiet hidden IMHO :-/
