### ISSUE TITLE
tests : Add new test periph_gpio_arduino to allow testing of arduino pin numbering

### ISSUE THREAD

**Issue by TomKeddie** [RIOT-OS/RIOT#9271]
Issue to track https://github.com/RIOT-OS/RIOT/pull/7392

A new test is desired that will enable easy testing of the arduino i/o api configuration for new and existing boards.

Should support
- Analog pins
- Digital pins (direction control and read/write)

**Comment by maribu** [comment]
Fixed by https://github.com/RIOT-OS/RIOT/pull/11058
