### ISSUE TITLE
gnrc not sending UDP packets with payload larger 1452B

### ISSUE THREAD

**Issue by jowlo** [RIOT-OS/RIOT#9286]
#### Description
Cannot send UDP Packets with a payload larger than 1452 bytes. 

#### Steps to reproduce the issue
I have only tested this on `native` so far, using two tap interfaces - as described in the [Readme](https://github.com/RIOT-OS/RIOT/blob/master/examples/gnrc_networking/README.md#connecting-two-riot-instances) to connect two RIOT instances. I am using Wireshark to monitor the `tap` interfaces. 

Based on the `gnrc_networking_example` i added a command switch to `udp.c` that sends out a packet with a variable length:
```
168,188d167
<     if (strcmp(argv[1], "sendbig") == 0) {
<         uint32_t num = 1;
<         uint32_t delay = 1000000;
<         if (argc < 5) {
<             printf("usage: %s sendbig <addr> <port> <size> [<num> [<delay in us>]]\n",
<                    argv[0]);
<             return 1;
<         }
<         if (argc > 5) {
<             num = atoi(argv[5]);
<         }
<         if (argc > 6) {
<             delay = atoi(argv[6]);
<         }
<         unsigned size = atoi(argv[4]) + 1;
<         char bigdata[size];
<         for(unsigned i = 0; i < size-1; i++) bigdata[i] = 'a';
<         // Null terminated string
<         bigdata[size-1] = 0;
<         send(argv[2], argv[3], bigdata, num, delay);
<     }
```

One instance starts a UDP server
```
main(): This is RIOT! (Version: 2018.04-x201-HEAD)
RIOT network stack example application
All up, running the shell now
> udp server start 8080
udp server start 8080
Success: started UDP server on port 8080
> ifconfig
ifconfig
Iface  6  HWaddr: ce:41:ac:66:28:73 
          MTU:1500  HL:64  RTR  
          RTR_ADV  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::cc41:acff:fe66:2873  scope: local
[...]
```

The other instance sends data with increasing payload size
```
main(): This is RIOT! (Version: 2018.04-x201-HEAD)
RIOT network stack example application
All up, running the shell now
> udp sendbig fe80::cc41:acff:fe66:2873 8080 1000
udp sendbig fe80::cc41:acff:fe66:2873 8080 1000
Success: sent 1000 byte(s) to [fe80::cc41:acff:fe66:2873]:8080
> udp sendbig fe80::cc41:acff:fe66:2873 8080 1500        
udp sendbig fe80::cc41:acff:fe66:2873 8080 1500
Success: sent 1500 byte(s) to [fe80::cc41:acff:fe66:2873]:8080
```
While the first packet is received (and displayed) correctly on the server side, the second packet with its larger payload never arrives. Wireshark does not report the packet being sent.

Using [`sock_udp_send`](https://riot-os.org/api/group__net__sock__udp.html#ga89562920ad89fe0e098fc989e3b064ec) directly shows the same behaviour: The return value correctly gives the packet size, however, nothing appears on the "wire".

#### Expected results
The client should send the (possibly fragmented?) packet, which would be visible to Wireshark. The packet should also be received on the server instance. Or an error should be reported.

#### Actual results
The packet does not arrive at the server side and is not reported to be sent by Wireshark.
Additionally, no error is thrown. 
Packets with less or equal to 1452 bytes are send correctly, anything larger seems to silently fail somewhere in the gnrc stack.

#### Versions
Operating system: Arch Linux
Build environment: GCC 8.1.0, CLang 6.0.0

**Comment by jowlo** [comment]
This might help to find where this packet disappears:
I added a test case to `tests/gnrc_sock_udp/main.c`, which - however - is reported as successful:
```
--- a/tests/gnrc_sock_udp/main.c
+++ b/tests/gnrc_sock_udp/main.c
@@ -515,6 +515,31 @@ static void test_sock_udp_send__socketed(void)
     assert(_check_net());
 }
 
+
+static void test_sock_udp_send_large__socketed(void)
+{
+    static const ipv6_addr_t src_addr = { .u8 = _TEST_ADDR_LOCAL };
+    static const ipv6_addr_t dst_addr = { .u8 = _TEST_ADDR_REMOTE };
+    static const sock_udp_ep_t local = { .addr = { .ipv6 = _TEST_ADDR_LOCAL },
+                                         .family = AF_INET6,
+                                         .netif = _TEST_NETIF,
+                                         .port = _TEST_PORT_LOCAL };
+    static const sock_udp_ep_t remote = { .addr = { .ipv6 = _TEST_ADDR_REMOTE },
+                                          .family = AF_INET6,
+                                          .port = _TEST_PORT_REMOTE };
+
+    static unsigned char largebuf[1500];
+
+    assert(0 == sock_udp_create(&_sock, &local, &remote, SOCK_FLAGS_REUSE_EP));
+    assert(sizeof(largebuf) == sock_udp_send(&_sock, &largebuf, sizeof(largebuf),
+                                           NULL));
+    assert(_check_packet(&src_addr, &dst_addr, _TEST_PORT_LOCAL,
+                         _TEST_PORT_REMOTE, &largebuf, sizeof(largebuf),
+                         _TEST_NETIF, false));
+    xtimer_usleep(1000);    /* let GNRC stack finish */
+    assert(_check_net());
+}
+
 static void test_sock_udp_send__socketed_other_remote(void)
 {
     static const ipv6_addr_t src_addr = { .u8 = _TEST_ADDR_LOCAL };
@@ -690,6 +715,7 @@ int main(void)
     CALL(test_sock_udp_send__socketed_no_netif());
     CALL(test_sock_udp_send__socketed_no_local());
     CALL(test_sock_udp_send__socketed());
+    CALL(test_sock_udp_send_large__socketed());
     CALL(test_sock_udp_send__socketed_other_remote());
     CALL(test_sock_udp_send__unsocketed_no_local_no_netif());
     CALL(test_sock_udp_send__unsocketed_no_netif());
```

```
$ cd tests/gnrc_sock_udp
$ make all tests
$ make term
[...]
Calling test_sock_udp_send__socketed()
gnrc_pktbuf_add len: 5
gnrc_sock_send call
Calling test_sock_udp_send_large__socketed()
gnrc_pktbuf_add len: 1500
gnrc_sock_send call
[...]
ALL TESTS SUCCESSFUL
```

Any help in tracking this down further is much appreciated.

**Comment by miri64** [comment]
@jowlo we don't support IPv6 fragmentation at the moment, but you are welcome to implement it. However, I agree, that for Ethernet IPv6 should be able to at least 1500 byte-sized packets

**Comment by miri64** [comment]
> However, I agree that for Ethernet IPv6 should be able to at least 1500 byte-sized packets

Actually it does: 1452 + 40 (IPv6 header) + 8 (UDP header) == 1500. So this issue is invalid. If you want to provide IPv6 fragmentation, please open a feature request issue where we can discuss this.

**Comment by pyropeter** [comment]
Wait a second... Surely this condition must be signalled to the upper layers? Similar to `EMSGSIZE` in POSIX.

**Comment by miri64** [comment]
@pyropeter there is: if you include the `gnrc_neterr` module (which is not well tested, I'm afraid), GNRC is able to report these kinds of errors, but you lose its asynchronouos advantages for sending.

**Comment by jowlo** [comment]
@miri64 Thanks for clearing this up. We opted for implementing fragmentation of our large (handshake) packets on the DTLS layer, which _MUST_ support it according to [RFC 6347](https://tools.ietf.org/html/rfc6347#section-4.2.3) anyways (although tinyDTLS does not as of now).

**Comment by miri64** [comment]
Ok. I guess then it is about high time, to finally clean up the extension header handling in GNRC. It's a mess at the moment. Let me know if you need help regarding the implementation of IPv6 fragmentation in GNRC.
