### ISSUE TITLE
net/sock_udp: assign ephemeral source port on `sock_udp_create()`

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#9376]
#### Description
In the current sock/udp implementation for GNRC (and probably others as well), an ephemeral source port is assigned only when calling `sock_udp_send()` for the first time. This casts IMO unnecessary restrictions on the interface, and this seems to be counter intuitive to me. 

Take the following example, using a dedicated listener thread to handle incoming data: 
- thread_1 is started during system init as pure listener thread
- thread_1: calls `sock_udp_create()` with `local := NULL`
- thread_1: enters its main loop and calls `sock_udp_recv()`
- main_thread: the user app calls (most likely indirectly) `sock_udp_send()` at some later point in time

This example will not work -> the call to `sock_udp_recv()` will return `-EADDRNOTAVAIL` as no local port has been assigned.

**Solution: I suggest to move the assignment of the ephemeral source port into `sock_udp_create()`.**

This has two advantages:
1. the sock interface is more flexible (see example above)
2. we can assert the `sock.local` field to be configured in the `sock_udp_send` function and thus save a tiny amount of run time overhead

TODOs that follow from this proposal:
- [ ] fix sock_udp documentation: state more specifically when, where, and how ephemeral source ports are assigned
- [ ] adapt existing sock implementations
  - [ ] GNRC
  - [ ] lwip
  - [ ] emb6

#### Steps to reproduce the issue
n/a

#### Expected results
Ephemeral source port is assigned to socket when `sock_udp_create()` is called with `local := NULL`

#### Actual results
Ephemeral source port is assigned on the first call of `sock_udp_send()

#### Versions
n/a

**Comment by haukepetersen** [comment]
Thinking and talking about it, I might have found a better solution: how about we change the semantics for `sock_udp_create()` to the following:
- `local == NULL` -> ephemeral source port is assigned when calling `sock_udp_send()` [no change]
- `local != NULL && local.port != 0` -> use given ep as local ep [no change]
- `local != NULL && local.port == 0` -> assign generate ephemeral port and use as source port [change]

**Comment by haukepetersen** [comment]
also local.family needs to be set accordingly, of course

**Comment by miri64** [comment]
:+1: This would keep the current API in tact (maybe doc needs some update though) and would be similar how such a case is handled with sockets.

**Comment by haukepetersen** [comment]
perfect. Can I get you to implement the changes? :-)

**Comment by miri64** [comment]
I can get do that.

**Comment by miri64** [comment]
@haukepetersen see https://github.com/RIOT-OS/RIOT/pull/9380

**Comment by miri64** [comment]
No, see https://github.com/RIOT-OS/RIOT/pull/9382. This time from the right branch and with tests + adaptations that came out of these tests

**Comment by haukepetersen** [comment]
thanks
