### ISSUE TITLE
Support for cc3200 and cc3220 chips

### ISSUE THREAD

**Issue by redradist** [RIOT-OS/RIOT#9385]
#### Description
Should be added support for the following chips cc3200 and cc3220

#### Expected results
Support should be added for cc3200 and cc3220

**Comment by PeterKietzmann** [comment]
Relates to #5733. Are you working on that? Personally I don't think this should be an open GitHub issue as long as there is no progress to track.

**Comment by PeterKietzmann** [comment]
Even relates to multiple efforts, [see](https://github.com/RIOT-OS/RIOT/pulls?q=is%3Apr+cc3200+is%3Aclosed)
