### ISSUE TITLE
shell `ping6` doesn't display duplicate packages

### ISSUE THREAD

**Issue by dingens** [RIOT-OS/RIOT#9387]
#### Description
This is rather a question. Maybe there is a good reason for this behavior.

When pinging and duplicates arrive, the riot shell `ping6` command just says
```
12 bytes from fe80::xxx: id=84 seq=1 hop limit=64 time = 0.280 ms
dropping additional response packet (probably caused by duplicates)
```

IPutils ping does it like this:
```
64 bytes from fe80::yyy%wlp3s0: icmp_seq=1 ttl=64 time=0.051 ms
64 bytes from fe80::zzz%wlp3s0: icmp_seq=1 ttl=64 time=166 ms (DUP!)
```

I wonder why you chose to do it like this. My primary reason to ask is that I use `ping ff02::1` etc for debugging the network, for which the latter output is way more useable. Also, in general, when you have duplicates, I suppose you'd want to know where they are from. (Plus, it is quite arbitrary which of the packets are "hidden" by not displaying their information.)

#### Steps to reproduce the issue
Set up a node in a way that there's at least two other hosts listening on the same network.
Run `ping6 ff02::1`

#### Versions
linux
             native gcc: gcc (GCC) 8.1.1 20180531
      arm-none-eabi-gcc: arm-none-eabi-gcc (Arch Repository) 8.1.0

**Comment by miri64** [comment]
I think there is no specific reason, other than a lazy approach to handling of packets... @OlegHahm according to `git blame` that error message is yours. Do you remember?

**Comment by miri64** [comment]
> […] it would require a rather big rewrite of the ping command handler […] 

You mean something like #9523? 🙃
