### ISSUE TITLE
ARM: Non-upstreamed openocd configs need to adopt new dap support

### ISSUE THREAD

**Issue by pyropeter** [RIOT-OS/RIOT#9401]
OpenOCD has changed their dap support and that requires all configs for ARM targets to be modified. More information here: http://openocd.zylin.com/#/c/4468/

The change was merged, but OpenOCD was not released since then, so there is still time to address this.

This only affects a few boards, as most boards use the configs contained in OpenOCD. Maybe it would be a good idea to push upstreaming efforts for the remaining board configs?

Affected boards:
* [ ] cc2650stk
* [ ] cc2650-launchpad
* [x] pba-d-01-kw2x, #9406
* [ ] lpc2387
* [x] All frdm boards with `USE_OLD_OPENOCD` (right?)

**Comment by gebart** [comment]
> - All frdm boards with USE_OLD_OPENOCD (right?)

If you have this new version of openocd you have, by definition, not an old openocd, so you should set USE_OLD_OPENOCD=0. We could improve it and let it be determined by a check of the openocd version. Help wanted.
