### ISSUE TITLE
github: rename "Ready for CI build" label to "CI: ready for build"

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#9449]
I'd like to rename the "Ready for CI build" label to "CI: ready for build" to be more in line with the "CI: run tests" label. However, I don't know how hard coded it is into Murdock that it has to be *that* label. So I rather ask ;-).

**Comment by kaspar030** [comment]
> I'd like to rename the "Ready for CI build" label to "CI: ready for build" to be more in line with the "CI: run tests" label.

+1

> how hard coded it is into Murdock that it has to be that label.

I checked, it is not hard-coded in current master (minus one place that I just commited a fix). As this is rather cosmetic, I'd rather not restart murdock. How about I keep this in mind and next time we do maintanance on Murdock I rename the label?

**Comment by miri64** [comment]
> How about I keep this in mind and next time we do maintanance on Murdock I rename the label?

If it doesn't *slip* your mind :+1: ;-)

**Comment by miri64** [comment]
Ping? When will that be?

**Comment by kaspar030** [comment]
> next time we do maintanance on Murdock I rename the label?

... still applies. 

(Problem is, Murdock is almost maintanance free, last restart was in Oktober. )

**Comment by smlng** [comment]
@kaspar030 the label is defined in `.murdock` file shouldn't be as simple as:
- defining the new label but  leaving the old intact
- create PR modifying the label in `.murdock`
- remove old label as soon as above is merged

No restart or update of workers needed?

**Comment by smlng** [comment]
see https://github.com/RIOT-OS/RIOT/blob/master/.murdock#L22

**Comment by smlng** [comment]
ah damn, sorry mixed things up

**Comment by miri64** [comment]
>> next time we do maintanance on Murdock I rename the label?
> 
> ... still applies. 
>
> (Problem is, Murdock is almost maintanance free, last restart was in Oktober. )

Ok, but there is something like a maintenance schedule, right?

**Comment by kaspar030** [comment]
> Ok, but there is something like a maintenance schedule, right?

Nope, not really. We schedule maintanance as needed.

**Comment by miri64** [comment]
@smlng @kaspar030 is this included into the current maintainance run?

**Comment by miri64** [comment]
Label is still called the old name, so apparently not :(

**Comment by kaspar030** [comment]
Ok, current live code can do this now, just needs to be configured. CI team is on it.

**Comment by miri64** [comment]
This is done :-)
