### ISSUE TITLE
stm32common i2c_1.c cannot write multiple registers (new i2c api)

### ISSUE THREAD

**Issue by MrKevinWeiss** [RIOT-OS/RIOT#9461]
#### Description
Cannot write multiple registers, it seems it gets locked up.  I think @aabadie has a solution already that works.  (This may be fixed, I won't have HW to fix until Monday, I just wanted it documented somewhere)

#### Steps to reproduce the issue
Write multiple registers to a sensor with any stm32f0/3/7 and l0/4. I used stm32f303 to test

#### Expected results
For it not to hang

#### Actual results
[automated test](
https://gist.github.com/MrKevinWeiss/e68873abc21e0d4703ebba7d94f54874)
It hangs

#### Versions
new_i2c_if branch

**Comment by dylad** [comment]
@MrKevinWeiss Does #9476 fix this issue ?

**Comment by MrKevinWeiss** [comment]
Yup #9476 points out other issues but it is at a usable state.
