### ISSUE TITLE
Something similar to shiftIn (Arduino)?

### ISSUE THREAD

**Issue by Citrullin** [RIOT-OS/RIOT#9712]
Hey,
the shiftIn function is really useful. I just don't rewrite this function. So I wanted to know if there is something similar in RIOT OS. I haven't found it yet in the API docu.

**Comment by PeterKietzmann** [comment]
AFAIK there is no such function. We have a (small) collection of bit operations in [bitarithm](https://riot-os.org/api/bitarithm_8h.html) but no helper for shifting.
