### ISSUE TITLE
tests/lwip_sock_*: compilation errors

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#9795]
Compilation of these tests throw the following error message on the ESP8266 platform:
```
.../tests/lwip_sock_ip/stack.c:355:36: error: 'msg.content.value' is used uninitialized in this function [-Werror=uninitialized]
     while (data_len != (msg.content.value - sizeof(ipv6_hdr_t)))
```
which seems to be indeed the case if stack variables are not initialized by default. If I understand the semantic of the source correctly, the following construct could solve the problem:
```
do {
    msg_receive(&msg);
} while (data_len != (msg.content.value - sizeof(ipv6_hdr_t)));

**Comment by gschorcht** [comment]
Additional comment: According to ISO/IEC 9899:TC3 WG14/N1256 (C99 standard) section 6.7.8 clause 10 an object that has automatic storage duration is not initialized explicitly, its value is indeterminate.

I'm a bit wondering that these tests do now throw error messages on other platforms.

**Comment by miri64** [comment]
> I'm a bit wondering that these tests do now throw error messages on other platforms.

That's surprising indeed. At least our static code analyzer should have picked that one up. While I agree that this should be fixed, I think

```C
    msg_t msg = { .content { .value = 0 } };

    while (data_len != (msg.content.value - sizeof(ipv6_hdr_t))) {
        msg_receive(&msg);
    }
```

offers a more readable solution than a foot-operated loop. Do you want to provide a fix for that or should I.

**Comment by gschorcht** [comment]
As you prefer. I could provide a fix, but I suppose  that merging into the master is done immediately by yourself if you fix it. I need the fix to satisfy murdock.

**Comment by miri64** [comment]
> As you prefer. I could provide a fix, but I suppose that merging into the master is done immediately by yourself if you fix it. I need the fix to satisfy murdock.

I can't ACK my own PRs either ;-)

**Comment by miri64** [comment]
(as such it would indeed go faster with the combination of you being the contributor, me being the reviewer, instead of waiting for a third party)

**Comment by gschorcht** [comment]
Ok, should I fix it?

**Comment by gschorcht** [comment]
Ok

**Comment by miri64** [comment]
Yes please.
