### ISSUE TITLE
Codacy: unused struct members errors

### ISSUE THREAD

**Issue by gschorcht** [RIOT-OS/RIOT#9803]
PRs are now checked against Codacy. Codacy very often claims that a member of a struct is not used,  e.g.:
```
struct member 'XTensa_rtos_int_frame_s::exitPtr' is never used.
...
struct XTensa_rtos_int_frame_s {
     uint32_t exitPtr;
     uint32_t pc;
     uint32_t ps;
     ...
};
```
The structure in the example defines the layout of the interrupt stack frame as used in ```thread_arch.c```. It is a standard approach to define the memory layout by structures even though not all the members are then really used.

Codacy should not claim unused members of structures as errors.

**Comment by jia200x** [comment]
@gschorcht thanks for pointing this out. I just turned off that style check.

We might find some other issues during these days, but we are working hard to solve them :)

**Comment by jia200x** [comment]
Solved. Closing
