### ISSUE TITLE
sock: sock_ip_ep_t and struct _sock_tl_ep code duplication

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/RIOT#9861]
#### Description

The definitions of `sock_ip_ep_t` and `struct _sock_tl_ep` are identical, except for the addition of the port member at the tail of `struct _sock_tl_ep`

#### Steps to reproduce the issue

Compare: 
https://github.com/RIOT-OS/RIOT/blob/8ada7a84c517249e30076b0c3e387651abc380a6/sys/include/net/sock.h#L158-L190

and:

https://github.com/RIOT-OS/RIOT/blob/8ada7a84c517249e30076b0c3e387651abc380a6/sys/include/net/sock.h#L195-L228

#### Resolution

Remove the duplication in `struct _sock_tl_ep` and add a `sock_ip_ep_t` member at the top of `struct _sock_tl_ep` as a replacement. This will remove the need for casting from `sock_udp_ep_t *` to `sock_ip_ep_t *` in sock_util.c and other places.

#### Versions

master branch at commit https://github.com/RIOT-OS/RIOT/blob/8ada7a84c517249e30076b0c3e387651abc380a6

**Comment by miri64** [comment]
I think this change would be sensible. @kaspar030 what do you say?
