### ISSUE TITLE
How-to-install-6LoWPAN-Linux-Kernel-on-Raspberry-Pi

### ISSUE THREAD

**Issue by 123ebad** [RIOT-OS/RIOT#9871]

**Comment by smlng** [comment]
Welcome to RIOT, have a look here https://github.com/RIOT-Makers/wpan-raspbian and also the associated wiki. Basically a standard Raspbian Linux is 6Lo-ready from the Kernel-side but you may need some additional tools depending on your use-case - but follow the guides in the wiki of the above repo.

If you need further help, don't hesitate to ask us again also consider to post on the mailing lists.

**Comment by 123ebad** [comment]
[image: 2018-09-02-032327_1024x768_scrot.png]
SIR I FOLLOW THE LINK
https://github.com/RIOT-OS/RIOT/wiki/How-to-install-6LoWPAN-Linux-Kernel-on-Raspberry-Pi
AND I FOUND AN ERROR HERE,I CANT UNDERSTAND HOW TO RESOLVE IT, PLZ GUIDE
ME,I WILL BE VERY THANKFULL TO YOU FOR THIS ACT OF KINDNESS

**Comment by 123ebad** [comment]
Thank you Sir but I solved it by myself,if I will find any errors or help
In future. I will contact with you.

**Comment by jia200x** [comment]
@123ebad sure. I will close this issue then. If you have any questions don't hesitate to open a new Issue and write the actual error and how to reproduce it.
