### ISSUE TITLE
i2c SAML21 using sercom5 gets stuck at poweron

### ISSUE THREAD

**Issue by fedepell** [RIOT-OS/RIOT#9874]
#### Description
On SAML21 based boards, for example saml21-xpro, if I2C is configured to use sercom5 it will get stuck forever during initialization in _i2c_poweron at:

```
 _i2c_poweron (dev=0)
     at xxx/RIOT/cpu/sam0_common/periph/i2c.c:262
 262	    while (bus(dev)->SYNCBUSY.bit.ENABLE) {}
``` 

The condition is never met and code is stuck there forever.

I see that sercom5 handling is slightly different from the others (has a separate clock) so maybe some detail is missing there. Using a different sercomX works as expected, but with specific pinout usage sercom5 needs to be used.

#### Steps to reproduce the issue
Configure the I2C to use sercom5, that is:
```
static const i2c_conf_t i2c_config[] = {
    {
        .dev      = &(SERCOM5->I2CM),
        .speed    = I2C_SPEED_NORMAL,
        .scl_pin  = GPIO_PIN(PB, 31),
        .sda_pin  = GPIO_PIN(PB, 30),
        .mux      = GPIO_MUX_D,
        .gclk_src = GCLK_PCHCTRL_GEN_GCLK0,
        .flags    = I2C_FLAG_NONE
    }
};
```
And add the i2c module to your application:
`USEMODULE += periph_i2c`

#### Expected results
I2C gets correctly initialized.

#### Actual results
I2C initialization stuck forever blocking whole RIOT OS.

#### Versions
arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by dylad** [comment]
feel free to close your issues when your PRs get merged :)
Thanks for spotting and fixing these bugs !

**Comment by fedepell** [comment]
Now that #9876 and #9877 have been merged the issue can be closed. I also checked that I2C reads correctly from a I2C configured on SERCOM5.
