### ISSUE TITLE
https://github.com/RIOT-OS/RIOT/wiki/How-to-install-6LoWPAN-Linux-Kernel-on-Raspberry-Pi,working on this link and got an error

### ISSUE THREAD

**Issue by 123ebad** [RIOT-OS/RIOT#9898]

**Comment by 123ebad** [comment]
https://github.com/RIOT-OS/RIOT/wiki/How-to-install-6LoWPAN-Linux-Kernel-on-Raspberry-Pi
I m currently working on an IOT project(6lowpab based patient monitoring system) and i m making my raspberry pi-2 as a border router by following this link,but when i fully got ready my sd-card for new kernel and put the sd-card in pi-2,it was not booting and only black screen occur on LCD ,kindly help me to resolve this issue and tell me where i made a mistake. I will be very thank full

**Comment by dylad** [comment]
Did you try skipping the Kernel build and tried with a default img from Raspbian ? I think 6LowPAN is enabled by default on recent Image.

**Comment by miri64** [comment]
That tutorial is pretty outdated anyway. @RIOT-OS/maintainers shall we remove it or add a deprecation note?

**Comment by dylad** [comment]
I would prefer add a deprecation note,
It would be a shame to drop some useful informations even if some parts are deprecated.

**Comment by miri64** [comment]
Just noticed: there is already a fat deprecation note on top ;-).

**Comment by miri64** [comment]
With link to an external, more cared for version.

**Comment by miri64** [comment]
Since the wiki page is already deprecated, please refer to the linked project in the deprecation note @123ebad.
