### ISSUE TITLE
CMake Upgrade

### ISSUE THREAD

**Issue by npcode15** [RIOT-OS/RIOT#9904]
Hello,

I was trying to follow the instructions from CCN-Lite-Relay example.
I encountered an error saying cmake needs to be upgraded.
I am not able to unzip/source from files after download.
Is there any other way to upgrade?

Thanks.

**Comment by dylad** [comment]
Hello @npcode15,
cmake is not related to RIOT or CCN-Lite-Relay but rather with your local installation.
If you're using an Ubuntu based distro, you can run` sudo apt-get install cmake`
that will do the trick.

**Comment by npcode15** [comment]
Hello @MesoticSAS, thanks for getting back. I am using Windows host and running RIOT OS via Vagrant. So I need to update Windows cmake?

**Comment by dylad** [comment]
I have no clue, I am not using Windows nor Vagrant.
Maybe try https://cmake.org/download/

**Comment by npcode15** [comment]
Hey @Citrullin, Already tried, I was able to find a way around unzip. But, when I try to upgrade, I receive an error saying C++ 11 not found.

**Comment by Citrullin** [comment]
@npcode15 You probably should also upgrade your gcc then.

**Comment by dylad** [comment]
@npcode15 If you managed to solve this issue, feels free to close it ;)

**Comment by npcode15** [comment]
@dylad, I did not check it. I will look at CCN later if needed. 

But, I will close it for now. Thanks, @Citrullin @dylad
