### ISSUE TITLE
drivers/tsl2561: The i2c bus is not released

### ISSUE THREAD

**Issue by jcarrano** [RIOT-OS/RIOT#9920]
#### Description

The driver for the TSL2561 acquires the bus and does not release it. This means that it is not possible to use other devices connected to the same bus.

See https://github.com/RIOT-OS/RIOT/blob/6265da2894ed5cb7c414a44cd2856be918c3a06b/drivers/tsl2561/tsl2561.c#L57

#### Expected results

- Every call to `i2c_acquire()` should be matched by a call to `i2c_release()`
- The bus should not be be held if it is not being used.

#### Actual results

- There is only one call to `i2c_acquire()` when the driver is initialized.
- There are no calls to  `i2c_release()`.

**Comment by dylad** [comment]
Good catch ! This bug must be there for a long time as it has not been introduced by the I2C rework.
Anyway, @jcarrano I can provide a PR for fixing this if you have the hardware to test it.

**Comment by jcarrano** [comment]
@dylad I don't have this hardware. I found the bug because I was implementing a "similar" sensor (TSL4531, #9911 ) which turned out not to be similar at all.

**Comment by dylad** [comment]
@jcarrano Alright, I'll provide a fix soon then and we'll see if someone can test it on real hardware.

**Comment by dylad** [comment]
@jcarrano I'm closing this, since #9937 got merged.
