### ISSUE TITLE
Replace printf and puts with logging functions

### ISSUE THREAD

**Issue by authmillenon** [RIOT-OS/RIOT#994]
Most of the output is not needed and maybe needs to be omitted (I'm looking at you, unittests).
I propose to introduce a new INFO() macro where output may be wished to be omitted, but otherwise could be printed (the startup sequence i. e.).

May be related to #641.

**Comment by PeterKietzmann** [comment]
Can we close this?

**Comment by authmillenon** [comment]
No, but #2503 and #2527 are fixing it.

**Comment by OlegHahm** [comment]
#2907 could solve this. Just someone has to replace all the printf and puts calls...

**Comment by kaspar030** [comment]
> RIOT is unable to generate valid XML for Jenkins to work with ;-)

Couldn't care less... :)

**Comment by kaspar030** [comment]
we should rephrase the issue title.

**Comment by authmillenon** [comment]
>> RIOT is unable to generate valid XML for Jenkins to work with ;-)
> Couldn't care less... :)

Does not apply anymore anyways ;-P

**Comment by LudwigOrtmann** [comment]
Not only the title, the discussion of this issue is unrelated as well .. I'd just close and open a new issue. No need for recycling bits.

**Comment by LudwigKnuepfer** [comment]
#2907 is merged.
