### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by snej** [RIOT-OS/RIOT#9944]
The `/boards` directory indicates Espressif’s ESP8266 SoC is supported, but not the newer ESP32. Are there plans to add support? Is there currently an unofficial configuration for it?

I’m evaluating IoT operating systems for my employer, and SparkFun’s ESP32 Thing is one of the boards I’m using. I’d love to try out Riot on it.

**Comment by snej** [comment]
Sorry, I forgot to search PRs too! Just found https://github.com/RIOT-OS/RIOT/pull/9426.

**Comment by miri64** [comment]
I guess we can close the issue then :-)
