### ISSUE TITLE
Nothing happens after flashing STM's with tests applications

### ISSUE THREAD

**Issue by kubazdz** [RIOT-OS/RIOT#9949]
#### Description

I'm new to RIOT and trying to run any test or example app on STM32f3discovery or nucleo-l432kc. Flashing works well, but then nothing happens as if the board wasnt flashed 

#### Steps to reproduce the issue

I'm trying to run /tests/leds with a command: 
`make flash BOARD=stm32f3discovery STLINK_VERSION=2-1` 

Also tried to run /examples/hello-world with:
`make flash term BOARD=stm32f3discovery STLINK_VERSION=2-1` 

and
`make flash term BOARD=nucleo-l432kc` 

#### Expected results

Blinking leds or printing hello world in terminal

#### Actual results

Nothing happens when using BOARD different than native (while on native port hello-world example works well)

Looking for help as I'm new to both RIOT and Linux

#### Versions

Operating system: Ubuntu 18.04
Build environment: GCC, gcc-arm-none-eabi

**Comment by aabadie** [comment]
Can you provide a more detailed list of the tools versions you are using (just print the output of ./dist/tools/ci/print_toolchain_versions.sh) ?
It could be that your gcc-arm-none-eabi is not working. Versions >= 7.2 are recommended for RIOT.

**Comment by kubazdz** [comment]
![obraz](https://user-images.githubusercontent.com/43334993/45614037-6cd40700-ba68-11e8-95ed-b2391eb5dd30.png)

**Comment by dylad** [comment]
@kubazdz Are you using the default arm-none-eabi-gcc from ubuntu repo ? (did you install it with `sudo apt install gcc-arm-none-eabi` ?

**Comment by kubazdz** [comment]
Yes i did

**Comment by kaspar030** [comment]
both "tests/led" and "examples/hello-world" are interactive applications (e.g., you'll need the terminal).
If flashing succeeded, can you confirm that ```BOARD=<board-name> make term``` opens the correct terminal device? Maybe check the output of "dmesg"?

For many boards, RIOT assumes the board will connect to a default tty device, for nucleos, that is often ```/dev/ttyACM0```. My laptop has an integrated LTE card on ttyACM0, so Nucleo boards get "/dev/ttyACM1", which I have to add with ```BOARD=... PORT=/dev/ttyACM1 make term```.

You can try ```dist/tools/usb-serial/list-ttys.sh```, which should list available tty devices.

**Comment by dylad** [comment]
Then your issue is related to #9248.
Please uninstall the ubuntu gcc-arm-none-eabi (`sudo apt autoremove gcc-arm-none-eabi`)
and install another toolchain like this [one](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads)
afterwards it will run just fine  !

**Comment by kubazdz** [comment]
I did as @dylad suggested and now it looks like this (the path to arm gcc is added):

![obraz](https://user-images.githubusercontent.com/43334993/45619806-effe5880-ba7a-11e8-9c81-a665d8f9b762.png)

But now what i get is this:

![obraz](https://user-images.githubusercontent.com/43334993/45619847-13c19e80-ba7b-11e8-88d6-a0301e186f2d.png)

**Comment by dylad** [comment]
Could you please paste the output of
`echo $PATH`

**Comment by kubazdz** [comment]
![obraz](https://user-images.githubusercontent.com/43334993/45620936-d101c580-ba7e-11e8-921b-d5911c4a2f63.png)

**Comment by dylad** [comment]
The only possible issue to me is a permission issue. If you're using the same terminal, you add your toolchain to the PATH variable and run make (everything without sudo) then maybe a permission is not set properly ?

**Comment by aabadie** [comment]
You $PATH is not correct, arm-none-eabi-gcc 7.3 is added after /usr/bin (where the old version resides). You should do export PATH=/home/kuba/Downloads/gcc-arm-none-eabi-7xxxx/bin:$PATH and you'll use the right version of all tools (including objcopy)

**Comment by dylad** [comment]
Could you also paste the whole output of the flash/run process please ?

**Comment by kubazdz** [comment]
I did run `make clean`.

![obraz](https://user-images.githubusercontent.com/43334993/45626394-c00d8000-ba8f-11e8-874d-817cc2e037ee.png)

**Comment by dylad** [comment]
`target halted due to breakpoint, current mode: Handler HardFault`
@aabadie is it even normal ?

**Comment by kYc0o** [comment]
No, it's not normal. It means that when the program started execution it went into HardFault directly. Something might be wrong on the linking phase.

@kubazdz can you paste the output of:

```console
$ arm-none-eabi-readelf bin/stm32f3discovery/test_leds.elf
```

You still run everything as root though, thus I strongly recommend to either change the user or create a new user.

**Comment by kubazdz** [comment]
@kYc0o I printed it all but skipped a part of a symbol table:

![obraz](https://user-images.githubusercontent.com/43334993/45666743-bbd87580-bb16-11e8-85c4-eda5ad1e842a.png)
![obraz](https://user-images.githubusercontent.com/43334993/45666817-00641100-bb17-11e8-9a65-5dd8b8d632ac.png)
![obraz](https://user-images.githubusercontent.com/43334993/45666877-34d7cd00-bb17-11e8-979d-ddb6031c05b6.png)

**Comment by aabadie** [comment]
If I understand correctly, the firmware is built with success and the board is flashed but you don't see the LEDs blinks ?

Since you are trying on a Nucleo board, this is probably related to the AUTO_INIT_LED0 macro that prevents the LED0 pin from being initialized (because it's shared with the SPI CLK pin).

Can you build your firmware with the following command:
```sh
CFLAGS=-DAUTO_INIT_LED0 make BOARD=nucleo-l432kc flash term
```
And tell us if it solves your problem ?

**Comment by kubazdz** [comment]
It worked, LED is blinking thank you very much. But still there's a problem with terminal. When I run hello-world example, the diode turns on which means that program runs, but there is no output in terminal (pyterm)

**Comment by dylad** [comment]
Can you paste the output of `dist/tools/usb-serial/list-ttys.sh`
Did you also try with another terminal like minicom/picocom ?

**Comment by kubazdz** [comment]
Here's how it looks like, after flashing hello-world

![obraz](https://user-images.githubusercontent.com/43334993/45675642-1205e280-bb30-11e8-831c-4591289d8d1a.png)

**Comment by kubazdz** [comment]
Yes, I have nucleo and stm32f3discovery. ACM0 is nucleo and as you see it connects to it (when I unplug the board it warns that it lost connection) but the problem is, there is no output. I don't know what am I doing wrong because when I run the same program using native, everything works fine

**Comment by aabadie** [comment]
I just tested with a nucleo-l432kc and the output is printed before the terminal is attached to the serial port. Solution: press the reset button.

For the stm32f3discovery, the serial port is not accessible from the USB ST-Link, you have to plug a serial to USB adapter to PA9(RX)/PA10(TX) pins and then it works (still after a board reset, with the black button)

**Comment by kubazdz** [comment]
Ah right it works, kinda embarrasing that i didn't think about it... Thank you very much!

**Comment by aabadie** [comment]
Then let's close this one !
