### ISSUE TITLE
Cannot Flash nrf52dk.

### ISSUE THREAD

**Issue by npcode15** [RIOT-OS/RIOT#9950]
Hello, There seems to a conflict between toolchain and RIOT OS (hard compilation vs soft compilation). Does anything come to your mind? I am using GCC ARM toolchain.

Refer to this image for exact error.
![image](https://user-images.githubusercontent.com/25517038/45657993-4b980880-bab2-11e8-8cbd-de747211c9ab.png)

Is there a particular toolchain I should be installing.

**Setup**: RIOT inside Virtual Ubuntu (Windows Host)
**Device**: nrf52840dk

**NOTE: Although, Hello World example gets flashed, but anything other than that doesn't.**

Thanks.

**Comment by aabadie** [comment]
You need arm-none-eabi-gcc 7.2 at least and you are using 6.3.1

**Comment by npcode15** [comment]
Hello @aabadie, I tried updating. Ubuntu says it is already updated.
![image](https://user-images.githubusercontent.com/25517038/45694828-b9314c80-bb25-11e8-9e12-67b1f6cbbd88.png)

Is this a correct link to update toolchain?
https://gnu-mcu-eclipse.github.io/toolchain/arm/install/

or launchpad one?

Thanks.

**Comment by aabadie** [comment]
> or launchpad one?

Yes prefer this one

**Comment by npcode15** [comment]
@aabadie 
There is no installer available for version 7.
RIOT is not finding the newly added version. (Added to path)

Is there a way to configure RIOT to check the new directory for arm-toolchain?

**Comment by aabadie** [comment]
> Successfully compiled. Thanks.

Great! So let's close this one then.
