### ISSUE TITLE
RFC: Introduce "Discussion: " label category

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#9975]
During the maintainer assembly at the RIOT summit last week, we discussed the introduction of a `NEEDS CONSENSUS` label, to mark PRs and issues where the discussion is stalled or so stuck in opposing arguments to involve a neutral arbiter to resolve it.

I propose that we introduce a new category of labels all-together (which IMHO also "Requests for Comments" belongs to) that also includes `NEEDS CONSENSUS`, that more fine-grainly would help to steer discussions before it even goes into the `NEEDS CONSESUS` category. Some other example that go into the direction that @danpetry proposed during that discussion would be a `Discussion: Final Comments` (to give people the time to give their final arguments) or `Discussion: Finished` (to mark that the decision making process was finished and now only implementation details are commented on).

**Comment by miri64** [comment]
A recording of the discussion can be found on [YouTube](https://www.youtube.com/watch?v=IBPHqAwLdI4&t=8949s) btw.

**Comment by jia200x** [comment]
+1 for trying it :)

**Comment by miri64** [comment]
No objections, only likes, in the last 2 weeks, so I guess I just implement it ;-).

**Comment by miri64** [comment]
Done
