### ISSUE TITLE
Nanocoap example query |  nrf52dk device IP

### ISSUE THREAD

**Issue by npcode15** [RIOT-OS/RIOT#9982]
Hello,

**Device**: nrf52840DK

**Setup**: Ubuntu 18.04 on Windows Host (using VMWare)

**Aim**
I have 2 of them and I want to make them talk with each other using UDP for which I would need their IP addresses. Before I can find get the IP,  I would need to connect them to the network. I am not sure if I can connect them directly. So,I am following this tutorial from nordic (IPv6 over BLE).
https://devzone.nordicsemi.com/b/blog/posts/setting-up-ipv6-over-ble-using-nrf52-series-and-ri

**Query**
The example mentioned in the tutorial was microcoap-example but I think RIOT replaced it with nanocoap-example. Anyway, this produces a Link-Local IPv6 (please refer to the screenshot below).
![image](https://user-images.githubusercontent.com/25517038/45839435-f9393080-bcd9-11e8-800e-f55d243c6b63.png)

I am trying to ping the IP and the output says invalid argument. I would like to know what exactly is the IP?

**Note:** I was not able to complete the tutorial. I got stuck at step, 'sudo hcitool lescan'. So, I wanted to know what is the significance of the IP displayed as output.

**Comment by aabadie** [comment]
If I understand correctly, your are facing issues with the Nordic tutorial. Note that Nordic tutorial is not using RIOT but their own software libraries.

I suggest that you ask them directly.

**Comment by aabadie** [comment]
Sorry, I replied a bit fast. It is actually about RIOT...

Maybe @dylad could answer that question. I remember he already played a bit with IPv6 and nrf52850dk.

**Comment by npcode15** [comment]
Okay, I did post a question on Nordic's forum as well.

**Comment by dylad** [comment]
@npcode15 In the current state, I think GNRC stack will not work with nrf52840dk board.
You will need #9473 to get merged before.
To explain things more clearly : 
The GNRC network stack of RIOT depends on the Nordic Softdevice blob for nRF devices. Currently RIOT supports Softdevice from Nordic SDK 14.2 (I think) but support for nRF52840 only start at Nordic SDK 15.
@miri64 Am I all wrong here ?

You can try to grab #9473 and redo your tests from there.

**Comment by miri64** [comment]
> @miri64 Am I all wrong here ?

I never used the soft device with GNRC myself, but when porting `gnrc_netif` I saw that it is supposed to support 6Lo. So I would guess it *should* work. Maybe @kaspar030 can provide a better answer (sorry for hot-potatoing this question, but I really don't know the answer)?

**Comment by npcode15** [comment]
@dylad @miri64 

"@npcode15 In the current state, I think GNRC stack will not work with nrf52840dk board." - 
would changing the networking stack to OpenThread make any difference?

**Comment by PeterKietzmann** [comment]
> would changing the networking stack to OpenThread make any difference?

AFAIK OpenThread is currently limited to 802.15.4 radios by atmel. However, we now have some other BLE features, among others, we provide BLE support by the nimBLE stack as external software package. Please have a look at these applications under examples/[nimle_gatt](https://github.com/RIOT-OS/RIOT/tree/master/examples/nimble_gatt), [sklad_eddystone](https://github.com/RIOT-OS/RIOT/tree/master/examples/skald_eddystone), [sklad_ibeacon](https://github.com/RIOT-OS/RIOT/tree/master/examples/skald_ibeacon)
